using System.Configuration;
using MapCall.Common.Model.Entities;
// ReSharper disable WrongIndentSize
// ReSharper disable RedundantBlankLines
// ReSharper disable MissingIndent

namespace MapCall.Common.Configuration
{
    public static class MenuConfiguration
    {
        public static Menu GetMenu()
        {
            return (Menu)new Menu()
                .Group("Help", "/Modules/mvc/HelpTopic/Search")

                .Group("Admin", mustBeSiteAdmin: true)
                    .Link("Administration", "Index", "AdminHome", "Admin")
                    .Link("Notes", "/Modules/Notes.aspx")
                    .BeginSection("Reports")
                        .Link("User Roles", "Search", "UserRole", "Reports")
                    .EndSection()

                .Group("Business Performance")
                    .BeginSection("Expense Lines")
                        .BeginSection("Reports")
                            .Link("Budget Rollup Department Area", "/Reports/BusinessPerformance/RptBudgetRollupDepartmentArea.aspx")
                            .Link("Budget Rollup OpCode", "/Reports/BusinessPerformance/RptBudgetReportByOpCode.aspx")
                            .Link("Budget Rollup OpCode, BU, Line Category", "/Reports/BusinessPerformance/RptBudgetReportByOpCodeBULineCategory.aspx")
                        .EndSection()
                    .EndSection()
                    .Link("Flow Diagrams", "/Modules/HR/Administrator/BusProcessFlowDiagrams.aspx")
                    .Link("Strategic Elements", "/Modules/BusinessPerformance/StrategicElements.aspx")
                    .Link("Goals", "/Modules/HR/Administrator/BusPerformanceGoals.aspx")
                    .BeginSection("Initiatives")
                        .Link("Initiatives", "/Modules/HR/Administrator/BusPerformanceInitiatives.aspx")
                        .Link("Initiative Steps", "/Modules/BusinessPerformance/InitiativeSteps.aspx")
                        .BeginSection("Reports")
                            .Link("Goals / Initiatives", "/Reports/BusinessPerformance/GoalInitiatives.aspx")
                            .Link("Initiative Summary", "/Reports/BusinessPerformance/InitiativeSummaryReport.aspx")
                            .Link("Initiative Steps Summary", "/Reports/BusinessPerformance/InitiativeStepsSummaryReport.aspx")
                            .Link("Strategic Elements / Initiatives", "/Reports/BusinessPerformance/StrategicElementsInitiatives.aspx")
                        .EndSection()
                    .EndSection()
                    .Link("KPI", "/Modules/HR/Administrator/BusPerformanceKPI.aspx")
                    .Link("KPI Measurements", "/Modules/HR/Administrator/BusPerformanceKPIMeasurement.aspx")
                    .Link("Reporting Requirements", "/Modules/HR/Administrator/BusPerformanceReportingRequirements.aspx")

                .Group("BPU")
                    .Link("Management Audits", "/Modules/BPU/ManagementAudits.aspx")
                    .Link("Markout Violations", "Search", "MarkoutViolation", "BPU")

                .Group("BAPP Team Sharing", role: RoleModules.BAPPTeamSharingGeneral)
                    .Link("BAPP Team Idea Sharing", "Search", "BappTeamIdea", role: RoleModules.BAPPTeamSharingGeneral)
                    .Link("BAPP Teams", "Index", "BappTeam", role: RoleModules.BAPPTeamSharingGeneral, mustBeAdminInRole: true)
                    .Link("Safety Implementation Categories", "Index", "SafetyImplementationCategory", role: RoleModules.BAPPTeamSharingGeneral, mustBeAdminInRole: true)

                .Group("Contractors")
                    .Link("Contractors", "Search", "Contractor", "Contractors", RoleModules.ContractorsGeneral)
                    .Link("Contractor Users", "Search", "ContractorUser", area: "Contractors", role: RoleModules.ContractorsGeneral)
                    .Link("Agreements", "Search", "ContractorAgreement", "Contractors", RoleModules.ContractorsAgreements)
                    .Link("Insurance", "Search", "ContractorInsurance", "Contractors", RoleModules.ContractorsGeneral)
                    .Link("Inventory", "/Modules/Contractors/ContractorInventory.aspx")
                    .Link("Current Inventory Report", "/Reports/Contractors/CurrentInventory.aspx")
                    .BeginSection("Lookups")
                        .Link("Contractor Work Categories", "/Modules/Contractors/ContractorWorkCategories.aspx")
                        .Link("Insurance Minimum Requirements", "/Modules/Contractors/ContractorInsuranceMinimumRequirements.aspx")
                    .EndSection()

                .Group("Customer")
                .Link("Customer Survey Data", "/Modules/Customer/CustomerSurveyData.aspx")
                    .Link("Critical Customers", "/Modules/Customer/CriticalCustomers.aspx")
                    .BeginSection("H2O Program")
                        .Link("H2O Surveys", "/Modules/Customer/H2OSurveys.aspx")
                        .Link("H2O Survey Reports", "/Reports/Customer/H2OSurveyReport.aspx")
                        .Link("H2O Survey Monthly Reports", "/Reports/Customer/H2OSurveyMonthlyReport.aspx")
                    .EndSection()
                    .BeginSection("Meter Routes")
                        .Link("Meter Routes", "/Modules/Customer/MeterRoutes.aspx")
                        .Link("Meter Route Details", "/Modules/Customer/MeterRouteDetails.aspx")
                    .EndSection()
                    .BeginSection("Premises")
                        .Link("Account Statuses", "/Modules/Customer/AccountStatuses.aspx")
                        .Link("Billing Classifications", "/Modules/Customer/BillingClassifications.aspx")
                        .Link("Collection Requirements", "/Modules/Customer/CollectionRequirements.aspx")
                        .Link("Districts", "/Modules/Customer/Districts.aspx")
                        .Link("Meter Locations", "/Modules/Customer/MeterLocations.aspx")
                        .Link("Meter Periodic Testing Requirements", "/Modules/Customer/MeterPeriodicTestingRequirements.aspx")
                        .Link("Meter Reading Codes", "/Modules/Customer/MeterReadingCodes.aspx")
                        .Link("Meter Sizes", "/Modules/Customer/MeterSizes.aspx")
                        .Link("Meter Water Utility Types", "/Modules/Customer/MeterWaterUtilityTypes.aspx")
                        .Link("Notice Codes", "/Modules/Customer/NoticeCodes.aspx")
                        .Link("Premises", "Search", "Premise", "Customer")
                        .Link("Process Sequences", "/Modules/Customer/ProcessSequences.aspx")
                        .Link("Service Order Categories", "/Modules/Customer/ServiceOrderCategories.aspx")
                        .Link("Service Order Codes", "/Modules/Customer/ServiceOrderCodes.aspx")
                        .Link("Service Order Code Types", "/Modules/Customer/ServiceOrderCodeTypes.aspx")
                        .Link("Service Order Schedule Types", "/Modules/Customer/ServiceOrderScheduleTypes.aspx")
                        .Link("Service Order Types", "/Modules/Customer/ServiceOrderTypes.aspx")
                        .Link("Service Utility Types", "/Modules/Customer/ServiceUtilityTypes.aspx")
                        .Link("Technical Master Data", "Search", "SAPTechnicalMasterAccount", "Customer")
                    .EndSection()
                    .BeginSection("Reports")
                        .Link("Fire Services (Inactive) Estimated Back Bill", "/Reports/Data/Services/FireServiceEstimatedBackBilling.aspx")
                        .Link("Fire Services (Inactive) Recovered Billing", "/Reports/Data/Services/FireServiceRecoveredBilling.aspx")
                        .Link("Fire Services (Inactive) Monthly Billing", "/Reports/Data/Services/FireServiceMonthlyBilling.aspx")
                    .EndSection()
                .Group("Engineering")
                        .Link("Arc Flash Studies", "Search", "ArcFlashStudy", "Engineering")
                        // MC-5096 requested the ArcFlashCompletions menu be hidden for now - Lynn 2/2/23
                        //.Link("Arc Flash Completions", "Index", "ArcFlashCompletion", "Engineering", RoleModules.EngineeringArcFlash)
                        .Link("AWIA Compliance", "Search", "AwiaCompliance", "Engineering", RoleModules.EngineeringRiskRegister)
                        .Link("Risk Register", "Search", "RiskRegisterAsset", "Engineering", RoleModules.EngineeringRiskRegister)
                .Group("Environmental", role: RoleModules.EnvironmentalGeneral)
                    .Link("Regulations", "Search", "Regulation", role: RoleModules.HumanResourcesSampleSites)
                    .Link("Permits", "Search", "EnvironmentalPermit", "Environmental")
                    .BeginSection("Allocations")
                        .Link("Allocation Groupings", "Search", "AllocationPermit", "Environmental")
                        .Link("Allocation Transactions", "/Modules/Production/AllocationTransactions.aspx")
                        .Link("Allocation Withdrawal Nodes", "Search", "AllocationPermitWithdrawalNode", "Environmental")
                    .EndSection()
                    .Link("Geological Formations", "/Modules/Production/GeologicalFormations.aspx")
                    .BeginSection("PWSID")
                        .Link("PWSID", "Search", "PublicWaterSupply", role: RoleModules.EnvironmentalWaterSystems)
                        .Link("PWSID Capacity", "Search", "PublicWaterSupplyFirmCapacity", "Environmental", RoleModules.EngineeringPWSIDCapacity)
                        .Link("PWSID Pressure Zones", "Search", "PublicWaterSupplyPressureZone", "Environmental")
                        .Link("PWSID Customer Data", "/Modules/Production/PWSIDCustomerData.aspx")
                        .Link("Water Sample Compliance", "Search", "WaterSampleComplianceForm", "Environmental")
                    .EndSection()
                    .BeginSection("Environmental Non-Compliance Events")
                        .Link("Environmental Non-Compliance Events", "Search", "EnvironmentalNonComplianceEvent", "Environmental")
                        .Link("Environmental Non-Compliance Event SubTypes", "Index", "EnvironmentalNonComplianceEventSubType", "Environmental")
                    .EndSection()
                    .BeginSection("Chemicals")
                        .Link("Chemicals", "Search", "Chemical", "Environmental")
                        .Link("Chemical Deliveries", "Search", "ChemicalDelivery", "Environmental")
                        .Link("Chemical Inventory Transactions", "Search", "ChemicalInventoryTransaction", "Environmental")
                        .Link("Chemical Storage", "Search", "ChemicalStorage", "Environmental")
                        .Link("Chemical Storage Location", "Search", "ChemicalStorageLocation", "Environmental")
                        .Link("Chemical Unit Costs", "Search", "ChemicalUnitCost", "Environmental")
                        .Link("Chemical Vendors", "Search", "ChemicalVendor", "Environmental")
                        .Link("Chemical Warehouse Numbers", "Search", "ChemicalWarehouseNumber", "Environmental")
                    .EndSection()
                    .BeginSection("Wastewater Systems")
                        .Link("Wastewater Systems", "Search", "WasteWaterSystem", "Environmental", role: RoleModules.EnvironmentalWasteWaterSystems)
                        .Link("End Of Pipe Exceedance", "Search", "EndOfPipeExceedance", "Environmental")
                        .Link("Wastewater System Basins", "Search", "WasteWaterSystemBasin", "Environmental")
                    .EndSection()
                        .BeginSection("Admin")
                        .Link("Allocation Categories", "", "AllocationCategory")
                    .EndSection()

                .Group("Events", role: RoleModules.EventsEvents)
                    .Link("Events", "Search", "Event", "Events")
                    .Link("Event Documents", "Search", "EventDocument", "Events")
                    .Link("Event Types", "Index", "EventType", "Events")

                .Group("Facilities & Properties")
                        .Link("Below Ground Hazard", "Search", "BelowGroundHazard", "Facilities")
                        .Link("Easements", "Search", "Easement", "Facilities")
                    .BeginSection("Facilities")
                        .Link("Community Right To Know", "Search", "CommunityRightToKnow", "Facilities")
                        .Link("Response Plans", "Search", "EmergencyResponsePlan", "Facilities")
                        .Link("Equipment", "Search", "Equipment")
                        .Link("Equipment Purposes", "Search", "EquipmentPurpose")
                        .Link("Equipment Types", "Index", "EquipmentType")
                        .Link("SCADA Readings", "Search", "ScadaReading", "Facilities")
                        .Link("Facilities", "Search", "Facility")
                        .Link("Facility Areas", "Index", "FacilityArea", "Facilities")
                        .Link("Facility Sub Areas", "Index", "FacilitySubArea", "Facilities")
                        .Link("Filter Media", "Search", "FilterMedia")
                        .BeginSection("Inspections")
                            .Link("Tank Inspection", "Search", "TankInspection", "Facilities")
                        .EndSection()
                        .BeginSection("Admin")
                            .Link("Drill Frequency", "", "DrillFrequency")
                            .Link("Facility Costs Per kWh", "", "FacilityKwhCost")
                            .Link("Emergency Plan Categories", "", "EmergencyPlanCategory")
                            .Link("Emergency Plan Subcategories", "", "EmergencyPlanSubcategory")
                            .Link("Emergency Power Types", "", "EmergencyPowerType")
                            .Link("Equipment Categories", "", "EquipmentCategory")
                            .Link("Equipment Lifespans", "", "EquipmentLifespan")
                            .Link("Equipment Manufacturers", "Search", "EquipmentManufacturer")
                            .Link("Equipment Models", "Search", "EquipmentModel")
                            .Link("Equipment Statuses", "", "EquipmentStatus")
                            .Link("Equipment Subcategories", "", "EquipmentSubCategory")
                            .Link("Fuel Type", "", "FuelType")
                            .Link("Tabletop Frequency", "", "TabletopFrequency")
                            .Link("Trailer Hitch Types", "", "TrailerHitchType")
                            .Link("Transportation Requirements", "", "TransportationRequirement")
                            .Link("Water Types", "", "WaterType")
                        .EndSection()
                    .EndSection()
                    .BeginSection("Interconnections")
                        .Link("Interconnection Details", "Search", "Interconnection", "Facilities")
                        .Link("Interconnection Tests", "Search", "InterconnectionTest", "Facilities")
                    .EndSection()
                    .BeginSection("Main Crossing and Easement Inspection")
                        .Link("Main Crossing and Easement Inspection", "Search", "MainCrossing", area: "Facilities")
                        .BeginSection("Admin", mustBeSiteAdmin: true)
                            .Link("Assessment Rating", "", "MainCrossingInspectionAssessmentRating")
                            .Link("Construction Type", "", "ConstructionType")
                            .Link("Crossing Category", "", "CrossingCategory")
                            .Link("Crossing Type", "", "CrossingType")
                            .Link("Customer Range", "", "CustomerRange")
                            .Link("Pressure Zone", "", "PressureZone")
                            .Link("Support Structure", "", "SupportStructure")
                        .EndSection()
                    .EndSection()
                    .BeginSection("Processes", role: RoleModules.ProductionFacilities)
                        .Link("Process Stages", "Index", "ProcessStage")
                    //.Link("Processes", "Index", "Process", area: "Facilities") // Hide until future use
                    //.Link("Facility Processes", "Search", "FacilityProcess", area: "Facilities") // Hide until future use
                    //.Link("Facility Process Steps", "Search", "FacilityProcessStep", area: "Facilities") // Hide until future use
                    .EndSection()
                 .Group("Field Operations")
                    .Link("RTO", "/Modules/Maps/RealTimeOperations.aspx")
                    .Link("Critical Customers", "/Modules/Customer/CriticalCustomers.aspx")
                    .Link("Flushing Schedules", "/Modules/FieldServices/FlushingSchedules.aspx")
                    .Link("Premises", "Search", "Premise", "Customer")
                    .BeginSection("Forms")
                        .Link("Cutoff Saw Safety Form", "Search", "CutoffSawQuestionnaire")
                        .Link("Job Site Check Lists", "Search", "JobSiteCheckList", "HealthAndSafety", role: RoleModules.OperationsHealthAndSafety)
                        .Link("Lockout Form", "Search", "LockoutForm", "HealthAndSafety", role: RoleModules.OperationsLockoutForms)
                        .Link("Markout Damages", "Search", "MarkoutDamage", "FieldOperations")
                        .BeginSection("Lookups")
                            .Link("Lockout Devices", "Search", "LockoutDevice", "HealthAndSafety", role: RoleModules.OperationsHealthAndSafety)
                            .Link("Lockout Device Colors", "", "LockoutDeviceColor", role: RoleModules.OperationsHealthAndSafety)
                            .Link("Lockout Device Locations", "", "LockoutDeviceLocation", role: RoleModules.OperationsHealthAndSafety)
                            .Link("Lockout Reasons", "", "LockoutReason", role: RoleModules.OperationsHealthAndSafety)
                        .EndSection()
                    .EndSection()
                    //.BeginSection("Reports")
                    //    .Link("Markout Damage BPU", "Search", "MarkoutDamageBPU", "Reports")
                    //.EndSection()
                    .BeginSection("Images")
                        .Link("Tap Orders", "Search", "TapImage", "FieldOperations")
                        .Link("As Builts", "Search", "AsBuiltImage", "FieldOperations")
                        .Link("Valves", "Search", "ValveImage", "FieldOperations")
                        .Link("Upload Counts", "/Modules/FieldServices/UploadCount.aspx")
                        .Link("Users Today", "Search", "UserViewedDailyReport", "Management")
                    .EndSection()
                    .BeginSection("Lookups")
                        .Link("Functional Locations", "Search", "FunctionalLocation", area: "FieldOperations")
                    .EndSection()
                    .BeginSection("Municipalities")
                        .Link("Bonds", "Search", "Bond", "FieldOperations")
                        .Link("Bond Types", "Index", "BondType")
                    .EndSection()
                    .BeginSection("Wastewater")
                       .Link("Bodies of Water", "Search", "BodyOfWater")
                       .BeginSection("Sewer", role: RoleModules.FieldServicesAssets)
                            .Link("Sewer Opening", "Search", "SewerOpening", "FieldOperations")
                            .Link("Smart Cover Alerts", "Search", "SmartCoverAlert", "FieldOperations", role: RoleModules.FieldServicesAssets)
                            .Link("Sewer Opening Inspections", "Search", "SewerOpeningInspection", "FieldOperations")
                            .Link("NPDES Regulator Inspections", "Search", "NpdesRegulatorInspection", "FieldOperations")
                            .Link("Main Inspections / Cleaning", "Search", "SewerMainCleaning", "FieldOperations")
                            .Link("Overflows", "Search", "SewerOverflow", "FieldOperations")
                            .BeginSection("Reports")
                                .Link("Overflows", "/Reports/FieldServices/SewerOverflowReport.aspx")
                                .Link("Inspection / Cleaning Footage Summary", "Search", "SewerMainCleaningFootage", "Reports")
                            .EndSection()
                        .EndSection()
                    .EndSection()
                    .BeginSection("Water")
                        .Link("Contractor Meter Crews", "Search", "ContractorMeterCrew", "FieldOperations", role: RoleModules.FieldServicesMeterChangeOuts)
                        .Link("Hydrants", "Search", "Hydrant", "FieldOperations")
                        .Link("Hydrant Inspections", "Search", "HydrantInspection", "FieldOperations")
                        .BeginSection("Meter Change Outs", role: RoleModules.FieldServicesMeterChangeOuts)
                            .Link("Meter Change Outs", "Search", "MeterChangeOut", "FieldOperations", role: RoleModules.FieldServicesMeterChangeOuts)
                            .Link("Meter Change Out Completions", "Search", "MeterChangeOutCompletions", "Reports", role: RoleModules.FieldServicesMeterChangeOuts)
                            .Link("Meter Change Out Contracts", "Search", "MeterChangeOutContract", "FieldOperations", role: RoleModules.FieldServicesMeterChangeOuts)
                            .Link("Meter Change Out Schedule", "Index", "MeterChangeOutSchedule", "Reports", role: RoleModules.FieldServicesMeterChangeOuts)
                        .EndSection()
                        .Link("Meter Set", "Search", "ServiceInstallation", "FieldOperations")
                        .Link("Services", "Search", "Service", "FieldOperations")
                        .Link("Service Line Protection Investigation", "Search", "ServiceLineProtectionInvestigation", "ServiceLineProtection")
                        .BeginSection("Service Lookups")
                            .Link("Fire Districts", "Search", "FireDistrict", role: RoleModules.FieldServicesDataLookups)
                            .Link("Main Type", "", "MainType", "")
                            .Link("Restoration Type", "", "RestorationType", "")
                            .Link("Service Installation Purpose", "", "ServiceInstallationPurpose", "")
                            .Link("Service Installation Material", "Search", "ServiceInstallationMaterial", "FieldOperations")
                            .Link("Service Material", "", "ServiceMaterial", "")
                            .Link("Service Sizes", "", "ServiceSize", "FieldOperations")
                            //.Link("Service Type", "", "ServiceType", "FieldOperations")
                            .Link("Street Material", "", "StreetMaterial", "")
                        .EndSection()
                        .BeginSection("Short Cycle")
                            .Link("Work Orders", "Search", "ShortCycleWorkOrder", "ShortCycle")
                            .Link("Status Updates", "Search", "ShortCycleWorkOrderStatusUpdate", "ShortCycle")
                            .Link("Completions", "Search", "ShortCycleWorkOrderCompletion", "ShortCycle")
                            .Link("Time Confirmations", "Search", "ShortCycleWorkOrderTimeConfirmation", "ShortCycle")
                            .Link("Requests", "Search", "ShortCycleWorkOrderRequest", "ShortCycle")
                            .Link("BPEM Cases", "Search", "BusinessProcessExceptionManagementCase", "ShortCycle")
                            .Link("FSR Availability", "Search", "FieldServiceRepresentativeNonAvailability", "ShortCycle")
                            .Link("Assignments", "Search", "ShortCycleAssignment", "ShortCycle")
                        .EndSection()
                        .Link("Valves", "Search", "Valve", "FieldOperations")
                        .Link("Valve Inspections", "Search", "ValveInspection", "FieldOperations")
                        .Link("Blow Off Inspections", "Search", "BlowOffInspection", "FieldOperations")
                        .BeginSection("Meters")
                            .Link("Comparison Meters", "/Modules/FieldServices/MeterTestComparisonMeters.aspx")
                            .Link("Contractors", "/Modules/FieldServices/MeterContractors.aspx")
                            .Link("Meters", "/Modules/FieldServices/Meters.aspx")
                            .Link("Meter Tests", "/Modules/FieldServices/MeterTests.aspx")
                            .Link("Profiles", "/Modules/FieldServices/MeterProfiles.aspx")
                            .Link("Recorders", "/Modules/FieldServices/MeterRecorders.aspx")
                        .EndSection()
                        .Link("Echoshore Leak Alerts", "Search", "EchoshoreLeakAlert", "FieldOperations")
                    .EndSection()
                    .BeginSection("Work Management")
                        .Link("General (With Mapping)", "Search", "GeneralWorkOrder", "FieldOperations")
                        .Link("Create Work Order", "New", "WorkOrder", "FieldOperations")
                        .Link("Markout Planning (New)", "Search", "MarkoutPlanning", "FieldOperations", role: RoleModules.FieldServicesWorkManagement)
                        .Link("Pre-Planning", "Search", "WorkOrderPrePlanning", "FieldOperations", role: RoleModules.FieldServicesWorkManagement, mustBeAdminInRole: true)
                        .Link("Planning (new!)", "Search", "WorkOrderPlanning", "FieldOperations", role: RoleModules.FieldServicesWorkManagement, mustBeAdminInRole: true)
                        .Link("Scheduling", "Search", "WorkOrderScheduling", "FieldOperations", role: RoleModules.FieldServicesWorkManagement, mustBeAdminInRole: true)
                        .Link("Crew Assignments", "ShowCalendar", "CrewAssignment", area: "FieldOperations")
                        .Link("Finalization (new!)", "Search", "WorkOrderFinalization", "FieldOperations")
                        .Link("Supervisor Approval (new!)", "Search", "WorkOrderSupervisorApproval", "FieldOperations", role: RoleModules.FieldServicesWorkManagement, mustBeAdminInRole: true)
                        .Link("Stock To Issue (new!)", "Search", "WorkOrderStockToissue", "FieldOperations", role: RoleModules.FieldServicesWorkManagement, mustBeAdminInRole: true)
                        .Link("Restorations", "Search", "Restoration", area: "FieldOperations", role: RoleModules.FieldServicesWorkManagement, mustBeAdminInRole: true)
                        .Link("Restoration Processing (New)", "Search", "RestorationProcessing", "FieldOperations", role: RoleModules.FieldServicesWorkManagement)
                        .Link("Street Opening Permits", "https://permits.mapcall.net", openInNewWindow: true)
                        .Link("SOP Processing (new!)", "Search", "WorkOrderStreetOpeningPermitProcessing", "FieldOperations")
                        .Link("Traffic Control", "Search", "TrafficControlTicket", "FieldOperations", RoleModules.FieldServicesWorkManagement)
                        .Link("Spoils Processing (new!)", "Search", "SpoilRemoval", "FieldOperations", role: RoleModules.FieldServicesWorkManagement, mustBeAdminInRole: true)
                        .Link("OneCall Markout Tickets", "Search", "OneCallMarkoutTicket", "FieldOperations")
                        .Link("OneCall Markout Responses", "Search", "OneCallMarkoutResponse", "FieldOperations")
                        .Link("OneCall Markout Audit", "Search", "OneCallMarkoutAudit", "FieldOperations")
                        .Link("Invoices", "Search", "WorkOrderInvoice", "FieldOperations")
                        .Link("SAP Notifications", "Search", "SapNotification", "FieldOperations", RoleModules.FieldServicesAssets)
                        .BeginSection("Legacy", RoleModules.FieldServicesWorkManagement, mustBeAdminInRole: true)
                            .Link("General Search", "/Modules/WorkOrders/Views/WorkOrders/General/WorkOrderGeneralResourceView.aspx")
                            .Link("Markout Planning", "/Modules/WorkOrders/Views/WorkOrders/MarkoutPlanning/WorkOrderMarkoutPlanningResourceView.aspx", role: RoleModules.FieldServicesWorkManagement, mustBeAdminInRole: true)
                            .Link("Planning", "/Modules/WorkOrders/Views/WorkOrders/Planning/WorkOrderPlanningResourceView.aspx")
                            .Link("Finalization", "/Modules/WorkOrders/Views/WorkOrders/Finalization/WorkOrderFinalizationResourceView.aspx")
                            .Link("Supervisor Approval", "/Modules/WorkOrders/Views/WorkOrders/SupervisorApproval/WorkOrderSupervisorApprovalResourceView.aspx")
                            .Link("Restoration Processing", "/Modules/WorkOrders/Views/WorkOrders/RestorationProcessing/WorkOrderRestorationProcessingResourceView.aspx", role: RoleModules.FieldServicesWorkManagement, mustBeAdminInRole: true)
                            .Link("Stock To Issue", "/Modules/WorkOrders/Views/WorkOrders/StockToIssue/WorkOrderStockToIssueResourceView.aspx", role: RoleModules.FieldServicesWorkManagement, mustBeAdminInRole: true)
                            .Link("Spoil Final Processing Locations", "/Modules/WorkOrders/Views/SpoilFinalProcessingLocations/SpoilFinalProcessingLocationResourceView.aspx", role: RoleModules.FieldServicesWorkManagement, mustBeAdminInRole: true)
                            .Link("Spoils Processing", "/Modules/WorkOrders/Views/SpoilRemovals/SpoilRemovalResourceView.aspx", role: RoleModules.FieldServicesWorkManagement, mustBeAdminInRole: true)
                            .Link("SOP Processing", "/Modules/WorkOrders/Views/WorkOrders/SOPProcessing/SOPProcessingResourceView.aspx", role: RoleModules.FieldServicesWorkManagement, mustBeAdminInRole: true)
                        .EndSection()
                        .BeginSection("Admin", role: RoleModules.FieldServicesWorkManagement, mustBeAdminInRole: true)
                            .Link("Materials", "Search", "Material", role: RoleModules.FieldServicesWorkManagement, mustBeAdminInRole: true)
                            .Link("Operating Center Stocked Materials", "Search", "OperatingCenterStockedMaterial", role: RoleModules.FieldServicesWorkManagement, mustBeAdminInRole: true)
                            .Link("Restoration Accounting Codes", "/Modules/WorkOrders/Views/RestorationAccountingCodes/RestorationAccountingCodeResourceView.aspx", role: RoleModules.FieldServicesWorkManagement, mustBeAdminInRole: true)
                            .Link("Restoration Product Codes", "/Modules/WorkOrders/Views/RestorationProductCodes/RestorationProductCodeResourceView.aspx", role: RoleModules.FieldServicesWorkManagement, mustBeAdminInRole: true)
                            .Link("Work Descriptions", "Search", "WorkDescription", area: "FieldOperations", role: RoleModules.FieldServicesWorkManagement, mustBeAdminInRole: true)
                            .Link("Crew Management", "Search", "Crew", "FieldOperations", role: RoleModules.FieldServicesWorkManagement, mustBeAdminInRole: true)
                            .Link("Restoration Type Costs", "Search", "RestorationTypeCost", "FieldOperations", role: RoleModules.FieldServicesWorkManagement, mustBeAdminInRole: true)
                            .Link("Stock Source Locations", "Search", "StockLocation", "FieldOperations", role: RoleModules.FieldServicesWorkManagement, mustBeAdminInRole: true)
                            .Link("Spoil Type Disposal Costs", "Search", "OperatingCenterSpoilRemovalCost", "FieldOperations", role: RoleModules.FieldServicesWorkManagement, mustBeAdminInRole: true)
                            .Link("Spoil Storage Locations", "Search", "SpoilStorageLocation", "FieldOperations", role: RoleModules.FieldServicesWorkManagement, mustBeAdminInRole: true)
                            .Link("Spoil Final Processing Locations(new!)", "Search", "SpoilFinalProcessingLocation", "FieldOperations", role: RoleModules.FieldServicesWorkManagement, mustBeAdminInRole: true)
                            .Link("Billing Parties", "Search", "BillingParty", "FieldOperations", RoleModules.FieldServicesWorkManagement)
                        .EndSection()
                    .EndSection()

                .Group("Health & Safety")
                    .Link("APC/Facility Inspection Items", "Search", "ApcInspectionItem", "HealthAndSafety", role: RoleModules.OperationsHealthAndSafety)
                    .Link("Auto/General Liability Claim", "Search", "GeneralLiabilityClaim", "HealthAndSafety")
                    .Link("Confined Space", "Search", "ConfinedSpaceForm", "HealthAndSafety", role: RoleModules.OperationsLockoutForms)
                    .Link("Gas Monitors", "Search", "GasMonitor", "HealthAndSafety")
                    .Link("Gas Monitor Calibrations", "Search", "GasMonitorCalibration", "HealthAndSafety")
                    .Link("Job Safety Analysis", "Search", "JobSiteSafetyAnalysis")
                    .Link("Job Observation", "Search", "JobObservation", "HealthAndSafety")
                    .Link("Lockout Form", "Search", "LockoutForm", "HealthAndSafety", role: RoleModules.OperationsHealthAndSafety)
                    .Link("Red Tag Permits", "Search", "RedTagPermit", "HealthAndSafety", role: RoleModules.ProductionWorkManagement)
                    .Link("Production Pre Job Safety Brief", "Search", "ProductionPreJobSafetyBrief", "Production")
                    .Link("Tailgate Talks", "Search", "TailgateTalk", "HealthAndSafety")
                    .Link("Tailgate Topic", "Search", "TailgateTalkTopic", "HealthAndSafety")
                    .BeginSection("Incidents")
                        .Link("Incidents", "Search", "Incident")
                        .Link("Near Misses", "Search", "NearMiss", "HealthAndSafety")
                        .Link("Near Misses Action Items", "Search", "NearMissActionItem", "HealthAndSafety")
                        .BeginSection("Lookups")
                        .Link("At Risk Behaviors", "Index", "AtRiskBehaviorSection", "Operations")
                            .Link("Incident Classifications", "", "IncidentClassification")
                            .Link("Incident Types", "", "IncidentType")
                            .Link("General Liability Codes", "", "GeneralLiabilityCode")
                            .Link("Motor Vehicle Codes", "", "MotorVehicleCode")
                            .Link("Drug And Alcohol Testing Decision", "", "IncidentDrugAndAlcoholTestingDecision")
                            .Link("Drug And Alcohol Testing Result", "", "IncidentDrugAndAlcoholTestingResult")
                        .EndSection()
                    .EndSection()

                .Group("Human Resources")
                    .Link("Covid Issues", "Search", "CovidIssue", area: "HumanResources", role: RoleModules.HumanResourcesCovid)
                    .Link("Documents", "/Modules/HR/Documents.aspx")
                    .BeginSection("Absence")
                        .Link("Absence Notifications", "Search", "AbsenceNotification", area: "Operations")
                        .Link("FMLA Cases", "Search", "FamilyMedicalLeaveActCase", area: "Operations")
                    .EndSection()
                    .BeginSection("Employee")
                        .BeginSection("Drivers Licenses")
                            .Link("Drivers Licenses", "Search", "DriversLicense")
                            .Link("Medical Certificates", "Search", "MedicalCertificate")
                            .Link("Cert. of Violation", "Search", "ViolationCertificate")
                            .BeginSection("Reports")
                              .Link("CDL Abstract", "Search", "CommercialDriversLicenseAbstract", area: "Reports")
                              .Link("CDL Compliance", "Search", "CommercialDriversLicenseCompliance", area: "Reports")
                              .Link("CDL Cert. Violation Due", "Search", "CommercialDriversLicenseViolationCertificatesDue", area: "Reports")
                              .Link("CDL Medical Cert. Due", "Search", "CommercialDriversLicenseMedicalCertificatesDue", area: "Reports")
                              .Link("Drivers License Renewals", "Search", "CommercialDriversLicensesDue", area: "Reports")
                            .EndSection()
                        .EndSection()
                        .BeginSection("System Operator Licenses")
                            .Link("System Operator Licenses", "Search", "OperatorLicense")
                            .BeginSection("Reports")
                                .Link("System Operator License Report", "Search", "OperatorLicenseReport", "Reports")
                            .EndSection()
                        .EndSection()
                        .Link("Employees", "Search", "Employee")
                        .Link("Employee Accountability Action Taken", "Search", "EmployeeAccountabilityAction", area: "HumanResources")
                        .Link("Employee / User Reconciliation", "Search", "EmployeeUserReconciliation", area: "Reports")
                        .Link("Employee Head Count", "Search", "EmployeeHeadCount", area: "HumanResources")
                        .Link("Hep B Vaccinations", "Search", "HepatitisBVaccination")
                        .Link("Ranking Numbers", "/Modules/HR/Administrator/NextRankingNumber.aspx")
                        .Link("Personnel Areas", "Search", "PersonnelArea")
                        .Link("Positions", "/Modules/HR/Employee/Positions.aspx")
                        .Link("Position Controls", "/Modules/HR/Administrator/EmployeePositionControls.aspx")
                        .Link("Position Control Summary", "/Reports/HR/Employee/EmployeePositionControlSummary.aspx")
                        .Link("Position Groups", "Search", "PositionGroup", "", RoleModules.HumanResourcesPositions)
                        .Link("Position Group Common Names", "Index", "PositionGroupCommonName", mustBeSiteAdmin: true)
                        .Link("Position History", "/Modules/HR/Employee/PositionHistory.aspx")
                        .Link("Position Postings", "/Modules/HR/Employee/PositionPostings.aspx")
                        .Link("SAP Company Codes", "Index", "SAPCompanyCode", mustBeSiteAdmin: true)
                        .Link("Sick Bank", "/Modules/HR/Employee/SickBank.aspx")
                        .Link("Staffing Hours", "/Modules/HR/Employee/StaffingHours.aspx")
                        .Link("Union Affiliation", "/Reports/HR/UnionAffiliation.aspx")
                    .EndSection()
                    .BeginSection("Union")
                        .Link("Union", "Search", "Union")
                        .Link("Locals", "Search", "Local")
                        .Link("Contracts", "Search", "UnionContract")
                        .Link("Contract Proposals", "Search", "UnionContractProposal")
                        .Link("Primary Drivers for Proposals", "Index", "PrimaryDriverForProposal")
                        .Link("Divisions", "Index", "Division")
                        .Link("Grievances", "Search", "Grievance")
                        .BeginSection("Reports")
                            .Link("Contract Proposals", "/Modules/HR/Union/ContractProposalsReport.aspx")
                            .Link("Log", "Search", "AuditLogEntryUnion", "Reports")
                        .EndSection()
                    .EndSection()

                .Group("Management")
                    .Link("Absence Notifications", "Search", "AbsenceNotification", area: "Operations")
                .Link("Regulations", "Search", "Regulation", role: RoleModules.HumanResourcesSampleSites)
                    .Link("User Tracking", "Search", "UserTracking", "Operations", role: RoleModules.ManagementGeneral)

                .Group("MapCall")
                    .Link("Home Page", "/Modules/HR/Home.aspx")
                    .Link("Help", "/Modules/mvc/HelpTopic/Search")
                    .Link("Notifications", "/Modules/Notifications.aspx")
                    .BeginSection("MapCall™")
                        .Link("Street Opening Permits", "https://permits.mapcall.net", openInNewWindow: true)
                        .Link("Streets", "Search", "Street", role: RoleModules.FieldServicesDataLookups)
                        .Link("Users", "Search", "User", string.Empty)
                    .EndSection()

                .Group("Planned Work")
                    .Link("Task Groups", "Index", "TaskGroup", "Production")
                    .Link("Task Group Categories", "Index", "TaskGroupCategory", "Production")
                    .Link("Maintenance Plans", "Search", "MaintenancePlan", "Production")

                .Group("Production/Treatment")
                    .Link("Asset Reliability", "Search", "AssetReliability", "Production")
                    .Link("Equipment", "Search", "Equipment")
                    .Link("Well Tests", "Search", "WellTest", "Production")
                    .BeginSection("Work Management")
                        .Link("Assignments", "Search", "EmployeeAssignment", "Production")
                        .Link("Create Work Order", "New", "ProductionWorkOrder", "Production")
                        .Link("Maintenance Plans", "Search", "SAPMaintenancePlan", "SAP")
                        .Link("Scheduling", "Search", "Scheduling", "Production")
                        .Link("Work Order Search", "Search", "ProductionWorkOrder", "Production")
                    .EndSection()
              .EndSection()

              .Group("System Delivery/System Flows")
                 .Link("Sys Del / Flow Entry", "New", "SystemDeliveryEntry", "Production")
                 .Link("Sys Del / Flow Search", "Search", "SystemDeliveryEntry", "Production")
                 .Link("Non Rev Water Unbilled", "Search", "NonRevenueWaterEntry", "Production")
              .EndSection()

                // WO0000000197410 requested that production menu links be hidden. -Ross 10/23/2017

                //.Group("Production")
                //    .Link("Process Changes", "/Modules/Production/ProcessChanges.aspx")
                //    .BeginSection("Account & Budgets")
                //        .Link("Utility Accounts", "/Modules/Production/UtilityAccounts.aspx")
                //        .Link("Utility Rates", "/Modules/Production/UtilityRates.aspx")
                //    .EndSection()
                //    .BeginSection("Chemicals")
                //        .Link("Chemicals", "/Modules/Production/Chemicals.aspx")
                //        .Link("Deliveries", "/Modules/Production/Deliveries.aspx")
                //        .Link("Dosage Budget", "/Modules/Production/Budget.aspx")
                //        .Link("Inventory", "/Modules/Production/Inventory.aspx")
                //        .Link("Storage", "/Modules/Production/Storage.aspx")
                //        .Link("UnitCost", "/Modules/Production/UnitCost.aspx")
                //        .Link("Vendors", "/Modules/Production/Vendors.aspx")
                //        .Link("Warehouse Numbers", "/Modules/Production/WarehouseNumbers.aspx")
                //    .EndSection()
                //    .BeginSection("System Delivery")
                //        .Link("Accounting", "/Modules/Production/SystemDelivery.aspx")
                //        .Link("SysDel_Facility", "/Modules/Production/SystemDeliveryBudget.aspx")
                //    .EndSection()

                .Group("Project Management")
                    .BeginSection("Estimating Projects")
                        .Link("Estimating Projects", "Search", "EstimatingProject", "ProjectManagement")
                        .BeginSection("Admin")
                            .Link("Company Labor Costs", "Index", "CompanyLaborCost", "ProjectManagement")
                            .Link("Contractor Labor Costs", "Index", "ContractorLaborCost", "ProjectManagement")
                            .Link("Contractor Override Labor Costs", "Search", "ContractorOverrideLaborCost", "ProjectManagement")
                            .Link("Estimating Project Types", "Index", "EstimatingProjectType", "ProjectManagement")
                            .Link("Permit Types", "Index", "PermitType", "ProjectManagement")
                        .EndSection()
                    .EndSection()
                    .Link("Projects-IP", "Search", "InvestmentProject", "ProjectManagement")
                    .EndSection()
                    .BeginSection("Projects-RP")
                        .Link("RP-Large Services", "Search", "LargeServiceProject", "ProjectManagement")
                        .Link("RP-Mains\\Valves", "Search", "RecurringProject", "ProjectManagement")
                        .BeginSection("Lookups")
                            .Link("Lookup Types", "Index", "PipeDataLookupType")
                            .Link("Lookup Values", "Index", "PipeDataLookupValue")
                            .Link("High Cost Factors", "Index", "HighCostFactor")
                            .Link("Pipe Diameters", "Index", "PipeDiameter")
                            .Link("Pipe Materials", "Index", "PipeMaterial")
                            .Link("Project Types", "Index", "RecurringProjectType")
                            .Link("Project Statuses", "Index", "RecurringProjectStatus")
                            .Link("Regulatory Statuses", "Index", "RecurringProjectRegulatoryStatus")
                        .EndSection()
                        .BeginSection("Reports")
                            .Link("Project List", "Search", "RecurringProjectList", "Reports")
                        .EndSection()
                    .EndSection()
                    .BeginSection("Projects-DV")
                        .Link("Projects-DV", "Search", "DevelopmentProject", "ProjectManagement")
                        .Link("Project Updates DV", "/Modules/Engineering/ProjectUpdatesDV.aspx")
                        .BeginSection("Lookups")
                            .Link("Development Project Categories", "", "DevelopmentProjectCategory")
                        .EndSection()
                    .EndSection()
                    .Link("Roadway Improvement Notifications", "Search", "RoadwayImprovementNotification", "ProjectManagement")
                    .Link("Roadway Improvement Notification Street Report", "Search", "RoadwayImprovementNotificationStreet", "ProjectManagement")
                .Group("Training", role: RoleModules.OperationsTrainingRecords)
                    .Link("Training Modules", "Search", "TrainingModule")
                    .Link("Training Records", "Search", "TrainingRecord")
                    .Link("Training Requirements", "Search", "TrainingRequirement")
                    .Link("Standard Operating Procedures", "Search", "StandardOperatingProcedure", role: RoleModules.ManagementGeneral)
                    .BeginSection("Lookups")
                        .Link("Job Title Common Name", "", "JobTitleCommonName")
                        .Link("Process Stage", "", "ProcessStage")
                        .Link("Program Coordinators", "", "TrainingContactHoursProgramCoordinator")
                        .Link("Training Module Category", "", "TrainingModuleCategory")
                        .Link("Training Class Location", "", "ClassLocation")
                    .EndSection()
                    .BeginSection("Reports")
                        .Link("Required Employee Training", "Search", "EmployeeTraining", "Reports")
                        .Link("Employee Training By Date", "Search", "EmployeeTrainingByDate", "Reports")
                        .Link("Employee Training Export", "Search", "EmployeeTrainingRecordExport", "Reports")
                        .Link("Employee Training Overview", "Search", "OperatingCenterTrainingOverview", "Reports")
                        .Link("Employee Training Summary", "Search", "OperatingCenterTrainingSummary", "Reports")
                        .Link("Classification Sum", "Search", "TrainingClassificationSum", "Reports")
                        .Link("Total Hours", "Search", "TrainingTotalHours", "Reports")
                    .EndSection()

                .Group("Water Quality")
                    .Link("Analysts", "Index", "BacterialWaterSampleAnalyst", "WaterQuality", role: RoleModules.WaterQualityGeneral, mustBeAdminInRole: true)
                    .Link("Regulations", "Search", "Regulation", role: RoleModules.HumanResourcesSampleSites)
                    .Link("Sample Sites", "Search", "SampleSite", "WaterQuality")
                    .Link("Water Constituents", "Search", "WaterConstituent", "WaterQuality")
                    .Link("Sample ID Matrix", "Search", "SampleIdMatrix", "WaterQuality")
                    .Link("Samples", "Search", "WaterSample", "WaterQuality")
                    .Link("Samples Bacti", "Search", "BacterialWaterSample", "WaterQuality")
                    .Link("Sample Plans", "Search", "SamplePlan", "WaterQuality")
                    .Link("WQ Complaints", "Search", "WaterQualityComplaint", "WaterQuality")

                .Group("Fleet & Communications")
                    .Link("Vehicles", "Search", "Vehicle", "FleetManagement")
                    .Link("EZ Pass", "Index", "VehicleEZPass", "FleetManagement")
                    .Link("Vehicle Tracking", "https://www.road.com/application/signon/secured/login.html", openInNewWindow: true)
                    .BeginSection("Reports")
                        .Link("Vehicle Utilization", "Search", "VehicleUtilization", "Reports")
                    .EndSection()

                .Group("Reports", "/Modules/Mvc/Reports/") // TODO: Group needs an action/controller/area overload like link has.
                .Group("Logout", "/logout.aspx");
        }
    }
}
