//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MapCall.SAP.CompleteScheduledUnscheduledWOWS
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://amwater.com/EAM/0009/MAPCALL/CompleteWorkOrder", ConfigurationName="CompleteScheduledUnscheduledWOWS.CompleteScheduledUnscheduledWO_OB_SYN")]
    public interface CompleteScheduledUnscheduledWO_OB_SYN {
        // CODEGEN: Generating message contract since the operation CompleteScheduledUnscheduledWO_OB_SYN is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MapCall.SAP.CompleteScheduledUnscheduledWOWS.CompleteScheduledUnscheduledWO_OB_SYNResponse CompleteScheduledUnscheduledWO_OB_SYN(MapCall.SAP.CompleteScheduledUnscheduledWOWS.CompleteScheduledUnscheduledWO_OB_SYNRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        System.Threading.Tasks.Task<MapCall.SAP.CompleteScheduledUnscheduledWOWS.CompleteScheduledUnscheduledWO_OB_SYNResponse> CompleteScheduledUnscheduledWO_OB_SYNAsync(MapCall.SAP.CompleteScheduledUnscheduledWOWS.CompleteScheduledUnscheduledWO_OB_SYNRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://amwater.com/EAM/0009/MAPCALL/CompleteWorkOrder")]
    public partial class CompleteScheduledUnscheduledWO : object, System.ComponentModel.INotifyPropertyChanged {
        private CompleteScheduledUnscheduledWOUnscheduledWORequest unscheduledWORequestField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public CompleteScheduledUnscheduledWOUnscheduledWORequest UnscheduledWORequest {
            get {
                return this.unscheduledWORequestField;
            }
            set {
                this.unscheduledWORequestField = value;
                this.RaisePropertyChanged("UnscheduledWORequest");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://amwater.com/EAM/0009/MAPCALL/CompleteWorkOrder")]
    public partial class CompleteScheduledUnscheduledWOUnscheduledWORequest : object, System.ComponentModel.INotifyPropertyChanged {
        private CompleteScheduledUnscheduledWOUnscheduledWORequestTimeConfirmation[] timeConfirmationField;
        
        private CompleteScheduledUnscheduledWOUnscheduledWORequestChangeOrder[] changeOrderField;
        
        private CompleteScheduledUnscheduledWOUnscheduledWORequestGoodsIssue[] goodsIssueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TimeConfirmation", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public CompleteScheduledUnscheduledWOUnscheduledWORequestTimeConfirmation[] TimeConfirmation {
            get {
                return this.timeConfirmationField;
            }
            set {
                this.timeConfirmationField = value;
                this.RaisePropertyChanged("TimeConfirmation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ChangeOrder", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public CompleteScheduledUnscheduledWOUnscheduledWORequestChangeOrder[] ChangeOrder {
            get {
                return this.changeOrderField;
            }
            set {
                this.changeOrderField = value;
                this.RaisePropertyChanged("ChangeOrder");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("GoodsIssue", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public CompleteScheduledUnscheduledWOUnscheduledWORequestGoodsIssue[] GoodsIssue {
            get {
                return this.goodsIssueField;
            }
            set {
                this.goodsIssueField = value;
                this.RaisePropertyChanged("GoodsIssue");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://amwater.com/EAM/0009/MAPCALL/CompleteWorkOrder")]
    public partial class CompleteScheduledUnscheduledWOUnscheduledWORequestTimeConfirmation : object, System.ComponentModel.INotifyPropertyChanged {
        private string orderNoField;
        
        private string dateCompletedField;
        
        private string employeeField;
        
        private string actualWorkField;
        
        private string finalizeField;
        
        private string startDateField;
        
        private string startTimeField;
        
        private string endDateField;
        
        private string endTimeField;
        
        private string capitalizedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string OrderNo {
            get {
                return this.orderNoField;
            }
            set {
                this.orderNoField = value;
                this.RaisePropertyChanged("OrderNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string DateCompleted {
            get {
                return this.dateCompletedField;
            }
            set {
                this.dateCompletedField = value;
                this.RaisePropertyChanged("DateCompleted");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Employee {
            get {
                return this.employeeField;
            }
            set {
                this.employeeField = value;
                this.RaisePropertyChanged("Employee");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string ActualWork {
            get {
                return this.actualWorkField;
            }
            set {
                this.actualWorkField = value;
                this.RaisePropertyChanged("ActualWork");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Finalize {
            get {
                return this.finalizeField;
            }
            set {
                this.finalizeField = value;
                this.RaisePropertyChanged("Finalize");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string StartDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
                this.RaisePropertyChanged("StartDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string StartTime {
            get {
                return this.startTimeField;
            }
            set {
                this.startTimeField = value;
                this.RaisePropertyChanged("StartTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string EndDate {
            get {
                return this.endDateField;
            }
            set {
                this.endDateField = value;
                this.RaisePropertyChanged("EndDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string EndTime {
            get {
                return this.endTimeField;
            }
            set {
                this.endTimeField = value;
                this.RaisePropertyChanged("EndTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string Capitalized {
            get {
                return this.capitalizedField;
            }
            set {
                this.capitalizedField = value;
                this.RaisePropertyChanged("Capitalized");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://amwater.com/EAM/0009/MAPCALL/CompleteWorkOrder")]
    public partial class CompleteScheduledUnscheduledWOUnscheduledWORequestChangeOrder : object, System.ComponentModel.INotifyPropertyChanged {
        private string workOrderDescField;
        
        private string pMActTypeField;
        
        private string notesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string WorkOrderDesc {
            get {
                return this.workOrderDescField;
            }
            set {
                this.workOrderDescField = value;
                this.RaisePropertyChanged("WorkOrderDesc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string PMActType {
            get {
                return this.pMActTypeField;
            }
            set {
                this.pMActTypeField = value;
                this.RaisePropertyChanged("PMActType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Notes {
            get {
                return this.notesField;
            }
            set {
                this.notesField = value;
                this.RaisePropertyChanged("Notes");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://amwater.com/EAM/0009/MAPCALL/CompleteWorkOrder")]
    public partial class CompleteScheduledUnscheduledWOUnscheduledWORequestGoodsIssue : object, System.ComponentModel.INotifyPropertyChanged {
        private string documentDateField;
        
        private string postingDateField;
        
        private string operatingCenterPlantField;
        
        private string sAPOrderNumberField;
        
        private string partNumberField;
        
        private string quantityField;
        
        private string sAPStockLocationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string DocumentDate {
            get {
                return this.documentDateField;
            }
            set {
                this.documentDateField = value;
                this.RaisePropertyChanged("DocumentDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string PostingDate {
            get {
                return this.postingDateField;
            }
            set {
                this.postingDateField = value;
                this.RaisePropertyChanged("PostingDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string OperatingCenterPlant {
            get {
                return this.operatingCenterPlantField;
            }
            set {
                this.operatingCenterPlantField = value;
                this.RaisePropertyChanged("OperatingCenterPlant");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string SAPOrderNumber {
            get {
                return this.sAPOrderNumberField;
            }
            set {
                this.sAPOrderNumberField = value;
                this.RaisePropertyChanged("SAPOrderNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string PartNumber {
            get {
                return this.partNumberField;
            }
            set {
                this.partNumberField = value;
                this.RaisePropertyChanged("PartNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
                this.RaisePropertyChanged("Quantity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string SAPStockLocation {
            get {
                return this.sAPStockLocationField;
            }
            set {
                this.sAPStockLocationField = value;
                this.RaisePropertyChanged("SAPStockLocation");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://amwater.com/EAM/0009/MAPCALL/CompleteWorkOrder")]
    public partial class CompleteScheduledUnscheduledWOStatusUnscheduledWOResponse : object, System.ComponentModel.INotifyPropertyChanged {
        private string orderNumberField;
        
        private string notificationNumberField;
        
        private string wBSElementField;
        
        private string materialDocumentField;
        
        private string sAPStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string OrderNumber {
            get {
                return this.orderNumberField;
            }
            set {
                this.orderNumberField = value;
                this.RaisePropertyChanged("OrderNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string NotificationNumber {
            get {
                return this.notificationNumberField;
            }
            set {
                this.notificationNumberField = value;
                this.RaisePropertyChanged("NotificationNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string WBSElement {
            get {
                return this.wBSElementField;
            }
            set {
                this.wBSElementField = value;
                this.RaisePropertyChanged("WBSElement");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string MaterialDocument {
            get {
                return this.materialDocumentField;
            }
            set {
                this.materialDocumentField = value;
                this.RaisePropertyChanged("MaterialDocument");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string SAPStatus {
            get {
                return this.sAPStatusField;
            }
            set {
                this.sAPStatusField = value;
                this.RaisePropertyChanged("SAPStatus");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CompleteScheduledUnscheduledWO_OB_SYNRequest {
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://amwater.com/EAM/0009/MAPCALL/CompleteWorkOrder", Order=0)]
        public MapCall.SAP.CompleteScheduledUnscheduledWOWS.CompleteScheduledUnscheduledWO CompleteScheduledUnscheduledWORequest;
        
        public CompleteScheduledUnscheduledWO_OB_SYNRequest() {
        }
        
        public CompleteScheduledUnscheduledWO_OB_SYNRequest(MapCall.SAP.CompleteScheduledUnscheduledWOWS.CompleteScheduledUnscheduledWO CompleteScheduledUnscheduledWORequest) {
            this.CompleteScheduledUnscheduledWORequest = CompleteScheduledUnscheduledWORequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CompleteScheduledUnscheduledWO_OB_SYNResponse {
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://amwater.com/EAM/0009/MAPCALL/CompleteWorkOrder", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("UnscheduledWOResponse", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public MapCall.SAP.CompleteScheduledUnscheduledWOWS.CompleteScheduledUnscheduledWOStatusUnscheduledWOResponse[] CompleteScheduledUnscheduledWOResponse;
        
        public CompleteScheduledUnscheduledWO_OB_SYNResponse() {
        }
        
        public CompleteScheduledUnscheduledWO_OB_SYNResponse(MapCall.SAP.CompleteScheduledUnscheduledWOWS.CompleteScheduledUnscheduledWOStatusUnscheduledWOResponse[] CompleteScheduledUnscheduledWOResponse) {
            this.CompleteScheduledUnscheduledWOResponse = CompleteScheduledUnscheduledWOResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CompleteScheduledUnscheduledWO_OB_SYNChannel : MapCall.SAP.CompleteScheduledUnscheduledWOWS.CompleteScheduledUnscheduledWO_OB_SYN, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CompleteScheduledUnscheduledWO_OB_SYNClient : System.ServiceModel.ClientBase<MapCall.SAP.CompleteScheduledUnscheduledWOWS.CompleteScheduledUnscheduledWO_OB_SYN>, MapCall.SAP.CompleteScheduledUnscheduledWOWS.CompleteScheduledUnscheduledWO_OB_SYN {
        public CompleteScheduledUnscheduledWO_OB_SYNClient() {
        }
        
        public CompleteScheduledUnscheduledWO_OB_SYNClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CompleteScheduledUnscheduledWO_OB_SYNClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CompleteScheduledUnscheduledWO_OB_SYNClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CompleteScheduledUnscheduledWO_OB_SYNClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MapCall.SAP.CompleteScheduledUnscheduledWOWS.CompleteScheduledUnscheduledWO_OB_SYNResponse MapCall.SAP.CompleteScheduledUnscheduledWOWS.CompleteScheduledUnscheduledWO_OB_SYN.CompleteScheduledUnscheduledWO_OB_SYN(MapCall.SAP.CompleteScheduledUnscheduledWOWS.CompleteScheduledUnscheduledWO_OB_SYNRequest request) {
            return base.Channel.CompleteScheduledUnscheduledWO_OB_SYN(request);
        }
        
        public MapCall.SAP.CompleteScheduledUnscheduledWOWS.CompleteScheduledUnscheduledWOStatusUnscheduledWOResponse[] CompleteScheduledUnscheduledWO_OB_SYN(MapCall.SAP.CompleteScheduledUnscheduledWOWS.CompleteScheduledUnscheduledWO CompleteScheduledUnscheduledWORequest) {
            MapCall.SAP.CompleteScheduledUnscheduledWOWS.CompleteScheduledUnscheduledWO_OB_SYNRequest inValue = new MapCall.SAP.CompleteScheduledUnscheduledWOWS.CompleteScheduledUnscheduledWO_OB_SYNRequest();
            inValue.CompleteScheduledUnscheduledWORequest = CompleteScheduledUnscheduledWORequest;
            MapCall.SAP.CompleteScheduledUnscheduledWOWS.CompleteScheduledUnscheduledWO_OB_SYNResponse retVal = ((MapCall.SAP.CompleteScheduledUnscheduledWOWS.CompleteScheduledUnscheduledWO_OB_SYN)(this)).CompleteScheduledUnscheduledWO_OB_SYN(inValue);
            return retVal.CompleteScheduledUnscheduledWOResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MapCall.SAP.CompleteScheduledUnscheduledWOWS.CompleteScheduledUnscheduledWO_OB_SYNResponse> MapCall.SAP.CompleteScheduledUnscheduledWOWS.CompleteScheduledUnscheduledWO_OB_SYN.CompleteScheduledUnscheduledWO_OB_SYNAsync(MapCall.SAP.CompleteScheduledUnscheduledWOWS.CompleteScheduledUnscheduledWO_OB_SYNRequest request) {
            return base.Channel.CompleteScheduledUnscheduledWO_OB_SYNAsync(request);
        }
        
        public System.Threading.Tasks.Task<MapCall.SAP.CompleteScheduledUnscheduledWOWS.CompleteScheduledUnscheduledWO_OB_SYNResponse> CompleteScheduledUnscheduledWO_OB_SYNAsync(MapCall.SAP.CompleteScheduledUnscheduledWOWS.CompleteScheduledUnscheduledWO CompleteScheduledUnscheduledWORequest) {
            MapCall.SAP.CompleteScheduledUnscheduledWOWS.CompleteScheduledUnscheduledWO_OB_SYNRequest inValue = new MapCall.SAP.CompleteScheduledUnscheduledWOWS.CompleteScheduledUnscheduledWO_OB_SYNRequest();
            inValue.CompleteScheduledUnscheduledWORequest = CompleteScheduledUnscheduledWORequest;
            return ((MapCall.SAP.CompleteScheduledUnscheduledWOWS.CompleteScheduledUnscheduledWO_OB_SYN)(this)).CompleteScheduledUnscheduledWO_OB_SYNAsync(inValue);
        }
    }
}
