//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MapCall.SAP.DeviceDetailWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://amwater.com/EAM/0018/MAPCALL/GetDeviceDetails", ConfigurationName="DeviceDetailWS.DeviceDetails_Get_OB_SYN")]
    public interface DeviceDetails_Get_OB_SYN {
        
        // CODEGEN: Generating message contract since the operation DeviceDetails_Get_OB_SYN is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MapCall.SAP.DeviceDetailWS.DeviceDetails_Get_OB_SYNResponse DeviceDetails_Get_OB_SYN(MapCall.SAP.DeviceDetailWS.DeviceDetails_Get_OB_SYNRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        System.Threading.Tasks.Task<MapCall.SAP.DeviceDetailWS.DeviceDetails_Get_OB_SYNResponse> DeviceDetails_Get_OB_SYNAsync(MapCall.SAP.DeviceDetailWS.DeviceDetails_Get_OB_SYNRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://amwater.com/EAM/0018/MAPCALL/GetDeviceDetails")]
    public partial class DeviceDetailsQuery : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sourceIdentifierField;
        
        private string meterManufacturerSerialNoField;
        
        private string equipmentIDField;
        
        private string actionCodeField;
        
        private string deviceLocationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string SourceIdentifier {
            get {
                return this.sourceIdentifierField;
            }
            set {
                this.sourceIdentifierField = value;
                this.RaisePropertyChanged("SourceIdentifier");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string MeterManufacturerSerialNo {
            get {
                return this.meterManufacturerSerialNoField;
            }
            set {
                this.meterManufacturerSerialNoField = value;
                this.RaisePropertyChanged("MeterManufacturerSerialNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string EquipmentID {
            get {
                return this.equipmentIDField;
            }
            set {
                this.equipmentIDField = value;
                this.RaisePropertyChanged("EquipmentID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string ActionCode {
            get {
                return this.actionCodeField;
            }
            set {
                this.actionCodeField = value;
                this.RaisePropertyChanged("ActionCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string DeviceLocation {
            get {
                return this.deviceLocationField;
            }
            set {
                this.deviceLocationField = value;
                this.RaisePropertyChanged("DeviceLocation");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://amwater.com/EAM/0018/MAPCALL/GetDeviceDetails")]
    public partial class DeviceDetailsInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private DeviceDetailsInfoRecord[] recordField;
        
        private string secureAccessField;
        
        private string exceptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Record", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public DeviceDetailsInfoRecord[] Record {
            get {
                return this.recordField;
            }
            set {
                this.recordField = value;
                this.RaisePropertyChanged("Record");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string SecureAccess {
            get {
                return this.secureAccessField;
            }
            set {
                this.secureAccessField = value;
                this.RaisePropertyChanged("SecureAccess");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Exception {
            get {
                return this.exceptionField;
            }
            set {
                this.exceptionField = value;
                this.RaisePropertyChanged("Exception");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://amwater.com/EAM/0018/MAPCALL/GetDeviceDetails")]
    public partial class DeviceDetailsInfoRecord : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string meterManufacturerSerialNoField;
        
        private string materialNumberField;
        
        private string sizeField;
        
        private string manufacturerField;
        
        private string meterSerialField;
        
        private string serviceTypeField;
        
        private string meterPositionLocationField;
        
        private string meterDirectionalLocationField;
        
        private string meterSupplementalLocationField;
        
        private string readingDeviceDirectionalLocationField;
        
        private string readingDevicePositionalLocationField;
        
        private string readingDeviceSupplementalLocationField;
        
        private string deviceLocationNotesField;
        
        private string pointOfControlNotesField;
        
        private string mIUNumber1Field;
        
        private string mIUNumber2Field;
        
        private string encoderIdField;
        
        private string encoderId2Field;
        
        private string rFMIUField;
        
        private string tPEncoderField;
        
        private string readType1Field;
        
        private string readTypedescriptionField;
        
        private string registerGroupField;
        
        private string deviceCategoryField;
        
        private string installationField;
        
        private string systemStatusField;
        
        private string userStatusField;
        
        private DeviceDetailsInfoRecordRegisterStructure[] registerStructureField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string MeterManufacturerSerialNo {
            get {
                return this.meterManufacturerSerialNoField;
            }
            set {
                this.meterManufacturerSerialNoField = value;
                this.RaisePropertyChanged("MeterManufacturerSerialNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string MaterialNumber {
            get {
                return this.materialNumberField;
            }
            set {
                this.materialNumberField = value;
                this.RaisePropertyChanged("MaterialNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Size {
            get {
                return this.sizeField;
            }
            set {
                this.sizeField = value;
                this.RaisePropertyChanged("Size");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Manufacturer {
            get {
                return this.manufacturerField;
            }
            set {
                this.manufacturerField = value;
                this.RaisePropertyChanged("Manufacturer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string MeterSerial {
            get {
                return this.meterSerialField;
            }
            set {
                this.meterSerialField = value;
                this.RaisePropertyChanged("MeterSerial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string ServiceType {
            get {
                return this.serviceTypeField;
            }
            set {
                this.serviceTypeField = value;
                this.RaisePropertyChanged("ServiceType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string MeterPositionLocation {
            get {
                return this.meterPositionLocationField;
            }
            set {
                this.meterPositionLocationField = value;
                this.RaisePropertyChanged("MeterPositionLocation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string MeterDirectionalLocation {
            get {
                return this.meterDirectionalLocationField;
            }
            set {
                this.meterDirectionalLocationField = value;
                this.RaisePropertyChanged("MeterDirectionalLocation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string MeterSupplementalLocation {
            get {
                return this.meterSupplementalLocationField;
            }
            set {
                this.meterSupplementalLocationField = value;
                this.RaisePropertyChanged("MeterSupplementalLocation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string ReadingDeviceDirectionalLocation {
            get {
                return this.readingDeviceDirectionalLocationField;
            }
            set {
                this.readingDeviceDirectionalLocationField = value;
                this.RaisePropertyChanged("ReadingDeviceDirectionalLocation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string ReadingDevicePositionalLocation {
            get {
                return this.readingDevicePositionalLocationField;
            }
            set {
                this.readingDevicePositionalLocationField = value;
                this.RaisePropertyChanged("ReadingDevicePositionalLocation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string ReadingDeviceSupplementalLocation {
            get {
                return this.readingDeviceSupplementalLocationField;
            }
            set {
                this.readingDeviceSupplementalLocationField = value;
                this.RaisePropertyChanged("ReadingDeviceSupplementalLocation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string DeviceLocationNotes {
            get {
                return this.deviceLocationNotesField;
            }
            set {
                this.deviceLocationNotesField = value;
                this.RaisePropertyChanged("DeviceLocationNotes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string PointOfControlNotes {
            get {
                return this.pointOfControlNotesField;
            }
            set {
                this.pointOfControlNotesField = value;
                this.RaisePropertyChanged("PointOfControlNotes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string MIUNumber1 {
            get {
                return this.mIUNumber1Field;
            }
            set {
                this.mIUNumber1Field = value;
                this.RaisePropertyChanged("MIUNumber1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string MIUNumber2 {
            get {
                return this.mIUNumber2Field;
            }
            set {
                this.mIUNumber2Field = value;
                this.RaisePropertyChanged("MIUNumber2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string EncoderId {
            get {
                return this.encoderIdField;
            }
            set {
                this.encoderIdField = value;
                this.RaisePropertyChanged("EncoderId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string EncoderId2 {
            get {
                return this.encoderId2Field;
            }
            set {
                this.encoderId2Field = value;
                this.RaisePropertyChanged("EncoderId2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string RFMIU {
            get {
                return this.rFMIUField;
            }
            set {
                this.rFMIUField = value;
                this.RaisePropertyChanged("RFMIU");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string TPEncoder {
            get {
                return this.tPEncoderField;
            }
            set {
                this.tPEncoderField = value;
                this.RaisePropertyChanged("TPEncoder");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string ReadType1 {
            get {
                return this.readType1Field;
            }
            set {
                this.readType1Field = value;
                this.RaisePropertyChanged("ReadType1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public string ReadTypedescription {
            get {
                return this.readTypedescriptionField;
            }
            set {
                this.readTypedescriptionField = value;
                this.RaisePropertyChanged("ReadTypedescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public string RegisterGroup {
            get {
                return this.registerGroupField;
            }
            set {
                this.registerGroupField = value;
                this.RaisePropertyChanged("RegisterGroup");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public string DeviceCategory {
            get {
                return this.deviceCategoryField;
            }
            set {
                this.deviceCategoryField = value;
                this.RaisePropertyChanged("DeviceCategory");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public string Installation {
            get {
                return this.installationField;
            }
            set {
                this.installationField = value;
                this.RaisePropertyChanged("Installation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=25)]
        public string SystemStatus {
            get {
                return this.systemStatusField;
            }
            set {
                this.systemStatusField = value;
                this.RaisePropertyChanged("SystemStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=26)]
        public string UserStatus {
            get {
                return this.userStatusField;
            }
            set {
                this.userStatusField = value;
                this.RaisePropertyChanged("UserStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RegisterStructure", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=27)]
        public DeviceDetailsInfoRecordRegisterStructure[] RegisterStructure {
            get {
                return this.registerStructureField;
            }
            set {
                this.registerStructureField = value;
                this.RaisePropertyChanged("RegisterStructure");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://amwater.com/EAM/0018/MAPCALL/GetDeviceDetails")]
    public partial class DeviceDetailsInfoRecordRegisterStructure : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string registerIDField;
        
        private string dialsField;
        
        private string uOMField;
        
        private string readDateField;
        
        private string readField;
        
        private string meterReadTypeField;
        
        private string meterReadReasonField;
        
        private string readTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string RegisterID {
            get {
                return this.registerIDField;
            }
            set {
                this.registerIDField = value;
                this.RaisePropertyChanged("RegisterID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Dials {
            get {
                return this.dialsField;
            }
            set {
                this.dialsField = value;
                this.RaisePropertyChanged("Dials");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string UOM {
            get {
                return this.uOMField;
            }
            set {
                this.uOMField = value;
                this.RaisePropertyChanged("UOM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string ReadDate {
            get {
                return this.readDateField;
            }
            set {
                this.readDateField = value;
                this.RaisePropertyChanged("ReadDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Read {
            get {
                return this.readField;
            }
            set {
                this.readField = value;
                this.RaisePropertyChanged("Read");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string MeterReadType {
            get {
                return this.meterReadTypeField;
            }
            set {
                this.meterReadTypeField = value;
                this.RaisePropertyChanged("MeterReadType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string MeterReadReason {
            get {
                return this.meterReadReasonField;
            }
            set {
                this.meterReadReasonField = value;
                this.RaisePropertyChanged("MeterReadReason");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string ReadType {
            get {
                return this.readTypeField;
            }
            set {
                this.readTypeField = value;
                this.RaisePropertyChanged("ReadType");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeviceDetails_Get_OB_SYNRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://amwater.com/EAM/0018/MAPCALL/GetDeviceDetails", Order=0)]
        public MapCall.SAP.DeviceDetailWS.DeviceDetailsQuery DeviceDetails_Request;
        
        public DeviceDetails_Get_OB_SYNRequest() {
        }
        
        public DeviceDetails_Get_OB_SYNRequest(MapCall.SAP.DeviceDetailWS.DeviceDetailsQuery DeviceDetails_Request) {
            this.DeviceDetails_Request = DeviceDetails_Request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeviceDetails_Get_OB_SYNResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://amwater.com/EAM/0018/MAPCALL/GetDeviceDetails", Order=0)]
        public MapCall.SAP.DeviceDetailWS.DeviceDetailsInfo DeviceDetails_Response;
        
        public DeviceDetails_Get_OB_SYNResponse() {
        }
        
        public DeviceDetails_Get_OB_SYNResponse(MapCall.SAP.DeviceDetailWS.DeviceDetailsInfo DeviceDetails_Response) {
            this.DeviceDetails_Response = DeviceDetails_Response;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DeviceDetails_Get_OB_SYNChannel : MapCall.SAP.DeviceDetailWS.DeviceDetails_Get_OB_SYN, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DeviceDetails_Get_OB_SYNClient : System.ServiceModel.ClientBase<MapCall.SAP.DeviceDetailWS.DeviceDetails_Get_OB_SYN>, MapCall.SAP.DeviceDetailWS.DeviceDetails_Get_OB_SYN {
        
        public DeviceDetails_Get_OB_SYNClient() {
        }
        
        public DeviceDetails_Get_OB_SYNClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DeviceDetails_Get_OB_SYNClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DeviceDetails_Get_OB_SYNClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DeviceDetails_Get_OB_SYNClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MapCall.SAP.DeviceDetailWS.DeviceDetails_Get_OB_SYNResponse MapCall.SAP.DeviceDetailWS.DeviceDetails_Get_OB_SYN.DeviceDetails_Get_OB_SYN(MapCall.SAP.DeviceDetailWS.DeviceDetails_Get_OB_SYNRequest request) {
            return base.Channel.DeviceDetails_Get_OB_SYN(request);
        }
        
        public MapCall.SAP.DeviceDetailWS.DeviceDetailsInfo DeviceDetails_Get_OB_SYN(MapCall.SAP.DeviceDetailWS.DeviceDetailsQuery DeviceDetails_Request) {
            MapCall.SAP.DeviceDetailWS.DeviceDetails_Get_OB_SYNRequest inValue = new MapCall.SAP.DeviceDetailWS.DeviceDetails_Get_OB_SYNRequest();
            inValue.DeviceDetails_Request = DeviceDetails_Request;
            MapCall.SAP.DeviceDetailWS.DeviceDetails_Get_OB_SYNResponse retVal = ((MapCall.SAP.DeviceDetailWS.DeviceDetails_Get_OB_SYN)(this)).DeviceDetails_Get_OB_SYN(inValue);
            return retVal.DeviceDetails_Response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MapCall.SAP.DeviceDetailWS.DeviceDetails_Get_OB_SYNResponse> MapCall.SAP.DeviceDetailWS.DeviceDetails_Get_OB_SYN.DeviceDetails_Get_OB_SYNAsync(MapCall.SAP.DeviceDetailWS.DeviceDetails_Get_OB_SYNRequest request) {
            return base.Channel.DeviceDetails_Get_OB_SYNAsync(request);
        }
        
        public System.Threading.Tasks.Task<MapCall.SAP.DeviceDetailWS.DeviceDetails_Get_OB_SYNResponse> DeviceDetails_Get_OB_SYNAsync(MapCall.SAP.DeviceDetailWS.DeviceDetailsQuery DeviceDetails_Request) {
            MapCall.SAP.DeviceDetailWS.DeviceDetails_Get_OB_SYNRequest inValue = new MapCall.SAP.DeviceDetailWS.DeviceDetails_Get_OB_SYNRequest();
            inValue.DeviceDetails_Request = DeviceDetails_Request;
            return ((MapCall.SAP.DeviceDetailWS.DeviceDetails_Get_OB_SYN)(this)).DeviceDetails_Get_OB_SYNAsync(inValue);
        }
    }
}
