<%@ Page Language="C#" AutoEventWireup="true" MasterPageFile="~/MapCallSite.Master" Theme="bender" CodeBehind="CustomerSurveyData.aspx.cs" Inherits="MapCall.Modules.Customer.CustomerSurveyData" %>

<%@ Register Src="~/Controls/Data/DataField.ascx" TagName="DataField" TagPrefix="mmsi" %>
<%@ Register Src="~/Controls/Data/CustomerSurveyDataField.ascx" TagName="CustomerSurveyDataField" TagPrefix="mmsi" %>
<%@ Register assembly="MMSINC" namespace="MMSINC" tagPrefix="mmsinc" %>

<asp:Content ID="Content1" runat="server" ContentPlaceHolderID="cphHeader">
CustomerSurveyData
</asp:Content>

<asp:Content ID="Content3" runat="server" ContentPlaceHolderID="cphMain">
    <asp:Label runat="server" ID="lblPermissionErrors" />
    <asp:Panel runat="server" ID="pnlSearch" DefaultButton="btnSearch" CssClass="searchPanel">
        <center>
            <table style="text-align:left;" border="0">
                <mmsi:DataField runat="server" ID="dfOpCode" DataType="DropDownList" 
                    DataFieldName="OperatingCenterID" HeaderText="OpCode : " 
                    ConnectionString="<%$ ConnectionStrings:MCProd %>" 
                    SelectCommand="SELECT DISTINCT OperatingCenterCode + ' - ' + OperatingCenterName AS [Txt], [OperatingCenterID] AS [Val] FROM [OperatingCenters];" />
                <mmsi:CustomerSurveyDataField runat="server" ID="Q01" QuestionID="1" DataType="DropDownList"  DataFieldName="CustomerAnswer" HeaderText="Q01: First, I would like to verify that you recently contacted your current water company, which is <STATE>: American Water?"  ConnectionString="<%$ ConnectionStrings:MCProd %>"   SelectCommand="SELECT Distinct CustomerAnswer as txt, CustomerAnswer as val from CustomerSurveyAnswers where CustomerSurveyQuestionID=1" />
                <mmsi:CustomerSurveyDataField runat="server" ID="Q02A" QuestionID="2" DataType="String" DataFieldName="CustomerAnswer" HeaderText=" Q02A: Thinking about your most recent contact with your water company, what was the reason for your contact? (PROVIDE RESPONSE?)" />
                <mmsi:CustomerSurveyDataField runat="server" ID="Q02AO" QuestionID="3" DataType="String"  DataFieldName="CustomerAnswer" HeaderText="Q02AO: Thinking about your most recent contact with your water company, what was the reason for your contact? (RECORDED AS VERBATIM)"  ConnectionString="<%$ ConnectionStrings:MCProd %>" />
                <mmsi:CustomerSurveyDataField runat="server" ID="Q02" QuestionID="4" DataType="DropDownList"  DataFieldName="CustomerAnswer" HeaderText="Q02: Thinking about your most recent contact with your water company, what was the reason for your contact? (CODED BY INTERVIEWER)"  ConnectionString="<%$ ConnectionStrings:MCProd %>"   SelectCommand="SELECT Distinct CustomerAnswer as txt, CustomerAnswer as val from CustomerSurveyAnswers where CustomerSurveyQuestionID=4" />
                <mmsi:CustomerSurveyDataField runat="server" ID="Q02O" QuestionID="5" DataType="String"  DataFieldName="CustomerAnswer" HeaderText="Q02O: Thinking about your most recent contact with your water company, what was the reason for your contact? (Other)"  ConnectionString="<%$ ConnectionStrings:MCProd %>"   SelectCommand="SELECT Distinct CustomerAnswer as txt, CustomerAnswer as val from CustomerSurveyAnswers where CustomerSurveyQuestionID=5" />
                <mmsi:CustomerSurveyDataField runat="server" ID="Q03" QuestionID="6" DataType="DropDownList"  DataFieldName="CustomerAnswer" HeaderText="Q03: How did you first initiate contact with your water company?"  ConnectionString="<%$ ConnectionStrings:MCProd %>"   SelectCommand="SELECT Distinct CustomerAnswer as txt, CustomerAnswer as val from CustomerSurveyAnswers where CustomerSurveyQuestionID=6" />
                <mmsi:CustomerSurveyDataField runat="server" ID="Q03O" QuestionID="7" DataType="String"  DataFieldName="CustomerAnswer" HeaderText="Q03O: How did you first initiate contact with your water company? (Other)"  ConnectionString="<%$ ConnectionStrings:MCProd %>"   SelectCommand="SELECT Distinct CustomerAnswer as txt, CustomerAnswer as val from CustomerSurveyAnswers where CustomerSurveyQuestionID=7" />
                <mmsi:CustomerSurveyDataField runat="server" ID="Q04" QuestionID="8" DataType="DropDownList"  DataFieldName="CustomerAnswer" HeaderText="Q04: How would you rate the overall ease of using the automated telephone answering system menu?"  ConnectionString="<%$ ConnectionStrings:MCProd %>"   SelectCommand="SELECT Distinct CustomerAnswer as txt, CustomerAnswer as val from CustomerSurveyAnswers where CustomerSurveyQuestionID=8" />
                <mmsi:CustomerSurveyDataField runat="server" ID="Q05" QuestionID="9" DataType="DropDownList"  DataFieldName="CustomerAnswer" HeaderText="Q05: How would you rate the amount of time it took to use the automated telephone answering system?"  ConnectionString="<%$ ConnectionStrings:MCProd %>"   SelectCommand="SELECT Distinct CustomerAnswer as txt, CustomerAnswer as val from CustomerSurveyAnswers where CustomerSurveyQuestionID=9" />
                <mmsi:CustomerSurveyDataField runat="server" ID="Q06" QuestionID="10" DataType="DropDownList"  DataFieldName="CustomerAnswer" HeaderText="Q06: How would you rate your ability to accomplish what you needed to through the automated telephone system?"  ConnectionString="<%$ ConnectionStrings:MCProd %>"   SelectCommand="SELECT Distinct CustomerAnswer as txt, CustomerAnswer as val from CustomerSurveyAnswers where CustomerSurveyQuestionID=10" />
                <mmsi:CustomerSurveyDataField runat="server" ID="Q07" QuestionID="11" DataType="DropDownList"  DataFieldName="CustomerAnswer" HeaderText="Q07: How would you rate your overall satisfaction with the quality of service you received through the automated answering system? Would you say you are:"  ConnectionString="<%$ ConnectionStrings:MCProd %>"   SelectCommand="SELECT Distinct CustomerAnswer as txt, CustomerAnswer as val from CustomerSurveyAnswers where CustomerSurveyQuestionID=11" />
                <mmsi:CustomerSurveyDataField runat="server" ID="Q08" QuestionID="12" DataType="String"  DataFieldName="CustomerAnswer" HeaderText="Q08: Did you complete your inquiry using the automated telephone answering system, or did you end up speaking to a customer service representative?"  ConnectionString="<%$ ConnectionStrings:MCProd %>"   SelectCommand="SELECT Distinct CustomerAnswer as txt, CustomerAnswer as val from CustomerSurveyAnswers where CustomerSurveyQuestionID=12" />
                <mmsi:CustomerSurveyDataField runat="server" ID="Q09" QuestionID="13" DataType="String"  DataFieldName="CustomerAnswer" HeaderText="Q09: How would you rate the overall ease of using the website?"  ConnectionString="<%$ ConnectionStrings:MCProd %>"   SelectCommand="SELECT Distinct CustomerAnswer as txt, CustomerAnswer as val from CustomerSurveyAnswers where CustomerSurveyQuestionID=13" />
                <mmsi:CustomerSurveyDataField runat="server" ID="Q10" QuestionID="14" DataType="String"  DataFieldName="CustomerAnswer" HeaderText="Q10: How would you rate the amount of time it took to use the website?"  ConnectionString="<%$ ConnectionStrings:MCProd %>"   SelectCommand="SELECT Distinct CustomerAnswer as txt, CustomerAnswer as val from CustomerSurveyAnswers where CustomerSurveyQuestionID=14" />
                <mmsi:CustomerSurveyDataField runat="server" ID="Q11" QuestionID="15" DataType="String"  DataFieldName="CustomerAnswer" HeaderText="Q11: How would you rate your ability to accomplish what you needed to through the website?"  ConnectionString="<%$ ConnectionStrings:MCProd %>"   SelectCommand="SELECT Distinct CustomerAnswer as txt, CustomerAnswer as val from CustomerSurveyAnswers where CustomerSurveyQuestionID=15" />
                <mmsi:CustomerSurveyDataField runat="server" ID="Q12" QuestionID="16" DataType="String"  DataFieldName="CustomerAnswer" HeaderText="Q12: How would you rate your overall satisfaction with the quality of service you received through the website? Would you say you are:"  ConnectionString="<%$ ConnectionStrings:MCProd %>"   SelectCommand="SELECT Distinct CustomerAnswer as txt, CustomerAnswer as val from CustomerSurveyAnswers where CustomerSurveyQuestionID=16" />
                <mmsi:CustomerSurveyDataField runat="server" ID="Q13" QuestionID="17" DataType="String"  DataFieldName="CustomerAnswer" HeaderText="Q13: Did you complete your inquiry using the website, or did you end up speaking to a customer service representative?"  ConnectionString="<%$ ConnectionStrings:MCProd %>"   SelectCommand="SELECT Distinct CustomerAnswer as txt, CustomerAnswer as val from CustomerSurveyAnswers where CustomerSurveyQuestionID=17" />
                <mmsi:CustomerSurveyDataField runat="server" ID="Q14" QuestionID="18" DataType="String"  DataFieldName="CustomerAnswer" HeaderText="Q14: Did you complete your inquiry using the mail, or did you end up speaking to a customer service representative?"  ConnectionString="<%$ ConnectionStrings:MCProd %>"   SelectCommand="SELECT Distinct CustomerAnswer as txt, CustomerAnswer as val from CustomerSurveyAnswers where CustomerSurveyQuestionID=18" />
                <mmsi:CustomerSurveyDataField runat="server" ID="Q15" QuestionID="19" DataType="String"  DataFieldName="CustomerAnswer" HeaderText="Q15: Did you complete your inquiry using e-mail, or did you end up speaking to a customer service representative?"  ConnectionString="<%$ ConnectionStrings:MCProd %>"   SelectCommand="SELECT Distinct CustomerAnswer as txt, CustomerAnswer as val from CustomerSurveyAnswers where CustomerSurveyQuestionID=19" />
                <mmsi:CustomerSurveyDataField runat="server" ID="Q15B" QuestionID="20" DataType="DropDownList"  DataFieldName="CustomerAnswer" HeaderText="Q15B: Did you end up speaking to a customer service representative?"  ConnectionString="<%$ ConnectionStrings:MCProd %>"   SelectCommand="SELECT Distinct CustomerAnswer as txt, CustomerAnswer as val from CustomerSurveyAnswers where CustomerSurveyQuestionID=20" />
                <mmsi:CustomerSurveyDataField runat="server" ID="Q16" QuestionID="21" DataType="DropDownList"  DataFieldName="CustomerAnswer" HeaderText="Q16: How would you rate the amount of time it took to reach a customer service representative?"  ConnectionString="<%$ ConnectionStrings:MCProd %>"   SelectCommand="SELECT Distinct CustomerAnswer as txt, CustomerAnswer as val from CustomerSurveyAnswers where CustomerSurveyQuestionID=21" />
                <mmsi:CustomerSurveyDataField runat="server" ID="Q17" QuestionID="22" DataType="DropDownList"  DataFieldName="CustomerAnswer" HeaderText="Q17: How would you rate the courtesy, professionalism and helpfulness of the customer service representative with whom you spoke most recently?"  ConnectionString="<%$ ConnectionStrings:MCProd %>"   SelectCommand="SELECT Distinct CustomerAnswer as txt, CustomerAnswer as val from CustomerSurveyAnswers where CustomerSurveyQuestionID=22" />
                <mmsi:CustomerSurveyDataField runat="server" ID="Q18" QuestionID="23" DataType="DropDownList"  DataFieldName="CustomerAnswer" HeaderText="Q18: How would you rate the customer service representative with whom you spoke most recently in terms of being knowledgeable about your question, request or concern?"  ConnectionString="<%$ ConnectionStrings:MCProd %>"   SelectCommand="SELECT Distinct CustomerAnswer as txt, CustomerAnswer as val from CustomerSurveyAnswers where CustomerSurveyQuestionID=23" />
                <mmsi:CustomerSurveyDataField runat="server" ID="Q19" QuestionID="24" DataType="DropDownList"  DataFieldName="CustomerAnswer" HeaderText="Q19: How would you rate the ability of the customer service representative with whom you spoke to resolve your question, request or concern?"  ConnectionString="<%$ ConnectionStrings:MCProd %>"   SelectCommand="SELECT Distinct CustomerAnswer as txt, CustomerAnswer as val from CustomerSurveyAnswers where CustomerSurveyQuestionID=24" />
                <mmsi:CustomerSurveyDataField runat="server" ID="Q20" QuestionID="25" DataType="DropDownList"  DataFieldName="CustomerAnswer" HeaderText="Q20: How would you rate the overall amount of time it took on the phone to address your question, request or concern?"  ConnectionString="<%$ ConnectionStrings:MCProd %>"   SelectCommand="SELECT Distinct CustomerAnswer as txt, CustomerAnswer as val from CustomerSurveyAnswers where CustomerSurveyQuestionID=25" />
                <mmsi:CustomerSurveyDataField runat="server" ID="Q21" QuestionID="26" DataType="DropDownList"  DataFieldName="CustomerAnswer" HeaderText="Q21: When you reached a customer service representative, did they introduce themself and the department to you?"  ConnectionString="<%$ ConnectionStrings:MCProd %>"   SelectCommand="SELECT Distinct CustomerAnswer as txt, CustomerAnswer as val from CustomerSurveyAnswers where CustomerSurveyQuestionID=26" />
                <mmsi:CustomerSurveyDataField runat="server" ID="Q22" QuestionID="27" DataType="DropDownList"  DataFieldName="CustomerAnswer" HeaderText="Q22: When you reached a customer service representative, did the representative ask you how they could help you?"  ConnectionString="<%$ ConnectionStrings:MCProd %>"   SelectCommand="SELECT Distinct CustomerAnswer as txt, CustomerAnswer as val from CustomerSurveyAnswers where CustomerSurveyQuestionID=27" />
                <mmsi:CustomerSurveyDataField runat="server" ID="Q23" QuestionID="28" DataType="DropDownList"  DataFieldName="CustomerAnswer" HeaderText="Q23: When you reached a customer service representative, did the representative thank you for the call?"  ConnectionString="<%$ ConnectionStrings:MCProd %>"   SelectCommand="SELECT Distinct CustomerAnswer as txt, CustomerAnswer as val from CustomerSurveyAnswers where CustomerSurveyQuestionID=28" />
                <mmsi:CustomerSurveyDataField runat="server" ID="Q24" QuestionID="29" DataType="DropDownList"  DataFieldName="CustomerAnswer" HeaderText="Q24: When you reached a customer service representative, at the end of the call, did the representative ask you if there is anything else they could help you with?"  ConnectionString="<%$ ConnectionStrings:MCProd %>"   SelectCommand="SELECT Distinct CustomerAnswer as txt, CustomerAnswer as val from CustomerSurveyAnswers where CustomerSurveyQuestionID=29" />
                <mmsi:CustomerSurveyDataField runat="server" ID="Q25_1" QuestionID="30" DataType="DropDownList"  DataFieldName="CustomerAnswer" HeaderText="Q25_1: During your initial phone call, were you transferred or placed on hold?|FIRST MENTIONED"  ConnectionString="<%$ ConnectionStrings:MCProd %>"   SelectCommand="SELECT Distinct CustomerAnswer as txt, CustomerAnswer as val from CustomerSurveyAnswers where CustomerSurveyQuestionID=30" />
                <mmsi:CustomerSurveyDataField runat="server" ID="Q25_2" QuestionID="31" DataType="String"  DataFieldName="CustomerAnswer" HeaderText="Q25_2: During your initial phone call, were you transferred or placed on hold?|SECOND MENTIONED"  ConnectionString="<%$ ConnectionStrings:MCProd %>"   SelectCommand="SELECT Distinct CustomerAnswer as txt, CustomerAnswer as val from CustomerSurveyAnswers where CustomerSurveyQuestionID=31" />
                <mmsi:CustomerSurveyDataField runat="server" ID="Q26" QuestionID="32" DataType="DropDownList"  DataFieldName="CustomerAnswer" HeaderText="Q26: When you were transferred, did the customer service representative explain why the call needed to be transferred?"  ConnectionString="<%$ ConnectionStrings:MCProd %>"   SelectCommand="SELECT Distinct CustomerAnswer as txt, CustomerAnswer as val from CustomerSurveyAnswers where CustomerSurveyQuestionID=32" />
                <mmsi:CustomerSurveyDataField runat="server" ID="Q27" QuestionID="33" DataType="DropDownList"  DataFieldName="CustomerAnswer" HeaderText="Q27: When you were transferred, did the customer service representative explain where the call was being transferred to?"  ConnectionString="<%$ ConnectionStrings:MCProd %>"   SelectCommand="SELECT Distinct CustomerAnswer as txt, CustomerAnswer as val from CustomerSurveyAnswers where CustomerSurveyQuestionID=33" />
                <mmsi:CustomerSurveyDataField runat="server" ID="Q28" QuestionID="34" DataType="DropDownList"  DataFieldName="CustomerAnswer" HeaderText="Q28: When you were transferred, did the customer service representative transfer the call to the right person or department?"  ConnectionString="<%$ ConnectionStrings:MCProd %>"   SelectCommand="SELECT Distinct CustomerAnswer as txt, CustomerAnswer as val from CustomerSurveyAnswers where CustomerSurveyQuestionID=34" />
                <mmsi:CustomerSurveyDataField runat="server" ID="Q29" QuestionID="35" DataType="DropDownList"  DataFieldName="CustomerAnswer" HeaderText="Q29: When you were placed on hold, did the customer service representative explain why you needed to be placed on hold?"  ConnectionString="<%$ ConnectionStrings:MCProd %>"   SelectCommand="SELECT Distinct CustomerAnswer as txt, CustomerAnswer as val from CustomerSurveyAnswers where CustomerSurveyQuestionID=35" />
                <mmsi:CustomerSurveyDataField runat="server" ID="Q30" QuestionID="36" DataType="DropDownList"  DataFieldName="CustomerAnswer" HeaderText="Q30: When you were placed on hold, did the customer service representative notify you of how long you may be on hold?"  ConnectionString="<%$ ConnectionStrings:MCProd %>"   SelectCommand="SELECT Distinct CustomerAnswer as txt, CustomerAnswer as val from CustomerSurveyAnswers where CustomerSurveyQuestionID=36" />
                <mmsi:CustomerSurveyDataField runat="server" ID="Q31" QuestionID="37" DataType="DropDownList"  DataFieldName="CustomerAnswer" HeaderText="Q31: How would you rate your overall satisfaction with the quality of service you received from the customer service representative from your water company? Would you say you are:"  ConnectionString="<%$ ConnectionStrings:MCProd %>"   SelectCommand="SELECT Distinct CustomerAnswer as txt, CustomerAnswer as val from CustomerSurveyAnswers where CustomerSurveyQuestionID=37" />
                <mmsi:CustomerSurveyDataField runat="server" ID="Q32" QuestionID="38" DataType="DropDownList"  DataFieldName="CustomerAnswer" HeaderText="Q32: Did your most recent contact with your water company involve the need to setup an appointment for a field service representative to come to your home or property?"  ConnectionString="<%$ ConnectionStrings:MCProd %>"   SelectCommand="SELECT Distinct CustomerAnswer as txt, CustomerAnswer as val from CustomerSurveyAnswers where CustomerSurveyQuestionID=38" />
                <mmsi:CustomerSurveyDataField runat="server" ID="Q33" QuestionID="39" DataType="DropDownList"  DataFieldName="CustomerAnswer" HeaderText="Q33: How would you rate the overall ease of scheduling a service appointment?"  ConnectionString="<%$ ConnectionStrings:MCProd %>"   SelectCommand="SELECT Distinct CustomerAnswer as txt, CustomerAnswer as val from CustomerSurveyAnswers where CustomerSurveyQuestionID=39" />
                <mmsi:CustomerSurveyDataField runat="server" ID="Q34" QuestionID="40" DataType="DropDownList"  DataFieldName="CustomerAnswer" HeaderText="Q34: How would you rate your ability to arrange a service appointment at a time that was convenient for you?"  ConnectionString="<%$ ConnectionStrings:MCProd %>"   SelectCommand="SELECT Distinct CustomerAnswer as txt, CustomerAnswer as val from CustomerSurveyAnswers where CustomerSurveyQuestionID=40" />
                <mmsi:CustomerSurveyDataField runat="server" ID="Q35" QuestionID="41" DataType="DropDownList"  DataFieldName="CustomerAnswer" HeaderText="Q35: How would you rate your overall satisfaction with the process of scheduling a service appointment? Would you say you are:"  ConnectionString="<%$ ConnectionStrings:MCProd %>"   SelectCommand="SELECT Distinct CustomerAnswer as txt, CustomerAnswer as val from CustomerSurveyAnswers where CustomerSurveyQuestionID=41" />
                <mmsi:CustomerSurveyDataField runat="server" ID="Q36" QuestionID="42" DataType="DropDownList"  DataFieldName="CustomerAnswer" HeaderText="Q36: Was it required for you to be at your home or property for the service appointment?"  ConnectionString="<%$ ConnectionStrings:MCProd %>"   SelectCommand="SELECT Distinct CustomerAnswer as txt, CustomerAnswer as val from CustomerSurveyAnswers where CustomerSurveyQuestionID=42" />
                <mmsi:CustomerSurveyDataField runat="server" ID="Q37" QuestionID="43" DataType="DropDownList"  DataFieldName="CustomerAnswer" HeaderText="Q37: Did you request to be called 30 minutes prior to the arrival of the field service representative on the day of your service appointment?"  ConnectionString="<%$ ConnectionStrings:MCProd %>"   SelectCommand="SELECT Distinct CustomerAnswer as txt, CustomerAnswer as val from CustomerSurveyAnswers where CustomerSurveyQuestionID=43" />
                <mmsi:CustomerSurveyDataField runat="server" ID="Q38" QuestionID="44" DataType="DropDownList"  DataFieldName="CustomerAnswer" HeaderText="Q38: Did you receive a call 30 minutes prior to the arrival of the field service representative on the day of your service appointment?"  ConnectionString="<%$ ConnectionStrings:MCProd %>"   SelectCommand="SELECT Distinct CustomerAnswer as txt, CustomerAnswer as val from CustomerSurveyAnswers where CustomerSurveyQuestionID=44" />
                <mmsi:CustomerSurveyDataField runat="server" ID="Q39" QuestionID="45" DataType="DropDownList"  DataFieldName="CustomerAnswer" HeaderText="Q39: Did the field service representative arrive as scheduled during the agreed upon appointment window?"  ConnectionString="<%$ ConnectionStrings:MCProd %>"   SelectCommand="SELECT Distinct CustomerAnswer as txt, CustomerAnswer as val from CustomerSurveyAnswers where CustomerSurveyQuestionID=45" />
                <mmsi:CustomerSurveyDataField runat="server" ID="Q40" QuestionID="46" DataType="DropDownList"  DataFieldName="CustomerAnswer" HeaderText="Q40: Did someone from your water company contact you to re-schedule your appointment or to let you know that they would be late?"  ConnectionString="<%$ ConnectionStrings:MCProd %>"   SelectCommand="SELECT Distinct CustomerAnswer as txt, CustomerAnswer as val from CustomerSurveyAnswers where CustomerSurveyQuestionID=46" />
                <mmsi:CustomerSurveyDataField runat="server" ID="Q41" QuestionID="47" DataType="DropDownList"  DataFieldName="CustomerAnswer" HeaderText="Q41: Did you have any interaction with the field service representative from your water company?"  ConnectionString="<%$ ConnectionStrings:MCProd %>"   SelectCommand="SELECT Distinct CustomerAnswer as txt, CustomerAnswer as val from CustomerSurveyAnswers where CustomerSurveyQuestionID=47" />
                <mmsi:CustomerSurveyDataField runat="server" ID="Q42" QuestionID="48" DataType="DropDownList"  DataFieldName="CustomerAnswer" HeaderText="Q42: How would you rate the courtesy, professionalism and helpfulness of the field service representative with whom you interacted most recently?"  ConnectionString="<%$ ConnectionStrings:MCProd %>"   SelectCommand="SELECT Distinct CustomerAnswer as txt, CustomerAnswer as val from CustomerSurveyAnswers where CustomerSurveyQuestionID=48" />
                <mmsi:CustomerSurveyDataField runat="server" ID="Q43" QuestionID="49" DataType="DropDownList"  DataFieldName="CustomerAnswer" HeaderText="Q43: How would you rate the field service representative with whom you interacted most recently in terms of being knowledgeable about your service question, request or concern?"  ConnectionString="<%$ ConnectionStrings:MCProd %>"   SelectCommand="SELECT Distinct CustomerAnswer as txt, CustomerAnswer as val from CustomerSurveyAnswers where CustomerSurveyQuestionID=49" />
                <mmsi:CustomerSurveyDataField runat="server" ID="Q44" QuestionID="50" DataType="DropDownList"  DataFieldName="CustomerAnswer" HeaderText="Q44: How would you rate the ability of the field service representative with whom you interacted to resolve your service question, request or concern?"  ConnectionString="<%$ ConnectionStrings:MCProd %>"   SelectCommand="SELECT Distinct CustomerAnswer as txt, CustomerAnswer as val from CustomerSurveyAnswers where CustomerSurveyQuestionID=50" />
                <mmsi:CustomerSurveyDataField runat="server" ID="Q45" QuestionID="51" DataType="DropDownList"  DataFieldName="CustomerAnswer" HeaderText="Q45: How would you rate the overall amount of time it took the field service representative to provide service at your home or property?"  ConnectionString="<%$ ConnectionStrings:MCProd %>"   SelectCommand="SELECT Distinct CustomerAnswer as txt, CustomerAnswer as val from CustomerSurveyAnswers where CustomerSurveyQuestionID=51" />
                <mmsi:CustomerSurveyDataField runat="server" ID="Q46" QuestionID="52" DataType="DropDownList"  DataFieldName="CustomerAnswer" HeaderText="Q46: When the field service representative visited your home or property, did the representative introduce themself and the company to you?"  ConnectionString="<%$ ConnectionStrings:MCProd %>"   SelectCommand="SELECT Distinct CustomerAnswer as txt, CustomerAnswer as val from CustomerSurveyAnswers where CustomerSurveyQuestionID=52" />
                <mmsi:CustomerSurveyDataField runat="server" ID="Q47" QuestionID="53" DataType="DropDownList"  DataFieldName="CustomerAnswer" HeaderText="Q47: When the field service representative visited your home or property, did the representative describe the reason for their visit?"  ConnectionString="<%$ ConnectionStrings:MCProd %>"   SelectCommand="SELECT Distinct CustomerAnswer as txt, CustomerAnswer as val from CustomerSurveyAnswers where CustomerSurveyQuestionID=53" />
                <mmsi:CustomerSurveyDataField runat="server" ID="Q48" QuestionID="54" DataType="DropDownList"  DataFieldName="CustomerAnswer" HeaderText="Q48: When the field service representative visited your home or property, did the representative explain how they would be handling the situation?"  ConnectionString="<%$ ConnectionStrings:MCProd %>"   SelectCommand="SELECT Distinct CustomerAnswer as txt, CustomerAnswer as val from CustomerSurveyAnswers where CustomerSurveyQuestionID=54" />
                <mmsi:CustomerSurveyDataField runat="server" ID="Q49" QuestionID="55" DataType="DropDownList"  DataFieldName="CustomerAnswer" HeaderText="Q49: When the field service representative visited your home or property, did the representative review with you the service that would be performed?"  ConnectionString="<%$ ConnectionStrings:MCProd %>"   SelectCommand="SELECT Distinct CustomerAnswer as txt, CustomerAnswer as val from CustomerSurveyAnswers where CustomerSurveyQuestionID=55" />
                <mmsi:CustomerSurveyDataField runat="server" ID="Q50" QuestionID="56" DataType="DropDownList"  DataFieldName="CustomerAnswer" HeaderText="Q50: When the field service representative visited your home or property, did the representative provide you with follow-up contact information in the event it was needed?"  ConnectionString="<%$ ConnectionStrings:MCProd %>"   SelectCommand="SELECT Distinct CustomerAnswer as txt, CustomerAnswer as val from CustomerSurveyAnswers where CustomerSurveyQuestionID=56" />
                <mmsi:CustomerSurveyDataField runat="server" ID="Q51" QuestionID="57" DataType="DropDownList"  DataFieldName="CustomerAnswer" HeaderText="Q51: When the field service representative visited your home or property, did the representative thank you for your recent contact?"  ConnectionString="<%$ ConnectionStrings:MCProd %>"   SelectCommand="SELECT Distinct CustomerAnswer as txt, CustomerAnswer as val from CustomerSurveyAnswers where CustomerSurveyQuestionID=57" />
                <mmsi:CustomerSurveyDataField runat="server" ID="Q52" QuestionID="58" DataType="DropDownList"  DataFieldName="CustomerAnswer" HeaderText="Q52: How would you rate your overall satisfaction with quality of service you received from the field service representative from your water company? Would you say you are:"  ConnectionString="<%$ ConnectionStrings:MCProd %>"   SelectCommand="SELECT Distinct CustomerAnswer as txt, CustomerAnswer as val from CustomerSurveyAnswers where CustomerSurveyQuestionID=58" />
                <mmsi:CustomerSurveyDataField runat="server" ID="Q53" QuestionID="59" DataType="DropDownList"  DataFieldName="CustomerAnswer" HeaderText="Q53: Did the field service representative leave an indication such as a door hanger that the requested work was completed?"  ConnectionString="<%$ ConnectionStrings:MCProd %>"   SelectCommand="SELECT Distinct CustomerAnswer as txt, CustomerAnswer as val from CustomerSurveyAnswers where CustomerSurveyQuestionID=59" />
                <mmsi:CustomerSurveyDataField runat="server" ID="Q54" QuestionID="60" DataType="DropDownList"  DataFieldName="CustomerAnswer" HeaderText="Q54: Overall, how satisfied were you with the outcome of your service contact? Would you say you are:"  ConnectionString="<%$ ConnectionStrings:MCProd %>"   SelectCommand="SELECT Distinct CustomerAnswer as txt, CustomerAnswer as val from CustomerSurveyAnswers where CustomerSurveyQuestionID=60" />
                <mmsi:CustomerSurveyDataField runat="server" ID="Q55" QuestionID="61" DataType="DropDownList"  DataFieldName="CustomerAnswer" HeaderText="Q55: Stated differently, how would you rate your overall satisfaction with the outcome of your most recent service contact with your water company?"  ConnectionString="<%$ ConnectionStrings:MCProd %>"   SelectCommand="SELECT Distinct CustomerAnswer as txt, CustomerAnswer as val from CustomerSurveyAnswers where CustomerSurveyQuestionID=61" />
                <mmsi:CustomerSurveyDataField runat="server" ID="Q56_1" QuestionID="62" DataType="DropDownList"  DataFieldName="CustomerAnswer" HeaderText="Q56_1: What factors contributed to your evaluation of your most recent service contact with your water company?|FIRST MENTIONED"  ConnectionString="<%$ ConnectionStrings:MCProd %>"   SelectCommand="SELECT Distinct CustomerAnswer as txt, CustomerAnswer as val from CustomerSurveyAnswers where CustomerSurveyQuestionID=62" />
                <mmsi:CustomerSurveyDataField runat="server" ID="Q56_1O" QuestionID="63" DataType="String"  DataFieldName="CustomerAnswer" HeaderText="Q56_1O: What factors contributed to your evaluation of your most recent service contact with your water company?|FIRST MENTIONED (Other)"  ConnectionString="<%$ ConnectionStrings:MCProd %>"   SelectCommand="SELECT Distinct CustomerAnswer as txt, CustomerAnswer as val from CustomerSurveyAnswers where CustomerSurveyQuestionID=63" />
                <mmsi:CustomerSurveyDataField runat="server" ID="Q56_2" QuestionID="64" DataType="DropDownList"  DataFieldName="CustomerAnswer" HeaderText="Q56_2: What factors contributed to your evaluation of your most recent service contact with your water company?|SECOND MENTIONED"  ConnectionString="<%$ ConnectionStrings:MCProd %>"   SelectCommand="SELECT Distinct CustomerAnswer as txt, CustomerAnswer as val from CustomerSurveyAnswers where CustomerSurveyQuestionID=64" />
                <mmsi:CustomerSurveyDataField runat="server" ID="Q56_2O" QuestionID="65" DataType="String"  DataFieldName="CustomerAnswer" HeaderText="Q56_2O: What factors contributed to your evaluation of your most recent service contact with your water company?|SECOND MENTIONED (Other)"  ConnectionString="<%$ ConnectionStrings:MCProd %>"   SelectCommand="SELECT Distinct CustomerAnswer as txt, CustomerAnswer as val from CustomerSurveyAnswers where CustomerSurveyQuestionID=65" />
                <mmsi:CustomerSurveyDataField runat="server" ID="Q56_3" QuestionID="66" DataType="DropDownList"  DataFieldName="CustomerAnswer" HeaderText="Q56_3: What factors contributed to your evaluation of your most recent service contact with your water company?|THIRD MENTIONED"  ConnectionString="<%$ ConnectionStrings:MCProd %>"   SelectCommand="SELECT Distinct CustomerAnswer as txt, CustomerAnswer as val from CustomerSurveyAnswers where CustomerSurveyQuestionID=66" />
                <mmsi:CustomerSurveyDataField runat="server" ID="Q56_3O" QuestionID="67" DataType="String"  DataFieldName="CustomerAnswer" HeaderText="Q56_3O: What factors contributed to your evaluation of your most recent service contact with your water company?|THIRD MENTIONED (Other)"  ConnectionString="<%$ ConnectionStrings:MCProd %>"   SelectCommand="SELECT Distinct CustomerAnswer as txt, CustomerAnswer as val from CustomerSurveyAnswers where CustomerSurveyQuestionID=67" />
                <mmsi:CustomerSurveyDataField runat="server" ID="Q56_4" QuestionID="68" DataType="DropDownList"  DataFieldName="CustomerAnswer" HeaderText="Q56_4: What factors contributed to your evaluation of your most recent service contact with your water company?|FOURTH MENTIONED"  ConnectionString="<%$ ConnectionStrings:MCProd %>"   SelectCommand="SELECT Distinct CustomerAnswer as txt, CustomerAnswer as val from CustomerSurveyAnswers where CustomerSurveyQuestionID=68" />
                <mmsi:CustomerSurveyDataField runat="server" ID="Q56_4O" QuestionID="69" DataType="String"  DataFieldName="CustomerAnswer" HeaderText="Q56_4O: What factors contributed to your evaluation of your most recent service contact with your water company?|FOURTH MENTIONED (Other)"  ConnectionString="<%$ ConnectionStrings:MCProd %>"   SelectCommand="SELECT Distinct CustomerAnswer as txt, CustomerAnswer as val from CustomerSurveyAnswers where CustomerSurveyQuestionID=69" />
                <mmsi:CustomerSurveyDataField runat="server" ID="Q56_5" QuestionID="70" DataType="DropDownList"  DataFieldName="CustomerAnswer" HeaderText="Q56_5: What factors contributed to your evaluation of your most recent service contact with your water company?|FIFTH MENTIONED"  ConnectionString="<%$ ConnectionStrings:MCProd %>"   SelectCommand="SELECT Distinct CustomerAnswer as txt, CustomerAnswer as val from CustomerSurveyAnswers where CustomerSurveyQuestionID=70" />
                <mmsi:CustomerSurveyDataField runat="server" ID="Q56_5O" QuestionID="71" DataType="String"  DataFieldName="CustomerAnswer" HeaderText="Q56_5O: What factors contributed to your evaluation of your most recent service contact with your water company?|FIFTH MENTIONED (Other)"  ConnectionString="<%$ ConnectionStrings:MCProd %>"   SelectCommand="SELECT Distinct CustomerAnswer as txt, CustomerAnswer as val from CustomerSurveyAnswers where CustomerSurveyQuestionID=71" />
                <mmsi:CustomerSurveyDataField runat="server" ID="Q56_6" QuestionID="72" DataType="DropDownList"  DataFieldName="CustomerAnswer" HeaderText="Q56_6: What factors contributed to your evaluation of your most recent service contact with your water company?|SIXTH MENTIONED"  ConnectionString="<%$ ConnectionStrings:MCProd %>"   SelectCommand="SELECT Distinct CustomerAnswer as txt, CustomerAnswer as val from CustomerSurveyAnswers where CustomerSurveyQuestionID=72" />
                <mmsi:CustomerSurveyDataField runat="server" ID="Q56_6O" QuestionID="73" DataType="String"  DataFieldName="CustomerAnswer" HeaderText="Q56_6O: What factors contributed to your evaluation of your most recent service contact with your water company?|SIXTH MENTIONED (Other)"  ConnectionString="<%$ ConnectionStrings:MCProd %>"   SelectCommand="SELECT Distinct CustomerAnswer as txt, CustomerAnswer as val from CustomerSurveyAnswers where CustomerSurveyQuestionID=73" />
                <mmsi:CustomerSurveyDataField runat="server" ID="Q56_7" QuestionID="74" DataType="DropDownList"  DataFieldName="CustomerAnswer" HeaderText="Q56_7: What factors contributed to your evaluation of your most recent service contact with your water company?|SEVENTH MENTIONED"  ConnectionString="<%$ ConnectionStrings:MCProd %>"   SelectCommand="SELECT Distinct CustomerAnswer as txt, CustomerAnswer as val from CustomerSurveyAnswers where CustomerSurveyQuestionID=74" />
                <mmsi:CustomerSurveyDataField runat="server" ID="Q56_7O" QuestionID="75" DataType="String"  DataFieldName="CustomerAnswer" HeaderText="Q56_7O: What factors contributed to your evaluation of your most recent service contact with your water company?|SEVENTH MENTIONED (Other)"  ConnectionString="<%$ ConnectionStrings:MCProd %>"   SelectCommand="SELECT Distinct CustomerAnswer as txt, CustomerAnswer as val from CustomerSurveyAnswers where CustomerSurveyQuestionID=75" />
                <mmsi:CustomerSurveyDataField runat="server" ID="Q56_8" QuestionID="76" DataType="DropDownList"  DataFieldName="CustomerAnswer" HeaderText="Q56_8: What factors contributed to your evaluation of your most recent service contact with your water company?|EIGHTH MENTIONED"  ConnectionString="<%$ ConnectionStrings:MCProd %>"   SelectCommand="SELECT Distinct CustomerAnswer as txt, CustomerAnswer as val from CustomerSurveyAnswers where CustomerSurveyQuestionID=76" />
                <mmsi:CustomerSurveyDataField runat="server" ID="Q56_8O" QuestionID="77" DataType="String"  DataFieldName="CustomerAnswer" HeaderText="Q56_8O: What factors contributed to your evaluation of your most recent service contact with your water company?|EIGHTH MENTIONED (Other)"  ConnectionString="<%$ ConnectionStrings:MCProd %>"   SelectCommand="SELECT Distinct CustomerAnswer as txt, CustomerAnswer as val from CustomerSurveyAnswers where CustomerSurveyQuestionID=77" />
                <mmsi:CustomerSurveyDataField runat="server" ID="Q56_9" QuestionID="78" DataType="DropDownList"  DataFieldName="CustomerAnswer" HeaderText="Q56_9: What factors contributed to your evaluation of your most recent service contact with your water company?|NINTH MENTIONED"  ConnectionString="<%$ ConnectionStrings:MCProd %>"   SelectCommand="SELECT Distinct CustomerAnswer as txt, CustomerAnswer as val from CustomerSurveyAnswers where CustomerSurveyQuestionID=78" />
                <mmsi:CustomerSurveyDataField runat="server" ID="Q56_9O" QuestionID="79" DataType="String"  DataFieldName="CustomerAnswer" HeaderText="Q56_9O: What factors contributed to your evaluation of your most recent service contact with your water company?|NINTH MENTIONED (Other)"  ConnectionString="<%$ ConnectionStrings:MCProd %>"   SelectCommand="SELECT Distinct CustomerAnswer as txt, CustomerAnswer as val from CustomerSurveyAnswers where CustomerSurveyQuestionID=79" />
                <mmsi:CustomerSurveyDataField runat="server" ID="Q56_10" QuestionID="80" DataType="DropDownList"  DataFieldName="CustomerAnswer" HeaderText="Q56_10: What factors contributed to your evaluation of your most recent service contact with your water company?|TENTH MENTIONED"  ConnectionString="<%$ ConnectionStrings:MCProd %>"   SelectCommand="SELECT Distinct CustomerAnswer as txt, CustomerAnswer as val from CustomerSurveyAnswers where CustomerSurveyQuestionID=80" />
                <mmsi:CustomerSurveyDataField runat="server" ID="Q56_10O" QuestionID="81" DataType="String"  DataFieldName="CustomerAnswer" HeaderText="Q56_10O: What factors contributed to your evaluation of your most recent service contact with your water company?|TENTH MENTIONED (Other)"  ConnectionString="<%$ ConnectionStrings:MCProd %>"   SelectCommand="SELECT Distinct CustomerAnswer as txt, CustomerAnswer as val from CustomerSurveyAnswers where CustomerSurveyQuestionID=81" />
                <mmsi:CustomerSurveyDataField runat="server" ID="Q56_11" QuestionID="82" DataType="DropDownList"  DataFieldName="CustomerAnswer" HeaderText="Q56_11: What factors contributed to your evaluation of your most recent service contact with your water company?|ELEVENTH MENTIONED"  ConnectionString="<%$ ConnectionStrings:MCProd %>"   SelectCommand="SELECT Distinct CustomerAnswer as txt, CustomerAnswer as val from CustomerSurveyAnswers where CustomerSurveyQuestionID=82" />
                <mmsi:CustomerSurveyDataField runat="server" ID="Q56_11O" QuestionID="83" DataType="String"  DataFieldName="CustomerAnswer" HeaderText="Q56_11O: What factors contributed to your evaluation of your most recent service contact with your water company?|ELEVENTH MENTIONED (Other)"  ConnectionString="<%$ ConnectionStrings:MCProd %>"   SelectCommand="SELECT Distinct CustomerAnswer as txt, CustomerAnswer as val from CustomerSurveyAnswers where CustomerSurveyQuestionID=83" />
                <mmsi:CustomerSurveyDataField runat="server" ID="Q56_12" QuestionID="84" DataType="DropDownList"  DataFieldName="CustomerAnswer" HeaderText="Q56_12: What factors contributed to your evaluation of your most recent service contact with your water company?|TWELFTH MENTIONED"  ConnectionString="<%$ ConnectionStrings:MCProd %>"   SelectCommand="SELECT Distinct CustomerAnswer as txt, CustomerAnswer as val from CustomerSurveyAnswers where CustomerSurveyQuestionID=84" />
                <mmsi:CustomerSurveyDataField runat="server" ID="Q56_12O" QuestionID="85" DataType="String"  DataFieldName="CustomerAnswer" HeaderText="Q56_12O: What factors contributed to your evaluation of your most recent service contact with your water company?|TWELFTH MENTIONED (Other)"  ConnectionString="<%$ ConnectionStrings:MCProd %>"   SelectCommand="SELECT Distinct CustomerAnswer as txt, CustomerAnswer as val from CustomerSurveyAnswers where CustomerSurveyQuestionID=85" />
                <mmsi:CustomerSurveyDataField runat="server" ID="Q56_13" QuestionID="86" DataType="DropDownList"  DataFieldName="CustomerAnswer" HeaderText="Q56_13: What factors contributed to your evaluation of your most recent service contact with your water company?|THIRTEENTH MENTIONED"  ConnectionString="<%$ ConnectionStrings:MCProd %>"   SelectCommand="SELECT Distinct CustomerAnswer as txt, CustomerAnswer as val from CustomerSurveyAnswers where CustomerSurveyQuestionID=86" />
                <mmsi:CustomerSurveyDataField runat="server" ID="Q56_13O" QuestionID="87" DataType="String"  DataFieldName="CustomerAnswer" HeaderText="Q56_13O: What factors contributed to your evaluation of your most recent service contact with your water company?|THIRTEENTH MENTIONED (Other)"  ConnectionString="<%$ ConnectionStrings:MCProd %>"   SelectCommand="SELECT Distinct CustomerAnswer as txt, CustomerAnswer as val from CustomerSurveyAnswers where CustomerSurveyQuestionID=87" />
                <mmsi:CustomerSurveyDataField runat="server" ID="Q56_14" QuestionID="88" DataType="DropDownList"  DataFieldName="CustomerAnswer" HeaderText="Q56_14: What factors contributed to your evaluation of your most recent service contact with your water company?|FOURTEENTH MENTIONED"  ConnectionString="<%$ ConnectionStrings:MCProd %>"   SelectCommand="SELECT Distinct CustomerAnswer as txt, CustomerAnswer as val from CustomerSurveyAnswers where CustomerSurveyQuestionID=88" />
                <mmsi:CustomerSurveyDataField runat="server" ID="Q56_14O" QuestionID="89" DataType="String"  DataFieldName="CustomerAnswer" HeaderText="Q56_14O: What factors contributed to your evaluation of your most recent service contact with your water company?|FOURTEENTH MENTIONED (Other)"  ConnectionString="<%$ ConnectionStrings:MCProd %>"   SelectCommand="SELECT Distinct CustomerAnswer as txt, CustomerAnswer as val from CustomerSurveyAnswers where CustomerSurveyQuestionID=89" />
                <mmsi:CustomerSurveyDataField runat="server" ID="Q56_15" QuestionID="90" DataType="DropDownList"  DataFieldName="CustomerAnswer" HeaderText="Q56_15: What factors contributed to your evaluation of your most recent service contact with your water company?|FIFTEENTH MENTIONED"  ConnectionString="<%$ ConnectionStrings:MCProd %>"   SelectCommand="SELECT Distinct CustomerAnswer as txt, CustomerAnswer as val from CustomerSurveyAnswers where CustomerSurveyQuestionID=90" />
                <mmsi:CustomerSurveyDataField runat="server" ID="Q56_15O" QuestionID="91" DataType="String"  DataFieldName="CustomerAnswer" HeaderText="Q56_15O: What factors contributed to your evaluation of your most recent service contact with your water company?|FIFTEENTH MENTIONED (Other)"  ConnectionString="<%$ ConnectionStrings:MCProd %>"   SelectCommand="SELECT Distinct CustomerAnswer as txt, CustomerAnswer as val from CustomerSurveyAnswers where CustomerSurveyQuestionID=91" />
                <mmsi:CustomerSurveyDataField runat="server" ID="Q56_16" QuestionID="92" DataType="DropDownList"  DataFieldName="CustomerAnswer" HeaderText="Q56_16: What factors contributed to your evaluation of your most recent service contact with your water company?|SIXTEENTH MENTIONED"  ConnectionString="<%$ ConnectionStrings:MCProd %>"   SelectCommand="SELECT Distinct CustomerAnswer as txt, CustomerAnswer as val from CustomerSurveyAnswers where CustomerSurveyQuestionID=92" />
                <mmsi:CustomerSurveyDataField runat="server" ID="Q56_16O" QuestionID="93" DataType="String"  DataFieldName="CustomerAnswer" HeaderText="Q56_16O: What factors contributed to your evaluation of your most recent service contact with your water company?|SIXTEENTH MENTIONED (Other)"  ConnectionString="<%$ ConnectionStrings:MCProd %>"   SelectCommand="SELECT Distinct CustomerAnswer as txt, CustomerAnswer as val from CustomerSurveyAnswers where CustomerSurveyQuestionID=93" />
                <mmsi:CustomerSurveyDataField runat="server" ID="Q56_17" QuestionID="94" DataType="DropDownList"  DataFieldName="CustomerAnswer" HeaderText="Q56_17: What factors contributed to your evaluation of your most recent service contact with your water company?|SEVENTEENTH MENTIONED"  ConnectionString="<%$ ConnectionStrings:MCProd %>"   SelectCommand="SELECT Distinct CustomerAnswer as txt, CustomerAnswer as val from CustomerSurveyAnswers where CustomerSurveyQuestionID=94" />
                <mmsi:CustomerSurveyDataField runat="server" ID="Q56_17O" QuestionID="95" DataType="String"  DataFieldName="CustomerAnswer" HeaderText="Q56_17O: What factors contributed to your evaluation of your most recent service contact with your water company?|SEVENTEENTH MENTIONED (Other)"  ConnectionString="<%$ ConnectionStrings:MCProd %>"   SelectCommand="SELECT Distinct CustomerAnswer as txt, CustomerAnswer as val from CustomerSurveyAnswers where CustomerSurveyQuestionID=95" />
                <mmsi:CustomerSurveyDataField runat="server" ID="Q56_18" QuestionID="96" DataType="DropDownList"  DataFieldName="CustomerAnswer" HeaderText="Q56_18: What factors contributed to your evaluation of your most recent service contact with your water company?|EIGHTEENTH MENTIONED"  ConnectionString="<%$ ConnectionStrings:MCProd %>"   SelectCommand="SELECT Distinct CustomerAnswer as txt, CustomerAnswer as val from CustomerSurveyAnswers where CustomerSurveyQuestionID=96" />
                <mmsi:CustomerSurveyDataField runat="server" ID="Q56_18O" QuestionID="97" DataType="String"  DataFieldName="CustomerAnswer" HeaderText="Q56_18O: What factors contributed to your evaluation of your most recent service contact with your water company?|EIGHTEENTH MENTIONED (Other)"  ConnectionString="<%$ ConnectionStrings:MCProd %>"   SelectCommand="SELECT Distinct CustomerAnswer as txt, CustomerAnswer as val from CustomerSurveyAnswers where CustomerSurveyQuestionID=97" />
                <mmsi:CustomerSurveyDataField runat="server" ID="Q56_19" QuestionID="98" DataType="DropDownList"  DataFieldName="CustomerAnswer" HeaderText="Q56_19: What factors contributed to your evaluation of your most recent service contact with your water company?|NINETEENTH MENTIONED"  ConnectionString="<%$ ConnectionStrings:MCProd %>"   SelectCommand="SELECT Distinct CustomerAnswer as txt, CustomerAnswer as val from CustomerSurveyAnswers where CustomerSurveyQuestionID=98" />
                <mmsi:CustomerSurveyDataField runat="server" ID="Q56_19O" QuestionID="99" DataType="String"  DataFieldName="CustomerAnswer" HeaderText="Q56_19O: What factors contributed to your evaluation of your most recent service contact with your water company?|NINETEENTH MENTIONED (Other)"  ConnectionString="<%$ ConnectionStrings:MCProd %>"   SelectCommand="SELECT Distinct CustomerAnswer as txt, CustomerAnswer as val from CustomerSurveyAnswers where CustomerSurveyQuestionID=99" />
                <mmsi:CustomerSurveyDataField runat="server" ID="Q56_20" QuestionID="100" DataType="DropDownList"  DataFieldName="CustomerAnswer" HeaderText="Q56_20: What factors contributed to your evaluation of your most recent service contact with your water company?|TWENTIETH MENTIONED"  ConnectionString="<%$ ConnectionStrings:MCProd %>"   SelectCommand="SELECT Distinct CustomerAnswer as txt, CustomerAnswer as val from CustomerSurveyAnswers where CustomerSurveyQuestionID=100" />
                <mmsi:CustomerSurveyDataField runat="server" ID="Q56_20O" QuestionID="101" DataType="String"  DataFieldName="CustomerAnswer" HeaderText="Q56_20O: What factors contributed to your evaluation of your most recent service contact with your water company?|TWENTIETH MENTIONED (Other)"  ConnectionString="<%$ ConnectionStrings:MCProd %>"   SelectCommand="SELECT Distinct CustomerAnswer as txt, CustomerAnswer as val from CustomerSurveyAnswers where CustomerSurveyQuestionID=101" />
                <mmsi:CustomerSurveyDataField runat="server" ID="Q57" QuestionID="102" DataType="DropDownList"  DataFieldName="CustomerAnswer" HeaderText="Q57: Thinking about your recent experience with your water company, how many different times did you need to contact your water company?"  ConnectionString="<%$ ConnectionStrings:MCProd %>"   SelectCommand="SELECT Distinct CustomerAnswer as txt, CustomerAnswer as val from CustomerSurveyAnswers where CustomerSurveyQuestionID=102" />
                <mmsi:CustomerSurveyDataField runat="server" ID="Q58" QuestionID="103" DataType="DropDownList"  DataFieldName="CustomerAnswer" HeaderText="Q58: Was the reason why you contacted your water company completely resolved?"  ConnectionString="<%$ ConnectionStrings:MCProd %>"   SelectCommand="SELECT Distinct CustomerAnswer as txt, CustomerAnswer as val from CustomerSurveyAnswers where CustomerSurveyQuestionID=103" />
                <mmsi:CustomerSurveyDataField runat="server" ID="Q59" QuestionID="104" DataType="DropDownList"  DataFieldName="CustomerAnswer" HeaderText="Q59: Would you like me to contact someone in customer service from your water company and ask them to contact you about your most recent service experience?"  ConnectionString="<%$ ConnectionStrings:MCProd %>"   SelectCommand="SELECT Distinct CustomerAnswer as txt, CustomerAnswer as val from CustomerSurveyAnswers where CustomerSurveyQuestionID=104" />
                <mmsi:CustomerSurveyDataField runat="server" ID="Q60" QuestionID="105" DataType="DropDownList"  DataFieldName="CustomerAnswer" HeaderText="Q60: Is there anything that your water company could have done differently that would have made your service experience better in any way?"  ConnectionString="<%$ ConnectionStrings:MCProd %>"   SelectCommand="SELECT Distinct CustomerAnswer as txt, CustomerAnswer as val from CustomerSurveyAnswers where CustomerSurveyQuestionID=105" />
                <mmsi:CustomerSurveyDataField runat="server" ID="Q61" QuestionID="106" DataType="DropDownList"  DataFieldName="CustomerAnswer" HeaderText="Q61: In your own words, what could your water company have done differently that would have made your service experience better?"  ConnectionString="<%$ ConnectionStrings:MCProd %>"   SelectCommand="SELECT Distinct CustomerAnswer as txt, CustomerAnswer as val from CustomerSurveyAnswers where CustomerSurveyQuestionID=106" />
                <mmsi:CustomerSurveyDataField runat="server" ID="Q61O" QuestionID="107" DataType="String"  DataFieldName="CustomerAnswer" HeaderText="Q61O: In your own words, what could your water company have done differently that would have made your service experience better? (Other)"  ConnectionString="<%$ ConnectionStrings:MCProd %>"   SelectCommand="SELECT Distinct CustomerAnswer as txt, CustomerAnswer as val from CustomerSurveyAnswers where CustomerSurveyQuestionID=107" />
                <mmsi:CustomerSurveyDataField runat="server" ID="Q62" QuestionID="108" DataType="DropDownList"  DataFieldName="CustomerAnswer" HeaderText="Q62: Have you contacted your local electric company for any reason in the past 6 months?"  ConnectionString="<%$ ConnectionStrings:MCProd %>"   SelectCommand="SELECT Distinct CustomerAnswer as txt, CustomerAnswer as val from CustomerSurveyAnswers where CustomerSurveyQuestionID=108" />
                <mmsi:CustomerSurveyDataField runat="server" ID="Q63" QuestionID="109" DataType="DropDownList"  DataFieldName="CustomerAnswer" HeaderText="Q63: Thinking about the most recent time you contacted your local electric company, what was the reason for the contact?"  ConnectionString="<%$ ConnectionStrings:MCProd %>"   SelectCommand="SELECT Distinct CustomerAnswer as txt, CustomerAnswer as val from CustomerSurveyAnswers where CustomerSurveyQuestionID=109" />
                <mmsi:CustomerSurveyDataField runat="server" ID="Q63O" QuestionID="110" DataType="String"  DataFieldName="CustomerAnswer" HeaderText="Q63O: Thinking about the most recent time you contacted your local electric company, what was the reason for the contact? (Other)"  ConnectionString="<%$ ConnectionStrings:MCProd %>"   SelectCommand="SELECT Distinct CustomerAnswer as txt, CustomerAnswer as val from CustomerSurveyAnswers where CustomerSurveyQuestionID=110" />
                <mmsi:CustomerSurveyDataField runat="server" ID="Q64" QuestionID="111" DataType="DropDownList"  DataFieldName="CustomerAnswer" HeaderText="Q64: How would you rate your overall satisfaction with the outcome of your most recent service contact with your local electric company? Would you say you are:"  ConnectionString="<%$ ConnectionStrings:MCProd %>"   SelectCommand="SELECT Distinct CustomerAnswer as txt, CustomerAnswer as val from CustomerSurveyAnswers where CustomerSurveyQuestionID=111" />
                <mmsi:CustomerSurveyDataField runat="server" ID="Q65" QuestionID="112" DataType="DropDownList"  DataFieldName="CustomerAnswer" HeaderText="Q65: Have you contacted your local natural gas company for any reason in the past 6 months?"  ConnectionString="<%$ ConnectionStrings:MCProd %>"   SelectCommand="SELECT Distinct CustomerAnswer as txt, CustomerAnswer as val from CustomerSurveyAnswers where CustomerSurveyQuestionID=112" />
                <mmsi:CustomerSurveyDataField runat="server" ID="Q66" QuestionID="113" DataType="DropDownList"  DataFieldName="CustomerAnswer" HeaderText="Q66: Thinking about the time you contacted your local natural gas company, what was the reason for the contact?"  ConnectionString="<%$ ConnectionStrings:MCProd %>"   SelectCommand="SELECT Distinct CustomerAnswer as txt, CustomerAnswer as val from CustomerSurveyAnswers where CustomerSurveyQuestionID=113" />
                <mmsi:CustomerSurveyDataField runat="server" ID="Q66O" QuestionID="114" DataType="String"  DataFieldName="CustomerAnswer" HeaderText="Q66O: Thinking about the time you contacted your local natural gas company, what was the reason for the contact? (Other)"  ConnectionString="<%$ ConnectionStrings:MCProd %>"   SelectCommand="SELECT Distinct CustomerAnswer as txt, CustomerAnswer as val from CustomerSurveyAnswers where CustomerSurveyQuestionID=114" />
                <mmsi:CustomerSurveyDataField runat="server" ID="Q67" QuestionID="115" DataType="DropDownList"  DataFieldName="CustomerAnswer" HeaderText="Q67: How would you rate your overall satisfaction with the outcome of your most recent service contact with your local natural gas company? Would you say you are:"  ConnectionString="<%$ ConnectionStrings:MCProd %>"   SelectCommand="SELECT Distinct CustomerAnswer as txt, CustomerAnswer as val from CustomerSurveyAnswers where CustomerSurveyQuestionID=115" />
                <mmsi:CustomerSurveyDataField runat="server" ID="D01" QuestionID="116" DataType="DropDownList"  DataFieldName="CustomerAnswer" HeaderText="D01: Age"  ConnectionString="<%$ ConnectionStrings:MCProd %>"   SelectCommand="SELECT Distinct CustomerAnswer as txt, CustomerAnswer as val from CustomerSurveyAnswers where CustomerSurveyQuestionID=116" />
                <mmsi:CustomerSurveyDataField runat="server" ID="D02" QuestionID="117" DataType="DropDownList"  DataFieldName="CustomerAnswer" HeaderText="D02: Do you own or rent the place where you live?"  ConnectionString="<%$ ConnectionStrings:MCProd %>"   SelectCommand="SELECT Distinct CustomerAnswer as txt, CustomerAnswer as val from CustomerSurveyAnswers where CustomerSurveyQuestionID=117" />
                <mmsi:CustomerSurveyDataField runat="server" ID="D03" QuestionID="118" DataType="DropDownList"  DataFieldName="CustomerAnswer" HeaderText="D03: Is your total household income above or below $50,000 per year before taxes?"  ConnectionString="<%$ ConnectionStrings:MCProd %>"   SelectCommand="SELECT Distinct CustomerAnswer as txt, CustomerAnswer as val from CustomerSurveyAnswers where CustomerSurveyQuestionID=118" />
                <mmsi:CustomerSurveyDataField runat="server" ID="D04" QuestionID="119" DataType="DropDownList"  DataFieldName="CustomerAnswer" HeaderText="D04: Income"  ConnectionString="<%$ ConnectionStrings:MCProd %>"   SelectCommand="SELECT Distinct CustomerAnswer as txt, CustomerAnswer as val from CustomerSurveyAnswers where CustomerSurveyQuestionID=119" />
                <mmsi:CustomerSurveyDataField runat="server" ID="GR" QuestionID="120" DataType="DropDownList"  DataFieldName="CustomerAnswer" HeaderText="GR: Gender of respondent"  ConnectionString="<%$ ConnectionStrings:MCProd %>"   SelectCommand="SELECT Distinct CustomerAnswer as txt, CustomerAnswer as val from CustomerSurveyAnswers where CustomerSurveyQuestionID=120" />
               
                <mmsi:CustomerSurveyDataField runat="server" ID="Q19New" QuestionID="121" DataType="DropDownList"  DataFieldName="CustomerAnswer" HeaderText="Q19 / Q19B COMBINED How satisfied were you with the outcome of your service contact?"  ConnectionString="<%$ ConnectionStrings:MCProd %>"   SelectCommand="SELECT Distinct CustomerAnswer as txt, CustomerAnswer as val from CustomerSurveyAnswers where CustomerSurveyQuestionID=121" />
                <mmsi:CustomerSurveyDataField runat="server" ID="Q21New" QuestionID="122" DataType="DropDownList"  DataFieldName="CustomerAnswer" HeaderText="Q21 How many different times did you contact American Water about your most recent request or concern?"  ConnectionString="<%$ ConnectionStrings:MCProd %>"   SelectCommand="SELECT Distinct CustomerAnswer as txt, CustomerAnswer as val from CustomerSurveyAnswers where CustomerSurveyQuestionID=122" />
                <mmsi:CustomerSurveyDataField runat="server" ID="Q15New" QuestionID="123" DataType="DropDownList"  DataFieldName="CustomerAnswer" HeaderText="Q15 Did the field service representative arrive as scheduled?"  ConnectionString="<%$ ConnectionStrings:MCProd %>"   SelectCommand="SELECT Distinct CustomerAnswer as txt, CustomerAnswer as val from CustomerSurveyAnswers where CustomerSurveyQuestionID=123" />
                <mmsi:CustomerSurveyDataField runat="server" ID="Q23New" QuestionID="124" DataType="DropDownList"  DataFieldName="CustomerAnswer" HeaderText="Q23 Did American Water leave information in the form of a door hanger, door tag, or a postcard?"  ConnectionString="<%$ ConnectionStrings:MCProd %>"   SelectCommand="SELECT Distinct CustomerAnswer as txt, CustomerAnswer as val from CustomerSurveyAnswers where CustomerSurveyQuestionID=124" />

               
                <tr>
                    <td></td>
                    <td>
                        <asp:Button runat="server" ID="btnSearch" Text="Search" OnClick="btnSearch_Click" />
                        <asp:Button runat="server" ID="btnReset" Text="Reset" OnClick="btnReset_Click" />
                        <asp:Button runat="server" ID="btnAdd" Text="Add" CausesValidation="False" OnClick="btnAdd_Click" />
                    </td>
                </tr>
            </table>
        </center>
    </asp:Panel>

    <asp:Panel runat="server" ID="pnlResults" Visible="false">
        <asp:HiddenField runat="server" ID="hidFilter" />
        <asp:Button runat="server" ID="btnExport" OnClick="btnExport_Click" Text="Export" />
        <asp:Button runat="server" ID="btnBackToSearch" OnClick="btnBackToSearch_Click" Text="Back to Search"/>
        <asp:Label runat="server" ID="lblRecordCount" />
        <asp:GridView ID="GridView1" runat="server" DataSourceID="SqlDataSource1" OnSelectedIndexChanged="GridView1_SelectedIndexChanged"
            DataKeyNames="CustomerSurveyID" AllowSorting="true" AllowPaging="true" PageSize="500"
            AutoGenerateColumns="false">
            <Columns>
                <asp:HyperLinkField DataNavigateUrlFields="CustomerSurveyID" DataNavigateUrlFormatString="~/Modules/Customer/CustomerSurvey.aspx?cmd=view&arg={0}" Text="View" />
                <mmsinc:BoundField DataField="Question" HeaderText="Question" SortExpression="Question" />
                <mmsinc:BoundField DataField="CustomerAnswer" HeaderText="Customer Answer" SortExpression="CustomerAnswer" />
                <mmsinc:BoundField DataField="OverallServiceQuality" HeaderText="Overall Service Quality" SortExpression="OverallServiceQuality" />
                <mmsinc:BoundField DataField="FSRServiceQuality" HeaderText="FSR Service Quality" SortExpression="FSRServiceQuality" />
            </Columns>
        </asp:GridView>
        <asp:SqlDataSource ID="SqlDataSource1" runat="server" 
            ConnectionString="<%$ ConnectionStrings:MCProd %>" 
            SelectCommand="
SELECT 
    A.CustomerSurveyID,
	Q.Question,
	A.CustomerSurveyQuestionID,
	A.CustomerAnswer,
	S.OperatingCenterID,
	S.OverallServiceQuality,
	S.FSRServiceQuality
FROM 
	CustomerSurveyAnswers A
INNER JOIN
	CustomerSurveyQuestions Q
ON
	Q.CustomerSurveyQuestionID = A.CustomerSurveyQuestionID
INNER JOIN
	CustomerSurveys S
ON
	s.CustomerSurveyID = A.CustomerSurveyID
            " />
    </asp:Panel>
</asp:Content>