#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MapCall.Common.Views.Shared
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/Error.cshtml")]
    public partial class Error : MapCall.Common.Views.TemplateViewBase<HandleErrorInfo>
    {
        public Error() : base() { }
        public override void Execute()
        {
            #line 3 "..\..\Views\Shared\Error.cshtml"
  
    ViewBag.Title = "Looks like there was a problem...";

            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" id=\"errWrapper\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" id=\"errMessage\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"error-section\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"error-section-message\"");

WriteLiteral(">\r\n                An unknown error has occurred while processing your request. A" +
" message regarding this error\r\n                has been sent to the site adminis" +
"trator. Please try again later.\r\n            </div>\r\n        </div>\r\n    </div>\r" +
"\n</div>");
        }
    }
}
#pragma warning restore 1591
