//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MapCall.SAP.service
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://amwater.com/EAM/0010/MAPCALL/CreateInspectionRecord", ConfigurationName="MapCall.SAP.service.InspectionRecord_Create_OB_SYN")]
    public interface InspectionRecord_Create_OB_SYN
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<MapCall.SAP.service.InspectionRecord_Create_OB_SYNResponse> InspectionRecord_Create_OB_SYNAsync(MapCall.SAP.service.InspectionRecord_Create_OB_SYNRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://amwater.com/EAM/0010/MAPCALL/CreateInspectionRecord")]
    public partial class InspectionRecordInspectionRecord
    {
        
        private string serviceObjectURLField;
        
        private string assetTypeField;
        
        private string notificationTypeField;
        
        private string shortTextField;
        
        private string notificationNoField;
        
        private string functionalLocationField;
        
        private string equipmentNoField;
        
        private string codeGroupField;
        
        private string codingField;
        
        private string planningPlantField;
        
        private string plannerGroupField;
        
        private string dateOfNotificationField;
        
        private string notificationTimeField;
        
        private string reportedByField;
        
        private string notificationLongTextField;
        
        private string priorityField;
        
        private string techInspectionByField;
        
        private string techInspectionOnField;
        
        private string inspectionTypeField;
        
        private string operatedField;
        
        private string positionFoundField;
        
        private string positionLeftField;
        
        private string openDirectionField;
        
        private string codeTypeField;
        
        private string rootCutterField;
        
        private string activityTextField;
        
        private string startDateField;
        
        private string startTimeOfActivityField;
        
        private string endDateField;
        
        private string endTimeOfActivityField;
        
        private string staticPressureField;
        
        private string flow1GPMField;
        
        private string flow1MinutesField;
        
        private string residualChlorineField;
        
        private string totalChlorineField;
        
        private string noTurnsOperatedField;
        
        private string flushWaterVolumeField;
        
        private string footageOfMainCleanedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ServiceObjectURL
        {
            get
            {
                return this.serviceObjectURLField;
            }
            set
            {
                this.serviceObjectURLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string AssetType
        {
            get
            {
                return this.assetTypeField;
            }
            set
            {
                this.assetTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string NotificationType
        {
            get
            {
                return this.notificationTypeField;
            }
            set
            {
                this.notificationTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string ShortText
        {
            get
            {
                return this.shortTextField;
            }
            set
            {
                this.shortTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string NotificationNo
        {
            get
            {
                return this.notificationNoField;
            }
            set
            {
                this.notificationNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string FunctionalLocation
        {
            get
            {
                return this.functionalLocationField;
            }
            set
            {
                this.functionalLocationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string EquipmentNo
        {
            get
            {
                return this.equipmentNoField;
            }
            set
            {
                this.equipmentNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string CodeGroup
        {
            get
            {
                return this.codeGroupField;
            }
            set
            {
                this.codeGroupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string Coding
        {
            get
            {
                return this.codingField;
            }
            set
            {
                this.codingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string PlanningPlant
        {
            get
            {
                return this.planningPlantField;
            }
            set
            {
                this.planningPlantField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string PlannerGroup
        {
            get
            {
                return this.plannerGroupField;
            }
            set
            {
                this.plannerGroupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string DateOfNotification
        {
            get
            {
                return this.dateOfNotificationField;
            }
            set
            {
                this.dateOfNotificationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string NotificationTime
        {
            get
            {
                return this.notificationTimeField;
            }
            set
            {
                this.notificationTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string ReportedBy
        {
            get
            {
                return this.reportedByField;
            }
            set
            {
                this.reportedByField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string NotificationLongText
        {
            get
            {
                return this.notificationLongTextField;
            }
            set
            {
                this.notificationLongTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string Priority
        {
            get
            {
                return this.priorityField;
            }
            set
            {
                this.priorityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string TechInspectionBy
        {
            get
            {
                return this.techInspectionByField;
            }
            set
            {
                this.techInspectionByField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string TechInspectionOn
        {
            get
            {
                return this.techInspectionOnField;
            }
            set
            {
                this.techInspectionOnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string InspectionType
        {
            get
            {
                return this.inspectionTypeField;
            }
            set
            {
                this.inspectionTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string Operated
        {
            get
            {
                return this.operatedField;
            }
            set
            {
                this.operatedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string PositionFound
        {
            get
            {
                return this.positionFoundField;
            }
            set
            {
                this.positionFoundField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public string PositionLeft
        {
            get
            {
                return this.positionLeftField;
            }
            set
            {
                this.positionLeftField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public string OpenDirection
        {
            get
            {
                return this.openDirectionField;
            }
            set
            {
                this.openDirectionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public string CodeType
        {
            get
            {
                return this.codeTypeField;
            }
            set
            {
                this.codeTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public string RootCutter
        {
            get
            {
                return this.rootCutterField;
            }
            set
            {
                this.rootCutterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=25)]
        public string ActivityText
        {
            get
            {
                return this.activityTextField;
            }
            set
            {
                this.activityTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=26)]
        public string StartDate
        {
            get
            {
                return this.startDateField;
            }
            set
            {
                this.startDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=27)]
        public string StartTimeOfActivity
        {
            get
            {
                return this.startTimeOfActivityField;
            }
            set
            {
                this.startTimeOfActivityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=28)]
        public string EndDate
        {
            get
            {
                return this.endDateField;
            }
            set
            {
                this.endDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=29)]
        public string EndTimeOfActivity
        {
            get
            {
                return this.endTimeOfActivityField;
            }
            set
            {
                this.endTimeOfActivityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=30)]
        public string StaticPressure
        {
            get
            {
                return this.staticPressureField;
            }
            set
            {
                this.staticPressureField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=31)]
        public string Flow1GPM
        {
            get
            {
                return this.flow1GPMField;
            }
            set
            {
                this.flow1GPMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=32)]
        public string Flow1Minutes
        {
            get
            {
                return this.flow1MinutesField;
            }
            set
            {
                this.flow1MinutesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=33)]
        public string ResidualChlorine
        {
            get
            {
                return this.residualChlorineField;
            }
            set
            {
                this.residualChlorineField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=34)]
        public string TotalChlorine
        {
            get
            {
                return this.totalChlorineField;
            }
            set
            {
                this.totalChlorineField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=35)]
        public string noTurnsOperated
        {
            get
            {
                return this.noTurnsOperatedField;
            }
            set
            {
                this.noTurnsOperatedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=36)]
        public string FlushWaterVolume
        {
            get
            {
                return this.flushWaterVolumeField;
            }
            set
            {
                this.flushWaterVolumeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=37)]
        public string FootageOfMainCleaned
        {
            get
            {
                return this.footageOfMainCleanedField;
            }
            set
            {
                this.footageOfMainCleanedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://amwater.com/EAM/0010/MAPCALL/CreateInspectionRecord")]
    public partial class SAPNotificationNumberNotificationNumber
    {
        
        private string sAPNotificationNumberField;
        
        private string statusField;
        
        private string costCenterField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string SAPNotificationNumber
        {
            get
            {
                return this.sAPNotificationNumberField;
            }
            set
            {
                this.sAPNotificationNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string CostCenter
        {
            get
            {
                return this.costCenterField;
            }
            set
            {
                this.costCenterField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InspectionRecord_Create_OB_SYNRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://amwater.com/EAM/0010/MAPCALL/CreateInspectionRecord", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("InspectionRecord", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public MapCall.SAP.service.InspectionRecordInspectionRecord[] InspectionRecordCreate_Req;
        
        public InspectionRecord_Create_OB_SYNRequest()
        {
        }
        
        public InspectionRecord_Create_OB_SYNRequest(MapCall.SAP.service.InspectionRecordInspectionRecord[] InspectionRecordCreate_Req)
        {
            this.InspectionRecordCreate_Req = InspectionRecordCreate_Req;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InspectionRecord_Create_OB_SYNResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://amwater.com/EAM/0010/MAPCALL/CreateInspectionRecord", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("NotificationNumber", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public MapCall.SAP.service.SAPNotificationNumberNotificationNumber[] SAPNotificationNumber_Res;
        
        public InspectionRecord_Create_OB_SYNResponse()
        {
        }
        
        public InspectionRecord_Create_OB_SYNResponse(MapCall.SAP.service.SAPNotificationNumberNotificationNumber[] SAPNotificationNumber_Res)
        {
            this.SAPNotificationNumber_Res = SAPNotificationNumber_Res;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface InspectionRecord_Create_OB_SYNChannel : MapCall.SAP.service.InspectionRecord_Create_OB_SYN, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class InspectionRecord_Create_OB_SYNClient : System.ServiceModel.ClientBase<MapCall.SAP.service.InspectionRecord_Create_OB_SYN>, MapCall.SAP.service.InspectionRecord_Create_OB_SYN
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public InspectionRecord_Create_OB_SYNClient() : 
                base(InspectionRecord_Create_OB_SYNClient.GetDefaultBinding(), InspectionRecord_Create_OB_SYNClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.port.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public InspectionRecord_Create_OB_SYNClient(EndpointConfiguration endpointConfiguration) : 
                base(InspectionRecord_Create_OB_SYNClient.GetBindingForEndpoint(endpointConfiguration), InspectionRecord_Create_OB_SYNClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public InspectionRecord_Create_OB_SYNClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(InspectionRecord_Create_OB_SYNClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public InspectionRecord_Create_OB_SYNClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(InspectionRecord_Create_OB_SYNClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public InspectionRecord_Create_OB_SYNClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MapCall.SAP.service.InspectionRecord_Create_OB_SYNResponse> MapCall.SAP.service.InspectionRecord_Create_OB_SYN.InspectionRecord_Create_OB_SYNAsync(MapCall.SAP.service.InspectionRecord_Create_OB_SYNRequest request)
        {
            return base.Channel.InspectionRecord_Create_OB_SYNAsync(request);
        }
        
        public System.Threading.Tasks.Task<MapCall.SAP.service.InspectionRecord_Create_OB_SYNResponse> InspectionRecord_Create_OB_SYNAsync(MapCall.SAP.service.InspectionRecordInspectionRecord[] InspectionRecordCreate_Req)
        {
            MapCall.SAP.service.InspectionRecord_Create_OB_SYNRequest inValue = new MapCall.SAP.service.InspectionRecord_Create_OB_SYNRequest();
            inValue.InspectionRecordCreate_Req = InspectionRecordCreate_Req;
            return ((MapCall.SAP.service.InspectionRecord_Create_OB_SYN)(this)).InspectionRecord_Create_OB_SYNAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.port))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.port))
            {
                return new System.ServiceModel.EndpointAddress("https://e10028-iflmap.hcisbt.us3.hana.ondemand.com/cxf/InspectionRecord_Create");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return InspectionRecord_Create_OB_SYNClient.GetBindingForEndpoint(EndpointConfiguration.port);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return InspectionRecord_Create_OB_SYNClient.GetEndpointAddress(EndpointConfiguration.port);
        }
        
        public enum EndpointConfiguration
        {
            
            port,
        }
    }
}
