using System.Collections.Generic;
using MapCallScheduler.JobHelpers.SapPremise;
using MapCallScheduler.Tests.Library.JobHelpers.Sap;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using MMSINC.Testing.MSTest.TestExtensions;

namespace MapCallScheduler.Tests.JobHelpers.SapPremises
{
    [TestClass]
    public class SapPremiseFileParserTest : SapFileParserTestBase<SapPremiseFileParser, SapPremiseFileRecord>
    {
        #region Properties

        protected override string SampleFile => "TestData/sap_premise_sample.csv";

        protected override IEnumerable<SapPremiseFileRecord> SampleRecords => new[] {
            new SapPremiseFileRecord {
                PremiseNumber = "8000014256",
                ConnectionObject = "4000006696",
                ServiceAddressApartment = "56",
                ServiceCity = "City of Whitwell",
                ServiceDistrict = "15",
                ServiceDistrictDescription = "Whitwell",
                AreaCode = "2615",
                AreaCodeDescription = "Sequatchie Valley",
                RegionCode = "26WW",
                RegionCodeDescription = "City of Whitwell",
                StatusCode = "Active",
                IsMajorAccount = true,
                MajorAccountManager = "Manager Name",
                AccountManagerEmail = "Accountmanager@account.com",
                AccountManagerContactNumber = "856-123-4567"
            },
            new SapPremiseFileRecord {
                PremiseNumber = "8000014257",
                ConnectionObject = "4000006697",
                ServiceAddressApartment = "57",
                ServiceCity = "City of Whitwell",
                ServiceDistrict = "15",
                ServiceDistrictDescription = "Whitwell",
                AreaCode = "2615",
                AreaCodeDescription = "Sequatchie Valley",
                RegionCode = "26WW",
                RegionCodeDescription = "City of Whitwell",
                StatusCode = "Active"
            },
            new SapPremiseFileRecord {
                PremiseNumber = "8000014867",
                ConnectionObject = "4000007307",
                ServiceAddressApartment = "67",
                ServiceCity = "City of Whitwell",
                ServiceDistrict = "15",
                ServiceDistrictDescription = "Whitwell",
                AreaCode = "2615",
                AreaCodeDescription = "Sequatchie Valley",
                RegionCode = "26WW",
                RegionCodeDescription = "City of Whitwell",
                StatusCode = "Active"
            },
            new SapPremiseFileRecord {
                PremiseNumber = "8000014885",
                ConnectionObject = "4000007325",
                ServiceAddressApartment = "85",
                ServiceCity = "City of Whitwell",
                ServiceDistrict = "15",
                ServiceDistrictDescription = "Whitwell",
                AreaCode = "2615",
                AreaCodeDescription = "Sequatchie Valley",
                RegionCode = "26WW",
                RegionCodeDescription = "City of Whitwell",
                StatusCode = "Active"
            },
            new SapPremiseFileRecord {
                PremiseNumber = "8000002123",
                ConnectionObject = "4000010201",
                ServiceAddressHouseNumber = "223",
                ServiceAddressFraction = "223",
                ServiceAddressApartment = "225",
                ServiceAddressStreet = "Kings Hwy E",
                ServiceCity = "Haddonfield",
                ServiceState = "NJ",
                ServiceZip = "08033-1902",
                ServiceDistrict = "15",
                ServiceDistrictDescription = "Burlington/Camden(Haddon)",
                AreaCode = "1816",
                AreaCodeDescription = "Haddonfield (Haddon)",
                RegionCode = "0417",
                RegionCodeDescription = "Haddonfield",
                StatusCode = "Active"
            },
            new SapPremiseFileRecord {
                PremiseNumber = "8000002242",
                ConnectionObject = "4000010240",
                ServiceAddressHouseNumber = "324",
                ServiceAddressFraction = "324",
                ServiceAddressApartment = "326",
                ServiceAddressStreet = "Belmont Ave",
                ServiceCity = "Haddonfield",
                ServiceState = "NJ",
                ServiceZip = "08033-1302",
                ServiceDistrict = "15",
                ServiceDistrictDescription = "Burlington/Camden(Haddon)",
                AreaCode = "1816",
                AreaCodeDescription = "Haddonfield (Haddon)",
                RegionCode = "0417",
                RegionCodeDescription = "Haddonfield",
                StatusCode = "Active"
            },
            new SapPremiseFileRecord {
                PremiseNumber = "8000001314",
                ConnectionObject = "4000010862",
                ServiceAddressHouseNumber = "224",
                ServiceAddressFraction = "224",
                ServiceAddressApartment = "1234",
                ServiceAddressStreet = "Center St",
                ServiceCity = "Haddonfield",
                ServiceState = "NJ",
                ServiceZip = "08033-1806",
                ServiceDistrict = "15",
                ServiceDistrictDescription = "Burlington/Camden(Haddon)",
                AreaCode = "1816",
                AreaCodeDescription = "Haddonfield (Haddon)",
                RegionCode = "0417",
                RegionCodeDescription = "Haddonfield",
                StatusCode = "Active"
            },
            new SapPremiseFileRecord {
                PremiseNumber = "8000002085",
                ConnectionObject = "4000010133",
                ServiceAddressHouseNumber = "80",
                ServiceAddressFraction = "80",
                ServiceAddressApartment = "82",
                ServiceAddressStreet = "Grove St",
                ServiceCity = "Haddonfield",
                ServiceState = "NJ",
                ServiceZip = "08033-1220",
                ServiceDistrict = "15",
                ServiceDistrictDescription = "Burlington/Camden(Haddon)",
                AreaCode = "1816",
                AreaCodeDescription = "Haddonfield (Haddon)",
                RegionCode = "0417",
                RegionCodeDescription = "Haddonfield",
                StatusCode = "Active"
            },
            new SapPremiseFileRecord {
                PremiseNumber = "8000002159",
                ConnectionObject = "4000010285",
                ServiceAddressHouseNumber = "145",
                ServiceAddressFraction = "145",
                ServiceAddressApartment = "147",
                ServiceAddressStreet = "Kings Hwy E",
                ServiceCity = "Haddonfield",
                ServiceState = "NJ",
                ServiceZip = "08033-2007",
                ServiceDistrict = "15",
                ServiceDistrictDescription = "Burlington/Camden(Haddon)",
                AreaCode = "1816",
                AreaCodeDescription = "Haddonfield (Haddon)",
                RegionCode = "0417",
                RegionCodeDescription = "Haddonfield",
                StatusCode = "Active"
            },
            new SapPremiseFileRecord {
                PremiseNumber = "8000002160",
                ConnectionObject = "4000010287",
                ServiceAddressHouseNumber = "145",
                ServiceAddressFraction = "145",
                ServiceAddressApartment = "147",
                ServiceAddressStreet = "Kings Hwy E",
                ServiceCity = "Haddonfield",
                ServiceState = "NJ",
                ServiceZip = "08033-2007",
                ServiceDistrict = "15",
                ServiceDistrictDescription = "Burlington/Camden(Haddon)",
                AreaCode = "1816",
                AreaCodeDescription = "Haddonfield (Haddon)",
                RegionCode = "0417",
                RegionCodeDescription = "Haddonfield",
                StatusCode = "Active"
            },
            new SapPremiseFileRecord {
                PremiseNumber = "8000002161",
                ConnectionObject = "4000010289",
                ServiceAddressHouseNumber = "145",
                ServiceAddressFraction = "145",
                ServiceAddressApartment = "147",
                ServiceAddressStreet = "Kings Hwy E",
                ServiceCity = "Haddonfield",
                ServiceState = "NJ",
                ServiceZip = "08033-2007",
                ServiceDistrict = "15",
                ServiceDistrictDescription = "Burlington/Camden(Haddon)",
                AreaCode = "1816",
                AreaCodeDescription = "Haddonfield (Haddon)",
                RegionCode = "0417",
                RegionCodeDescription = "Haddonfield",
                StatusCode = "Active"
            },
            new SapPremiseFileRecord {
                PremiseNumber = "8000002162",
                ConnectionObject = "4000010291",
                ServiceAddressHouseNumber = "145",
                ServiceAddressFraction = "145",
                ServiceAddressApartment = "147",
                ServiceAddressStreet = "Kings Hwy E",
                ServiceCity = "Haddonfield",
                ServiceState = "NJ",
                ServiceZip = "08033-2007",
                ServiceDistrict = "15",
                ServiceDistrictDescription = "Burlington/Camden(Haddon)",
                AreaCode = "1816",
                AreaCodeDescription = "Haddonfield (Haddon)",
                RegionCode = "0417",
                RegionCodeDescription = "Haddonfield",
                StatusCode = "Active"
            },
            new SapPremiseFileRecord {
                PremiseNumber = "8000002175",
                ConnectionObject = "4000010313",
                ServiceAddressHouseNumber = "21",
                ServiceAddressFraction = "21",
                ServiceAddressApartment = "23",
                ServiceAddressStreet = "Mechanic St",
                ServiceCity = "Haddonfield",
                ServiceState = "NJ",
                ServiceZip = "08033-2411",
                ServiceDistrict = "15",
                ServiceDistrictDescription = "Burlington/Camden(Haddon)",
                AreaCode = "1816",
                AreaCodeDescription = "Haddonfield (Haddon)",
                RegionCode = "0417",
                RegionCodeDescription = "Haddonfield",
                StatusCode = "Active"
            },
            new SapPremiseFileRecord {
                PremiseNumber = "8000002177",
                ConnectionObject = "4000010317",
                ServiceAddressHouseNumber = "18",
                ServiceAddressFraction = "18",
                ServiceAddressApartment = "22",
                ServiceAddressStreet = "S Haddon Ave",
                ServiceCity = "Haddonfield",
                ServiceState = "NJ",
                ServiceZip = "08033-1860",
                ServiceDistrict = "15",
                ServiceDistrictDescription = "Burlington/Camden(Haddon)",
                AreaCode = "1816",
                AreaCodeDescription = "Haddonfield (Haddon)",
                RegionCode = "0417",
                RegionCodeDescription = "Haddonfield",
                StatusCode = "Active"
            },
            new SapPremiseFileRecord {
                PremiseNumber = "8000002178",
                ConnectionObject = "4000010319",
                ServiceAddressHouseNumber = "135",
                ServiceAddressFraction = "135",
                ServiceAddressApartment = "137",
                ServiceAddressStreet = "Kings Hwy E",
                ServiceCity = "Haddonfield",
                ServiceState = "NJ",
                ServiceZip = "08033-2014",
                ServiceDistrict = "15",
                ServiceDistrictDescription = "Burlington/Camden(Haddon)",
                AreaCode = "1816",
                AreaCodeDescription = "Haddonfield (Haddon)",
                RegionCode = "0417",
                RegionCodeDescription = "Haddonfield",
                StatusCode = "Active"
            },
            new SapPremiseFileRecord {
                PremiseNumber = "8000002485",
                ConnectionObject = "4000010539",
                ServiceAddressHouseNumber = "69",
                ServiceAddressFraction = "69",
                ServiceAddressApartment = "APT",
                ServiceAddressStreet = "Ellis St",
                ServiceCity = "Haddonfield",
                ServiceState = "NJ",
                ServiceZip = "08033-1826",
                ServiceDistrict = "15",
                ServiceDistrictDescription = "Burlington/Camden(Haddon)",
                AreaCode = "1816",
                AreaCodeDescription = "Haddonfield (Haddon)",
                RegionCode = "0417",
                RegionCodeDescription = "Haddonfield",
                StatusCode = "Active"
            },
            new SapPremiseFileRecord {
                PremiseNumber = "8000002206",
                ConnectionObject = "4000010380",
                ServiceAddressHouseNumber = "119",
                ServiceAddressFraction = "119",
                ServiceAddressApartment = "121",
                ServiceAddressStreet = "Kings Hwy E",
                ServiceCity = "Haddonfield",
                ServiceState = "NJ",
                ServiceZip = "08033-2003",
                ServiceDistrict = "15",
                ServiceDistrictDescription = "Burlington/Camden(Haddon)",
                AreaCode = "1816",
                AreaCodeDescription = "Haddonfield (Haddon)",
                RegionCode = "0417",
                RegionCodeDescription = "Haddonfield",
                StatusCode = "Active"
            },
            new SapPremiseFileRecord {
                PremiseNumber = "8000002207",
                ConnectionObject = "4000010382",
                ServiceAddressHouseNumber = "119",
                ServiceAddressFraction = "119",
                ServiceAddressApartment = "121",
                ServiceAddressStreet = "Kings Hwy E",
                ServiceCity = "Haddonfield",
                ServiceState = "NJ",
                ServiceZip = "08033-2003",
                ServiceDistrict = "15",
                ServiceDistrictDescription = "Burlington/Camden(Haddon)",
                AreaCode = "1816",
                AreaCodeDescription = "Haddonfield (Haddon)",
                RegionCode = "0417",
                RegionCodeDescription = "Haddonfield",
                StatusCode = "Active"
            },
            new SapPremiseFileRecord {
                PremiseNumber = "8000002455",
                ConnectionObject = "4000010479",
                ServiceAddressHouseNumber = "220",
                ServiceAddressFraction = "220",
                ServiceAddressApartment = "224",
                ServiceAddressStreet = "Kings Hwy E",
                ServiceCity = "Haddonfield",
                ServiceState = "NJ",
                ServiceZip = "08033-1907",
                ServiceDistrict = "15",
                ServiceDistrictDescription = "Burlington/Camden(Haddon)",
                AreaCode = "1816",
                AreaCodeDescription = "Haddonfield (Haddon)",
                RegionCode = "0417",
                RegionCodeDescription = "Haddonfield",
                StatusCode = "Active"
            },
            new SapPremiseFileRecord {
                PremiseNumber = "8000002458",
                ConnectionObject = "4000010485",
                ServiceAddressHouseNumber = "230",
                ServiceAddressFraction = "230",
                ServiceAddressApartment = "232",
                ServiceAddressStreet = "Kings Hwy E",
                ServiceCity = "Haddonfield",
                ServiceState = "NJ",
                ServiceZip = "08033-1907",
                ServiceDistrict = "15",
                ServiceDistrictDescription = "Burlington/Camden(Haddon)",
                AreaCode = "1816",
                AreaCodeDescription = "Haddonfield (Haddon)",
                RegionCode = "0417",
                RegionCodeDescription = "Haddonfield",
                StatusCode = "Active"
            },
            new SapPremiseFileRecord {
                PremiseNumber = "8000002515",
                ConnectionObject = "4000010599",
                ServiceAddressHouseNumber = "202",
                ServiceAddressFraction = "202",
                ServiceAddressApartment = "204",
                ServiceAddressStreet = "Kings Hwy E",
                ServiceCity = "Haddonfield",
                ServiceState = "NJ",
                ServiceZip = "08033-1905",
                ServiceDistrict = "15",
                ServiceDistrictDescription = "Burlington/Camden(Haddon)",
                AreaCode = "1816",
                AreaCodeDescription = "Haddonfield (Haddon)",
                RegionCode = "0417",
                RegionCodeDescription = "Haddonfield",
                StatusCode = "Active"
            },
            new SapPremiseFileRecord {
                PremiseNumber = "8000002521",
                ConnectionObject = "4000010611",
                ServiceAddressHouseNumber = "14",
                ServiceAddressFraction = "14",
                ServiceAddressApartment = "16-18",
                ServiceAddressStreet = "S Haddon Ave",
                ServiceCity = "Haddonfield",
                ServiceState = "NJ",
                ServiceZip = "08033-1860",
                ServiceDistrict = "15",
                ServiceDistrictDescription = "Burlington/Camden(Haddon)",
                AreaCode = "1816",
                AreaCodeDescription = "Haddonfield (Haddon)",
                RegionCode = "0417",
                RegionCodeDescription = "Haddonfield",
                StatusCode = "Active"
            },
            new SapPremiseFileRecord {
                PremiseNumber = "8000002540",
                ConnectionObject = "4000010639",
                ServiceAddressHouseNumber = "114",
                ServiceAddressFraction = "114",
                ServiceAddressApartment = "116",
                ServiceAddressStreet = "Kings Hwy E",
                ServiceCity = "Haddonfield",
                ServiceState = "NJ",
                ServiceZip = "08033-2004",
                ServiceDistrict = "15",
                ServiceDistrictDescription = "Burlington/Camden(Haddon)",
                AreaCode = "1816",
                AreaCodeDescription = "Haddonfield (Haddon)",
                RegionCode = "0417",
                RegionCodeDescription = "Haddonfield",
                StatusCode = "Active"
            },
            new SapPremiseFileRecord {
                PremiseNumber = "8000003520",
                ConnectionObject = "4000011589",
                ServiceAddressHouseNumber = "309",
                ServiceAddressFraction = "309",
                ServiceAddressApartment = "311",
                ServiceAddressStreet = "Warwick Rd",
                ServiceCity = "Haddonfield",
                ServiceState = "NJ",
                ServiceZip = "08033-3827",
                ServiceDistrict = "15",
                ServiceDistrictDescription = "Burlington/Camden(Haddon)",
                AreaCode = "1816",
                AreaCodeDescription = "Haddonfield (Haddon)",
                RegionCode = "0417",
                RegionCodeDescription = "Haddonfield",
                StatusCode = "Active"
            },
            new SapPremiseFileRecord {
                PremiseNumber = "8000002581",
                ConnectionObject = "4000010726",
                ServiceAddressHouseNumber = "25",
                ServiceAddressFraction = "25",
                ServiceAddressApartment = "27",
                ServiceAddressStreet = "Chestnut St",
                ServiceCity = "Haddonfield",
                ServiceState = "NJ",
                ServiceZip = "08033-1875",
                ServiceDistrict = "15",
                ServiceDistrictDescription = "Burlington/Camden(Haddon)",
                AreaCode = "1816",
                AreaCodeDescription = "Haddonfield (Haddon)",
                RegionCode = "0417",
                RegionCodeDescription = "Haddonfield",
                StatusCode = "Active"
            },
            new SapPremiseFileRecord {
                PremiseNumber = "8000002584",
                ConnectionObject = "4000010732",
                ServiceAddressHouseNumber = "134",
                ServiceAddressFraction = "134",
                ServiceAddressApartment = "138",
                ServiceAddressStreet = "Kings Hwy E",
                ServiceCity = "Haddonfield",
                ServiceState = "NJ",
                ServiceZip = "08033-2093",
                ServiceDistrict = "15",
                ServiceDistrictDescription = "Burlington/Camden(Haddon)",
                AreaCode = "1816",
                AreaCodeDescription = "Haddonfield (Haddon)",
                RegionCode = "0417",
                RegionCodeDescription = "Haddonfield",
                StatusCode = "Active"
            },
            new SapPremiseFileRecord {
                PremiseNumber = "8000002586",
                ConnectionObject = "4000010736",
                ServiceAddressHouseNumber = "142",
                ServiceAddressFraction = "142",
                ServiceAddressApartment = "144",
                ServiceAddressStreet = "Kings Hwy E",
                ServiceCity = "Haddonfield",
                ServiceState = "NJ",
                ServiceZip = "08033-2004",
                ServiceDistrict = "15",
                ServiceDistrictDescription = "Burlington/Camden(Haddon)",
                AreaCode = "1816",
                AreaCodeDescription = "Haddonfield (Haddon)",
                RegionCode = "0417",
                RegionCodeDescription = "Haddonfield",
                StatusCode = "Active"
            },
            new SapPremiseFileRecord {
                PremiseNumber = "8000002591",
                ConnectionObject = "4000010750",
                ServiceAddressHouseNumber = "6",
                ServiceAddressFraction = "6",
                ServiceAddressApartment = "8",
                ServiceAddressStreet = "Kings Hwy E",
                ServiceCity = "Haddonfield",
                ServiceState = "NJ",
                ServiceZip = "08033-2000",
                ServiceDistrict = "15",
                ServiceDistrictDescription = "Burlington/Camden(Haddon)",
                AreaCode = "1816",
                AreaCodeDescription = "Haddonfield (Haddon)",
                RegionCode = "0417",
                RegionCodeDescription = "Haddonfield",
                StatusCode = "Active"
            },
            new SapPremiseFileRecord {
                PremiseNumber = "8000002592",
                ConnectionObject = "4000010752",
                ServiceAddressHouseNumber = "6",
                ServiceAddressFraction = "6",
                ServiceAddressApartment = "8",
                ServiceAddressStreet = "Kings Hwy E",
                ServiceCity = "Haddonfield",
                ServiceState = "NJ",
                ServiceZip = "08033-2000",
                ServiceDistrict = "15",
                ServiceDistrictDescription = "Burlington/Camden(Haddon)",
                AreaCode = "1816",
                AreaCodeDescription = "Haddonfield (Haddon)",
                RegionCode = "0417",
                RegionCodeDescription = "Haddonfield",
                StatusCode = "Active"
            },
            new SapPremiseFileRecord {
                PremiseNumber = "8000002593",
                ConnectionObject = "4000010754",
                ServiceAddressHouseNumber = "6",
                ServiceAddressFraction = "6",
                ServiceAddressApartment = "8",
                ServiceAddressStreet = "Kings Hwy E",
                ServiceCity = "Haddonfield",
                ServiceState = "NJ",
                ServiceZip = "08033-2000",
                ServiceDistrict = "15",
                ServiceDistrictDescription = "Burlington/Camden(Haddon)",
                AreaCode = "1816",
                AreaCodeDescription = "Haddonfield (Haddon)",
                RegionCode = "0417",
                RegionCodeDescription = "Haddonfield",
                StatusCode = "Active"
            },
            new SapPremiseFileRecord {
                PremiseNumber = "8000002715",
                ConnectionObject = "4000010787",
                ServiceAddressHouseNumber = "349",
                ServiceAddressFraction = "349",
                ServiceAddressApartment = "351",
                ServiceAddressStreet = "Lincoln Ave",
                ServiceCity = "Haddonfield",
                ServiceState = "NJ",
                ServiceZip = "08033-1634",
                ServiceDistrict = "15",
                ServiceDistrictDescription = "Burlington/Camden(Haddon)",
                AreaCode = "1816",
                AreaCodeDescription = "Haddonfield (Haddon)",
                RegionCode = "0417",
                RegionCodeDescription = "Haddonfield",
                StatusCode = "Active"
            },
            new SapPremiseFileRecord {
                PremiseNumber = "5000006006",
                ConnectionObject = "4000000018",
                ServiceAddressApartment = "7 \" F",
                ServiceCity = "Dlpra Water O&M",
                ServiceDistrict = "15",
                ServiceDistrictDescription = "DLPRA Water O&M",
                AreaCode = "0990",
                AreaCodeDescription = "DLPRA Water O&M",
                RegionCode = "0707",
                RegionCodeDescription = "Dlpra Water O&M",
                StatusCode = "Active"
            },
            new SapPremiseFileRecord {
                PremiseNumber = "8000004878",
                ConnectionObject = "4000012918",
                ServiceAddressHouseNumber = "35",
                ServiceAddressFraction = "35",
                ServiceAddressApartment = "41",
                ServiceAddressStreet = "Kings Hwy E",
                ServiceCity = "Haddonfield",
                ServiceState = "NJ",
                ServiceZip = "08033-2009",
                ServiceDistrict = "15",
                ServiceDistrictDescription = "Burlington/Camden(Haddon)",
                AreaCode = "1816",
                AreaCodeDescription = "Haddonfield (Haddon)",
                RegionCode = "0417",
                RegionCodeDescription = "Haddonfield",
                StatusCode = "Active"
            },
            new SapPremiseFileRecord {
                PremiseNumber = "8000004882",
                ConnectionObject = "4000012926",
                ServiceAddressHouseNumber = "27",
                ServiceAddressFraction = "27",
                ServiceAddressApartment = "29",
                ServiceAddressStreet = "Kings Hwy E",
                ServiceCity = "Haddonfield",
                ServiceState = "NJ",
                ServiceZip = "08033-2001",
                ServiceDistrict = "15",
                ServiceDistrictDescription = "Burlington/Camden(Haddon)",
                AreaCode = "1816",
                AreaCodeDescription = "Haddonfield (Haddon)",
                RegionCode = "0417",
                RegionCodeDescription = "Haddonfield",
                StatusCode = "Active"
            },
            new SapPremiseFileRecord {
                PremiseNumber = "8000004886",
                ConnectionObject = "4000012934",
                ServiceAddressHouseNumber = "9",
                ServiceAddressFraction = "9",
                ServiceAddressApartment = "11",
                ServiceAddressStreet = "Kings Hwy E",
                ServiceCity = "Haddonfield",
                ServiceState = "NJ",
                ServiceZip = "08033-2005",
                ServiceDistrict = "15",
                ServiceDistrictDescription = "Burlington/Camden(Haddon)",
                AreaCode = "1816",
                AreaCodeDescription = "Haddonfield (Haddon)",
                RegionCode = "0417",
                RegionCodeDescription = "Haddonfield",
                StatusCode = "Active"
            },
            new SapPremiseFileRecord {
                PremiseNumber = "8000004887",
                ConnectionObject = "4000012936",
                ServiceAddressHouseNumber = "9",
                ServiceAddressFraction = "9",
                ServiceAddressApartment = "11",
                ServiceAddressStreet = "Kings Hwy E",
                ServiceCity = "Haddonfield",
                ServiceState = "NJ",
                ServiceZip = "08033-2005",
                ServiceDistrict = "15",
                ServiceDistrictDescription = "Burlington/Camden(Haddon)",
                AreaCode = "1816",
                AreaCodeDescription = "Haddonfield (Haddon)",
                RegionCode = "0417",
                RegionCodeDescription = "Haddonfield",
                StatusCode = "Active"
            },
            new SapPremiseFileRecord {
                PremiseNumber = "8000004888",
                ConnectionObject = "4000012938",
                ServiceAddressHouseNumber = "9",
                ServiceAddressFraction = "9",
                ServiceAddressApartment = "11",
                ServiceAddressStreet = "Kings Hwy E",
                ServiceCity = "Haddonfield",
                ServiceState = "NJ",
                ServiceZip = "08033-2005",
                ServiceDistrict = "15",
                ServiceDistrictDescription = "Burlington/Camden(Haddon)",
                AreaCode = "1816",
                AreaCodeDescription = "Haddonfield (Haddon)",
                RegionCode = "0417",
                RegionCodeDescription = "Haddonfield",
                StatusCode = "Active"
            },
            new SapPremiseFileRecord {
                PremiseNumber = "8000004889",
                ConnectionObject = "4000012940",
                ServiceAddressHouseNumber = "9",
                ServiceAddressFraction = "9",
                ServiceAddressApartment = "11",
                ServiceAddressStreet = "Kings Hwy E",
                ServiceCity = "Haddonfield",
                ServiceState = "NJ",
                ServiceZip = "08033-2005",
                ServiceDistrict = "15",
                ServiceDistrictDescription = "Burlington/Camden(Haddon)",
                AreaCode = "1816",
                AreaCodeDescription = "Haddonfield (Haddon)",
                RegionCode = "0417",
                RegionCodeDescription = "Haddonfield",
                StatusCode = "Active"
            },
            new SapPremiseFileRecord {
                PremiseNumber = "8000004829",
                ConnectionObject = "4000013018",
                ServiceAddressHouseNumber = "70",
                ServiceAddressFraction = "70",
                ServiceAddressApartment = "72",
                ServiceAddressStreet = "Tanner St",
                ServiceCity = "Haddonfield",
                ServiceState = "NJ",
                ServiceZip = "08033-2419",
                ServiceDistrict = "15",
                ServiceDistrictDescription = "Burlington/Camden(Haddon)",
                AreaCode = "1816",
                AreaCodeDescription = "Haddonfield (Haddon)",
                RegionCode = "0417",
                RegionCodeDescription = "Haddonfield",
                StatusCode = "Active"
            },
            new SapPremiseFileRecord {
                PremiseNumber = "8000004830",
                ConnectionObject = "4000013020",
                ServiceAddressHouseNumber = "48",
                ServiceAddressFraction = "48",
                ServiceAddressApartment = "62",
                ServiceAddressStreet = "Tanner St",
                ServiceCity = "Haddonfield",
                ServiceState = "NJ",
                ServiceZip = "08033-2420",
                ServiceDistrict = "15",
                ServiceDistrictDescription = "Burlington/Camden(Haddon)",
                AreaCode = "1816",
                AreaCodeDescription = "Haddonfield (Haddon)",
                RegionCode = "0417",
                RegionCodeDescription = "Haddonfield",
                StatusCode = "Active"
            }
        };

        #endregion

        #region Private Methods

        protected override void CompareResult(SapPremiseFileRecord sampleRecord, SapPremiseFileRecord resultRecord)
        {
            MyAssert.AreEqual(sampleRecord, resultRecord, x => x.OperatingCentre);
            MyAssert.AreEqual(sampleRecord, resultRecord, x => x.PremiseNumber);
            MyAssert.AreEqual(sampleRecord, resultRecord, x => x.ConnectionObject);
            MyAssert.AreEqual(sampleRecord, resultRecord, x => x.DeviceLocation);
            MyAssert.AreEqual(sampleRecord, resultRecord, x => x.DeviceCategory);
            MyAssert.AreEqual(sampleRecord, resultRecord, x => x.Equipment);
            MyAssert.AreEqual(sampleRecord, resultRecord, x => x.NextMeterReadingdate);
            MyAssert.AreEqual(sampleRecord, resultRecord, x => x.DeviceSerialNumber);
            MyAssert.AreEqual(sampleRecord, resultRecord, x => x.Latitude);
            MyAssert.AreEqual(sampleRecord, resultRecord, x => x.Longitude);
            MyAssert.AreEqual(sampleRecord, resultRecord, x => x.ServiceAddressHouseNumber);
            MyAssert.AreEqual(sampleRecord, resultRecord, x => x.ServiceAddressFraction);
            MyAssert.AreEqual(sampleRecord, resultRecord, x => x.ServiceAddressApartment);
            MyAssert.AreEqual(sampleRecord, resultRecord, x => x.ServiceAddressStreet);
            MyAssert.AreEqual(sampleRecord, resultRecord, x => x.ServiceCity);
            MyAssert.AreEqual(sampleRecord, resultRecord, x => x.ServiceState);
            MyAssert.AreEqual(sampleRecord, resultRecord, x => x.ServiceZip);
            MyAssert.AreEqual(sampleRecord, resultRecord, x => x.ServiceDistrict);
            MyAssert.AreEqual(sampleRecord, resultRecord, x => x.ServiceDistrictDescription);
            MyAssert.AreEqual(sampleRecord, resultRecord, x => x.AreaCode);
            MyAssert.AreEqual(sampleRecord, resultRecord, x => x.AreaCodeDescription);
            MyAssert.AreEqual(sampleRecord, resultRecord, x => x.RegionCode);
            MyAssert.AreEqual(sampleRecord, resultRecord, x => x.RegionCodeDescription);
            MyAssert.AreEqual(sampleRecord, resultRecord, x => x.RouteNumber);
            MyAssert.AreEqual(sampleRecord, resultRecord, x => x.RouteNumberDescription);
            MyAssert.AreEqual(sampleRecord, resultRecord, x => x.StatusCode);
            MyAssert.AreEqual(sampleRecord, resultRecord, x => x.ServiceUtilityType);
            MyAssert.AreEqual(sampleRecord, resultRecord, x => x.MeterSize);
            MyAssert.AreEqual(sampleRecord, resultRecord, x => x.MeterLocation);
            MyAssert.AreEqual(sampleRecord, resultRecord, x => x.MeterLocationFreeText);
            MyAssert.AreEqual(sampleRecord, resultRecord, x => x.Installation);
            MyAssert.AreEqual(sampleRecord, resultRecord, x => x.MeterSerialNumber);
            MyAssert.AreEqual(sampleRecord, resultRecord, x => x.IsMajorAccount);
            MyAssert.AreEqual(sampleRecord, resultRecord, x => x.MajorAccountManager);
            MyAssert.AreEqual(sampleRecord, resultRecord, x => x.AccountManagerContactNumber);
            MyAssert.AreEqual(sampleRecord, resultRecord, x => x.AccountManagerEmail);
        }

        #endregion
    }
}
