using FluentMigrator;
using MMSINC.ClassExtensions.FluentMigratorExtensions;

namespace MapCall.Common.Model.Migrations._2023
{
    [Migration(20230822161241437), Tags("Production")]
    public class MC5333ChangeNotificationCompletedByFromStringToInt : Migration
    {
        public struct Tables
        {
            public const string WATER_QUALITY_COMPLAINTS = "WaterQualityComplaints",
                                EMPLOYEE = "tblEmployee";
        }

        public struct Columns
        {
            public const string NOTIFICATION_COMPLETED_BY_EMPLOYEE_ID = "NotificationCompletedById",
                                EMPLOYEE_ID = "tblEmployeeId";
        }
        
        private readonly string SET_EMPLOYEE_ID = @"
Select tblEmployeeID,EmployeeID Into #tmpEmployees From tblEmployee Where EmployeeID is not null;

Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60002546') Where NotificationCompletedBy = 'Aaron Campbell';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '50293057') Where NotificationCompletedBy = 'sleepeaw';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60001520') Where NotificationCompletedBy = 'Quinn Baughmiller FSR';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60001520') Where NotificationCompletedBy = 'Quinn Baughmiller FSR, Alex Indrutz WQ';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60001520') Where NotificationCompletedBy = 'Alex Indrutz WQ';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60001520') Where NotificationCompletedBy = 'Alex WQ';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60001520') Where NotificationCompletedBy = 'WQ Alex';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60001817') Where NotificationCompletedBy = 'ZSOMBOA';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60005689') Where NotificationCompletedBy = 'A. Felsburg';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60005689') Where NotificationCompletedBy = 'A.Felsburg';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60005689') Where NotificationCompletedBy = 'Allyson Felsburg';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60001578') Where NotificationCompletedBy = 'Amanda Cyprich';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '50589600') Where NotificationCompletedBy = 'amanpreettiwana';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '50589600') Where NotificationCompletedBy = 'tiwanaa';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '90004737') Where NotificationCompletedBy = 'A. Court';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '50305241') Where NotificationCompletedBy = 'A Castro';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '50305241') Where NotificationCompletedBy = 'A Csatro';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '50305241') Where NotificationCompletedBy = 'A Cstro';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '50305241') Where NotificationCompletedBy = 'A. Castro';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '50305241') Where NotificationCompletedBy = 'A.Castro';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '50305241') Where NotificationCompletedBy = 'AC';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '50305241') Where NotificationCompletedBy = 'ACastro';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '50305241') Where NotificationCompletedBy = 'Castro, Andrea - 50305241 - EW2';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '50305241') Where NotificationCompletedBy = 'Castro, Andrea : 50305241';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '50305241') Where NotificationCompletedBy = 'castroa';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '50589596') Where NotificationCompletedBy = 'AM';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '50589596') Where NotificationCompletedBy = 'anthonymarcucci';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '50589596') Where NotificationCompletedBy = 'martuccia';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60000890') Where NotificationCompletedBy = 'A. Johnse';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60000890') Where NotificationCompletedBy = 'A.Johnse';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60001339') Where NotificationCompletedBy = 'AA';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60001339') Where NotificationCompletedBy = 'Ayite Amegniki';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60001339') Where NotificationCompletedBy = 'AA';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60001339') Where NotificationCompletedBy = 'Ayite Amegniki';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '50230637') Where NotificationCompletedBy = 'Coma';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '51025428') Where NotificationCompletedBy = 'BALLE';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60002004') Where NotificationCompletedBy = 'Brandy Brau';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60002004') Where NotificationCompletedBy = 'Brandy Braun and Bill Blosser';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60002004') Where NotificationCompletedBy = 'Brandy Braun/ Jesse Edwards';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60002004') Where NotificationCompletedBy = 'Brandy M Brau';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60003053') Where NotificationCompletedBy = 'FSR Brennan Storie';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60005670') Where NotificationCompletedBy = 'B.Brandes';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60005670') Where NotificationCompletedBy = 'Brett Brandes';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60002619') Where NotificationCompletedBy = 'Brooke Strong';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60006494') Where NotificationCompletedBy = 'B. Hooks';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60006494') Where NotificationCompletedBy = 'Bryan Hooks';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '110060326') Where NotificationCompletedBy = 'Camryn Keeno';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '50467761') Where NotificationCompletedBy = 'Carada Springstead';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '50142382') Where NotificationCompletedBy = 'Carl Phillips';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60001324') Where NotificationCompletedBy = 'cartermarquette';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60000357') Where NotificationCompletedBy = 'C. Alle';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60003703') Where NotificationCompletedBy = 'C Hall';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60003703') Where NotificationCompletedBy = 'C. Hall';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60003703') Where NotificationCompletedBy = 'Chad Hall';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '24006906') Where NotificationCompletedBy = 'C Motley';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '24006906') Where NotificationCompletedBy = 'C. Motley (per notes by C. Springstead/M. Goldie)';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '24006906') Where NotificationCompletedBy = 'S. Bukowski (C. Motley per notes)';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '50268663') Where NotificationCompletedBy = 'C . Wait';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '50268663') Where NotificationCompletedBy = 'C .wait';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '50268663') Where NotificationCompletedBy = 'C wait';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '50268663') Where NotificationCompletedBy = 'C,wait';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '50268663') Where NotificationCompletedBy = 'C. Wait';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '50268663') Where NotificationCompletedBy = 'C.wait';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '50268663') Where NotificationCompletedBy = 'Chris wait';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '50268663') Where NotificationCompletedBy = 'Cwait';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '50268663') Where NotificationCompletedBy = 'Wait';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '50268663') Where NotificationCompletedBy = 'Wait.';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '24007042') Where NotificationCompletedBy = 'C Sledgeski';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '24007042') Where NotificationCompletedBy = 'Christine Sledgeski';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '50655787') Where NotificationCompletedBy = 'Christine Stanishefski';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60006970') Where NotificationCompletedBy = 'CT';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '50434598') Where NotificationCompletedBy = 'C Olenczuk';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '50434598') Where NotificationCompletedBy = 'Chris Olenczuk';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '50434598') Where NotificationCompletedBy = 'Colenczuc';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '50434598') Where NotificationCompletedBy = 'olenczuc';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '50434598') Where NotificationCompletedBy = 'olenczuckc';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '50434598') Where NotificationCompletedBy = 'Olenczuk';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '50434598') Where NotificationCompletedBy = 'Olenczuk, Christopher M - 50434598 - NJ7';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60005302') Where NotificationCompletedBy = 'Chris Bellini';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60005302') Where NotificationCompletedBy = 'Chris Bellini / Leah Shopene';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60005707') Where NotificationCompletedBy = 'Chris Chick';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60000612') Where NotificationCompletedBy = 'Chris Tucker';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60005707') Where NotificationCompletedBy = 'Christopher Chick';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60000612') Where NotificationCompletedBy = 'Christopher Tucker';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60007267') Where NotificationCompletedBy = 'CAM';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60007267') Where NotificationCompletedBy = 'Clayton M';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60001050') Where NotificationCompletedBy = 'Cody Cutler';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '50079270') Where NotificationCompletedBy = 'Corey Robinso';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '600002016') Where NotificationCompletedBy = 'Craig Symons/Zack Frisko';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60001556') Where NotificationCompletedBy = 'Curtis Wheaat';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60001564') Where NotificationCompletedBy = 'Cyril Weakland';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '24017216') Where NotificationCompletedBy = 'Dale E Warner';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '24017216') Where NotificationCompletedBy = 'Dale Warer';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '24017216') Where NotificationCompletedBy = 'Dale Warner';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '24017216') Where NotificationCompletedBy = 'Warner, Dale';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '10000098') Where NotificationCompletedBy = 'Dan A';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '50179981') Where NotificationCompletedBy = 'Danielle VanSant';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '50179981') Where NotificationCompletedBy = 'daniellevansant';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '51022188') Where NotificationCompletedBy = 'Darla P.';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '24008381') Where NotificationCompletedBy = 'Daryl Conner';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '51037618') Where NotificationCompletedBy = 'ROWLANJR';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '51014650') Where NotificationCompletedBy = 'SantardJ';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '90000640') Where NotificationCompletedBy = 'David Nat';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60006143') Where NotificationCompletedBy = 'David Marfell';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60006041') Where NotificationCompletedBy = 'David See';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '24014534') Where NotificationCompletedBy = 'Dave Rowland';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '50580954') Where NotificationCompletedBy = 'Dawn Beck, Brennan Storie FSR, Alex Indrutz WQ';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '50305059') Where NotificationCompletedBy = 'DD';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '50305059') Where NotificationCompletedBy = 'debderwid';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '50305059') Where NotificationCompletedBy = 'Deborah Derwid';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '50305059') Where NotificationCompletedBy = 'DSD';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '50305059') Where NotificationCompletedBy = 'DSD for AC';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '50305059') Where NotificationCompletedBy = 'DSD for SB';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60006963') Where NotificationCompletedBy = 'Dennis Maso';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '50382125') Where NotificationCompletedBy = 'dionnapisel';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60005716') Where NotificationCompletedBy = 'BRENNAD';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '51025376') Where NotificationCompletedBy = 'Duane C.';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60006116') Where NotificationCompletedBy = 'Dyllon Dunca';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60001212') Where NotificationCompletedBy = 'HALLEP';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60001212') Where NotificationCompletedBy = 'E Hall';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60001212') Where NotificationCompletedBy = 'Eamon Hall';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '50297741') Where NotificationCompletedBy = 'E. Doellma';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '50297741') Where NotificationCompletedBy = 'E.Doellma';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '50297741') Where NotificationCompletedBy = 'Elizabeth Doellma';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '24006983') Where NotificationCompletedBy = 'Emery Yurko';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '24006983') Where NotificationCompletedBy = 'Emery Yurko  (See notes)';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60007078') Where NotificationCompletedBy = 'E PIrl';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60000611') Where NotificationCompletedBy = 'E. LeReau';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '3000129') Where NotificationCompletedBy = 'abramsf';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '18506798') Where NotificationCompletedBy = 'Frank Hadley';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '50562539') Where NotificationCompletedBy = 'Greer';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '50562539') Where NotificationCompletedBy = 'Greer Thacker';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '50562539') Where NotificationCompletedBy = 'Greer Thacket';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '50562539') Where NotificationCompletedBy = 'GT';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60001959') Where NotificationCompletedBy = 'HIL';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60001959') Where NotificationCompletedBy = 'HL';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60001959') Where NotificationCompletedBy = 'Hannah I Lewis';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60001959') Where NotificationCompletedBy = 'Hannah Irene Lewis';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60001959') Where NotificationCompletedBy = 'Hannah Korte-Runge';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60001959') Where NotificationCompletedBy = 'Hannah Lewis';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60007727') Where NotificationCompletedBy = 'Heather Weekley';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60000734') Where NotificationCompletedBy = 'Ian Rischmiller';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60001239') Where NotificationCompletedBy = 'Iali Hanso';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60001239') Where NotificationCompletedBy = 'Ida';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60001239') Where NotificationCompletedBy = 'Idali';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60001239') Where NotificationCompletedBy = 'Idali Hanos';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60001239') Where NotificationCompletedBy = 'Idali Hansom';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60001239') Where NotificationCompletedBy = 'Idali Hanso';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60001239') Where NotificationCompletedBy = 'Idali M. Hanso';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60001239') Where NotificationCompletedBy = 'Idali Rios';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60001239') Where NotificationCompletedBy = 'Idali Rios-Hanso';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60001239') Where NotificationCompletedBy = 'Idlai';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60001239') Where NotificationCompletedBy = 'Idlali';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60001239') Where NotificationCompletedBy = 'IRios';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '18695939') Where NotificationCompletedBy = 'I. Patel';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '18695939') Where NotificationCompletedBy = 'I.Patel';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '18695939') Where NotificationCompletedBy = 'iaptel';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '18695939') Where NotificationCompletedBy = 'Ila Patel';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '18695939') Where NotificationCompletedBy = 'ilapatel';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '18695939') Where NotificationCompletedBy = 'IP';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '18695939') Where NotificationCompletedBy = 'ipatel';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '18695939') Where NotificationCompletedBy = 'Patel';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '18695939') Where NotificationCompletedBy = 'pateli';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '90004252') Where NotificationCompletedBy = 'Ivan Sinkevich';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60005587') Where NotificationCompletedBy = 'Jack Beal';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '50646385') Where NotificationCompletedBy = 'jameswalker';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '50646385') Where NotificationCompletedBy = 'JW';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60003707') Where NotificationCompletedBy = 'ARMILLJJ';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '50280471') Where NotificationCompletedBy = 'SHORTJE';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '50202917') Where NotificationCompletedBy = 'Jamie Gough';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '13000388') Where NotificationCompletedBy = 'Jason Brow';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '50419093') Where NotificationCompletedBy = 'Jeff Stout';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '50315444') Where NotificationCompletedBy = 'Jeremy Waite FSR';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '50197804') Where NotificationCompletedBy = 'Jeremy Resseguie';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60000584') Where NotificationCompletedBy = 'Jeremy Rice';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '24006991') Where NotificationCompletedBy = 'Jesse Edwards';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '50589601') Where NotificationCompletedBy = 'johneppensteiner';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '50397065') Where NotificationCompletedBy = 'John Walker';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60000387') Where NotificationCompletedBy = 'John Rowlands';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60001491') Where NotificationCompletedBy = 'FSR John McConnell';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60001491') Where NotificationCompletedBy = 'John M. FSR';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60001491') Where NotificationCompletedBy = 'John McConnell FSR';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '50448520') Where NotificationCompletedBy = 'jordanspitzerlondo';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60003540') Where NotificationCompletedBy = 'JV';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '50577616') Where NotificationCompletedBy = 'joecorbett';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '18507053') Where NotificationCompletedBy = 'J. Habrack';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '18507053') Where NotificationCompletedBy = 'jhabrack';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '50004785') Where NotificationCompletedBy = 'Kalen O''Bria';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60002396') Where NotificationCompletedBy = 'K. Mesch';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '50568214') Where NotificationCompletedBy = 'Kelly Ply';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60003238') Where NotificationCompletedBy = 'Kelly Hays';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '50433340') Where NotificationCompletedBy = 'kelly rya';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '9009339') Where NotificationCompletedBy = 'Kenda Kitner';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '18508574') Where NotificationCompletedBy = 'Habrack';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '18505541') Where NotificationCompletedBy = 'kevinkirwa';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60001188') Where NotificationCompletedBy = 'Kevin Nylander';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '26000109') Where NotificationCompletedBy = 'KP';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '50645476') Where NotificationCompletedBy = 'K. West';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60002710') Where NotificationCompletedBy = 'Kim Carr';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60002710') Where NotificationCompletedBy = 'Kimberly Carr';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60002710') Where NotificationCompletedBy = 'Kimberly Carr  SHORTJE';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '26000109') Where NotificationCompletedBy = 'KP';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '50475657') Where NotificationCompletedBy = 'Kirk Kurowia WQ';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '24007315') Where NotificationCompletedBy = 'K. Snyder';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '24007315') Where NotificationCompletedBy = 'Kristen Snyder';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60005598') Where NotificationCompletedBy = 'Kyle Smith';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60005938') Where NotificationCompletedBy = 'Larry Ford';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '18507660') Where NotificationCompletedBy = 'lauravancho';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '50452285') Where NotificationCompletedBy = 'Laura Marcasciano';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60000424') Where NotificationCompletedBy = 'Laura Walter';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '50416809') Where NotificationCompletedBy = 'Lauren Bertonazzi';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '50416809') Where NotificationCompletedBy = 'laurenbertonazzi';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60006144') Where NotificationCompletedBy = 'Lauren Hamby';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60007483') Where NotificationCompletedBy = 'Leah Shopene';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60007483') Where NotificationCompletedBy = 'Leah Shopene & Brian Buttacavoli';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60007483') Where NotificationCompletedBy = 'Leah Shopene & Justin Nash';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60007483') Where NotificationCompletedBy = 'Leah Shopene and Ryan Hardgrove';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60000728') Where NotificationCompletedBy = 'Linda Fry';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60005668') Where NotificationCompletedBy = 'L. Schopper';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60005668') Where NotificationCompletedBy = 'L. Schopper - Following up with Cust Serv & Reg'
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60005668') Where NotificationCompletedBy = 'L. Schopper / Engineering follow-up'
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60005668') Where NotificationCompletedBy = 'L. Schopper / Follow-Up with Engineering'
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60005668') Where NotificationCompletedBy = 'L. Schopper / FSR'
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60005668') Where NotificationCompletedBy = 'L. Schopper / FSR Follow-up'
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60005668') Where NotificationCompletedBy = 'L. Schopper / FSR Visit to Premise'
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60005668') Where NotificationCompletedBy = 'L. Schopper/ Follow-up with Engineering Contractor'
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60005668') Where NotificationCompletedBy = 'L. Schoppper';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60005668') Where NotificationCompletedBy = 'Lisa Schopper';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '50198967') Where NotificationCompletedBy = 'Lisa Adams';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '17002945') Where NotificationCompletedBy = 'Henderso';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '17002945') Where NotificationCompletedBy = 'Henderson Lonnie';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '17002945') Where NotificationCompletedBy = 'L. Henderso';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '17002945') Where NotificationCompletedBy = 'LHenderso';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '17002945') Where NotificationCompletedBy = 'Lonnie Henderso';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '17002945') Where NotificationCompletedBy = 'PLonnie Henderso';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '50518185') Where NotificationCompletedBy = 'L. Graziano';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '50518185') Where NotificationCompletedBy = 'L. Graziano for C. Wait';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '50518185') Where NotificationCompletedBy = 'L. Graziano for L. Henderso';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '50518185') Where NotificationCompletedBy = 'L. Graziano for L. Hudso';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '50318684') Where NotificationCompletedBy = 'Hudso';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '50318684') Where NotificationCompletedBy = 'Hudsonla';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '50318684') Where NotificationCompletedBy = 'L. Hudso';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '50318684') Where NotificationCompletedBy = 'LHUDSO';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '50345385') Where NotificationCompletedBy = 'Marevic N. Clark';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '50305286') Where NotificationCompletedBy = 'MW';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '50305286') Where NotificationCompletedBy = 'wiggank';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60006254') Where NotificationCompletedBy = 'M. Davis';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60006254') Where NotificationCompletedBy = 'M.Davis';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60006254') Where NotificationCompletedBy = 'Markesha Davis';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '9008883') Where NotificationCompletedBy = 'M Robiso';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '9008883') Where NotificationCompletedBy = 'M. Robiso';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '9008883') Where NotificationCompletedBy = 'M. Robison on behalf of C. Wait';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '9008883') Where NotificationCompletedBy = 'M. Robison on behalf of L. Graziano';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '9008883') Where NotificationCompletedBy = 'M. Robison on behalf of L. Henderso';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '9008883') Where NotificationCompletedBy = 'M. Robison on behalf of L. Hudso';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '9008883') Where NotificationCompletedBy = 'M. Robison on behalf of S. Lane';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '9008883') Where NotificationCompletedBy = 'M. Robsio';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '9008883') Where NotificationCompletedBy = 'M. Robson on behalf of L. Graziano';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '9008883') Where NotificationCompletedBy = 'M.Robiso';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '9008883') Where NotificationCompletedBy = 'Martin Robiso';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '9008883') Where NotificationCompletedBy = 'MLR';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60002718') Where NotificationCompletedBy = 'M. Goldie';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60002718') Where NotificationCompletedBy = 'Mary Ann Goldie';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60002718') Where NotificationCompletedBy = 'MaryAnn Goldie / Brandy Brau';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60002718') Where NotificationCompletedBy = 'MaryAnne Goldie';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60002718') Where NotificationCompletedBy = 'MG';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60001414') Where NotificationCompletedBy = 'M Bellifemine';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60005051') Where NotificationCompletedBy = 'M. Lester';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60006685') Where NotificationCompletedBy = 'Matt Woomer (FSR), Alex Indrutz (WQ)';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60006685') Where NotificationCompletedBy = 'Matt Woomer FSR, Alex Indrutz WQ';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '27002209') Where NotificationCompletedBy = 'Matt Norris';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '27002209') Where NotificationCompletedBy = 'm';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60003625') Where NotificationCompletedBy = 'MC';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60003625') Where NotificationCompletedBy = 'Megan Cordero';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60003625') Where NotificationCompletedBy = 'NC';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '50447655') Where NotificationCompletedBy = 'melissasmall';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60003705') Where NotificationCompletedBy = 'Kelly';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60000658') Where NotificationCompletedBy = 'Michael Turano';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60003705') Where NotificationCompletedBy = 'mkelly';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '50425858') Where NotificationCompletedBy = 'M. Hopkins FSR';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '24017098') Where NotificationCompletedBy = 'Bauer, Michael : 24017098';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60006360') Where NotificationCompletedBy = 'Michelle Mancuso';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60006738') Where NotificationCompletedBy = 'Morgan Adams';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '50602288') Where NotificationCompletedBy = 'JD';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '50602288') Where NotificationCompletedBy = 'NJ';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '50214856') Where NotificationCompletedBy = 'Nathan Mitchell';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '10009003') Where NotificationCompletedBy = 'Nate Carr FSR';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60006704') Where NotificationCompletedBy = 'Nick Koschak';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '90001199') Where NotificationCompletedBy = 'N. Provost';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60000640') Where NotificationCompletedBy = 'P Godes';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60000640') Where NotificationCompletedBy = 'P Goede';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60000640') Where NotificationCompletedBy = 'P Ingersoll Goede';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60000640') Where NotificationCompletedBy = 'P Ingersoll-Goede';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60000640') Where NotificationCompletedBy = 'P. Ingersoll Goede';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60000640') Where NotificationCompletedBy = 'Pam Goede';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60000640') Where NotificationCompletedBy = 'Pam Ingersoll Goede';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60000640') Where NotificationCompletedBy = 'Pam Ingersoll-Goede';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60000640') Where NotificationCompletedBy = 'Pamela Ingersoll-Goede';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '17008726') Where NotificationCompletedBy = 'P. Radford';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60006290') Where NotificationCompletedBy = 'P. Zolpher';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '3018540') Where NotificationCompletedBy = 'Rachel Bretz';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '50524827') Where NotificationCompletedBy = 'Rich Stonebarger';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '24020763') Where NotificationCompletedBy = 'R. Gunderso';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60005626') Where NotificationCompletedBy = 'Rudy Menhart';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60005626') Where NotificationCompletedBy = 'Rudy Menhart and Kelly Hays';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60002666') Where NotificationCompletedBy = 'Ryan Renner';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '50180151') Where NotificationCompletedBy = 'Ryan Smith';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60002374') Where NotificationCompletedBy = 'Ryan Hardgrov';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60002374') Where NotificationCompletedBy = 'Ryan Hardgrove';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60002875') Where NotificationCompletedBy = 'Sam Saucier';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60006695') Where NotificationCompletedBy = 'Sarah Vang';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60002904') Where NotificationCompletedBy = 'Sarah Parker';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '18503933') Where NotificationCompletedBy = 'baxter';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '18503933') Where NotificationCompletedBy = 'Scott Baxter Gree';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '50216991') Where NotificationCompletedBy = 'Scott Brezinski';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '50216991') Where NotificationCompletedBy = 'Scott H. Brezinski';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '18503933') Where NotificationCompletedBy = 'scottbaxtergree';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '50216991') Where NotificationCompletedBy = 'scottbrezinski';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '24007132') Where NotificationCompletedBy = 's. sharp';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '24007132') Where NotificationCompletedBy = 'S.Sharp';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '24007132') Where NotificationCompletedBy = 'scott sharp';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '24007132') Where NotificationCompletedBy = 'Scott Sharp/Jen Milakeve';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60002400') Where NotificationCompletedBy = 'olivies';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60002400') Where NotificationCompletedBy = 'S Oliver';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60002400') Where NotificationCompletedBy = 'S Olivier';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60007118') Where NotificationCompletedBy = 'Shealynn O''Toole';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60007118') Where NotificationCompletedBy = 'SMO';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60007118') Where NotificationCompletedBy = 'SO';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '50481485') Where NotificationCompletedBy = 'Shelley  Lane';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '50481485') Where NotificationCompletedBy = 'Shelley Lane';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60000937') Where NotificationCompletedBy = 'Silvanus Jackso';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '50301305') Where NotificationCompletedBy = 'Stacy Ortiz';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60000418') Where NotificationCompletedBy = 'sdenigris';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60006818') Where NotificationCompletedBy = 'Stephanie Ackerma';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60002572') Where NotificationCompletedBy = 'Stephen Jurick';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60003204') Where NotificationCompletedBy = 'Stephen Straub';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60001720') Where NotificationCompletedBy = 'Bukowski Steve';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60001720') Where NotificationCompletedBy = 'Steven Bukowski';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '50213550') Where NotificationCompletedBy = 'PatilS';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '50213550') Where NotificationCompletedBy = 'S Patil';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '50213550') Where NotificationCompletedBy = 'S.Patil';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '50213550') Where NotificationCompletedBy = 'SP';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '50213550') Where NotificationCompletedBy = 'SPatil';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '50213550') Where NotificationCompletedBy = 'Sunil';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '50213550') Where NotificationCompletedBy = 'sunil patil';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '50213550') Where NotificationCompletedBy = 'sunilpatil';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '50213550') Where NotificationCompletedBy = 'Sunil';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60006713') Where NotificationCompletedBy = 'S. Widauf';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60006713') Where NotificationCompletedBy = 'S.Widauf';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60006713') Where NotificationCompletedBy = 'S.Widuaf';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60006713') Where NotificationCompletedBy = 'Sydney Widauf';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '18507264') Where NotificationCompletedBy = 'T. Burrows';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '18507264') Where NotificationCompletedBy = 'T.Burrows';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '18507264') Where NotificationCompletedBy = 'tburrows';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '18507264') Where NotificationCompletedBy = 'teresaburrows';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60003426') Where NotificationCompletedBy = 'TH';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60003426') Where NotificationCompletedBy = 'Thalika Hollingsworth';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60001168') Where NotificationCompletedBy = 'Garcia, Thomas - 60001168 - NJ7';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60001168') Where NotificationCompletedBy = 'Garcia, Thomas : 60001168';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60001168') Where NotificationCompletedBy = 'garciatj';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60001168') Where NotificationCompletedBy = 'T  Garcia';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60001168') Where NotificationCompletedBy = 'T garcia';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60001168') Where NotificationCompletedBy = 'TG';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60001168') Where NotificationCompletedBy = 'TGarcia';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '18714950') Where NotificationCompletedBy = 'Thomas Iverso';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '18714950') Where NotificationCompletedBy = 'thomasiverso';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60005068') Where NotificationCompletedBy = 'Thomas Neri';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60005068') Where NotificationCompletedBy = 'T';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60005068') Where NotificationCompletedBy = 'Tom Neri';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '50432029') Where NotificationCompletedBy = 'Todd M Zaehringer';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '50432029') Where NotificationCompletedBy = 'Todd Zaeh';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '50432029') Where NotificationCompletedBy = 'Todd Zaehringer';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60006498') Where NotificationCompletedBy = 'T. Christma';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60005954') Where NotificationCompletedBy = 'Todd Meserole';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60002621') Where NotificationCompletedBy = 't stieglitz';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60002621') Where NotificationCompletedBy = 'T. Stieglitz';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60002621') Where NotificationCompletedBy = 'Troy Stieglitz';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '50454315') Where NotificationCompletedBy = 'RiosI';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '50454315') Where NotificationCompletedBy = 'modi';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '50454315') Where NotificationCompletedBy = 'ModiV';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '50454315') Where NotificationCompletedBy = 'riosi/modiv';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '50454315') Where NotificationCompletedBy = 'Vishal';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '50454315') Where NotificationCompletedBy = 'Vishal Modi';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '50454315') Where NotificationCompletedBy = 'vishalmodi';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '50454315') Where NotificationCompletedBy = 'VM';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '50454315') Where NotificationCompletedBy = 'VMM';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '50454315') Where NotificationCompletedBy = 'VModi';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '50274134') Where NotificationCompletedBy = 'William A Lewis';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60005187') Where NotificationCompletedBy = 'William Orr';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60006075') Where NotificationCompletedBy = 'Yanesi Martinez';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60001842') Where NotificationCompletedBy = 'iversoz';
Update WaterQualityComplaints Set NotificationCompletedById = (Select tblEmployeeID from #tmpEmployees Where EmployeeID = '60001842') Where NotificationCompletedBy = 'Zach Iverso';

drop table #tmpEmployees;

";
        public override void Up()
        {
            Alter.Table(Tables.WATER_QUALITY_COMPLAINTS)
                 .AddForeignKeyColumn(Columns.NOTIFICATION_COMPLETED_BY_EMPLOYEE_ID, Tables.EMPLOYEE, Columns.EMPLOYEE_ID);
            Execute.Sql(@SET_EMPLOYEE_ID);

            //We'll keep the NotificationCompletedBy field around for a bit and delete in a later ticket.
        }

        public override void Down()
        {
            Delete.ForeignKeyColumn(Tables.WATER_QUALITY_COMPLAINTS, Columns.NOTIFICATION_COMPLETED_BY_EMPLOYEE_ID, Tables.EMPLOYEE, Columns.EMPLOYEE_ID);
        }
    }
}