using FluentMigrator;
using MapCall.Common.ClassExtensions;
using MMSINC.ClassExtensions.FluentMigratorExtensions;

namespace MapCall.Common.Model.Migrations._2023
{
    [Migration(20230524132723418), Tags("Production")]
    public class MC4807_AddSubjectMatterFieldToHelpTopics : Migration
    {
        public override void Up()
        {
            this.CreateLookupTableWithValues("HelpTopicSubjectMatters", "Production", "Distribution (T&D)",
                "Field Service (FSR)", "Water Quality", "Environmental", "Asset Management", "Safety", "General Help",
                "Human Resources", "Other");
            Alter.Table("HelpTopics").AddForeignKeyColumn("HelpTopicSubjectMatterId", "HelpTopicSubjectMatters");

            #region Update HelpTopicSubjectMatterId

            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Distribution (T&D)') WHERE HelpTopicId = 	1	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Distribution (T&D)') WHERE HelpTopicId = 	3	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Asset Management') WHERE HelpTopicId = 	4	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Distribution (T&D)') WHERE HelpTopicId = 	5	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Distribution (T&D)') WHERE HelpTopicId = 	7	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Distribution (T&D)') WHERE HelpTopicId = 	8	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Distribution (T&D)') WHERE HelpTopicId = 	9	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'General Help') WHERE HelpTopicId = 	10	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Safety') WHERE HelpTopicId = 	11	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Asset Management') WHERE HelpTopicId = 	12	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Distribution (T&D)') WHERE HelpTopicId = 	13	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Asset Management') WHERE HelpTopicId = 	14	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Distribution (T&D)') WHERE HelpTopicId = 	15	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Distribution (T&D)') WHERE HelpTopicId = 	16	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Distribution (T&D)') WHERE HelpTopicId = 	17	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Distribution (T&D)') WHERE HelpTopicId = 	18	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Distribution (T&D)') WHERE HelpTopicId = 	19	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Distribution (T&D)') WHERE HelpTopicId = 	20	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Distribution (T&D)') WHERE HelpTopicId = 	21	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'General Help') WHERE HelpTopicId = 	22	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Asset Management') WHERE HelpTopicId = 	24	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Asset Management') WHERE HelpTopicId = 	25	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Asset Management') WHERE HelpTopicId = 	26	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Asset Management') WHERE HelpTopicId = 	27	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Safety') WHERE HelpTopicId = 	28	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Distribution (T&D)') WHERE HelpTopicId = 	29	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Distribution (T&D)') WHERE HelpTopicId = 	30	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Distribution (T&D)') WHERE HelpTopicId = 	31	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Distribution (T&D)') WHERE HelpTopicId = 	32	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Distribution (T&D)') WHERE HelpTopicId = 	33	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Distribution (T&D)') WHERE HelpTopicId = 	34	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'General Help') WHERE HelpTopicId = 	36	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'General Help') WHERE HelpTopicId = 	37	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Field Service (FSR)') WHERE HelpTopicId = 	38	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Field Service (FSR)') WHERE HelpTopicId = 	39	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Field Service (FSR)') WHERE HelpTopicId = 	40	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Distribution (T&D)') WHERE HelpTopicId = 	41	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Distribution (T&D)') WHERE HelpTopicId = 	42	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Field Service (FSR)') WHERE HelpTopicId = 	43	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'General Help') WHERE HelpTopicId = 	44	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'General Help') WHERE HelpTopicId = 	45	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'General Help') WHERE HelpTopicId = 	46	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Distribution (T&D)') WHERE HelpTopicId = 	47	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Distribution (T&D)') WHERE HelpTopicId = 	48	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Other') WHERE HelpTopicId = 	49	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Distribution (T&D)') WHERE HelpTopicId = 	50	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Environmental') WHERE HelpTopicId = 	51	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Human Resources') WHERE HelpTopicId = 	52	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Human Resources') WHERE HelpTopicId = 	53	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'General Help') WHERE HelpTopicId = 	54	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'General Help') WHERE HelpTopicId = 	55	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'General Help') WHERE HelpTopicId = 	57	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'General Help') WHERE HelpTopicId = 	58	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Distribution (T&D)') WHERE HelpTopicId = 	59	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'General Help') WHERE HelpTopicId = 	61	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Distribution (T&D)') WHERE HelpTopicId = 	63	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'General Help') WHERE HelpTopicId = 	65	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Safety') WHERE HelpTopicId = 	66	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'General Help') WHERE HelpTopicId = 	67	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Asset Management') WHERE HelpTopicId = 	69	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'General Help') WHERE HelpTopicId = 	71	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Distribution (T&D)') WHERE HelpTopicId = 	72	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'General Help') WHERE HelpTopicId = 	74	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Distribution (T&D)') WHERE HelpTopicId = 	75	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Water Quality') WHERE HelpTopicId = 	76	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'General Help') WHERE HelpTopicId = 	77	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Distribution (T&D)') WHERE HelpTopicId = 	78	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Distribution (T&D)') WHERE HelpTopicId = 	79	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Distribution (T&D)') WHERE HelpTopicId = 	80	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Distribution (T&D)') WHERE HelpTopicId = 	81	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Distribution (T&D)') WHERE HelpTopicId = 	82	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Distribution (T&D)') WHERE HelpTopicId = 	83	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Water Quality') WHERE HelpTopicId = 	84	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Water Quality') WHERE HelpTopicId = 	85	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Distribution (T&D)') WHERE HelpTopicId = 	86	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Distribution (T&D)') WHERE HelpTopicId = 	87	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Environmental') WHERE HelpTopicId = 	88	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Water Quality') WHERE HelpTopicId = 	89	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Distribution (T&D)') WHERE HelpTopicId = 	90	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Distribution (T&D)') WHERE HelpTopicId = 	91	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Water Quality') WHERE HelpTopicId = 	92	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Distribution (T&D)') WHERE HelpTopicId = 	93	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Distribution (T&D)') WHERE HelpTopicId = 	94	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'General Help') WHERE HelpTopicId = 	95	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Human Resources') WHERE HelpTopicId = 	96	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Distribution (T&D)') WHERE HelpTopicId = 	97	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Distribution (T&D)') WHERE HelpTopicId = 	98	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Safety') WHERE HelpTopicId = 	100	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Distribution (T&D)') WHERE HelpTopicId = 	101	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Distribution (T&D)') WHERE HelpTopicId = 	102	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Distribution (T&D)') WHERE HelpTopicId = 	103	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Water Quality') WHERE HelpTopicId = 	104	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Human Resources') WHERE HelpTopicId = 	105	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Distribution (T&D)') WHERE HelpTopicId = 	106	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Distribution (T&D)') WHERE HelpTopicId = 	107	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Distribution (T&D)') WHERE HelpTopicId = 	108	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Distribution (T&D)') WHERE HelpTopicId = 	109	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Distribution (T&D)') WHERE HelpTopicId = 	110	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Distribution (T&D)') WHERE HelpTopicId = 	111	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Distribution (T&D)') WHERE HelpTopicId = 	112	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Safety') WHERE HelpTopicId = 	113	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Distribution (T&D)') WHERE HelpTopicId = 	114	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Asset Management') WHERE HelpTopicId = 	115	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Distribution (T&D)') WHERE HelpTopicId = 	116	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Production') WHERE HelpTopicId = 	117	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Distribution (T&D)') WHERE HelpTopicId = 	118	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Distribution (T&D)') WHERE HelpTopicId = 	119	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Asset Management') WHERE HelpTopicId = 	120	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Human Resources') WHERE HelpTopicId = 	121	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'General Help') WHERE HelpTopicId = 	122	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'General Help') WHERE HelpTopicId = 	123	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Distribution (T&D)') WHERE HelpTopicId = 	125	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'General Help') WHERE HelpTopicId = 	126	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Safety') WHERE HelpTopicId = 	127	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Water Quality') WHERE HelpTopicId = 	128	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Asset Management') WHERE HelpTopicId = 	129	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Water Quality') WHERE HelpTopicId = 	130	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'General Help') WHERE HelpTopicId = 	131	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Distribution (T&D)') WHERE HelpTopicId = 	132	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Distribution (T&D)') WHERE HelpTopicId = 	133	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Field Service (FSR)') WHERE HelpTopicId = 	134	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Distribution (T&D)') WHERE HelpTopicId = 	135	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Distribution (T&D)') WHERE HelpTopicId = 	136	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Distribution (T&D)') WHERE HelpTopicId = 	137	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Distribution (T&D)') WHERE HelpTopicId = 	138	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Distribution (T&D)') WHERE HelpTopicId = 	139	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Asset Management') WHERE HelpTopicId = 	140	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Production') WHERE HelpTopicId = 	141	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Distribution (T&D)') WHERE HelpTopicId = 	142	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'General Help') WHERE HelpTopicId = 	143	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'General Help') WHERE HelpTopicId = 	144	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Asset Management') WHERE HelpTopicId = 	145	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Asset Management') WHERE HelpTopicId = 	146	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'General Help') WHERE HelpTopicId = 	147	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Distribution (T&D)') WHERE HelpTopicId = 	148	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Production') WHERE HelpTopicId = 	150	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Production') WHERE HelpTopicId = 	152	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'General Help') WHERE HelpTopicId = 	154	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Distribution (T&D)') WHERE HelpTopicId = 	155	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Distribution (T&D)') WHERE HelpTopicId = 	156	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'General Help') WHERE HelpTopicId = 	157	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Distribution (T&D)') WHERE HelpTopicId = 	158	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Distribution (T&D)') WHERE HelpTopicId = 	159	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Asset Management') WHERE HelpTopicId = 	160	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Distribution (T&D)') WHERE HelpTopicId = 	161	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Distribution (T&D)') WHERE HelpTopicId = 	162	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Production') WHERE HelpTopicId = 	163	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Production') WHERE HelpTopicId = 	164	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Production') WHERE HelpTopicId = 	165	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Safety') WHERE HelpTopicId = 	166	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Other') WHERE HelpTopicId = 	167	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Distribution (T&D)') WHERE HelpTopicId = 	168	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Distribution (T&D)') WHERE HelpTopicId = 	169	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Distribution (T&D)') WHERE HelpTopicId = 	170	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Safety') WHERE HelpTopicId = 	171	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'General Help') WHERE HelpTopicId = 	172	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Distribution (T&D)') WHERE HelpTopicId = 	173	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Distribution (T&D)') WHERE HelpTopicId = 	174	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'General Help') WHERE HelpTopicId = 	175	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'General Help') WHERE HelpTopicId = 	176	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Asset Management') WHERE HelpTopicId = 	177	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Distribution (T&D)') WHERE HelpTopicId = 	178	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Production') WHERE HelpTopicId = 	179	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'General Help') WHERE HelpTopicId = 	180	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Asset Management') WHERE HelpTopicId = 	181	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Other') WHERE HelpTopicId = 	182	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Water Quality') WHERE HelpTopicId = 	183	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Production') WHERE HelpTopicId = 	184	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Safety') WHERE HelpTopicId = 	185	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'General Help') WHERE HelpTopicId = 	186	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Safety') WHERE HelpTopicId = 	187	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Production') WHERE HelpTopicId = 	188	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Production') WHERE HelpTopicId = 	189	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Production') WHERE HelpTopicId = 	190	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Production') WHERE HelpTopicId = 	191	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Distribution (T&D)') WHERE HelpTopicId = 	192	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Production') WHERE HelpTopicId = 	194	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'General Help') WHERE HelpTopicId = 	195	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Asset Management') WHERE HelpTopicId = 	196	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Environmental') WHERE HelpTopicId = 	198	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Distribution (T&D)') WHERE HelpTopicId = 	199	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Distribution (T&D)') WHERE HelpTopicId = 	200	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Distribution (T&D)') WHERE HelpTopicId = 	201	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Production') WHERE HelpTopicId = 	202	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Distribution (T&D)') WHERE HelpTopicId = 	203	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Production') WHERE HelpTopicId = 	204	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Distribution (T&D)') WHERE HelpTopicId = 	206	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Production') WHERE HelpTopicId = 	207	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'General Help') WHERE HelpTopicId = 	208	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Environmental') WHERE HelpTopicId = 	209	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'General Help') WHERE HelpTopicId = 	210	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'General Help') WHERE HelpTopicId = 	211	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Asset Management') WHERE HelpTopicId = 	212	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Environmental') WHERE HelpTopicId = 	213	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Safety') WHERE HelpTopicId = 	214	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Distribution (T&D)') WHERE HelpTopicId = 	215	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Distribution (T&D)') WHERE HelpTopicId = 	216	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Distribution (T&D)') WHERE HelpTopicId = 	217	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Field Service (FSR)') WHERE HelpTopicId = 	218	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'General Help') WHERE HelpTopicId = 	219	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Production') WHERE HelpTopicId = 	220	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Production') WHERE HelpTopicId = 	221	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Production') WHERE HelpTopicId = 	222	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Distribution (T&D)') WHERE HelpTopicId = 	223	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Distribution (T&D)') WHERE HelpTopicId = 	224	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Production') WHERE HelpTopicId = 	225	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Production') WHERE HelpTopicId = 	226	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Distribution (T&D)') WHERE HelpTopicId = 	227	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Distribution (T&D)') WHERE HelpTopicId = 	228	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'General Help') WHERE HelpTopicId = 	229	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'General Help') WHERE HelpTopicId = 	230	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'General Help') WHERE HelpTopicId = 	231	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Distribution (T&D)') WHERE HelpTopicId = 	232	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Distribution (T&D)') WHERE HelpTopicId = 	233	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Environmental') WHERE HelpTopicId = 	234	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Production') WHERE HelpTopicId = 	235	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Asset Management') WHERE HelpTopicId = 	236	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Distribution (T&D)') WHERE HelpTopicId = 	237	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'General Help') WHERE HelpTopicId = 	238	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Distribution (T&D)') WHERE HelpTopicId = 	239	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Distribution (T&D)') WHERE HelpTopicId = 	240	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Production') WHERE HelpTopicId = 	241	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Production') WHERE HelpTopicId = 	242	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Production') WHERE HelpTopicId = 	243	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Other') WHERE HelpTopicId = 	244	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Other') WHERE HelpTopicId = 	245	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Distribution (T&D)') WHERE HelpTopicId = 	246	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Other') WHERE HelpTopicId = 	247	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Distribution (T&D)') WHERE HelpTopicId = 	248	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Distribution (T&D)') WHERE HelpTopicId = 	249	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Other') WHERE HelpTopicId = 	250	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'General Help') WHERE HelpTopicId = 	252	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'General Help') WHERE HelpTopicId = 	253	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Production') WHERE HelpTopicId = 	254	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Other') WHERE HelpTopicId = 	255	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Environmental') WHERE HelpTopicId = 	256	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Asset Management') WHERE HelpTopicId = 	257	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Production') WHERE HelpTopicId = 	258	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Distribution (T&D)') WHERE HelpTopicId = 	259	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Production') WHERE HelpTopicId = 	260	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Distribution (T&D)') WHERE HelpTopicId = 	261	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Distribution (T&D)') WHERE HelpTopicId = 	262	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Other') WHERE HelpTopicId = 	263	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Water Quality') WHERE HelpTopicId = 	264	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Production') WHERE HelpTopicId = 	265	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Asset Management') WHERE HelpTopicId = 	266	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Other') WHERE HelpTopicId = 	267	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Distribution (T&D)') WHERE HelpTopicId = 	268	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Distribution (T&D)') WHERE HelpTopicId = 	270	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Environmental') WHERE HelpTopicId = 	271	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Distribution (T&D)') WHERE HelpTopicId = 	272	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'General Help') WHERE HelpTopicId = 	273	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Water Quality') WHERE HelpTopicId = 	274	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'General Help') WHERE HelpTopicId = 	275	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Water Quality') WHERE HelpTopicId = 	276	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Distribution (T&D)') WHERE HelpTopicId = 	277	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Other') WHERE HelpTopicId = 	278	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Distribution (T&D)') WHERE HelpTopicId = 	279	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'General Help') WHERE HelpTopicId = 	280	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Water Quality') WHERE HelpTopicId = 	281	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Water Quality') WHERE HelpTopicId = 	282	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Environmental') WHERE HelpTopicId = 	283	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Other') WHERE HelpTopicId = 	285	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Other') WHERE HelpTopicId = 	288	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Other') WHERE HelpTopicId = 	291	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Safety') WHERE HelpTopicId = 	293	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Water Quality') WHERE HelpTopicId = 	295	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'General Help') WHERE HelpTopicId = 	296	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Distribution (T&D)') WHERE HelpTopicId = 	297	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'General Help') WHERE HelpTopicId = 	298	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'General Help') WHERE HelpTopicId = 	299	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Other') WHERE HelpTopicId = 	300	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Water Quality') WHERE HelpTopicId = 	301	");
            Execute.Sql("UPDATE HelpTopics set HelpTopicSubjectMatterId = (SELECT Id FROM HelpTopicSubjectMatters WHERE Description = 'Water Quality') WHERE HelpTopicId = 	302	");

            #endregion
        }

        public override void Down()
        {
            Delete.ForeignKeyColumn("HelpTopics", "HelpTopicSubjectMatterId", "HelpTopicSubjectMatters");
            Delete.Table("HelpTopicSubjectMatters");
        }
    }
}