using FluentMigrator;
using MMSINC.ClassExtensions.FluentMigratorExtensions;

namespace MapCall.Common.Model.Migrations._2023
{
    [Migration(20230206081610816), Tags("Production")]
    public class Mc5314UpdateTaskGroupsWithTaskGroupCategories : Migration
    {
        public override void Up()
        {
            Execute.Sql(
                @"Update [TaskGroups] Set [TaskGroups].[TaskGroupCategoryId] = [TaskGroupsTaskGroupCategories].[TaskGroupCategoryId]
                        FROM [TaskGroupsTaskGroupCategories]
                        WHERE [TaskGroupsTaskGroupCategories].[TaskGroupId] = [TaskGroups].[Id]");
            Delete.Table("TaskGroupsTaskGroupCategories");
        }

        public override void Down()
        {
            Execute.Sql(
                @"Update [TaskGroups] Set [TaskGroups].[TaskGroupCategoryId] = NULL
                        WHERE [TaskGroups].[Id] < 184");
            Create.Table("TaskGroupsTaskGroupCategories")
                  .WithForeignKeyColumn("TaskGroupId", "TaskGroups").NotNullable()
                  .WithForeignKeyColumn("TaskGroupCategoryId", "TaskGroupCategories").NotNullable();

            Execute.Sql(@"declare @taskGroupId int, @taskGroupCategoryId int;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'CH01'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Electrical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'CH02'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Electrical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'CH03'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Chemical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'CH04'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Chemical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'CH04'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Instrumentation'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'CH04'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Mechanical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'CH05'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Chemical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'CH06'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Chemical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'CH07'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Chemical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'CH08'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Chemical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'CH09'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Chemical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'CH10'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Chemical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'CH10'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Instrumentation'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'CH10'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Mechanical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'CH11'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Chemical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'CH12'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Chemical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'CH12'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Mechanical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'CH13'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Mechanical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'CH15'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Chemical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'CH15'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Electrical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'CH15'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Mechanical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'CH16'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Chemical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'CH17'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Chemical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'CH18'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Chemical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'CH19'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Instrumentation'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'CH20'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Instrumentation'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'CH21'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Mechanical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'CH22'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Instrumentation'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'CH23'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Chemical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'CH24'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Chemical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'CH25'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Chemical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'CH26'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Chemical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'CH27'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Chemical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'CH28'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Chemical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'CH29'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Chemical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'CH30'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Chemical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'E01'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Electrical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'E02'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Electrical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'E03'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Electrical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'E04'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Electrical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'E05'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Electrical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'E06'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Electrical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'E07'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Electrical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'E08'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Electrical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'E09'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Electrical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'E09'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Mechanical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'E10'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Electrical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'E10'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Mechanical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'E11'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Electrical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'E12'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Electrical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'E13'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Electrical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'E14'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Electrical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'E15'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Instrumentation'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'H01'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Mechanical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'H02'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Mechanical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'H04'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Mechanical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'H05'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Mechanical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'H06'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Mechanical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'I01'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Instrumentation'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'I02'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Instrumentation'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'I03'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Instrumentation'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'I04'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Instrumentation'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'I05'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Instrumentation'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'I06'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Instrumentation'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'I07'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Instrumentation'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'I08'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Instrumentation'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'I09'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Instrumentation'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'I10'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Instrumentation'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'I11'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Instrumentation'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'I12'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Instrumentation'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'I12A'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Instrumentation'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'I13'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Instrumentation'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'I14'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Instrumentation'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'I15'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Instrumentation'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'I16'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Instrumentation'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'I17'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Instrumentation'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'I18'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Instrumentation'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'I19'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Instrumentation'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'I20'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Instrumentation'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'I21'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Instrumentation'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'I22'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Chemical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'I22'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Instrumentation'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'I23'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Instrumentation'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'I29'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Instrumentation'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'I30'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Instrumentation'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'M01'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Mechanical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'M02'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Mechanical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'M03'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Mechanical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'M04'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Mechanical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'M05'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Mechanical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'M06'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Mechanical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'M07'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Mechanical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'M08'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Electrical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'M08'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Mechanical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'M09'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Mechanical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'M10'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Mechanical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'M11'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Electrical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'M11'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Mechanical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'M12'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Electrical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'M12'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Mechanical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'M13'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Mechanical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'M15'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Mechanical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'M16'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Mechanical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'M16A'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Mechanical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'M17'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Mechanical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'M18'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Mechanical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'M19'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Electrical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'M19'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Mechanical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'M20'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Mechanical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'M21'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Mechanical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'M22'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Mechanical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'M23'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Mechanical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'M24'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Mechanical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'M25'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Mechanical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'M26'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Mechanical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'M27'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Mechanical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'M28'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Mechanical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'M29'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Mechanical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'M30'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Mechanical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'M31'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Mechanical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'M32'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Mechanical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'M33'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Mechanical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'M34'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Mechanical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'M35'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Mechanical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'M36'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Mechanical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'M37'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Mechanical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'M38'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Mechanical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'M40'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Mechanical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'M41'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Mechanical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'M42'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Mechanical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'M43'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Mechanical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'M44'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Mechanical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'M45'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Mechanical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'M46'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Mechanical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'M47'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Mechanical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'M48'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Mechanical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'M49'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Mechanical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'M50'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Mechanical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'M51'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Mechanical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'M52'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Mechanical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'M53'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Mechanical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'M54'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Mechanical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'M55'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Chemical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'M55'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Mechanical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'M56'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Chemical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'M56'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Mechanical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'M57'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Mechanical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'M58'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Mechanical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'M59'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Mechanical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'M60'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Mechanical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'M61'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Mechanical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'M63'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Mechanical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'M64'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Mechanical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'M65'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Mechanical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'M66'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Mechanical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'M67'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Mechanical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'M70'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Mechanical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'M71'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Mechanical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'M72'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Mechanical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'M75'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Mechanical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'S01'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Safety'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'S02'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Safety'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'S03'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Safety'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'S04'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Safety'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'S05'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Chemical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'S05'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Electrical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'S05'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Instrumentation'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'S05'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Mechanical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'S05'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Safety'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'S06'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Operational'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'S07'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Electrical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'S07'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Instrumentation'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'S07'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Mechanical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'S07'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Safety'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'S08'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Safety'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'S09'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Safety'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'S10'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Safety'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'S11'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Safety'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'S12'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Safety'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'S13'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Safety'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'S14'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Safety'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'S15'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Safety'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'S16'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Safety'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'S17'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Safety'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'S18'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Safety'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'S19'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Safety'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'S20'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Safety'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'S21'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Safety'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'S22'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Safety'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'S23'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Safety'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'S24'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Safety'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'S25'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Safety'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'S26'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Safety'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'S27'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Safety'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'S28'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Safety'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'S29'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Safety'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'T01'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Chemical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'T02'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Chemical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'V01'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Mechanical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'V32'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Mechanical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'V33'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Mechanical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'W01'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Mechanical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'W02'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Mechanical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
            select @taskGroupId = Id from TaskGroups where TaskGroupId = 'W03'  select @taskGroupCategoryId = Id from TaskGroupCategories where Type = 'Mechanical'  insert into TaskGroupsTaskGroupCategories (TaskGroupId, TaskGroupCategoryId) select @taskGroupId, @taskGroupCategoryId;
                        ");
        }
    }
}