//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MapCall.SAP.WBSElementWS
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://amwater.com/EAM/0020/MAPCALL/GetWBSElement", ConfigurationName="WBSElementWS.WBSElement_Get_OB_SYN")]
    public interface WBSElement_Get_OB_SYN {
        // CODEGEN: Generating message contract since the operation WBSElement_Get_OB_SYN is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MapCall.SAP.WBSElementWS.WBSElement_Get_OB_SYNResponse WBSElement_Get_OB_SYN(MapCall.SAP.WBSElementWS.WBSElement_Get_OB_SYNRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        System.Threading.Tasks.Task<MapCall.SAP.WBSElementWS.WBSElement_Get_OB_SYNResponse> WBSElement_Get_OB_SYNAsync(MapCall.SAP.WBSElementWS.WBSElement_Get_OB_SYNRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://amwater.com/EAM/0020/MAPCALL/GetWBSElement")]
    public partial class WBSElementQuery : object, System.ComponentModel.INotifyPropertyChanged {
        private WBSElementQueryRecord recordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public WBSElementQueryRecord Record {
            get {
                return this.recordField;
            }
            set {
                this.recordField = value;
                this.RaisePropertyChanged("Record");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://amwater.com/EAM/0020/MAPCALL/GetWBSElement")]
    public partial class WBSElementQueryRecord : object, System.ComponentModel.INotifyPropertyChanged {
        private string wBSNumberField;
        
        private string wBSDescriptionField;
        
        private string projectDefinitionField;
        
        private string planningPlantField;
        
        private string projectTypeField;
        
        private string profitCentreField;
        
        private string profitCentreFieldNameField;
        
        private string assetCodeField;
        
        private string yearField;
        
        private string systemStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string WBSNumber {
            get {
                return this.wBSNumberField;
            }
            set {
                this.wBSNumberField = value;
                this.RaisePropertyChanged("WBSNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string WBSDescription {
            get {
                return this.wBSDescriptionField;
            }
            set {
                this.wBSDescriptionField = value;
                this.RaisePropertyChanged("WBSDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string ProjectDefinition {
            get {
                return this.projectDefinitionField;
            }
            set {
                this.projectDefinitionField = value;
                this.RaisePropertyChanged("ProjectDefinition");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string PlanningPlant {
            get {
                return this.planningPlantField;
            }
            set {
                this.planningPlantField = value;
                this.RaisePropertyChanged("PlanningPlant");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string ProjectType {
            get {
                return this.projectTypeField;
            }
            set {
                this.projectTypeField = value;
                this.RaisePropertyChanged("ProjectType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string ProfitCentre {
            get {
                return this.profitCentreField;
            }
            set {
                this.profitCentreField = value;
                this.RaisePropertyChanged("ProfitCentre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string ProfitCentreFieldName {
            get {
                return this.profitCentreFieldNameField;
            }
            set {
                this.profitCentreFieldNameField = value;
                this.RaisePropertyChanged("ProfitCentreFieldName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string AssetCode {
            get {
                return this.assetCodeField;
            }
            set {
                this.assetCodeField = value;
                this.RaisePropertyChanged("AssetCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string Year {
            get {
                return this.yearField;
            }
            set {
                this.yearField = value;
                this.RaisePropertyChanged("Year");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string SystemStatus {
            get {
                return this.systemStatusField;
            }
            set {
                this.systemStatusField = value;
                this.RaisePropertyChanged("SystemStatus");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://amwater.com/EAM/0020/MAPCALL/GetWBSElement")]
    public partial class WBSElementInfo : object, System.ComponentModel.INotifyPropertyChanged {
        private WBSElementInfoRecord[] recordField;
        
        private string sAPStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Record", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public WBSElementInfoRecord[] Record {
            get {
                return this.recordField;
            }
            set {
                this.recordField = value;
                this.RaisePropertyChanged("Record");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string SAPStatus {
            get {
                return this.sAPStatusField;
            }
            set {
                this.sAPStatusField = value;
                this.RaisePropertyChanged("SAPStatus");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://amwater.com/EAM/0020/MAPCALL/GetWBSElement")]
    public partial class WBSElementInfoRecord : object, System.ComponentModel.INotifyPropertyChanged {
        private string wBSElementField;
        
        private string wBSDescriptionField;
        
        private string statusCodeField;
        
        private string startDateField;
        
        private string endDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string WBSElement {
            get {
                return this.wBSElementField;
            }
            set {
                this.wBSElementField = value;
                this.RaisePropertyChanged("WBSElement");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string WBSDescription {
            get {
                return this.wBSDescriptionField;
            }
            set {
                this.wBSDescriptionField = value;
                this.RaisePropertyChanged("WBSDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string StatusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
                this.RaisePropertyChanged("StatusCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string StartDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
                this.RaisePropertyChanged("StartDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string EndDate {
            get {
                return this.endDateField;
            }
            set {
                this.endDateField = value;
                this.RaisePropertyChanged("EndDate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WBSElement_Get_OB_SYNRequest {
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://amwater.com/EAM/0020/MAPCALL/GetWBSElement", Order=0)]
        public MapCall.SAP.WBSElementWS.WBSElementQuery WBSElementRequest;
        
        public WBSElement_Get_OB_SYNRequest() {
        }
        
        public WBSElement_Get_OB_SYNRequest(MapCall.SAP.WBSElementWS.WBSElementQuery WBSElementRequest) {
            this.WBSElementRequest = WBSElementRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WBSElement_Get_OB_SYNResponse {
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://amwater.com/EAM/0020/MAPCALL/GetWBSElement", Order=0)]
        public MapCall.SAP.WBSElementWS.WBSElementInfo WBSElementResponse;
        
        public WBSElement_Get_OB_SYNResponse() {
        }
        
        public WBSElement_Get_OB_SYNResponse(MapCall.SAP.WBSElementWS.WBSElementInfo WBSElementResponse) {
            this.WBSElementResponse = WBSElementResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WBSElement_Get_OB_SYNChannel : MapCall.SAP.WBSElementWS.WBSElement_Get_OB_SYN, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WBSElement_Get_OB_SYNClient : System.ServiceModel.ClientBase<MapCall.SAP.WBSElementWS.WBSElement_Get_OB_SYN>, MapCall.SAP.WBSElementWS.WBSElement_Get_OB_SYN {
        public WBSElement_Get_OB_SYNClient() {
        }
        
        public WBSElement_Get_OB_SYNClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WBSElement_Get_OB_SYNClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WBSElement_Get_OB_SYNClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WBSElement_Get_OB_SYNClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MapCall.SAP.WBSElementWS.WBSElement_Get_OB_SYNResponse MapCall.SAP.WBSElementWS.WBSElement_Get_OB_SYN.WBSElement_Get_OB_SYN(MapCall.SAP.WBSElementWS.WBSElement_Get_OB_SYNRequest request) {
            return base.Channel.WBSElement_Get_OB_SYN(request);
        }
        
        public MapCall.SAP.WBSElementWS.WBSElementInfo WBSElement_Get_OB_SYN(MapCall.SAP.WBSElementWS.WBSElementQuery WBSElementRequest) {
            MapCall.SAP.WBSElementWS.WBSElement_Get_OB_SYNRequest inValue = new MapCall.SAP.WBSElementWS.WBSElement_Get_OB_SYNRequest();
            inValue.WBSElementRequest = WBSElementRequest;
            MapCall.SAP.WBSElementWS.WBSElement_Get_OB_SYNResponse retVal = ((MapCall.SAP.WBSElementWS.WBSElement_Get_OB_SYN)(this)).WBSElement_Get_OB_SYN(inValue);
            return retVal.WBSElementResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MapCall.SAP.WBSElementWS.WBSElement_Get_OB_SYNResponse> MapCall.SAP.WBSElementWS.WBSElement_Get_OB_SYN.WBSElement_Get_OB_SYNAsync(MapCall.SAP.WBSElementWS.WBSElement_Get_OB_SYNRequest request) {
            return base.Channel.WBSElement_Get_OB_SYNAsync(request);
        }
        
        public System.Threading.Tasks.Task<MapCall.SAP.WBSElementWS.WBSElement_Get_OB_SYNResponse> WBSElement_Get_OB_SYNAsync(MapCall.SAP.WBSElementWS.WBSElementQuery WBSElementRequest) {
            MapCall.SAP.WBSElementWS.WBSElement_Get_OB_SYNRequest inValue = new MapCall.SAP.WBSElementWS.WBSElement_Get_OB_SYNRequest();
            inValue.WBSElementRequest = WBSElementRequest;
            return ((MapCall.SAP.WBSElementWS.WBSElement_Get_OB_SYN)(this)).WBSElement_Get_OB_SYNAsync(inValue);
        }
    }
}
