//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace MapCall.Modules.FieldServices {
    
    
    public partial class StormDrainInspectionCleanings {
        
        /// <summary>
        /// template control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MapCall.Controls.DetailsViewDataPageTemplate template;
        
        /// <summary>
        /// searchStormWaterAssetSearch control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MMSINC.Controls.MvpDropDownList searchStormWaterAssetSearch;
        
        /// <summary>
        /// cddStormWaterAssetsSearch control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AjaxControlToolkit.CascadingDropDown cddStormWaterAssetsSearch;
    }
}
