#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/EditorTemplates/AjaxFileUpload.cshtml")]
    public partial class _Views_Shared_EditorTemplates_AjaxFileUpload_cshtml_ : MapCall.Common.Views.TemplateViewBase<MMSINC.Metadata.AjaxFileUpload>
    {
        public _Views_Shared_EditorTemplates_AjaxFileUpload_cshtml_() { }
        public override void Execute()
        {
WriteLiteral("           ");

            #line 2 "..\..\Views\Shared\EditorTemplates\AjaxFileUpload.cshtml"
             
               var fu = Control.FileUpload("");
               var exts = string.Join(", ", fu.AllowedExtensions);
               var allowed = "Allowed extensions: " + (string.IsNullOrWhiteSpace(exts) ? "Any" : exts);
               var maxSize = "Max File Size: " + (fu.MaxSize.HasValue ? fu.MaxSize.Value.ToString() + " KB" : "unset");
           
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("\r\n");

            #line 9 "..\..\Views\Shared\EditorTemplates\AjaxFileUpload.cshtml"
Write(RenderEditorForTemplate(item => new System.Web.WebPages.HelperResult(__razor_template_writer => {
            #line default
            #line hidden
            
            #line 9 "..\..\Views\Shared\EditorTemplates\AjaxFileUpload.cshtml"
WriteTo(__razor_template_writer, fu);

            #line default
            #line hidden
WriteLiteralTo(__razor_template_writer, " ");

            #line 9 "..\..\Views\Shared\EditorTemplates\AjaxFileUpload.cshtml"
    WriteTo(__razor_template_writer, allowed);

            #line default
            #line hidden
WriteLiteralTo(__razor_template_writer, " <br/> ");

            #line 9 "..\..\Views\Shared\EditorTemplates\AjaxFileUpload.cshtml"
                   WriteTo(__razor_template_writer, maxSize);

            #line default
            #line hidden
WriteLiteralTo(__razor_template_writer, " ");

            #line 9 "..\..\Views\Shared\EditorTemplates\AjaxFileUpload.cshtml"
                            WriteTo(__razor_template_writer, Html.ValidationMessage("Key"));

            #line default
            #line hidden
            
            #line 9 "..\..\Views\Shared\EditorTemplates\AjaxFileUpload.cshtml"
                                                                                               })));

            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
