#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MapCall.Common.Views.Shared.EditorTemplates
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/EditorTemplates/Password.cshtml")]
    public partial class Password_ : MapCall.Common.Views.TemplateViewBase<dynamic>
    {
        public Password_() : base() { }
        public override void Execute()
        {
WriteLiteral("\r\n");

WriteLiteral("\r\n\r\n");

            #line 11 "..\..\Views\Shared\EditorTemplates\Password.cshtml"
Write(RenderEditorForTemplate(item => new System.Web.WebPages.HelperResult(__razor_template_writer => {
            #line default
            #line hidden
            
            #line 11 "..\..\Views\Shared\EditorTemplates\Password.cshtml"
WriteTo(__razor_template_writer, Control.Password("").WithValue(ViewData.TemplateInfo.FormattedModelValue).With(ViewTemplateHelper.HtmlAttributes));

            #line default
            #line hidden
WriteLiteralTo(__razor_template_writer, " ");

            #line 11 "..\..\Views\Shared\EditorTemplates\Password.cshtml"
                                                                                                                   WriteTo(__razor_template_writer, Html.ValidationMessage(""));

            #line default
            #line hidden
            
            #line 11 "..\..\Views\Shared\EditorTemplates\Password.cshtml"
                                                                                                                                                                                   })));

            #line default
            #line hidden
WriteLiteral("\r\n");
        }
    }
}
#pragma warning restore 1591
