//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MapCall.SAP.GetPMOrderWS
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://amwater.com/EAM/0028/MAPCALL/PreventiveMaintenanceOrders", ConfigurationName="GetPMOrderWS.PMOrders_Get_OB_SYN")]
    public interface PMOrders_Get_OB_SYN {
        // CODEGEN: Generating message contract since the operation PMOrders_Get_OB_SYN is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MapCall.SAP.GetPMOrderWS.PMOrders_Get_OB_SYNResponse PMOrders_Get_OB_SYN(MapCall.SAP.GetPMOrderWS.PMOrders_Get_OB_SYNRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        System.Threading.Tasks.Task<MapCall.SAP.GetPMOrderWS.PMOrders_Get_OB_SYNResponse> PMOrders_Get_OB_SYNAsync(MapCall.SAP.GetPMOrderWS.PMOrders_Get_OB_SYNRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2116.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://amwater.com/EAM/0028/MAPCALL/PreventiveMaintenanceOrders")]
    public partial class PMOrdersQuery : object, System.ComponentModel.INotifyPropertyChanged {
        private string planningPlantField;
        
        private string orderTypeField;
        
        private string createdOnField;
        
        private string companyCodeField;
        
        private string lastRunTimeField;
        
        private string orderField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string PlanningPlant {
            get {
                return this.planningPlantField;
            }
            set {
                this.planningPlantField = value;
                this.RaisePropertyChanged("PlanningPlant");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string OrderType {
            get {
                return this.orderTypeField;
            }
            set {
                this.orderTypeField = value;
                this.RaisePropertyChanged("OrderType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string CreatedOn {
            get {
                return this.createdOnField;
            }
            set {
                this.createdOnField = value;
                this.RaisePropertyChanged("CreatedOn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string CompanyCode {
            get {
                return this.companyCodeField;
            }
            set {
                this.companyCodeField = value;
                this.RaisePropertyChanged("CompanyCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string LastRunTime {
            get {
                return this.lastRunTimeField;
            }
            set {
                this.lastRunTimeField = value;
                this.RaisePropertyChanged("LastRunTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string Order {
            get {
                return this.orderField;
            }
            set {
                this.orderField = value;
                this.RaisePropertyChanged("Order");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2116.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://amwater.com/EAM/0028/MAPCALL/PreventiveMaintenanceOrders")]
    public partial class PMOrdersInfo : object, System.ComponentModel.INotifyPropertyChanged {
        private PMOrdersInfoRecord[] recordField;
        
        private string sAPStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Record", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public PMOrdersInfoRecord[] Record {
            get {
                return this.recordField;
            }
            set {
                this.recordField = value;
                this.RaisePropertyChanged("Record");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string SAPStatus {
            get {
                return this.sAPStatusField;
            }
            set {
                this.sAPStatusField = value;
                this.RaisePropertyChanged("SAPStatus");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2116.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://amwater.com/EAM/0028/MAPCALL/PreventiveMaintenanceOrders")]
    public partial class PMOrdersInfoRecord : object, System.ComponentModel.INotifyPropertyChanged {
        private string orderNoField;
        
        private string planningPlantField;
        
        private string orderTypeField;
        
        private string shortTextField;
        
        private string systemStatusField;
        
        private string longTextField;
        
        private string plannerGroupField;
        
        private string maintWorkcenterField;
        
        private string maintActivitytypeField;
        
        private string basicStartField;
        
        private string basicFinishField;
        
        private string priorityField;
        
        private string functionalLocationField;
        
        private string equipmentField;
        
        private string sAPNotificationNoField;
        
        private string addressField;
        
        private string searchterm1_2Field;
        
        private string categoryField;
        
        private string settlementReceiverField;
        
        private string maintPlanField;
        
        private string listSAPWOField;
        
        private string taskListTypeField;
        
        private string taskListGroupField;
        
        private string taskListCounterField;
        
        private PMOrdersInfoRecordOperationList[] operationListField;
        
        private PMOrdersInfoRecordComponentList[] componentListField;
        
        private PMOrdersInfoRecordObjectList[] objectListField;
        
        private PMOrdersInfoRecordPermits[] permitsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string OrderNo {
            get {
                return this.orderNoField;
            }
            set {
                this.orderNoField = value;
                this.RaisePropertyChanged("OrderNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string PlanningPlant {
            get {
                return this.planningPlantField;
            }
            set {
                this.planningPlantField = value;
                this.RaisePropertyChanged("PlanningPlant");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string OrderType {
            get {
                return this.orderTypeField;
            }
            set {
                this.orderTypeField = value;
                this.RaisePropertyChanged("OrderType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string ShortText {
            get {
                return this.shortTextField;
            }
            set {
                this.shortTextField = value;
                this.RaisePropertyChanged("ShortText");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string SystemStatus {
            get {
                return this.systemStatusField;
            }
            set {
                this.systemStatusField = value;
                this.RaisePropertyChanged("SystemStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string LongText {
            get {
                return this.longTextField;
            }
            set {
                this.longTextField = value;
                this.RaisePropertyChanged("LongText");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string PlannerGroup {
            get {
                return this.plannerGroupField;
            }
            set {
                this.plannerGroupField = value;
                this.RaisePropertyChanged("PlannerGroup");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string MaintWorkcenter {
            get {
                return this.maintWorkcenterField;
            }
            set {
                this.maintWorkcenterField = value;
                this.RaisePropertyChanged("MaintWorkcenter");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string MaintActivitytype {
            get {
                return this.maintActivitytypeField;
            }
            set {
                this.maintActivitytypeField = value;
                this.RaisePropertyChanged("MaintActivitytype");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string BasicStart {
            get {
                return this.basicStartField;
            }
            set {
                this.basicStartField = value;
                this.RaisePropertyChanged("BasicStart");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string BasicFinish {
            get {
                return this.basicFinishField;
            }
            set {
                this.basicFinishField = value;
                this.RaisePropertyChanged("BasicFinish");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string Priority {
            get {
                return this.priorityField;
            }
            set {
                this.priorityField = value;
                this.RaisePropertyChanged("Priority");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string FunctionalLocation {
            get {
                return this.functionalLocationField;
            }
            set {
                this.functionalLocationField = value;
                this.RaisePropertyChanged("FunctionalLocation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string Equipment {
            get {
                return this.equipmentField;
            }
            set {
                this.equipmentField = value;
                this.RaisePropertyChanged("Equipment");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string SAPNotificationNo {
            get {
                return this.sAPNotificationNoField;
            }
            set {
                this.sAPNotificationNoField = value;
                this.RaisePropertyChanged("SAPNotificationNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
                this.RaisePropertyChanged("Address");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string Searchterm1_2 {
            get {
                return this.searchterm1_2Field;
            }
            set {
                this.searchterm1_2Field = value;
                this.RaisePropertyChanged("Searchterm1_2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string Category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
                this.RaisePropertyChanged("Category");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string SettlementReceiver {
            get {
                return this.settlementReceiverField;
            }
            set {
                this.settlementReceiverField = value;
                this.RaisePropertyChanged("SettlementReceiver");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string MaintPlan {
            get {
                return this.maintPlanField;
            }
            set {
                this.maintPlanField = value;
                this.RaisePropertyChanged("MaintPlan");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string ListSAPWO {
            get {
                return this.listSAPWOField;
            }
            set {
                this.listSAPWOField = value;
                this.RaisePropertyChanged("ListSAPWO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public string TaskListType {
            get {
                return this.taskListTypeField;
            }
            set {
                this.taskListTypeField = value;
                this.RaisePropertyChanged("TaskListType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public string TaskListGroup {
            get {
                return this.taskListGroupField;
            }
            set {
                this.taskListGroupField = value;
                this.RaisePropertyChanged("TaskListGroup");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public string TaskListCounter {
            get {
                return this.taskListCounterField;
            }
            set {
                this.taskListCounterField = value;
                this.RaisePropertyChanged("TaskListCounter");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OperationList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public PMOrdersInfoRecordOperationList[] OperationList {
            get {
                return this.operationListField;
            }
            set {
                this.operationListField = value;
                this.RaisePropertyChanged("OperationList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ComponentList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=25)]
        public PMOrdersInfoRecordComponentList[] ComponentList {
            get {
                return this.componentListField;
            }
            set {
                this.componentListField = value;
                this.RaisePropertyChanged("ComponentList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ObjectList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=26)]
        public PMOrdersInfoRecordObjectList[] ObjectList {
            get {
                return this.objectListField;
            }
            set {
                this.objectListField = value;
                this.RaisePropertyChanged("ObjectList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Permits", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=27)]
        public PMOrdersInfoRecordPermits[] Permits {
            get {
                return this.permitsField;
            }
            set {
                this.permitsField = value;
                this.RaisePropertyChanged("Permits");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2116.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://amwater.com/EAM/0028/MAPCALL/PreventiveMaintenanceOrders")]
    public partial class PMOrdersInfoRecordOperationList : object, System.ComponentModel.INotifyPropertyChanged {
        private string operationNoField;
        
        private string shortTextField;
        
        private string workCenterField;
        
        private string plantField;
        
        private string operationDurationField;
        
        private string numberOfPersonsField;
        
        private string workDurationField;
        
        private string stdTextKeyField;
        
        private string unitField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string OperationNo {
            get {
                return this.operationNoField;
            }
            set {
                this.operationNoField = value;
                this.RaisePropertyChanged("OperationNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ShortText {
            get {
                return this.shortTextField;
            }
            set {
                this.shortTextField = value;
                this.RaisePropertyChanged("ShortText");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string WorkCenter {
            get {
                return this.workCenterField;
            }
            set {
                this.workCenterField = value;
                this.RaisePropertyChanged("WorkCenter");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Plant {
            get {
                return this.plantField;
            }
            set {
                this.plantField = value;
                this.RaisePropertyChanged("Plant");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string OperationDuration {
            get {
                return this.operationDurationField;
            }
            set {
                this.operationDurationField = value;
                this.RaisePropertyChanged("OperationDuration");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string NumberOfPersons {
            get {
                return this.numberOfPersonsField;
            }
            set {
                this.numberOfPersonsField = value;
                this.RaisePropertyChanged("NumberOfPersons");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string WorkDuration {
            get {
                return this.workDurationField;
            }
            set {
                this.workDurationField = value;
                this.RaisePropertyChanged("WorkDuration");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string StdTextKey {
            get {
                return this.stdTextKeyField;
            }
            set {
                this.stdTextKeyField = value;
                this.RaisePropertyChanged("StdTextKey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string Unit {
            get {
                return this.unitField;
            }
            set {
                this.unitField = value;
                this.RaisePropertyChanged("Unit");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2116.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://amwater.com/EAM/0028/MAPCALL/PreventiveMaintenanceOrders")]
    public partial class PMOrdersInfoRecordComponentList : object, System.ComponentModel.INotifyPropertyChanged {
        private string orderItemNoField;
        
        private string orderOperationnoField;
        
        private string orderComponentField;
        
        private string desciptionField;
        
        private string qtyRequiredField;
        
        private string uOMField;
        
        private string itemCategoryField;
        
        private string storageLocationField;
        
        private string orderplantdateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string OrderItemNo {
            get {
                return this.orderItemNoField;
            }
            set {
                this.orderItemNoField = value;
                this.RaisePropertyChanged("OrderItemNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string OrderOperationno {
            get {
                return this.orderOperationnoField;
            }
            set {
                this.orderOperationnoField = value;
                this.RaisePropertyChanged("OrderOperationno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string OrderComponent {
            get {
                return this.orderComponentField;
            }
            set {
                this.orderComponentField = value;
                this.RaisePropertyChanged("OrderComponent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Desciption {
            get {
                return this.desciptionField;
            }
            set {
                this.desciptionField = value;
                this.RaisePropertyChanged("Desciption");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string QtyRequired {
            get {
                return this.qtyRequiredField;
            }
            set {
                this.qtyRequiredField = value;
                this.RaisePropertyChanged("QtyRequired");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string UOM {
            get {
                return this.uOMField;
            }
            set {
                this.uOMField = value;
                this.RaisePropertyChanged("UOM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string ItemCategory {
            get {
                return this.itemCategoryField;
            }
            set {
                this.itemCategoryField = value;
                this.RaisePropertyChanged("ItemCategory");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string StorageLocation {
            get {
                return this.storageLocationField;
            }
            set {
                this.storageLocationField = value;
                this.RaisePropertyChanged("StorageLocation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string Orderplantdate {
            get {
                return this.orderplantdateField;
            }
            set {
                this.orderplantdateField = value;
                this.RaisePropertyChanged("Orderplantdate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2116.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://amwater.com/EAM/0028/MAPCALL/PreventiveMaintenanceOrders")]
    public partial class PMOrdersInfoRecordObjectList : object, System.ComponentModel.INotifyPropertyChanged {
        private string counterField;
        
        private string sAPEquipmentNoField;
        
        private string equipmentDescField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Counter {
            get {
                return this.counterField;
            }
            set {
                this.counterField = value;
                this.RaisePropertyChanged("Counter");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string SAPEquipmentNo {
            get {
                return this.sAPEquipmentNoField;
            }
            set {
                this.sAPEquipmentNoField = value;
                this.RaisePropertyChanged("SAPEquipmentNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string EquipmentDesc {
            get {
                return this.equipmentDescField;
            }
            set {
                this.equipmentDescField = value;
                this.RaisePropertyChanged("EquipmentDesc");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2116.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://amwater.com/EAM/0028/MAPCALL/PreventiveMaintenanceOrders")]
    public partial class PMOrdersInfoRecordPermits : object, System.ComponentModel.INotifyPropertyChanged {
        private string counterField;
        
        private string permitField;
        
        private string permitCategoryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Counter {
            get {
                return this.counterField;
            }
            set {
                this.counterField = value;
                this.RaisePropertyChanged("Counter");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Permit {
            get {
                return this.permitField;
            }
            set {
                this.permitField = value;
                this.RaisePropertyChanged("Permit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string PermitCategory {
            get {
                return this.permitCategoryField;
            }
            set {
                this.permitCategoryField = value;
                this.RaisePropertyChanged("PermitCategory");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PMOrders_Get_OB_SYNRequest {
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://amwater.com/EAM/0028/MAPCALL/PreventiveMaintenanceOrders", Order=0)]
        public MapCall.SAP.GetPMOrderWS.PMOrdersQuery PMOrders_Request;
        
        public PMOrders_Get_OB_SYNRequest() {
        }
        
        public PMOrders_Get_OB_SYNRequest(MapCall.SAP.GetPMOrderWS.PMOrdersQuery PMOrders_Request) {
            this.PMOrders_Request = PMOrders_Request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PMOrders_Get_OB_SYNResponse {
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://amwater.com/EAM/0028/MAPCALL/PreventiveMaintenanceOrders", Order=0)]
        public MapCall.SAP.GetPMOrderWS.PMOrdersInfo PMOrders_Response;
        
        public PMOrders_Get_OB_SYNResponse() {
        }
        
        public PMOrders_Get_OB_SYNResponse(MapCall.SAP.GetPMOrderWS.PMOrdersInfo PMOrders_Response) {
            this.PMOrders_Response = PMOrders_Response;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PMOrders_Get_OB_SYNChannel : MapCall.SAP.GetPMOrderWS.PMOrders_Get_OB_SYN, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PMOrders_Get_OB_SYNClient : System.ServiceModel.ClientBase<MapCall.SAP.GetPMOrderWS.PMOrders_Get_OB_SYN>, MapCall.SAP.GetPMOrderWS.PMOrders_Get_OB_SYN {
        public PMOrders_Get_OB_SYNClient() {
        }
        
        public PMOrders_Get_OB_SYNClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PMOrders_Get_OB_SYNClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PMOrders_Get_OB_SYNClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PMOrders_Get_OB_SYNClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MapCall.SAP.GetPMOrderWS.PMOrders_Get_OB_SYNResponse MapCall.SAP.GetPMOrderWS.PMOrders_Get_OB_SYN.PMOrders_Get_OB_SYN(MapCall.SAP.GetPMOrderWS.PMOrders_Get_OB_SYNRequest request) {
            return base.Channel.PMOrders_Get_OB_SYN(request);
        }
        
        public MapCall.SAP.GetPMOrderWS.PMOrdersInfo PMOrders_Get_OB_SYN(MapCall.SAP.GetPMOrderWS.PMOrdersQuery PMOrders_Request) {
            MapCall.SAP.GetPMOrderWS.PMOrders_Get_OB_SYNRequest inValue = new MapCall.SAP.GetPMOrderWS.PMOrders_Get_OB_SYNRequest();
            inValue.PMOrders_Request = PMOrders_Request;
            MapCall.SAP.GetPMOrderWS.PMOrders_Get_OB_SYNResponse retVal = ((MapCall.SAP.GetPMOrderWS.PMOrders_Get_OB_SYN)(this)).PMOrders_Get_OB_SYN(inValue);
            return retVal.PMOrders_Response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MapCall.SAP.GetPMOrderWS.PMOrders_Get_OB_SYNResponse> MapCall.SAP.GetPMOrderWS.PMOrders_Get_OB_SYN.PMOrders_Get_OB_SYNAsync(MapCall.SAP.GetPMOrderWS.PMOrders_Get_OB_SYNRequest request) {
            return base.Channel.PMOrders_Get_OB_SYNAsync(request);
        }
        
        public System.Threading.Tasks.Task<MapCall.SAP.GetPMOrderWS.PMOrders_Get_OB_SYNResponse> PMOrders_Get_OB_SYNAsync(MapCall.SAP.GetPMOrderWS.PMOrdersQuery PMOrders_Request) {
            MapCall.SAP.GetPMOrderWS.PMOrders_Get_OB_SYNRequest inValue = new MapCall.SAP.GetPMOrderWS.PMOrders_Get_OB_SYNRequest();
            inValue.PMOrders_Request = PMOrders_Request;
            return ((MapCall.SAP.GetPMOrderWS.PMOrders_Get_OB_SYN)(this)).PMOrders_Get_OB_SYNAsync(inValue);
        }
    }
}
