//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace LINQTo271.Views.WorkOrders.Finalization
{


    public partial class WorkOrderFinalizationDetailView
    {

        /// <summary>
        /// lblWorkOrderID control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblWorkOrderID;

        /// <summary>
        /// phMarkoutViolations control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.PlaceHolder phMarkoutViolations;

        /// <summary>
        /// phSewerOverflows control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.PlaceHolder phSewerOverflows;

        /// <summary>
        /// phWorkOrderMainBreakForm control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.PlaceHolder phWorkOrderMainBreakForm;

        /// <summary>
        /// phScheduleOfValues control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.PlaceHolder phScheduleOfValues;

        /// <summary>
        /// phNewServiceInstallation control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.PlaceHolder phNewServiceInstallation;

        /// <summary>
        /// hidOperatingCenterIDForMaterialLookup control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hidOperatingCenterIDForMaterialLookup;

        /// <summary>
        /// upMaterialsUsed control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MMSINC.Controls.MvpUpdatePanel upMaterialsUsed;

        /// <summary>
        /// womufMaterialsUsed control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::LINQTo271.Controls.WorkOrders.WorkOrderMaterialsUsedForm womufMaterialsUsed;

        /// <summary>
        /// upSpoils control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MMSINC.Controls.MvpUpdatePanel upSpoils;

        /// <summary>
        /// wospSpoils control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::LINQTo271.Controls.WorkOrders.WorkOrderSpoilsForm wospSpoils;

        /// <summary>
        /// wofrRestorations control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::LINQTo271.Controls.WorkOrders.WorkOrderRestorationForm wofrRestorations;

        /// <summary>
        /// upCrewAssignments control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MMSINC.Controls.MvpUpdatePanel upCrewAssignments;

        /// <summary>
        /// woCrewAssignments control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::LINQTo271.Controls.WorkOrders.WorkOrderCrewAssignmentForm woCrewAssignments;

        /// <summary>
        /// woafiAdditionalInfo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::LINQTo271.Controls.WorkOrders.WorkOrderAdditionalFinalizationInfoForm woafiAdditionalInfo;

        /// <summary>
        /// pnlMainBreak control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.PlaceHolder pnlMainBreak;

        /// <summary>
        /// WorkOrderMainBreakForm control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::LINQTo271.Controls.WorkOrders.WorkOrderMainBreakForm WorkOrderMainBreakForm;

        /// <summary>
        /// pnlScheduleOfValues control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.PlaceHolder pnlScheduleOfValues;

        /// <summary>
        /// hidOperatingCenterHasWorkOrderInvoicing control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hidOperatingCenterHasWorkOrderInvoicing;

        /// <summary>
        /// woScheduleOfValues control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::LINQTo271.Controls.WorkOrders.WorkOrderScheduleOfValuesForm woScheduleOfValues;

        /// <summary>
        /// worJobSiteCheckListForm control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::LINQTo271.Controls.WorkOrders.JobSiteCheckListForm worJobSiteCheckListForm;

        /// <summary>
        /// pnlNewServiceInstallations control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.PlaceHolder pnlNewServiceInstallations;

        /// <summary>
        /// woWorkOrderNewServiceInstallationForm control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::LINQTo271.Controls.WorkOrders.NewServiceInstallationForm woWorkOrderNewServiceInstallationForm;

        /// <summary>
        /// upDocuments control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MMSINC.Controls.MvpUpdatePanel upDocuments;

        /// <summary>
        /// woDocumentForm control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::LINQTo271.Controls.WorkOrders.WorkOrderDocumentsForm woDocumentForm;

        /// <summary>
        /// txtDateCompleted control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtDateCompleted;

        /// <summary>
        /// dpDateCompleted control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AjaxControlToolkit.CalendarExtender dpDateCompleted;

        /// <summary>
        /// cvDateCompleted control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CompareValidator cvDateCompleted;

        /// <summary>
        /// meeDateCompleted control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AjaxControlToolkit.MaskedEditExtender meeDateCompleted;

        /// <summary>
        /// ddlFlushingNoticeType control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MMSINC.Controls.MvpDropDownList ddlFlushingNoticeType;

        /// <summary>
        /// odsFlushingNoticeTypes control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ObjectDataSource odsFlushingNoticeTypes;

        /// <summary>
        /// hidTrafficControlRequired control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MMSINC.Controls.MvpHiddenField hidTrafficControlRequired;

        /// <summary>
        /// hidStreetOpeningPermitRequired control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MMSINC.Controls.MvpHiddenField hidStreetOpeningPermitRequired;

        /// <summary>
        /// lblMainBreakError control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblMainBreakError;

        /// <summary>
        /// btnRefresh control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::LINQTo271.Common.MyButton btnRefresh;

        /// <summary>
        /// lnkCreateService control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MMSINC.Controls.MvpHyperLink lnkCreateService;
    }
}
