require 'tiny_tds'

values = [
  {type: 'ADJSPD', mfr: 'ABB'},
  {type: 'ADJSPD', mfr: 'ALLEN BRADLEY'},
  {type: 'ADJSPD', mfr: 'BALDOR'},
  {type: 'ADJSPD', mfr: 'BARDAC'},
  {type: 'ADJSPD', mfr: 'BENSHAW'},
  {type: 'ADJSPD', mfr: 'CUTLER HAMMER'},
  {type: 'ADJSPD', mfr: 'EATON/CUTLER HAMMER'},
  {type: 'ADJSPD', mfr: 'EMERSON'},
  {type: 'ADJSPD', mfr: 'GE'},
  {type: 'ADJSPD', mfr: 'GOULDS'},
  {type: 'ADJSPD', mfr: 'GRUNDFOS'},
  {type: 'ADJSPD', mfr: 'ITT'},
  {type: 'ADJSPD', mfr: 'KOLLMORGEN'},
  {type: 'ADJSPD', mfr: 'LENZE-AC TECH'},
  {type: 'ADJSPD', mfr: 'MAGNETEK'},
  {type: 'ADJSPD', mfr: 'MITSUBISHI'},
  {type: 'ADJSPD', mfr: 'RELIANCE'},
  {type: 'ADJSPD', mfr: 'ROBICON'},
  {type: 'ADJSPD', mfr: 'SAFETRONICS'},
  {type: 'ADJSPD', mfr: 'SIEMENS'},
  {type: 'ADJSPD', mfr: 'SQUARE D'},
  {type: 'ADJSPD', mfr: 'TELEMECANIQUE'},
  {type: 'ADJSPD', mfr: 'TOSHIBA'},
  {type: 'ADJSPD', mfr: 'UNKNOWN'},
  {type: 'ADJSPD', mfr: 'US DRIVES'},
  {type: 'ADJSPD', mfr: 'US FILTER'},
  {type: 'ADJSPD', mfr: 'VACON'},
  {type: 'ADJSPD', mfr: 'WALLACE-TIERNAN'},
  {type: 'ADJSPD', mfr: 'WESTINGHOUSE'},
  {type: 'ADJSPD', mfr: 'YASKAWA'},
  {type: 'AED', mfr: 'ADT'},
  {type: 'AED', mfr: 'CARDIAC SCIENCE'},
  {type: 'AED', mfr: 'UNKNOWN'},
  {type: 'AMIDATACOLL', mfr: 'ACLARA'},
  {type: 'AMIDATACOLL', mfr: 'ITRON'},
  {type: 'AMIDATACOLL', mfr: 'MUELLER'},
  {type: 'AMIDATACOLL', mfr: 'SENSUS'},
  {type: 'BATT', mfr: 'BEST-UPS'},
  {type: 'BATT', mfr: 'CAPITAL CONTROLS'},
  {type: 'BATT', mfr: 'CATERPILLAR'},
  {type: 'BATT', mfr: 'CD TECHNOLOGIES'},
  {type: 'BATT', mfr: 'DEKA'},
  {type: 'BATT', mfr: 'DETROIT'},
  {type: 'BATT', mfr: 'DYNACELL'},
  {type: 'BATT', mfr: 'EXIDE'},
  {type: 'BATT', mfr: 'FIAMM-MONOLITE'},
  {type: 'BATT', mfr: 'HALOGEN'},
  {type: 'BATT', mfr: 'HAZE BATTERY'},
  {type: 'BATT', mfr: 'INTERSTATE'},
  {type: 'BATT', mfr: 'MAXI POWER'},
  {type: 'BATT', mfr: 'NAPA'},
  {type: 'BATT', mfr: 'PHOENIX CONTACT'},
  {type: 'BATT', mfr: 'POWERGUARD'},
  {type: 'BATT', mfr: 'POWERSONIC'},
  {type: 'BATT', mfr: 'RAYOVAC'},
  {type: 'BATT', mfr: 'SAFT'},
  {type: 'BATT', mfr: 'UNIVERSAL BATTERY'},
  {type: 'BATT', mfr: 'UNKNOWN'},
  {type: 'BATT', mfr: 'VARTA'},
  {type: 'BATT', mfr: 'YUASA'},
  {type: 'BATTCHGR', mfr: 'CATERPILLAR'},
  {type: 'BATTCHGR', mfr: 'CHARLES INDUSTRIES'},
  {type: 'BATTCHGR', mfr: 'CUMMINS'},
  {type: 'BATTCHGR', mfr: 'DAYTON'},
  {type: 'BATTCHGR', mfr: 'DETROIT'},
  {type: 'BATTCHGR', mfr: 'EXIDE'},
  {type: 'BATTCHGR', mfr: 'GENERAC'},
  {type: 'BATTCHGR', mfr: 'GUARDIAN'},
  {type: 'BATTCHGR', mfr: 'GUEST'},
  {type: 'BATTCHGR', mfr: 'INTERSTATE'},
  {type: 'BATTCHGR', mfr: 'KATOLIGHT'},
  {type: 'BATTCHGR', mfr: 'KOHLER'},
  {type: 'BATTCHGR', mfr: 'LAMARCHE'},
  {type: 'BATTCHGR', mfr: 'MASTER CONTROL SYSTEMS'},
  {type: 'BATTCHGR', mfr: 'METRON'},
  {type: 'BATTCHGR', mfr: 'ONAN'},
  {type: 'BATTCHGR', mfr: 'POWERGUARD'},
  {type: 'BATTCHGR', mfr: 'POWERSONIC'},
  {type: 'BATTCHGR', mfr: 'SAFT'},
  {type: 'BATTCHGR', mfr: 'SCHUMACHER'},
  {type: 'BATTCHGR', mfr: 'STORED ENERGY SYSTEMS'},
  {type: 'BATTCHGR', mfr: 'UNKNOWN'},
  {type: 'BATTCHGR', mfr: 'VARTA'},
  {type: 'BLWR', mfr: 'AMERICAN FAN'},
  {type: 'BLWR', mfr: 'AMETEK'},
  {type: 'BLWR', mfr: 'CINCINNATI FAN'},
  {type: 'BLWR', mfr: 'FANTECH'},
  {type: 'BLWR', mfr: 'GARDNER DENVER'},
  {type: 'BLWR', mfr: 'GAST'},
  {type: 'BLWR', mfr: 'HOFFMAN'},
  {type: 'BLWR', mfr: 'NEW YORK BLOWER'},
  {type: 'BLWR', mfr: 'ROOTS'},
  {type: 'BLWR', mfr: 'SEMBLEX'},
  {type: 'BLWR', mfr: 'SPENCER'},
  {type: 'BLWR', mfr: 'SULLAIR'},
  {type: 'BLWR', mfr: 'TROY-BILT'},
  {type: 'BLWR', mfr: 'TWIN CITY FAN-BLOWER'},
  {type: 'BLWR', mfr: 'UNKNOWN'},
  {type: 'BOILER', mfr: 'BURNHAM'},
  {type: 'BOILER', mfr: 'CLEAVER-BROOKS'},
  {type: 'BOILER', mfr: 'HARSCO-PATTERSON-KELLEY'},
  {type: 'BOILER', mfr: 'HEAT TRANSFER PRODUCTS'},
  {type: 'BOILER', mfr: 'KEWAUNEE'},
  {type: 'BOILER', mfr: 'LOCHINVAR'},
  {type: 'BOILER', mfr: 'MESTEK'},
  {type: 'BOILER', mfr: 'PEERLESS'},
  {type: 'BOILER', mfr: 'RAYPAK'},
  {type: 'BOILER', mfr: 'REZNOR'},
  {type: 'BOILER', mfr: 'RUUD'},
  {type: 'BOILER', mfr: 'UNKNOWN'},
  {type: 'BOILER', mfr: 'WEIL'},
  {type: 'BURNER', mfr: 'LENNOX'},
  {type: 'BURNER', mfr: 'MODINE'},
  {type: 'BURNER', mfr: 'UNKNOWN'},
  {type: 'CALIB', mfr: 'FLUKE'},
  {type: 'CALIB', mfr: 'UNKNOWN'},
  {type: 'CATHODIC', mfr: 'UNKNOWN'},
  {type: 'CHEM-GEN', mfr: 'SEVERN TRENT'},
  {type: 'CHEM-GEN', mfr: 'SIEMENS'},
  {type: 'CHEM-GEN', mfr: 'UNKNOWN'},
  {type: 'CHEM-GEN', mfr: 'WALLACE-TIERNAN'},
  {type: 'CHEM-GEN', mfr: 'WATSON-MARLOW'},
  {type: 'CHEM-PIP', mfr: 'BIF'},
  {type: 'CHEM-PIP', mfr: 'CHEMCO SYSTEMS'},
  {type: 'CHEM-PIP', mfr: 'LMI'},
  {type: 'CHEM-PIP', mfr: 'MASTERFLEX'},
  {type: 'CHEM-PIP', mfr: 'PULSATRON'},
  {type: 'CHEM-PIP', mfr: 'SEVERN TRENT'},
  {type: 'CHEM-PIP', mfr: 'SIEMENS'},
  {type: 'CHEM-PIP', mfr: 'STENNER'},
  {type: 'CHEM-PIP', mfr: 'UNKNOWN'},
  {type: 'CHEM-PIP', mfr: 'WALLACE-TIERNAN'},
  {type: 'CHEM-PIP', mfr: 'WATSON-MARLOW'},
  {type: 'CHMF-DRY', mfr: 'ALLIED COLLOIDS'},
  {type: 'CHMF-DRY', mfr: 'BIF'},
  {type: 'CHMF-DRY', mfr: 'CHEMCO SYSTEMS'},
  {type: 'CHMF-DRY', mfr: 'MERRICK'},
  {type: 'CHMF-DRY', mfr: 'SEVERN TRENT'},
  {type: 'CHMF-DRY', mfr: 'SIEMENS'},
  {type: 'CHMF-DRY', mfr: 'UNKNOWN'},
  {type: 'CHMF-DRY', mfr: 'US FILTER'},
  {type: 'CHMF-DRY', mfr: 'WALLACE-TIERNAN'},
  {type: 'CHMF-GAS', mfr: 'CAPITAL CONTROLS'},
  {type: 'CHMF-GAS', mfr: 'FISCHER PORTER'},
  {type: 'CHMF-GAS', mfr: 'REGAL'},
  {type: 'CHMF-GAS', mfr: 'SEVERN TRENT'},
  {type: 'CHMF-GAS', mfr: 'SIEMENS'},
  {type: 'CHMF-GAS', mfr: 'SUPERIOR'},
  {type: 'CHMF-GAS', mfr: 'UNKNOWN'},
  {type: 'CHMF-GAS', mfr: 'US FILTER'},
  {type: 'CHMF-GAS', mfr: 'WALLACE-TIERNAN'},
  {type: 'CHMF-LIQ', mfr: 'BIF'},
  {type: 'CHMF-LIQ', mfr: 'CAPITAL CONTROLS'},
  {type: 'CHMF-LIQ', mfr: 'LMI'},
  {type: 'CHMF-LIQ', mfr: 'MASTERFLEX'},
  {type: 'CHMF-LIQ', mfr: 'PULSATRON'},
  {type: 'CHMF-LIQ', mfr: 'SEVERN TRENT'},
  {type: 'CHMF-LIQ', mfr: 'SIEMENS'},
  {type: 'CHMF-LIQ', mfr: 'STENNER'},
  {type: 'CHMF-LIQ', mfr: 'UNKNOWN'},
  {type: 'CHMF-LIQ', mfr: 'US FILTER'},
  {type: 'CHMF-LIQ', mfr: 'WALLACE-TIERNAN'},
  {type: 'CHMF-LIQ', mfr: 'WATSON-MARLOW'},
  {type: 'CNTRLPNL', mfr: 'ACCO'},
  {type: 'CNTRLPNL', mfr: 'ACS DESIGN'},
  {type: 'CNTRLPNL', mfr: 'ALLEN BRADLEY'},
  {type: 'CNTRLPNL', mfr: 'ALLIED COLLOIDS'},
  {type: 'CNTRLPNL', mfr: 'ASCO'},
  {type: 'CNTRLPNL', mfr: 'BENSHAW'},
  {type: 'CNTRLPNL', mfr: 'BIF'},
  {type: 'CNTRLPNL', mfr: 'BRISTOL'},
  {type: 'CNTRLPNL', mfr: 'BRISTOL BABCOCK'},
  {type: 'CNTRLPNL', mfr: 'CARGOCAIRE/MUNTERS'},
  {type: 'CNTRLPNL', mfr: 'CHALLENGER'},
  {type: 'CNTRLPNL', mfr: 'CLA-VAL'},
  {type: 'CNTRLPNL', mfr: 'CUTLER HAMMER'},
  {type: 'CNTRLPNL', mfr: 'EATON/CUTLER HAMMER'},
  {type: 'CNTRLPNL', mfr: 'FIRETROL'},
  {type: 'CNTRLPNL', mfr: 'FISCHER PORTER'},
  {type: 'CNTRLPNL', mfr: 'FLYGT'},
  {type: 'CNTRLPNL', mfr: 'FRANKLIN'},
  {type: 'CNTRLPNL', mfr: 'FRANKLIN ELECTRIC'},
  {type: 'CNTRLPNL', mfr: 'FURNAS'},
  {type: 'CNTRLPNL', mfr: 'GE'},
  {type: 'CNTRLPNL', mfr: 'GOLDEN ANDERSON'},
  {type: 'CNTRLPNL', mfr: 'GORMAN RUPP'},
  {type: 'CNTRLPNL', mfr: 'GRUNDFOS'},
  {type: 'CNTRLPNL', mfr: 'HALOGEN'},
  {type: 'CNTRLPNL', mfr: 'HOFFMAN'},
  {type: 'CNTRLPNL', mfr: 'HYDROMATIC'},
  {type: 'CNTRLPNL', mfr: 'ITE'},
  {type: 'CNTRLPNL', mfr: 'ITT'},
  {type: 'CNTRLPNL', mfr: 'LAMSON'},
  {type: 'CNTRLPNL', mfr: 'LEVITON'},
  {type: 'CNTRLPNL', mfr: 'MERRICK'},
  {type: 'CNTRLPNL', mfr: 'MILTON ROY'},
  {type: 'CNTRLPNL', mfr: 'MYERS'},
  {type: 'CNTRLPNL', mfr: 'PACO'},
  {type: 'CNTRLPNL', mfr: 'PRATT'},
  {type: 'CNTRLPNL', mfr: 'REVERE CONTROL SYSTEMS'},
  {type: 'CNTRLPNL', mfr: 'RUSS ELECTRIC'},
  {type: 'CNTRLPNL', mfr: 'SAFETRONICS'},
  {type: 'CNTRLPNL', mfr: 'SENTINEL-CALGON'},
  {type: 'CNTRLPNL', mfr: 'SIEMENS'},
  {type: 'CNTRLPNL', mfr: 'SMITH'},
  {type: 'CNTRLPNL', mfr: 'SMITH AND LOVELESS'},
  {type: 'CNTRLPNL', mfr: 'SQUARE D'},
  {type: 'CNTRLPNL', mfr: 'TIME MARK'},
  {type: 'CNTRLPNL', mfr: 'TITAN CONTROLS'},
  {type: 'CNTRLPNL', mfr: 'UNKNOWN'},
  {type: 'CNTRLPNL', mfr: 'US FILTER'},
  {type: 'CNTRLPNL', mfr: 'WARRICK'},
  {type: 'CNTRLPNL', mfr: 'WESTINGHOUSE'},
  {type: 'CNTRLPNL', mfr: 'WILO-DAVIS-EMU'},
  {type: 'CNTRLR', mfr: 'ALLEN BRADLEY'},
  {type: 'CNTRLR', mfr: 'AQUATROL'},
  {type: 'CNTRLR', mfr: 'AUTOMATION DIRECT'},
  {type: 'CNTRLR', mfr: 'BRISTOL BABCOCK'},
  {type: 'CNTRLR', mfr: 'FISCHER PORTER'},
  {type: 'CNTRLR', mfr: 'HONEYWELL'},
  {type: 'CNTRLR', mfr: 'QEI'},
  {type: 'CNTRLR', mfr: 'UNKNOWN'},
  {type: 'CNTRLR', mfr: 'WALLACE-TIERNAN'},
  {type: 'CO', mfr: 'UNKNOWN'},
  {type: 'COLLSYS', mfr: 'UNKNOWN'},
  {type: 'COMM-FWL', mfr: 'FORTINET'},
  {type: 'COMM-FWL', mfr: 'MDS'},
  {type: 'COMM-FWL', mfr: 'MULTITECH INDUSTRIES'},
  {type: 'COMM-FWL', mfr: 'UNKNOWN'},
  {type: 'COMM-MOD', mfr: 'B-B ELECTRONICS'},
  {type: 'COMM-MOD', mfr: 'BLACK BOX'},
  {type: 'COMM-MOD', mfr: 'BRISTOL BABCOCK'},
  {type: 'COMM-MOD', mfr: 'CISCO'},
  {type: 'COMM-MOD', mfr: 'MDS'},
  {type: 'COMM-MOD', mfr: 'MOTOROLA'},
  {type: 'COMM-MOD', mfr: 'RAYLAN'},
  {type: 'COMM-MOD', mfr: 'SIERRA WIRELESS'},
  {type: 'COMM-MOD', mfr: 'UNKNOWN'},
  {type: 'COMM-RAD', mfr: 'BRISTOL BABCOCK'},
  {type: 'COMM-RAD', mfr: 'CAMBIUM'},
  {type: 'COMM-RAD', mfr: 'CONTROLWAVE'},
  {type: 'COMM-RAD', mfr: 'DATA-LINC'},
  {type: 'COMM-RAD', mfr: 'FREEWAVE'},
  {type: 'COMM-RAD', mfr: 'GE-MDS'},
  {type: 'COMM-RAD', mfr: 'MDS'},
  {type: 'COMM-RAD', mfr: 'MOTOROLA'},
  {type: 'COMM-RAD', mfr: 'REPCO'},
  {type: 'COMM-RAD', mfr: 'UNKNOWN'},
  {type: 'COMM-RAD', mfr: 'XETAWAVE'},
  {type: 'COMM-RTR', mfr: 'BLACK BOX'},
  {type: 'COMM-RTR', mfr: 'CISCO'},
  {type: 'COMM-RTR', mfr: 'MDS'},
  {type: 'COMM-RTR', mfr: 'UNKNOWN'},
  {type: 'COMM-SW', mfr: 'ALLEN BRADLEY'},
  {type: 'COMM-SW', mfr: 'BLACK BOX'},
  {type: 'COMM-SW', mfr: 'CISCO'},
  {type: 'COMM-SW', mfr: 'HIRSCHMANN'},
  {type: 'COMM-SW', mfr: 'MDS'},
  {type: 'COMM-SW', mfr: 'UNKNOWN'},
  {type: 'COMM-TEL', mfr: 'B-B ELECTRONICS'},
  {type: 'COMM-TEL', mfr: 'BLACK BOX'},
  {type: 'COMM-TEL', mfr: 'BRISTOL BABCOCK'},
  {type: 'COMM-TEL', mfr: 'CISCO'},
  {type: 'COMM-TEL', mfr: 'ICX-DAQ ELECTRONICS'},
  {type: 'COMM-TEL', mfr: 'MDS'},
  {type: 'COMM-TEL', mfr: 'MOTOROLA'},
  {type: 'COMM-TEL', mfr: 'OPTIMUM CONTROLS'},
  {type: 'COMM-TEL', mfr: 'QEI'},
  {type: 'COMM-TEL', mfr: 'RACO'},
  {type: 'COMM-TEL', mfr: 'RADIONICS'},
  {type: 'COMM-TEL', mfr: 'SENSAPHONE'},
  {type: 'COMM-TEL', mfr: 'UNKNOWN'},
  {type: 'COMP', mfr: 'CAMBELL HAUSFIELD'},
  {type: 'COMP', mfr: 'CHALLENGER'},
  {type: 'COMP', mfr: 'CHAMPION'},
  {type: 'COMP', mfr: 'COPCO'},
  {type: 'COMP', mfr: 'DAYTON'},
  {type: 'COMP', mfr: 'EMGLO'},
  {type: 'COMP', mfr: 'FORD MOTOR COMPANY'},
  {type: 'COMP', mfr: 'GARDNER DENVER'},
  {type: 'COMP', mfr: 'GAST'},
  {type: 'COMP', mfr: 'INGERSOL RAND'},
  {type: 'COMP', mfr: 'ITT'},
  {type: 'COMP', mfr: 'MAXUS'},
  {type: 'COMP', mfr: 'MIDWEST'},
  {type: 'COMP', mfr: 'QUINCY'},
  {type: 'COMP', mfr: 'RIETSCHE THOMES'},
  {type: 'COMP', mfr: 'SPEEDAIRE'},
  {type: 'COMP', mfr: 'SULLAIR'},
  {type: 'COMP', mfr: 'SULLIVAN-PALATEK'},
  {type: 'COMP', mfr: 'THOMAS'},
  {type: 'COMP', mfr: 'UNKNOWN'},
  {type: 'COMP', mfr: 'WORTHINGTON'},
  {type: 'CONTACTR', mfr: 'ABB'},
  {type: 'CONTACTR', mfr: 'ALLEN BRADLEY'},
  {type: 'CONTACTR', mfr: 'ASCO'},
  {type: 'CONTACTR', mfr: 'CUTLER HAMMER'},
  {type: 'CONTACTR', mfr: 'EATON/CUTLER HAMMER'},
  {type: 'CONTACTR', mfr: 'GE'},
  {type: 'CONTACTR', mfr: 'HOFFMAN'},
  {type: 'CONTACTR', mfr: 'MITSUBISHI'},
  {type: 'CONTACTR', mfr: 'SIEMENS'},
  {type: 'CONTACTR', mfr: 'SPRECHER-SCHUH'},
  {type: 'CONTACTR', mfr: 'SQUARE D'},
  {type: 'CONTACTR', mfr: 'TELEMECANIQUE'},
  {type: 'CONTACTR', mfr: 'UNKNOWN'},
  {type: 'CONTACTR', mfr: 'WESTINGHOUSE'},
  {type: 'CONTAIN', mfr: 'CHEM-TAINER'},
  {type: 'CONTAIN', mfr: 'EAGLE'},
  {type: 'CONTAIN', mfr: 'ENPAC'},
  {type: 'CONTAIN', mfr: 'POLYPROCESSING'},
  {type: 'CONTAIN', mfr: 'UNKNOWN'},
  {type: 'CONVEYOR', mfr: 'OLIVER'},
  {type: 'CONVEYOR', mfr: 'UNKNOWN'},
  {type: 'DAM', mfr: 'UNKNOWN'},
  {type: 'DISTSYS', mfr: 'UNKNOWN'},
  {type: 'DISTTOOL', mfr: 'FISHER SCIENTIFIC'},
  {type: 'DISTTOOL', mfr: 'UNKNOWN'},
  {type: 'DISTTOOL', mfr: 'VIVAX-METROTECH'},
  {type: 'ELEVATOR', mfr: 'DOVER'},
  {type: 'ELEVATOR', mfr: 'OTIS'},
  {type: 'ELEVATOR', mfr: 'UNKNOWN'},
  {type: 'ELIGHT', mfr: 'BRADLEY'},
  {type: 'ELIGHT', mfr: 'DUALITE'},
  {type: 'ELIGHT', mfr: 'EMERGI-LITE'},
  {type: 'ELIGHT', mfr: 'EXIDE'},
  {type: 'ELIGHT', mfr: 'ISOLITE'},
  {type: 'ELIGHT', mfr: 'LIGHTALARMS ELECTRONICS'},
  {type: 'ELIGHT', mfr: 'LITHONIA'},
  {type: 'ELIGHT', mfr: 'PHILIPS-MCPHILBEN'},
  {type: 'ELIGHT', mfr: 'SURE-LITES'},
  {type: 'ELIGHT', mfr: 'UNKNOWN'},
  {type: 'ENG', mfr: 'BALDOR'},
  {type: 'ENG', mfr: 'BRIGGS-STRATTON'},
  {type: 'ENG', mfr: 'CATERPILLAR'},
  {type: 'ENG', mfr: 'CHEVROLET'},
  {type: 'ENG', mfr: 'CUMMINS'},
  {type: 'ENG', mfr: 'DETROIT'},
  {type: 'ENG', mfr: 'ENERGY DYNAMICS'},
  {type: 'ENG', mfr: 'FORD MOTOR COMPANY'},
  {type: 'ENG', mfr: 'GE'},
  {type: 'ENG', mfr: 'GENERAC'},
  {type: 'ENG', mfr: 'GUARDIAN'},
  {type: 'ENG', mfr: 'HOMELITE'},
  {type: 'ENG', mfr: 'HONDA'},
  {type: 'ENG', mfr: 'INGERSOL RAND'},
  {type: 'ENG', mfr: 'INTERNATIONAL'},
  {type: 'ENG', mfr: 'JOHN DEERE'},
  {type: 'ENG', mfr: 'KATOLIGHT'},
  {type: 'ENG', mfr: 'KOHLER'},
  {type: 'ENG', mfr: 'KUBOTA'},
  {type: 'ENG', mfr: 'MAXI POWER'},
  {type: 'ENG', mfr: 'MITSUBISHI'},
  {type: 'ENG', mfr: 'OLYMPLAN'},
  {type: 'ENG', mfr: 'ONAN'},
  {type: 'ENG', mfr: 'PERKINS'},
  {type: 'ENG', mfr: 'TECUMSEH'},
  {type: 'ENG', mfr: 'TORO'},
  {type: 'ENG', mfr: 'UNKNOWN'},
  {type: 'ENG', mfr: 'WAUKESHA'},
  {type: 'ENG', mfr: 'WHITE'},
  {type: 'ENG', mfr: 'WINCO'},
  {type: 'ENG', mfr: 'WISCONSIN'},
  {type: 'EYEWASH', mfr: 'BRADLEY'},
  {type: 'EYEWASH', mfr: 'DAYTON'},
  {type: 'EYEWASH', mfr: 'ENCON'},
  {type: 'EYEWASH', mfr: 'FENDALL'},
  {type: 'EYEWASH', mfr: 'FEUDALL CO'},
  {type: 'EYEWASH', mfr: 'GUARDIAN'},
  {type: 'EYEWASH', mfr: 'HAWS'},
  {type: 'EYEWASH', mfr: 'NORTH'},
  {type: 'EYEWASH', mfr: 'SCIENCEWARE'},
  {type: 'EYEWASH', mfr: 'SPEAKMAN'},
  {type: 'EYEWASH', mfr: 'UNKNOWN'},
  {type: 'FACILITY', mfr: 'ABB'},
  {type: 'FACILITY', mfr: 'AMERICAN STD'},
  {type: 'FACILITY', mfr: 'UNKNOWN'},
  {type: 'FIRE-AL', mfr: 'ADT'},
  {type: 'FIRE-AL', mfr: 'AMEREX CORP'},
  {type: 'FIRE-AL', mfr: 'GE'},
  {type: 'FIRE-AL', mfr: 'GENTEX'},
  {type: 'FIRE-AL', mfr: 'GENTEX CORP'},
  {type: 'FIRE-AL', mfr: 'KIDDE'},
  {type: 'FIRE-AL', mfr: 'NAPCO'},
  {type: 'FIRE-AL', mfr: 'SIEMENS'},
  {type: 'FIRE-AL', mfr: 'SIMPLEX'},
  {type: 'FIRE-AL', mfr: 'UNKNOWN'},
  {type: 'FIRE-AL', mfr: 'VIKING'},
  {type: 'FIRE-EX', mfr: 'AMEREX CORP'},
  {type: 'FIRE-EX', mfr: 'ANSUL-SCNTRY'},
  {type: 'FIRE-EX', mfr: 'BADGER'},
  {type: 'FIRE-EX', mfr: 'BROOKS'},
  {type: 'FIRE-EX', mfr: 'BUCKEYE'},
  {type: 'FIRE-EX', mfr: 'FLAG FIRE'},
  {type: 'FIRE-EX', mfr: 'GENERAL FIRE EX CORP'},
  {type: 'FIRE-EX', mfr: 'GETZ'},
  {type: 'FIRE-EX', mfr: 'KIDDE'},
  {type: 'FIRE-EX', mfr: 'PEM ALL'},
  {type: 'FIRE-EX', mfr: 'SIMPLEX'},
  {type: 'FIRE-EX', mfr: 'UNKNOWN'},
  {type: 'FIRE-SUP', mfr: 'ADT'},
  {type: 'FIRE-SUP', mfr: 'GENERAL FIRE EX CORP'},
  {type: 'FIRE-SUP', mfr: 'SIMPLEX'},
  {type: 'FIRE-SUP', mfr: 'UNKNOWN'},
  {type: 'FIRE-SUP', mfr: 'VIKING'},
  {type: 'FLO-MET', mfr: 'ABB'},
  {type: 'FLO-MET', mfr: 'BADGER'},
  {type: 'FLO-MET', mfr: 'BEECO-HERSEY'},
  {type: 'FLO-MET', mfr: 'BIF'},
  {type: 'FLO-MET', mfr: 'BRISTOL'},
  {type: 'FLO-MET', mfr: 'BRISTOL BABCOCK'},
  {type: 'FLO-MET', mfr: 'CAPITAL CONTROLS'},
  {type: 'FLO-MET', mfr: 'DANFOSS'},
  {type: 'FLO-MET', mfr: 'DYNASONICS'},
  {type: 'FLO-MET', mfr: 'EASTECH'},
  {type: 'FLO-MET', mfr: 'EMERSON'},
  {type: 'FLO-MET', mfr: 'ENDRESS-HAUSER'},
  {type: 'FLO-MET', mfr: 'FISCHER PORTER'},
  {type: 'FLO-MET', mfr: 'FLOWMOTION'},
  {type: 'FLO-MET', mfr: 'FOXBORO'},
  {type: 'FLO-MET', mfr: 'GREYLINE INSTRUMENTS'},
  {type: 'FLO-MET', mfr: 'HACH'},
  {type: 'FLO-MET', mfr: 'HOFFER'},
  {type: 'FLO-MET', mfr: 'INFILCO-DEGREMONT'},
  {type: 'FLO-MET', mfr: 'KING INSTRUMENT'},
  {type: 'FLO-MET', mfr: 'KROHNE'},
  {type: 'FLO-MET', mfr: 'MARSH MCBIRNEY'},
  {type: 'FLO-MET', mfr: 'MCCROMETER'},
  {type: 'FLO-MET', mfr: 'MICROMOTION'},
  {type: 'FLO-MET', mfr: 'NEPTUNE'},
  {type: 'FLO-MET', mfr: 'NORGAS'},
  {type: 'FLO-MET', mfr: 'NUSONICS-MESA'},
  {type: 'FLO-MET', mfr: 'PFS'},
  {type: 'FLO-MET', mfr: 'PRATT'},
  {type: 'FLO-MET', mfr: 'PRECISION'},
  {type: 'FLO-MET', mfr: 'ROSEMOUNT'},
  {type: 'FLO-MET', mfr: 'SEAMETRICS'},
  {type: 'FLO-MET', mfr: 'SENSUS'},
  {type: 'FLO-MET', mfr: 'SIEMENS'},
  {type: 'FLO-MET', mfr: 'SIGMA'},
  {type: 'FLO-MET', mfr: 'SIMPLEX'},
  {type: 'FLO-MET', mfr: 'SPARLING'},
  {type: 'FLO-MET', mfr: 'SWAGELOK'},
  {type: 'FLO-MET', mfr: 'UNKNOWN'},
  {type: 'FLO-MET', mfr: 'US FILTER'},
  {type: 'FLO-MET', mfr: 'WATER SPECIALTIES'},
  {type: 'FLO-WEIR', mfr: 'INVENTRON'},
  {type: 'FLO-WEIR', mfr: 'SIEMENS'},
  {type: 'FLO-WEIR', mfr: 'UNKNOWN'},
  {type: 'GEARBOX', mfr: 'BONFIGLIOLI'},
  {type: 'GEARBOX', mfr: 'DELROYD'},
  {type: 'GEARBOX', mfr: 'DODGE'},
  {type: 'GEARBOX', mfr: 'ENVIREX'},
  {type: 'GEARBOX', mfr: 'FALK REXNORD'},
  {type: 'GEARBOX', mfr: 'FMC'},
  {type: 'GEARBOX', mfr: 'LIGHTNIN-SPX'},
  {type: 'GEARBOX', mfr: 'LINK-BELT REX NORD'},
  {type: 'GEARBOX', mfr: 'NORD GEAR'},
  {type: 'GEARBOX', mfr: 'PHILADELPHIA'},
  {type: 'GEARBOX', mfr: 'RELIANCE'},
  {type: 'GEARBOX', mfr: 'SEW'},
  {type: 'GEARBOX', mfr: 'UNKNOWN'},
  {type: 'GEARBOX', mfr: 'WINFIELD H. SMITH'},
  {type: 'GEN', mfr: 'ALPS TECHNOLOGY'},
  {type: 'GEN', mfr: 'BALDOR'},
  {type: 'GEN', mfr: 'BRIGGS-STRATTON'},
  {type: 'GEN', mfr: 'CATERPILLAR'},
  {type: 'GEN', mfr: 'CHEVROLET'},
  {type: 'GEN', mfr: 'COPCO'},
  {type: 'GEN', mfr: 'CORNELL'},
  {type: 'GEN', mfr: 'CUMMINS'},
  {type: 'GEN', mfr: 'DELCO-REMY'},
  {type: 'GEN', mfr: 'DETROIT'},
  {type: 'GEN', mfr: 'ENERGY DYNAMICS'},
  {type: 'GEN', mfr: 'FORD MOTOR COMPANY'},
  {type: 'GEN', mfr: 'GE'},
  {type: 'GEN', mfr: 'GENERAC'},
  {type: 'GEN', mfr: 'GUARDIAN'},
  {type: 'GEN', mfr: 'HOMELITE'},
  {type: 'GEN', mfr: 'HONDA'},
  {type: 'GEN', mfr: 'INGERSOL RAND'},
  {type: 'GEN', mfr: 'INTERNATIONAL'},
  {type: 'GEN', mfr: 'JOHN DEERE'},
  {type: 'GEN', mfr: 'KATOLIGHT'},
  {type: 'GEN', mfr: 'KOHLER'},
  {type: 'GEN', mfr: 'KUBOTA'},
  {type: 'GEN', mfr: 'MAGNAPLUS'},
  {type: 'GEN', mfr: 'MARATHON'},
  {type: 'GEN', mfr: 'MAXI POWER'},
  {type: 'GEN', mfr: 'MITSUBISHI'},
  {type: 'GEN', mfr: 'OLYMPLAN'},
  {type: 'GEN', mfr: 'ONAN'},
  {type: 'GEN', mfr: 'PERKINS'},
  {type: 'GEN', mfr: 'POWERGUARD'},
  {type: 'GEN', mfr: 'SAMLEX'},
  {type: 'GEN', mfr: 'STAMFORD'},
  {type: 'GEN', mfr: 'TECUMSEH'},
  {type: 'GEN', mfr: 'TORO'},
  {type: 'GEN', mfr: 'UNKNOWN'},
  {type: 'GEN', mfr: 'WAUKESHA'},
  {type: 'GEN', mfr: 'WINCO'},
  {type: 'GEN', mfr: 'WISCONSIN'},
  {type: 'GMAIN', mfr: 'UNKNOWN'},
  {type: 'GRINDER', mfr: 'JWC ENVIRONMENTAL'},
  {type: 'GRINDER', mfr: 'MOYNO'},
  {type: 'GRINDER', mfr: 'MYERS'},
  {type: 'GRINDER', mfr: 'SEW'},
  {type: 'GRINDER', mfr: 'TPI CORP'},
  {type: 'GRINDER', mfr: 'UNKNOWN'},
  {type: 'HOIST', mfr: 'ACCO'},
  {type: 'HOIST', mfr: 'AUTOCRANE'},
  {type: 'HOIST', mfr: 'BUDGIT'},
  {type: 'HOIST', mfr: 'CHESTER'},
  {type: 'HOIST', mfr: 'COFFING'},
  {type: 'HOIST', mfr: 'COLUMBUS MCKINNON'},
  {type: 'HOIST', mfr: 'DAVID ROUND'},
  {type: 'HOIST', mfr: 'DAYTON'},
  {type: 'HOIST', mfr: 'HARRINGTON'},
  {type: 'HOIST', mfr: 'KONECRANES'},
  {type: 'HOIST', mfr: 'LIFTMOORE'},
  {type: 'HOIST', mfr: 'MANNING-MAXWELL-MOORE'},
  {type: 'HOIST', mfr: 'MILLER'},
  {type: 'HOIST', mfr: 'R-M MATERIAL HANDLING'},
  {type: 'HOIST', mfr: 'UNKNOWN'},
  {type: 'HOIST', mfr: 'WRIGHT'},
  {type: 'HOIST', mfr: 'YALE'},
  {type: 'HVAC-CHL', mfr: 'AMERICAN STD'},
  {type: 'HVAC-CHL', mfr: 'BARD MFG'},
  {type: 'HVAC-CHL', mfr: 'CARRIER'},
  {type: 'HVAC-CHL', mfr: 'DOMETIC-DUOTHERM'},
  {type: 'HVAC-CHL', mfr: 'FASCO'},
  {type: 'HVAC-CHL', mfr: 'FRIGIDAIRE'},
  {type: 'HVAC-CHL', mfr: 'LENNOX'},
  {type: 'HVAC-CHL', mfr: 'LIEBERT'},
  {type: 'HVAC-CHL', mfr: 'TRANE'},
  {type: 'HVAC-CHL', mfr: 'UNKNOWN'},
  {type: 'HVAC-CMB', mfr: 'AMANA'},
  {type: 'HVAC-CMB', mfr: 'AMERICAN STD'},
  {type: 'HVAC-CMB', mfr: 'BARD MFG'},
  {type: 'HVAC-CMB', mfr: 'CARRIER'},
  {type: 'HVAC-CMB', mfr: 'EMERSON'},
  {type: 'HVAC-CMB', mfr: 'FRIGIDAIRE'},
  {type: 'HVAC-CMB', mfr: 'GE'},
  {type: 'HVAC-CMB', mfr: 'HONEYWELL'},
  {type: 'HVAC-CMB', mfr: 'LENNOX'},
  {type: 'HVAC-CMB', mfr: 'LIEBERT'},
  {type: 'HVAC-CMB', mfr: 'MITSUBISHI'},
  {type: 'HVAC-CMB', mfr: 'REZNOR'},
  {type: 'HVAC-CMB', mfr: 'TRANE'},
  {type: 'HVAC-CMB', mfr: 'UNKNOWN'},
  {type: 'HVAC-CMB', mfr: 'YORK'},
  {type: 'HVAC-DHM', mfr: 'AIR TECHNOLOGY'},
  {type: 'HVAC-DHM', mfr: 'AMANA'},
  {type: 'HVAC-DHM', mfr: 'BRY-AIR'},
  {type: 'HVAC-DHM', mfr: 'CARGOCAIRE/MUNTERS'},
  {type: 'HVAC-DHM', mfr: 'CROSLEY'},
  {type: 'HVAC-DHM', mfr: 'DAYTON'},
  {type: 'HVAC-DHM', mfr: 'DESERT-AIRE'},
  {type: 'HVAC-DHM', mfr: 'DRYOMATIC'},
  {type: 'HVAC-DHM', mfr: 'FANTECH'},
  {type: 'HVAC-DHM', mfr: 'FRIGIDAIRE'},
  {type: 'HVAC-DHM', mfr: 'HANKINSON'},
  {type: 'HVAC-DHM', mfr: 'KENMORE'},
  {type: 'HVAC-DHM', mfr: 'LIEBERT'},
  {type: 'HVAC-DHM', mfr: 'MITSUBISHI'},
  {type: 'HVAC-DHM', mfr: 'OASIS'},
  {type: 'HVAC-DHM', mfr: 'PENN VENTILATION'},
  {type: 'HVAC-DHM', mfr: 'UNKNOWN'},
  {type: 'HVAC-DHM', mfr: 'WHIRLPOOL'},
  {type: 'HVAC-EXC', mfr: 'BELL-GOSSETT'},
  {type: 'HVAC-EXC', mfr: 'TRANE'},
  {type: 'HVAC-EXC', mfr: 'UNKNOWN'},
  {type: 'HVAC-HTR', mfr: 'AMERICAN STD'},
  {type: 'HVAC-HTR', mfr: 'BARD MFG'},
  {type: 'HVAC-HTR', mfr: 'BEACON-MORRIS'},
  {type: 'HVAC-HTR', mfr: 'BURNHAM'},
  {type: 'HVAC-HTR', mfr: 'CADET'},
  {type: 'HVAC-HTR', mfr: 'CARRIER'},
  {type: 'HVAC-HTR', mfr: 'CHROMALOX'},
  {type: 'HVAC-HTR', mfr: 'COMFORT GLOW'},
  {type: 'HVAC-HTR', mfr: 'COOK'},
  {type: 'HVAC-HTR', mfr: 'DAYTON'},
  {type: 'HVAC-HTR', mfr: 'DRAVO'},
  {type: 'HVAC-HTR', mfr: 'EMERSON'},
  {type: 'HVAC-HTR', mfr: 'EMPIRE COMFORT SYS'},
  {type: 'HVAC-HTR', mfr: 'ENERCO'},
  {type: 'HVAC-HTR', mfr: 'FEDERAL PACIFIC'},
  {type: 'HVAC-HTR', mfr: 'FOSTORIA'},
  {type: 'HVAC-HTR', mfr: 'GE'},
  {type: 'HVAC-HTR', mfr: 'HEAT-FLO'},
  {type: 'HVAC-HTR', mfr: 'INDEECO'},
  {type: 'HVAC-HTR', mfr: 'ITT'},
  {type: 'HVAC-HTR', mfr: 'JANITROL'},
  {type: 'HVAC-HTR', mfr: 'LENNOX'},
  {type: 'HVAC-HTR', mfr: 'MARLEY ELEC'},
  {type: 'HVAC-HTR', mfr: 'MITSUBISHI'},
  {type: 'HVAC-HTR', mfr: 'MODINE'},
  {type: 'HVAC-HTR', mfr: 'NALCO'},
  {type: 'HVAC-HTR', mfr: 'NESBITTAIRE'},
  {type: 'HVAC-HTR', mfr: 'PEERLESS'},
  {type: 'HVAC-HTR', mfr: 'PENN VENTILATION'},
  {type: 'HVAC-HTR', mfr: 'POWERHOUSE'},
  {type: 'HVAC-HTR', mfr: 'QMARK'},
  {type: 'HVAC-HTR', mfr: 'REZNOR'},
  {type: 'HVAC-HTR', mfr: 'SINGER'},
  {type: 'HVAC-HTR', mfr: 'SQUARE D'},
  {type: 'HVAC-HTR', mfr: 'STERLING'},
  {type: 'HVAC-HTR', mfr: 'TEMPCO'},
  {type: 'HVAC-HTR', mfr: 'TPI CORP'},
  {type: 'HVAC-HTR', mfr: 'TRANE'},
  {type: 'HVAC-HTR', mfr: 'UNKNOWN'},
  {type: 'HVAC-HTR', mfr: 'VANGUARD HEATERS'},
  {type: 'HVAC-HTR', mfr: 'XERXES'},
  {type: 'HVAC-TWR', mfr: 'REZNOR'},
  {type: 'HVAC-TWR', mfr: 'UNKNOWN'},
  {type: 'HVAC-VNT', mfr: 'ACME'},
  {type: 'HVAC-VNT', mfr: 'ADVANCE'},
  {type: 'HVAC-VNT', mfr: 'AEROVENT'},
  {type: 'HVAC-VNT', mfr: 'ALLEN BRADLEY'},
  {type: 'HVAC-VNT', mfr: 'AO SMITH'},
  {type: 'HVAC-VNT', mfr: 'BALDOR'},
  {type: 'HVAC-VNT', mfr: 'BARBER COLMAN'},
  {type: 'HVAC-VNT', mfr: 'BARD MFG'},
  {type: 'HVAC-VNT', mfr: 'BELIMO'},
  {type: 'HVAC-VNT', mfr: 'BROAN'},
  {type: 'HVAC-VNT', mfr: 'CARRIER'},
  {type: 'HVAC-VNT', mfr: 'CENTRAL FAN'},
  {type: 'HVAC-VNT', mfr: 'CHELSEA'},
  {type: 'HVAC-VNT', mfr: 'COOK'},
  {type: 'HVAC-VNT', mfr: 'DAYTON'},
  {type: 'HVAC-VNT', mfr: 'DOMEX'},
  {type: 'HVAC-VNT', mfr: 'DURALAB'},
  {type: 'HVAC-VNT', mfr: 'EMERSON'},
  {type: 'HVAC-VNT', mfr: 'EMPIRE COMFORT SYS'},
  {type: 'HVAC-VNT', mfr: 'FANTECH'},
  {type: 'HVAC-VNT', mfr: 'FUMEX'},
  {type: 'HVAC-VNT', mfr: 'GE'},
  {type: 'HVAC-VNT', mfr: 'GREENHECK'},
  {type: 'HVAC-VNT', mfr: 'GREENTECH'},
  {type: 'HVAC-VNT', mfr: 'HARTZELL'},
  {type: 'HVAC-VNT', mfr: 'HEMCO'},
  {type: 'HVAC-VNT', mfr: 'ILG INDUSTRIES'},
  {type: 'HVAC-VNT', mfr: 'KANALFLAKT'},
  {type: 'HVAC-VNT', mfr: 'KEWAUNEE'},
  {type: 'HVAC-VNT', mfr: 'KEWAUNEE SCIENTIFIC'},
  {type: 'HVAC-VNT', mfr: 'LABCONOCO'},
  {type: 'HVAC-VNT', mfr: 'LASKO'},
  {type: 'HVAC-VNT', mfr: 'LEADER'},
  {type: 'HVAC-VNT', mfr: 'OMEGA'},
  {type: 'HVAC-VNT', mfr: 'PENN FAN'},
  {type: 'HVAC-VNT', mfr: 'PENN VENTILATION'},
  {type: 'HVAC-VNT', mfr: 'TRANE'},
  {type: 'HVAC-VNT', mfr: 'TSI-ALNOR'},
  {type: 'HVAC-VNT', mfr: 'UNKNOWN'},
  {type: 'HVAC-VNT', mfr: 'ZEPHYR'},
  {type: 'HVAC-WH', mfr: 'AMERICAN STD'},
  {type: 'HVAC-WH', mfr: 'AO SMITH'},
  {type: 'HVAC-WH', mfr: 'ARISTON THERMO'},
  {type: 'HVAC-WH', mfr: 'BRADFORD WHITE'},
  {type: 'HVAC-WH', mfr: 'DAYTON'},
  {type: 'HVAC-WH', mfr: 'EEMAX'},
  {type: 'HVAC-WH', mfr: 'GE'},
  {type: 'HVAC-WH', mfr: 'HUBBELL'},
  {type: 'HVAC-WH', mfr: 'INDEECO'},
  {type: 'HVAC-WH', mfr: 'LOCHINVAR'},
  {type: 'HVAC-WH', mfr: 'PEERLESS'},
  {type: 'HVAC-WH', mfr: 'PVI INDUSTRIES'},
  {type: 'HVAC-WH', mfr: 'RHEEM'},
  {type: 'HVAC-WH', mfr: 'RUUD'},
  {type: 'HVAC-WH', mfr: 'STATE INDUSTRIES'},
  {type: 'HVAC-WH', mfr: 'UNKNOWN'},
  {type: 'HVAC-WH', mfr: 'VANGUARD HEATERS'},
  {type: 'HVAC-WH', mfr: 'WHIRLPOOL'},
  {type: 'HYD', mfr: 'ABS'},
  {type: 'HYD', mfr: 'AMERICAN CAST IRON PIPE'},
  {type: 'HYD', mfr: 'AMERICAN DARLING'},
  {type: 'HYD', mfr: 'AMERICAN FLOW CONTROL'},
  {type: 'HYD', mfr: 'AMERICAN FOUNDRY'},
  {type: 'HYD', mfr: 'AP SMITH'},
  {type: 'HYD', mfr: 'CHAPMAN'},
  {type: 'HYD', mfr: 'CLOW'},
  {type: 'HYD', mfr: 'COREY'},
  {type: 'HYD', mfr: 'CRANE'},
  {type: 'HYD', mfr: 'DARLING'},
  {type: 'HYD', mfr: 'DRESSER'},
  {type: 'HYD', mfr: 'EAST JORDAN'},
  {type: 'HYD', mfr: 'ECLIPSE'},
  {type: 'HYD', mfr: 'EDDY'},
  {type: 'HYD', mfr: 'FRANKLIN HYDRANTS'},
  {type: 'HYD', mfr: 'GREENBERG'},
  {type: 'HYD', mfr: 'IOWA'},
  {type: 'HYD', mfr: 'JONES'},
  {type: 'HYD', mfr: 'KENMORE'},
  {type: 'HYD', mfr: 'KENNEDY'},
  {type: 'HYD', mfr: 'KUPFERLE'},
  {type: 'HYD', mfr: 'LONG BEACH'},
  {type: 'HYD', mfr: 'LUDLOW'},
  {type: 'HYD', mfr: 'M-H/MCWANE'},
  {type: 'HYD', mfr: 'MATHEWS'},
  {type: 'HYD', mfr: 'MICHIGAN'},
  {type: 'HYD', mfr: 'MUELLER'},
  {type: 'HYD', mfr: 'PACIFIC STATES'},
  {type: 'HYD', mfr: 'PENN-TROY'},
  {type: 'HYD', mfr: 'PRATT'},
  {type: 'HYD', mfr: 'PRATT-CADY'},
  {type: 'HYD', mfr: 'RD WOOD'},
  {type: 'HYD', mfr: 'RENSSELAER'},
  {type: 'HYD', mfr: 'RICH'},
  {type: 'HYD', mfr: 'SMITH'},
  {type: 'HYD', mfr: 'TCIW'},
  {type: 'HYD', mfr: 'TRAVERSE CITY'},
  {type: 'HYD', mfr: 'U.S. FOUNDRY'},
  {type: 'HYD', mfr: 'UNKNOWN'},
  {type: 'HYD', mfr: 'US PIPE'},
  {type: 'HYD', mfr: 'WATEROUS'},
  {type: 'HYD', mfr: 'WESTCOTT'},
  {type: 'HYD', mfr: 'WHARF'},
  {type: 'INDICATR', mfr: 'ACTION INSTRUMENTS'},
  {type: 'INDICATR', mfr: 'ASHCROFT'},
  {type: 'INDICATR', mfr: 'BANNER'},
  {type: 'INDICATR', mfr: 'BINMASTER'},
  {type: 'INDICATR', mfr: 'BKZ INSTRUMENTS'},
  {type: 'INDICATR', mfr: 'BRISTOL BABCOCK'},
  {type: 'INDICATR', mfr: 'CAPITAL'},
  {type: 'INDICATR', mfr: 'CAPITAL CONTROLS'},
  {type: 'INDICATR', mfr: 'DEVAR'},
  {type: 'INDICATR', mfr: 'DRAGER'},
  {type: 'INDICATR', mfr: 'DREXELBROOK'},
  {type: 'INDICATR', mfr: 'DWYER'},
  {type: 'INDICATR', mfr: 'ENDRESS-HAUSER'},
  {type: 'INDICATR', mfr: 'FLOW LINE'},
  {type: 'INDICATR', mfr: 'FLOWSERVE'},
  {type: 'INDICATR', mfr: 'FORCE FLOW'},
  {type: 'INDICATR', mfr: 'HACH'},
  {type: 'INDICATR', mfr: 'HONEYWELL'},
  {type: 'INDICATR', mfr: 'INVENTRON'},
  {type: 'INDICATR', mfr: 'KESSLER'},
  {type: 'INDICATR', mfr: 'MAGNATROL'},
  {type: 'INDICATR', mfr: 'MERCOID'},
  {type: 'INDICATR', mfr: 'MILLTRONICS'},
  {type: 'INDICATR', mfr: 'MKS INSTRUMENTS'},
  {type: 'INDICATR', mfr: 'PRECISION'},
  {type: 'INDICATR', mfr: 'RED LION CONTROLS'},
  {type: 'INDICATR', mfr: 'REGAL'},
  {type: 'INDICATR', mfr: 'ROSEMOUNT'},
  {type: 'INDICATR', mfr: 'SCHNEIDER ELECTRIC-APC'},
  {type: 'INDICATR', mfr: 'SENSUS'},
  {type: 'INDICATR', mfr: 'SIGMA'},
  {type: 'INDICATR', mfr: 'SIMPSON'},
  {type: 'INDICATR', mfr: 'UNKNOWN'},
  {type: 'INDICATR', mfr: 'VORNE'},
  {type: 'INDICATR', mfr: 'WIKA'},
  {type: 'INDICATR', mfr: 'WIZARD'},
  {type: 'INST-SW', mfr: 'ALLEN BRADLEY'},
  {type: 'INST-SW', mfr: 'ANCHOR SCIENTIFIC'},
  {type: 'INST-SW', mfr: 'ANDERSON INSTRUMENTS'},
  {type: 'INST-SW', mfr: 'ASCO'},
  {type: 'INST-SW', mfr: 'ASHCROFT'},
  {type: 'INST-SW', mfr: 'BARKSDALE'},
  {type: 'INST-SW', mfr: 'BINDICATOR'},
  {type: 'INST-SW', mfr: 'BRISTOL'},
  {type: 'INST-SW', mfr: 'BRISTOL BABCOCK'},
  {type: 'INST-SW', mfr: 'CAPITAL CONTROLS'},
  {type: 'INST-SW', mfr: 'DAYTON'},
  {type: 'INST-SW', mfr: 'DREXELBROOK'},
  {type: 'INST-SW', mfr: 'DWYER'},
  {type: 'INST-SW', mfr: 'ENDRESS-HAUSER'},
  {type: 'INST-SW', mfr: 'FLO-TECH'},
  {type: 'INST-SW', mfr: 'FLOW LINE'},
  {type: 'INST-SW', mfr: 'FOXBORO'},
  {type: 'INST-SW', mfr: 'FURNAS'},
  {type: 'INST-SW', mfr: 'GEMS'},
  {type: 'INST-SW', mfr: 'HACH'},
  {type: 'INST-SW', mfr: 'HONEYWELL'},
  {type: 'INST-SW', mfr: 'INTERMATIC'},
  {type: 'INST-SW', mfr: 'JOHNSON'},
  {type: 'INST-SW', mfr: 'JOHNSON CONTROLS'},
  {type: 'INST-SW', mfr: 'KOBOLD'},
  {type: 'INST-SW', mfr: 'LEED-NORTHRUP CO'},
  {type: 'INST-SW', mfr: 'MAGNATROL'},
  {type: 'INST-SW', mfr: 'MAGNETEK'},
  {type: 'INST-SW', mfr: 'MCCROMETER'},
  {type: 'INST-SW', mfr: 'MCDONNELL'},
  {type: 'INST-SW', mfr: 'MERCOID'},
  {type: 'INST-SW', mfr: 'MH'},
  {type: 'INST-SW', mfr: 'MILLTRONICS'},
  {type: 'INST-SW', mfr: 'MSA'},
  {type: 'INST-SW', mfr: 'OLIVER'},
  {type: 'INST-SW', mfr: 'OMRON'},
  {type: 'INST-SW', mfr: 'PEECO'},
  {type: 'INST-SW', mfr: 'POTTER'},
  {type: 'INST-SW', mfr: 'ROSEMOUNT'},
  {type: 'INST-SW', mfr: 'SEAMETRICS'},
  {type: 'INST-SW', mfr: 'SIEMENS'},
  {type: 'INST-SW', mfr: 'SQUARE D'},
  {type: 'INST-SW', mfr: 'UNKNOWN'},
  {type: 'INST-SW', mfr: 'VERDER'},
  {type: 'INST-SW', mfr: 'VICTAULIC'},
  {type: 'INST-SW', mfr: 'WARRICK'},
  {type: 'INST-SW', mfr: 'WIKA'},
  {type: 'KIT', mfr: 'ACME'},
  {type: 'KIT', mfr: 'CINTAS'},
  {type: 'KIT', mfr: 'MILLER'},
  {type: 'KIT', mfr: 'MSA'},
  {type: 'KIT', mfr: 'UNKNOWN'},
  {type: 'KIT', mfr: 'WATTS'},
  {type: 'KIT', mfr: 'ZEE MEDICAL'},
  {type: 'LABEQ', mfr: 'BARNSTEAD'},
  {type: 'LABEQ', mfr: 'BLAK-RAY'},
  {type: 'LABEQ', mfr: 'BLUE M'},
  {type: 'LABEQ', mfr: 'BOEKEL SCIENTIFIC'},
  {type: 'LABEQ', mfr: 'CORNING'},
  {type: 'LABEQ', mfr: 'FISHER SCIENTIFIC'},
  {type: 'LABEQ', mfr: 'FRIGIDAIRE'},
  {type: 'LABEQ', mfr: 'GE'},
  {type: 'LABEQ', mfr: 'GRIEVE'},
  {type: 'LABEQ', mfr: 'H-B INSTRUMENT'},
  {type: 'LABEQ', mfr: 'HACH'},
  {type: 'LABEQ', mfr: 'HUMBOLDT'},
  {type: 'LABEQ', mfr: 'IDEXX'},
  {type: 'LABEQ', mfr: 'KENMORE'},
  {type: 'LABEQ', mfr: 'KESSLER'},
  {type: 'LABEQ', mfr: 'LABCONOCO'},
  {type: 'LABEQ', mfr: 'LEICA'},
  {type: 'LABEQ', mfr: 'MAGIC CHEF'},
  {type: 'LABEQ', mfr: 'MARKET FORGE'},
  {type: 'LABEQ', mfr: 'MARVEL'},
  {type: 'LABEQ', mfr: 'METROHM'},
  {type: 'LABEQ', mfr: 'MILLIPORE'},
  {type: 'LABEQ', mfr: 'NAPCO'},
  {type: 'LABEQ', mfr: 'OHAUS'},
  {type: 'LABEQ', mfr: 'OLYMPUS'},
  {type: 'LABEQ', mfr: 'PHILPS-BIRD'},
  {type: 'LABEQ', mfr: 'PRECISION'},
  {type: 'LABEQ', mfr: 'QUINCY'},
  {type: 'LABEQ', mfr: 'REICHART'},
  {type: 'LABEQ', mfr: 'SHELDON'},
  {type: 'LABEQ', mfr: 'TELEDYNE'},
  {type: 'LABEQ', mfr: 'THERMO-ORION'},
  {type: 'LABEQ', mfr: 'TUTTNAUER'},
  {type: 'LABEQ', mfr: 'UNKNOWN'},
  {type: 'LABEQ', mfr: 'US FILTER'},
  {type: 'LABEQ', mfr: 'UVP'},
  {type: 'LABEQ', mfr: 'VWR SCIENTIFIC'},
  {type: 'LABEQ', mfr: 'WHIRLPOOL'},
  {type: 'LABEQ', mfr: 'WINDMERE'},
  {type: 'LABEQ', mfr: 'YAMATO'},
  {type: 'MH', mfr: 'UNKNOWN'},
  {type: 'MIXR', mfr: 'ABS'},
  {type: 'MIXR', mfr: 'CHEMINEER'},
  {type: 'MIXR', mfr: 'DAYTON'},
  {type: 'MIXR', mfr: 'FMC'},
  {type: 'MIXR', mfr: 'JMS-JIM MYERS EQUIP'},
  {type: 'MIXR', mfr: 'KOFLO'},
  {type: 'MIXR', mfr: 'KOMAX'},
  {type: 'MIXR', mfr: 'LANDIA'},
  {type: 'MIXR', mfr: 'LEESON'},
  {type: 'MIXR', mfr: 'LIGHTNIN-SPX'},
  {type: 'MIXR', mfr: 'MERRICK'},
  {type: 'MIXR', mfr: 'NEPTUNE'},
  {type: 'MIXR', mfr: 'PHILADELPHIA'},
  {type: 'MIXR', mfr: 'SEW'},
  {type: 'MIXR', mfr: 'SIEMENS'},
  {type: 'MIXR', mfr: 'STRANCO'},
  {type: 'MIXR', mfr: 'UNKNOWN'},
  {type: 'MIXR', mfr: 'US FILTER'},
  {type: 'MIXR', mfr: 'WINFIELD H. SMITH'},
  {type: 'MOT', mfr: 'ABS'},
  {type: 'MOT', mfr: 'ALLIS CHALMERS'},
  {type: 'MOT', mfr: 'ALLIS CHAMBERS'},
  {type: 'MOT', mfr: 'AMERICAN FAN'},
  {type: 'MOT', mfr: 'AMETEK'},
  {type: 'MOT', mfr: 'AO SMITH'},
  {type: 'MOT', mfr: 'ARMSTRONG'},
  {type: 'MOT', mfr: 'BALDOR'},
  {type: 'MOT', mfr: 'BELL-GOSSETT'},
  {type: 'MOT', mfr: 'CENTURY'},
  {type: 'MOT', mfr: 'CONTINENTAL'},
  {type: 'MOT', mfr: 'CORNELL'},
  {type: 'MOT', mfr: 'DAYTON'},
  {type: 'MOT', mfr: 'EBARA'},
  {type: 'MOT', mfr: 'EMERSON'},
  {type: 'MOT', mfr: 'FAIRBANKS'},
  {type: 'MOT', mfr: 'FLEX PRO'},
  {type: 'MOT', mfr: 'FLOWSERVE'},
  {type: 'MOT', mfr: 'FLYGT'},
  {type: 'MOT', mfr: 'FRANKLIN'},
  {type: 'MOT', mfr: 'FRANKLIN ELECTRIC'},
  {type: 'MOT', mfr: 'FURNAS'},
  {type: 'MOT', mfr: 'GE'},
  {type: 'MOT', mfr: 'GENERAL DYNAMICS'},
  {type: 'MOT', mfr: 'GORMAN RUPP'},
  {type: 'MOT', mfr: 'GOULDS'},
  {type: 'MOT', mfr: 'GRUNDFOS'},
  {type: 'MOT', mfr: 'HITACHI'},
  {type: 'MOT', mfr: 'INGERSOL RAND'},
  {type: 'MOT', mfr: 'ITT'},
  {type: 'MOT', mfr: 'KOLLMORGEN'},
  {type: 'MOT', mfr: 'LEESON'},
  {type: 'MOT', mfr: 'LIBERTY'},
  {type: 'MOT', mfr: 'LIGHTNIN-SPX'},
  {type: 'MOT', mfr: 'LINCOLN MOTORS'},
  {type: 'MOT', mfr: 'LMI'},
  {type: 'MOT', mfr: 'LOUIS ALLIS'},
  {type: 'MOT', mfr: 'MAC'},
  {type: 'MOT', mfr: 'MAGNETEK'},
  {type: 'MOT', mfr: 'MARATHON'},
  {type: 'MOT', mfr: 'MERRICK'},
  {type: 'MOT', mfr: 'MIDWEST'},
  {type: 'MOT', mfr: 'MONOFLO'},
  {type: 'MOT', mfr: 'MYERS'},
  {type: 'MOT', mfr: 'NORD GEAR'},
  {type: 'MOT', mfr: 'ORIENTAL MOTOR'},
  {type: 'MOT', mfr: 'PACO'},
  {type: 'MOT', mfr: 'PEABODY ENG'},
  {type: 'MOT', mfr: 'PEERLESS'},
  {type: 'MOT', mfr: 'PMSL'},
  {type: 'MOT', mfr: 'RELIANCE'},
  {type: 'MOT', mfr: 'REX MANUFACTURING'},
  {type: 'MOT', mfr: 'ROBBINS'},
  {type: 'MOT', mfr: 'SEW'},
  {type: 'MOT', mfr: 'SIEMENS'},
  {type: 'MOT', mfr: 'SMITH'},
  {type: 'MOT', mfr: 'SMITH AND LOVELESS'},
  {type: 'MOT', mfr: 'SPENCER'},
  {type: 'MOT', mfr: 'SQUARE D'},
  {type: 'MOT', mfr: 'STA-RITE-BERKELEY'},
  {type: 'MOT', mfr: 'STENNER'},
  {type: 'MOT', mfr: 'STERLING'},
  {type: 'MOT', mfr: 'TECO'},
  {type: 'MOT', mfr: 'TOSHIBA'},
  {type: 'MOT', mfr: 'UNKNOWN'},
  {type: 'MOT', mfr: 'US ELECTRIC'},
  {type: 'MOT', mfr: 'US MOTORS'},
  {type: 'MOT', mfr: 'US SELECT'},
  {type: 'MOT', mfr: 'WAGNER'},
  {type: 'MOT', mfr: 'WARNER ELECTRIC'},
  {type: 'MOT', mfr: 'WEG'},
  {type: 'MOT', mfr: 'WESTINGHOUSE'},
  {type: 'MOT', mfr: 'WILO-DAVIS-EMU'},
  {type: 'MOT', mfr: 'ZOELLER'},
  {type: 'MOTSTR', mfr: 'ABB'},
  {type: 'MOTSTR', mfr: 'ALLEN BRADLEY'},
  {type: 'MOTSTR', mfr: 'ALLIS CHAMBERS'},
  {type: 'MOTSTR', mfr: 'ASCO'},
  {type: 'MOTSTR', mfr: 'BALDOR'},
  {type: 'MOTSTR', mfr: 'BENSHAW'},
  {type: 'MOTSTR', mfr: 'CHALLENGER'},
  {type: 'MOTSTR', mfr: 'CUTLER HAMMER'},
  {type: 'MOTSTR', mfr: 'DAYNE'},
  {type: 'MOTSTR', mfr: 'EATON/CUTLER HAMMER'},
  {type: 'MOTSTR', mfr: 'FIRETROL'},
  {type: 'MOTSTR', mfr: 'FRANKLIN ELECTRIC'},
  {type: 'MOTSTR', mfr: 'FURNAS'},
  {type: 'MOTSTR', mfr: 'GE'},
  {type: 'MOTSTR', mfr: 'GRUNDFOS'},
  {type: 'MOTSTR', mfr: 'ITE'},
  {type: 'MOTSTR', mfr: 'LYNN'},
  {type: 'MOTSTR', mfr: 'MARATHON'},
  {type: 'MOTSTR', mfr: 'MITSUBISHI'},
  {type: 'MOTSTR', mfr: 'MOELLER'},
  {type: 'MOTSTR', mfr: 'ROBICON'},
  {type: 'MOTSTR', mfr: 'RONK'},
  {type: 'MOTSTR', mfr: 'SAFETRONICS'},
  {type: 'MOTSTR', mfr: 'SCHNEIDER ELECTRIC-APC'},
  {type: 'MOTSTR', mfr: 'SIEMENS'},
  {type: 'MOTSTR', mfr: 'SQUARE D'},
  {type: 'MOTSTR', mfr: 'TELEMECANIQUE'},
  {type: 'MOTSTR', mfr: 'TOSHIBA'},
  {type: 'MOTSTR', mfr: 'TPI CORP'},
  {type: 'MOTSTR', mfr: 'UNKNOWN'},
  {type: 'MOTSTR', mfr: 'US DRIVES'},
  {type: 'MOTSTR', mfr: 'WALLACE-TIERNAN'},
  {type: 'MOTSTR', mfr: 'WESTINGHOUSE'},
  {type: 'OIT', mfr: 'ALLEN BRADLEY'},
  {type: 'OIT', mfr: 'DELL'},
  {type: 'OIT', mfr: 'EZAUTOMATION'},
  {type: 'OIT', mfr: 'HP'},
  {type: 'OIT', mfr: 'RED LION CONTROLS'},
  {type: 'OIT', mfr: 'UNKNOWN'},
  {type: 'PC', mfr: 'ALLEN BRADLEY'},
  {type: 'PC', mfr: 'DELL'},
  {type: 'PC', mfr: 'DYNICS'},
  {type: 'PC', mfr: 'HP'},
  {type: 'PC', mfr: 'IBM'},
  {type: 'PC', mfr: 'UNKNOWN'},
  {type: 'PDMTOOL', mfr: 'BAKER'},
  {type: 'PDMTOOL', mfr: 'UNKNOWN'},
  {type: 'PHASECON', mfr: 'RONK'},
  {type: 'PHASECON', mfr: 'UNKNOWN'},
  {type: 'PMP-CENT', mfr: 'A-C PUMP'},
  {type: 'PMP-CENT', mfr: 'ABS'},
  {type: 'PMP-CENT', mfr: 'ADVANCE'},
  {type: 'PMP-CENT', mfr: 'ALLIS CHALMERS'},
  {type: 'PMP-CENT', mfr: 'ALLIS CHAMBERS'},
  {type: 'PMP-CENT', mfr: 'AO SMITH'},
  {type: 'PMP-CENT', mfr: 'ARMSTRONG'},
  {type: 'PMP-CENT', mfr: 'AURORA'},
  {type: 'PMP-CENT', mfr: 'AY MCDONALD'},
  {type: 'PMP-CENT', mfr: 'BAKER'},
  {type: 'PMP-CENT', mfr: 'BELL-GOSSETT'},
  {type: 'PMP-CENT', mfr: 'BERKLEY'},
  {type: 'PMP-CENT', mfr: 'BYRON JACKSON'},
  {type: 'PMP-CENT', mfr: 'CARRIER'},
  {type: 'PMP-CENT', mfr: 'CATERPILLAR'},
  {type: 'PMP-CENT', mfr: 'CHRISTENSEN'},
  {type: 'PMP-CENT', mfr: 'CLOW'},
  {type: 'PMP-CENT', mfr: 'CONTINENTAL'},
  {type: 'PMP-CENT', mfr: 'CORNELL'},
  {type: 'PMP-CENT', mfr: 'CRANE'},
  {type: 'PMP-CENT', mfr: 'CRANE BURKS'},
  {type: 'PMP-CENT', mfr: 'CRANE DEMING'},
  {type: 'PMP-CENT', mfr: 'CROKER WHEELER'},
  {type: 'PMP-CENT', mfr: 'CROWN'},
  {type: 'PMP-CENT', mfr: 'DAYTON'},
  {type: 'PMP-CENT', mfr: 'DELAVAL'},
  {type: 'PMP-CENT', mfr: 'DOBBS'},
  {type: 'PMP-CENT', mfr: 'DURCO'},
  {type: 'PMP-CENT', mfr: 'DURIRON'},
  {type: 'PMP-CENT', mfr: 'EBARA'},
  {type: 'PMP-CENT', mfr: 'ENVIROTECH'},
  {type: 'PMP-CENT', mfr: 'FAIRBANKS'},
  {type: 'PMP-CENT', mfr: 'FEDERAL PACIFIC'},
  {type: 'PMP-CENT', mfr: 'FINISH THOMPSON'},
  {type: 'PMP-CENT', mfr: 'FLOWAY'},
  {type: 'PMP-CENT', mfr: 'FLOWSERVE'},
  {type: 'PMP-CENT', mfr: 'FLYGT'},
  {type: 'PMP-CENT', mfr: 'FM'},
  {type: 'PMP-CENT', mfr: 'FRANKLIN ELECTRIC'},
  {type: 'PMP-CENT', mfr: 'G-L'},
  {type: 'PMP-CENT', mfr: 'GAST'},
  {type: 'PMP-CENT', mfr: 'GE'},
  {type: 'PMP-CENT', mfr: 'GORMAN RUPP'},
  {type: 'PMP-CENT', mfr: 'GOULDS'},
  {type: 'PMP-CENT', mfr: 'GRUNDFOS'},
  {type: 'PMP-CENT', mfr: 'HAZLETON'},
  {type: 'PMP-CENT', mfr: 'HIDROSTAL'},
  {type: 'PMP-CENT', mfr: 'HOMELITE'},
  {type: 'PMP-CENT', mfr: 'HONDA'},
  {type: 'PMP-CENT', mfr: 'HYDROMATIC'},
  {type: 'PMP-CENT', mfr: 'INGERSOL RAND'},
  {type: 'PMP-CENT', mfr: 'ITT'},
  {type: 'PMP-CENT', mfr: 'IWAKI'},
  {type: 'PMP-CENT', mfr: 'JOHNSON'},
  {type: 'PMP-CENT', mfr: 'KSB'},
  {type: 'PMP-CENT', mfr: 'LAYNE-BOWLER'},
  {type: 'PMP-CENT', mfr: 'LE COURTNEY'},
  {type: 'PMP-CENT', mfr: 'LENNOX'},
  {type: 'PMP-CENT', mfr: 'LIBERTY'},
  {type: 'PMP-CENT', mfr: 'LITTLE GIANT'},
  {type: 'PMP-CENT', mfr: 'LUTZ'},
  {type: 'PMP-CENT', mfr: 'MARATHON'},
  {type: 'PMP-CENT', mfr: 'MARCH'},
  {type: 'PMP-CENT', mfr: 'MILLIPORE'},
  {type: 'PMP-CENT', mfr: 'MILTON ROY'},
  {type: 'PMP-CENT', mfr: 'MONOFLO'},
  {type: 'PMP-CENT', mfr: 'MORSE'},
  {type: 'PMP-CENT', mfr: 'MOYNO'},
  {type: 'PMP-CENT', mfr: 'MUELLER'},
  {type: 'PMP-CENT', mfr: 'MYERS'},
  {type: 'PMP-CENT', mfr: 'NASH'},
  {type: 'PMP-CENT', mfr: 'NATIONAL PUMP CO'},
  {type: 'PMP-CENT', mfr: 'PACO'},
  {type: 'PMP-CENT', mfr: 'PATTERSON'},
  {type: 'PMP-CENT', mfr: 'PEERLESS'},
  {type: 'PMP-CENT', mfr: 'PENN VALLEY PUMP'},
  {type: 'PMP-CENT', mfr: 'PRICE PUMP'},
  {type: 'PMP-CENT', mfr: 'PUMPEX'},
  {type: 'PMP-CENT', mfr: 'RED JACKET'},
  {type: 'PMP-CENT', mfr: 'SERFILCO'},
  {type: 'PMP-CENT', mfr: 'SIMMONS PUMP'},
  {type: 'PMP-CENT', mfr: 'SJE-RHOMBUS'},
  {type: 'PMP-CENT', mfr: 'SMITH AND LOVELESS'},
  {type: 'PMP-CENT', mfr: 'SPENCER'},
  {type: 'PMP-CENT', mfr: 'STA-RITE-BERKELEY'},
  {type: 'PMP-CENT', mfr: 'SULZER'},
  {type: 'PMP-CENT', mfr: 'TACO'},
  {type: 'PMP-CENT', mfr: 'TEEL'},
  {type: 'PMP-CENT', mfr: 'UNKNOWN'},
  {type: 'PMP-CENT', mfr: 'US MOTORS'},
  {type: 'PMP-CENT', mfr: 'WACKER'},
  {type: 'PMP-CENT', mfr: 'WACKER NEUSON'},
  {type: 'PMP-CENT', mfr: 'WEIL'},
  {type: 'PMP-CENT', mfr: 'WEIR POWER AND INDUSTRIA'},
  {type: 'PMP-CENT', mfr: 'WEMCO'},
  {type: 'PMP-CENT', mfr: 'WESTINGHOUSE'},
  {type: 'PMP-CENT', mfr: 'WILO-DAVIS-EMU'},
  {type: 'PMP-CENT', mfr: 'WORTHINGTON'},
  {type: 'PMP-CENT', mfr: 'ZOELLER'},
  {type: 'PMP-GRND', mfr: 'ABS'},
  {type: 'PMP-GRND', mfr: 'CRANE'},
  {type: 'PMP-GRND', mfr: 'CRANE DEMING'},
  {type: 'PMP-GRND', mfr: 'CROWN'},
  {type: 'PMP-GRND', mfr: 'ENVIRONMENT ONE'},
  {type: 'PMP-GRND', mfr: 'FAIRBANKS'},
  {type: 'PMP-GRND', mfr: 'FLYGT'},
  {type: 'PMP-GRND', mfr: 'FRANKLIN ELECTRIC'},
  {type: 'PMP-GRND', mfr: 'GORMAN RUPP'},
  {type: 'PMP-GRND', mfr: 'GOULDS'},
  {type: 'PMP-GRND', mfr: 'HYDROMATIC'},
  {type: 'PMP-GRND', mfr: 'LIBERTY'},
  {type: 'PMP-GRND', mfr: 'MONOFLO'},
  {type: 'PMP-GRND', mfr: 'MOYNO'},
  {type: 'PMP-GRND', mfr: 'MYERS'},
  {type: 'PMP-GRND', mfr: 'SIMPLEX'},
  {type: 'PMP-GRND', mfr: 'UNKNOWN'},
  {type: 'PMP-GRND', mfr: 'ZOELLER'},
  {type: 'PMP-PD', mfr: 'ALYAN'},
  {type: 'PMP-PD', mfr: 'AO SMITH'},
  {type: 'PMP-PD', mfr: 'BLUE-WHITE INDUSTRIES'},
  {type: 'PMP-PD', mfr: 'CARTER'},
  {type: 'PMP-PD', mfr: 'CH AND E PUMPS'},
  {type: 'PMP-PD', mfr: 'COLE-PARMER'},
  {type: 'PMP-PD', mfr: 'DAYTON'},
  {type: 'PMP-PD', mfr: 'DURCO'},
  {type: 'PMP-PD', mfr: 'ENVIRONMENT ONE'},
  {type: 'PMP-PD', mfr: 'FLEX PRO'},
  {type: 'PMP-PD', mfr: 'FLOWMOTION'},
  {type: 'PMP-PD', mfr: 'G-L'},
  {type: 'PMP-PD', mfr: 'GAST'},
  {type: 'PMP-PD', mfr: 'GOULDS'},
  {type: 'PMP-PD', mfr: 'GRUNDFOS'},
  {type: 'PMP-PD', mfr: 'HONDA'},
  {type: 'PMP-PD', mfr: 'INGERSOL RAND'},
  {type: 'PMP-PD', mfr: 'ITT'},
  {type: 'PMP-PD', mfr: 'IWAKI'},
  {type: 'PMP-PD', mfr: 'JAC'},
  {type: 'PMP-PD', mfr: 'JESCO'},
  {type: 'PMP-PD', mfr: 'LAKESIDE'},
  {type: 'PMP-PD', mfr: 'LMI'},
  {type: 'PMP-PD', mfr: 'M-D PNEUMATICS'},
  {type: 'PMP-PD', mfr: 'MARATHON'},
  {type: 'PMP-PD', mfr: 'MARCH'},
  {type: 'PMP-PD', mfr: 'MASTERFLEX'},
  {type: 'PMP-PD', mfr: 'MILLIPORE'},
  {type: 'PMP-PD', mfr: 'MILROY'},
  {type: 'PMP-PD', mfr: 'MILTON ROY'},
  {type: 'PMP-PD', mfr: 'MONOFLO'},
  {type: 'PMP-PD', mfr: 'MOYNO'},
  {type: 'PMP-PD', mfr: 'NASH'},
  {type: 'PMP-PD', mfr: 'NETZSCH'},
  {type: 'PMP-PD', mfr: 'NGC'},
  {type: 'PMP-PD', mfr: 'PROMINENT'},
  {type: 'PMP-PD', mfr: 'PULSAFEEDER'},
  {type: 'PMP-PD', mfr: 'PULSAR'},
  {type: 'PMP-PD', mfr: 'PULSATRON'},
  {type: 'PMP-PD', mfr: 'ROBBINS'},
  {type: 'PMP-PD', mfr: 'SIEMENS'},
  {type: 'PMP-PD', mfr: 'STENNER'},
  {type: 'PMP-PD', mfr: 'STRANCO'},
  {type: 'PMP-PD', mfr: 'TEEL'},
  {type: 'PMP-PD', mfr: 'THERMO-ORION'},
  {type: 'PMP-PD', mfr: 'TUTHILL'},
  {type: 'PMP-PD', mfr: 'UNKNOWN'},
  {type: 'PMP-PD', mfr: 'US FILTER'},
  {type: 'PMP-PD', mfr: 'VERDER'},
  {type: 'PMP-PD', mfr: 'WACKER'},
  {type: 'PMP-PD', mfr: 'WALLACE-TIERNAN'},
  {type: 'PMP-PD', mfr: 'WARREN RUPP'},
  {type: 'PMP-PD', mfr: 'WATSON-MARLOW'},
  {type: 'PMP-PD', mfr: 'WOERNER'},
  {type: 'PPE-ARC', mfr: 'LITHONIA'},
  {type: 'PPE-ARC', mfr: 'NORTH'},
  {type: 'PPE-ARC', mfr: 'SALISBURY'},
  {type: 'PPE-ARC', mfr: 'UNKNOWN'},
  {type: 'PPE-FALL', mfr: 'MILLER'},
  {type: 'PPE-FALL', mfr: 'MSA'},
  {type: 'PPE-FALL', mfr: 'SALISBURY'},
  {type: 'PPE-FALL', mfr: 'TRACTEL'},
  {type: 'PPE-FALL', mfr: 'UNKNOWN'},
  {type: 'PPE-FLOT', mfr: 'UNKNOWN'},
  {type: 'PPE-RESP', mfr: 'DRAGER'},
  {type: 'PPE-RESP', mfr: 'MSA'},
  {type: 'PPE-RESP', mfr: 'NORTH'},
  {type: 'PPE-RESP', mfr: 'SCOTT'},
  {type: 'PPE-RESP', mfr: 'SURVIVAIR'},
  {type: 'PPE-RESP', mfr: 'UNKNOWN'},
  {type: 'PRESDMP', mfr: 'UNKNOWN'},
  {type: 'PRESDMP', mfr: 'WATTS'},
  {type: 'PRNTR', mfr: 'CANON'},
  {type: 'PRNTR', mfr: 'HP'},
  {type: 'PRNTR', mfr: 'KODAK'},
  {type: 'PRNTR', mfr: 'UNKNOWN'},
  {type: 'PVLV', mfr: 'A-T CONTROLS'},
  {type: 'PVLV', mfr: 'ALLIS CHALMERS'},
  {type: 'PVLV', mfr: 'ALLIS CHAMBERS'},
  {type: 'PVLV', mfr: 'AMERICAN CONE VALVE'},
  {type: 'PVLV', mfr: 'AMERICAN DARLING'},
  {type: 'PVLV', mfr: 'AMERICAN FLOW CONTROL'},
  {type: 'PVLV', mfr: 'AMERICAN STD'},
  {type: 'PVLV', mfr: 'AMES'},
  {type: 'PVLV', mfr: 'AP SMITH'},
  {type: 'PVLV', mfr: 'APCO'},
  {type: 'PVLV', mfr: 'APOLLO'},
  {type: 'PVLV', mfr: 'AQUATROL'},
  {type: 'PVLV', mfr: 'ASAHI/AMERICA'},
  {type: 'PVLV', mfr: 'ASCO'},
  {type: 'PVLV', mfr: 'ASHCROFT'},
  {type: 'PVLV', mfr: 'AUMA'},
  {type: 'PVLV', mfr: 'AVK'},
  {type: 'PVLV', mfr: 'BAILEY'},
  {type: 'PVLV', mfr: 'BECK'},
  {type: 'PVLV', mfr: 'BEECO-HERSEY'},
  {type: 'PVLV', mfr: 'BERMAD'},
  {type: 'PVLV', mfr: 'BIF'},
  {type: 'PVLV', mfr: 'BLACOH'},
  {type: 'PVLV', mfr: 'BRADLEY'},
  {type: 'PVLV', mfr: 'BRAY'},
  {type: 'PVLV', mfr: 'CAMERON-DEMCO'},
  {type: 'PVLV', mfr: 'CAPITAL CONTROLS'},
  {type: 'PVLV', mfr: 'CENTERLINE'},
  {type: 'PVLV', mfr: 'CHAPMAN'},
  {type: 'PVLV', mfr: 'CLA-VAL'},
  {type: 'PVLV', mfr: 'CLOW'},
  {type: 'PVLV', mfr: 'CONBRACO'},
  {type: 'PVLV', mfr: 'CRANE'},
  {type: 'PVLV', mfr: 'CRISPIN'},
  {type: 'PVLV', mfr: 'DANFOSS'},
  {type: 'PVLV', mfr: 'DARLING'},
  {type: 'PVLV', mfr: 'DEZURICK'},
  {type: 'PVLV', mfr: 'DRESSER'},
  {type: 'PVLV', mfr: 'EDDY'},
  {type: 'PVLV', mfr: 'EIM COMPANY'},
  {type: 'PVLV', mfr: 'FAIRBANKS'},
  {type: 'PVLV', mfr: 'FEBCO'},
  {type: 'PVLV', mfr: 'FLOMATIC'},
  {type: 'PVLV', mfr: 'FLYGT'},
  {type: 'PVLV', mfr: 'FMC'},
  {type: 'PVLV', mfr: 'FNW'},
  {type: 'PVLV', mfr: 'FONTAINE'},
  {type: 'PVLV', mfr: 'FORD METER BOX'},
  {type: 'PVLV', mfr: 'GF PIPING SYSTEMS'},
  {type: 'PVLV', mfr: 'GOLDEN ANDERSON'},
  {type: 'PVLV', mfr: 'GRIFFCO'},
  {type: 'PVLV', mfr: 'GRISWOLD'},
  {type: 'PVLV', mfr: 'GRUNDFOS'},
  {type: 'PVLV', mfr: 'HALOGEN'},
  {type: 'PVLV', mfr: 'HAMMOND'},
  {type: 'PVLV', mfr: 'HAYWARD'},
  {type: 'PVLV', mfr: 'HILLS-MCCANNA'},
  {type: 'PVLV', mfr: 'INLINE INDUSTRIES'},
  {type: 'PVLV', mfr: 'ITT FABRI-VALVE'},
  {type: 'PVLV', mfr: 'KATES-CUSTOM VLV CONCEPT'},
  {type: 'PVLV', mfr: 'KECKLEY'},
  {type: 'PVLV', mfr: 'KENNEDY'},
  {type: 'PVLV', mfr: 'KENSEAL'},
  {type: 'PVLV', mfr: 'KEYSTONE'},
  {type: 'PVLV', mfr: 'KUNKLE'},
  {type: 'PVLV', mfr: 'LEONARD'},
  {type: 'PVLV', mfr: 'LIMITORQUE'},
  {type: 'PVLV', mfr: 'LUDLOW'},
  {type: 'PVLV', mfr: 'M-H/MCWANE'},
  {type: 'PVLV', mfr: 'MAGNATROL'},
  {type: 'PVLV', mfr: 'MATCO NORCA'},
  {type: 'PVLV', mfr: 'MAX-AIR'},
  {type: 'PVLV', mfr: 'MCDONALD'},
  {type: 'PVLV', mfr: 'MCDONNELL'},
  {type: 'PVLV', mfr: 'METRAFLEX'},
  {type: 'PVLV', mfr: 'METSO-JAMESBURY'},
  {type: 'PVLV', mfr: 'MH'},
  {type: 'PVLV', mfr: 'MHV-F'},
  {type: 'PVLV', mfr: 'MILLIKEN'},
  {type: 'PVLV', mfr: 'MILTON ROY'},
  {type: 'PVLV', mfr: 'MILWAUKEE VALVE'},
  {type: 'PVLV', mfr: 'MUELLER'},
  {type: 'PVLV', mfr: 'NEPTUNE'},
  {type: 'PVLV', mfr: 'NIBCO'},
  {type: 'PVLV', mfr: 'NIL-COR'},
  {type: 'PVLV', mfr: 'ORBINOX'},
  {type: 'PVLV', mfr: 'PENN-TROY'},
  {type: 'PVLV', mfr: 'PENTAIR'},
  {type: 'PVLV', mfr: 'PLAST-O-MATIC'},
  {type: 'PVLV', mfr: 'PRATT'},
  {type: 'PVLV', mfr: 'RED FLAG'},
  {type: 'PVLV', mfr: 'REGAL'},
  {type: 'PVLV', mfr: 'RENSSELAER'},
  {type: 'PVLV', mfr: 'ROCKWELL'},
  {type: 'PVLV', mfr: 'RODNEY HUNT'},
  {type: 'PVLV', mfr: 'ROLL SEAL'},
  {type: 'PVLV', mfr: 'ROSS'},
  {type: 'PVLV', mfr: 'SENSUS'},
  {type: 'PVLV', mfr: 'SEVERN TRENT'},
  {type: 'PVLV', mfr: 'SIEMENS'},
  {type: 'PVLV', mfr: 'SINGER'},
  {type: 'PVLV', mfr: 'SMITH'},
  {type: 'PVLV', mfr: 'SMITH AND LOVELESS'},
  {type: 'PVLV', mfr: 'SPEARS'},
  {type: 'PVLV', mfr: 'STOCKHAM'},
  {type: 'PVLV', mfr: 'SUREFLOW'},
  {type: 'PVLV', mfr: 'TCIW'},
  {type: 'PVLV', mfr: 'TECHNO VALVES'},
  {type: 'PVLV', mfr: 'TOYO VALVE'},
  {type: 'PVLV', mfr: 'TRIAC'},
  {type: 'PVLV', mfr: 'ULTRAFLO'},
  {type: 'PVLV', mfr: 'UNKNOWN'},
  {type: 'PVLV', mfr: 'US FILTER'},
  {type: 'PVLV', mfr: 'US PIPE'},
  {type: 'PVLV', mfr: 'VAL-MATIC'},
  {type: 'PVLV', mfr: 'VALVE AND PRIMER'},
  {type: 'PVLV', mfr: 'VICTAULIC'},
  {type: 'PVLV', mfr: 'VIKING'},
  {type: 'PVLV', mfr: 'WACO'},
  {type: 'PVLV', mfr: 'WADSWORTH'},
  {type: 'PVLV', mfr: 'WALLACE-TIERNAN'},
  {type: 'PVLV', mfr: 'WATERMAN'},
  {type: 'PVLV', mfr: 'WATEROUS'},
  {type: 'PVLV', mfr: 'WATSON-MCDANIEL'},
  {type: 'PVLV', mfr: 'WATTS'},
  {type: 'PVLV', mfr: 'WESTCOTT'},
  {type: 'PVLV', mfr: 'WHIPPS'},
  {type: 'PVLV', mfr: 'WILKINS-ZURN'},
  {type: 'PVLV', mfr: 'WILLAMETTE'},
  {type: 'PWRBRKR', mfr: 'ABB'},
  {type: 'PWRBRKR', mfr: 'ACME'},
  {type: 'PWRBRKR', mfr: 'ALLEN BRADLEY'},
  {type: 'PWRBRKR', mfr: 'BEST-UPS'},
  {type: 'PWRBRKR', mfr: 'CHALLENGER'},
  {type: 'PWRBRKR', mfr: 'CUTLER HAMMER'},
  {type: 'PWRBRKR', mfr: 'EATON/CUTLER HAMMER'},
  {type: 'PWRBRKR', mfr: 'EMERSON'},
  {type: 'PWRBRKR', mfr: 'ENVIRONMENT ONE'},
  {type: 'PWRBRKR', mfr: 'FURNAS'},
  {type: 'PWRBRKR', mfr: 'GE'},
  {type: 'PWRBRKR', mfr: 'GRUNDFOS'},
  {type: 'PWRBRKR', mfr: 'HAMMOND'},
  {type: 'PWRBRKR', mfr: 'HOFFMAN'},
  {type: 'PWRBRKR', mfr: 'ITE'},
  {type: 'PWRBRKR', mfr: 'MIDWEST'},
  {type: 'PWRBRKR', mfr: 'MURRAY'},
  {type: 'PWRBRKR', mfr: 'ONAN'},
  {type: 'PWRBRKR', mfr: 'RUSS ELECTRIC'},
  {type: 'PWRBRKR', mfr: 'SIEMENS'},
  {type: 'PWRBRKR', mfr: 'SMITH AND LOVELESS'},
  {type: 'PWRBRKR', mfr: 'SQUARE D'},
  {type: 'PWRBRKR', mfr: 'TELEMECANIQUE'},
  {type: 'PWRBRKR', mfr: 'UNKNOWN'},
  {type: 'PWRBRKR', mfr: 'WESTINGHOUSE'},
  {type: 'PWRCOND', mfr: 'AEROVOX'},
  {type: 'PWRCOND', mfr: 'ALLEN BRADLEY'},
  {type: 'PWRCOND', mfr: 'CHALLENGER'},
  {type: 'PWRCOND', mfr: 'COMMONWEALTH SPRAGUE'},
  {type: 'PWRCOND', mfr: 'CORNELL'},
  {type: 'PWRCOND', mfr: 'CUTLER HAMMER'},
  {type: 'PWRCOND', mfr: 'EATON/CUTLER HAMMER'},
  {type: 'PWRCOND', mfr: 'GE'},
  {type: 'PWRCOND', mfr: 'HOFFMAN'},
  {type: 'PWRCOND', mfr: 'LAMARCHE'},
  {type: 'PWRCOND', mfr: 'MYRON ZUCKER'},
  {type: 'PWRCOND', mfr: 'RONK'},
  {type: 'PWRCOND', mfr: 'SQUARE D'},
  {type: 'PWRCOND', mfr: 'TCI'},
  {type: 'PWRCOND', mfr: 'UNKNOWN'},
  {type: 'PWRCOND', mfr: 'VERSATEX'},
  {type: 'PWRCOND', mfr: 'WESTINGHOUSE'},
  {type: 'PWRDISC', mfr: 'ABB'},
  {type: 'PWRDISC', mfr: 'ALLEN BRADLEY'},
  {type: 'PWRDISC', mfr: 'ALLIS CHALMERS'},
  {type: 'PWRDISC', mfr: 'AMERICAN ELECTRICAL'},
  {type: 'PWRDISC', mfr: 'ASCO'},
  {type: 'PWRDISC', mfr: 'BEST-UPS'},
  {type: 'PWRDISC', mfr: 'CHALLENGER'},
  {type: 'PWRDISC', mfr: 'CLIPPER POWER SYS'},
  {type: 'PWRDISC', mfr: 'CUTLER HAMMER'},
  {type: 'PWRDISC', mfr: 'EATON/CUTLER HAMMER'},
  {type: 'PWRDISC', mfr: 'FEDERAL'},
  {type: 'PWRDISC', mfr: 'FEDERAL PACIFIC'},
  {type: 'PWRDISC', mfr: 'FRANKLIN'},
  {type: 'PWRDISC', mfr: 'FRANKLIN ELECTRIC'},
  {type: 'PWRDISC', mfr: 'GE'},
  {type: 'PWRDISC', mfr: 'GOULDS'},
  {type: 'PWRDISC', mfr: 'ITE'},
  {type: 'PWRDISC', mfr: 'LEVITON'},
  {type: 'PWRDISC', mfr: 'MET ED/GPU'},
  {type: 'PWRDISC', mfr: 'MTL INSTRUMENTS'},
  {type: 'PWRDISC', mfr: 'MURRAY'},
  {type: 'PWRDISC', mfr: 'ROBICON'},
  {type: 'PWRDISC', mfr: 'SCHNEIDER ELECTRIC-APC'},
  {type: 'PWRDISC', mfr: 'SIEMENS'},
  {type: 'PWRDISC', mfr: 'SPANG-MAGNETICS'},
  {type: 'PWRDISC', mfr: 'SQUARE D'},
  {type: 'PWRDISC', mfr: 'TRUMBULL'},
  {type: 'PWRDISC', mfr: 'UNKNOWN'},
  {type: 'PWRDISC', mfr: 'WADSWORTH'},
  {type: 'PWRDISC', mfr: 'WESTINGHOUSE'},
  {type: 'PWRFEEDR', mfr: 'ABB'},
  {type: 'PWRFEEDR', mfr: 'ALLEN BRADLEY'},
  {type: 'PWRFEEDR', mfr: 'CHALLENGER'},
  {type: 'PWRFEEDR', mfr: 'CUTLER HAMMER'},
  {type: 'PWRFEEDR', mfr: 'EATON/CUTLER HAMMER'},
  {type: 'PWRFEEDR', mfr: 'FEDERAL'},
  {type: 'PWRFEEDR', mfr: 'FURNAS'},
  {type: 'PWRFEEDR', mfr: 'GE'},
  {type: 'PWRFEEDR', mfr: 'HOFFMAN'},
  {type: 'PWRFEEDR', mfr: 'MET ED'},
  {type: 'PWRFEEDR', mfr: 'MET ED/GPU'},
  {type: 'PWRFEEDR', mfr: 'SIEMENS'},
  {type: 'PWRFEEDR', mfr: 'SMITH AND LOVELESS'},
  {type: 'PWRFEEDR', mfr: 'SQUARE D'},
  {type: 'PWRFEEDR', mfr: 'UNKNOWN'},
  {type: 'PWRMON', mfr: 'ABB'},
  {type: 'PWRMON', mfr: 'ALLEN BRADLEY'},
  {type: 'PWRMON', mfr: 'APT'},
  {type: 'PWRMON', mfr: 'CHALLENGER'},
  {type: 'PWRMON', mfr: 'CLIPPER POWER SYS'},
  {type: 'PWRMON', mfr: 'CUTLER HAMMER'},
  {type: 'PWRMON', mfr: 'DIVERSIFIED ELECTRONICS'},
  {type: 'PWRMON', mfr: 'E-MON'},
  {type: 'PWRMON', mfr: 'EATON/CUTLER HAMMER'},
  {type: 'PWRMON', mfr: 'FRANKLIN'},
  {type: 'PWRMON', mfr: 'FRANKLIN ELECTRIC'},
  {type: 'PWRMON', mfr: 'FURNAS'},
  {type: 'PWRMON', mfr: 'GE'},
  {type: 'PWRMON', mfr: 'INNOVATIVE TECH'},
  {type: 'PWRMON', mfr: 'INTERMATIC'},
  {type: 'PWRMON', mfr: 'ITE'},
  {type: 'PWRMON', mfr: 'LEVITON'},
  {type: 'PWRMON', mfr: 'SEL'},
  {type: 'PWRMON', mfr: 'SIEMENS'},
  {type: 'PWRMON', mfr: 'SIMPSON'},
  {type: 'PWRMON', mfr: 'SQUARE D'},
  {type: 'PWRMON', mfr: 'SYMCOM'},
  {type: 'PWRMON', mfr: 'TELEMECANIQUE'},
  {type: 'PWRMON', mfr: 'TIME MARK'},
  {type: 'PWRMON', mfr: 'UNKNOWN'},
  {type: 'PWRMON', mfr: 'WESTINGHOUSE'},
  {type: 'PWRPNL', mfr: 'ALLEN BRADLEY'},
  {type: 'PWRPNL', mfr: 'BEST-UPS'},
  {type: 'PWRPNL', mfr: 'CHALLENGER'},
  {type: 'PWRPNL', mfr: 'CUTLER HAMMER'},
  {type: 'PWRPNL', mfr: 'EATON/CUTLER HAMMER'},
  {type: 'PWRPNL', mfr: 'FEDERAL'},
  {type: 'PWRPNL', mfr: 'FEDERAL PACIFIC'},
  {type: 'PWRPNL', mfr: 'FURNAS'},
  {type: 'PWRPNL', mfr: 'GE'},
  {type: 'PWRPNL', mfr: 'GOULDS'},
  {type: 'PWRPNL', mfr: 'HOFFMAN'},
  {type: 'PWRPNL', mfr: 'ITE'},
  {type: 'PWRPNL', mfr: 'LEVITON'},
  {type: 'PWRPNL', mfr: 'MET ED'},
  {type: 'PWRPNL', mfr: 'MURRAY'},
  {type: 'PWRPNL', mfr: 'SIEMENS'},
  {type: 'PWRPNL', mfr: 'SQUARE D'},
  {type: 'PWRPNL', mfr: 'UNKNOWN'},
  {type: 'PWRPNL', mfr: 'WESTINGHOUSE'},
  {type: 'PWRRELAY', mfr: 'ABB'},
  {type: 'PWRRELAY', mfr: 'ALLEN BRADLEY'},
  {type: 'PWRRELAY', mfr: 'BASLER'},
  {type: 'PWRRELAY', mfr: 'BECKWITH'},
  {type: 'PWRRELAY', mfr: 'FLYGT'},
  {type: 'PWRRELAY', mfr: 'GE'},
  {type: 'PWRRELAY', mfr: 'LEVITON'},
  {type: 'PWRRELAY', mfr: 'SEL'},
  {type: 'PWRRELAY', mfr: 'SQUARE D'},
  {type: 'PWRRELAY', mfr: 'UNKNOWN'},
  {type: 'PWRSURG', mfr: 'ABB'},
  {type: 'PWRSURG', mfr: 'ALANTIC SCIENTIFIC'},
  {type: 'PWRSURG', mfr: 'ALLEN BRADLEY'},
  {type: 'PWRSURG', mfr: 'APT'},
  {type: 'PWRSURG', mfr: 'CLIPPER POWER SYS'},
  {type: 'PWRSURG', mfr: 'COOPER CROUSE-HINDS'},
  {type: 'PWRSURG', mfr: 'CUTLER HAMMER'},
  {type: 'PWRSURG', mfr: 'DELTA'},
  {type: 'PWRSURG', mfr: 'DITEK-TVSS'},
  {type: 'PWRSURG', mfr: 'EATON/CUTLER HAMMER'},
  {type: 'PWRSURG', mfr: 'FERRAZ SHAWMUT'},
  {type: 'PWRSURG', mfr: 'GE'},
  {type: 'PWRSURG', mfr: 'HOFFMAN'},
  {type: 'PWRSURG', mfr: 'HUBBELL'},
  {type: 'PWRSURG', mfr: 'INNOVATIVE TECH'},
  {type: 'PWRSURG', mfr: 'INTERMATIC'},
  {type: 'PWRSURG', mfr: 'ITE'},
  {type: 'PWRSURG', mfr: 'LEA INTERNATIONAL'},
  {type: 'PWRSURG', mfr: 'LEVITON'},
  {type: 'PWRSURG', mfr: 'MCG SURGE'},
  {type: 'PWRSURG', mfr: 'MTL INSTRUMENTS'},
  {type: 'PWRSURG', mfr: 'PHOENIX CONTACT'},
  {type: 'PWRSURG', mfr: 'SCHNEIDER ELECTRIC-APC'},
  {type: 'PWRSURG', mfr: 'SIEMENS'},
  {type: 'PWRSURG', mfr: 'SOLA'},
  {type: 'PWRSURG', mfr: 'SQUARE D'},
  {type: 'PWRSURG', mfr: 'SYMCOM'},
  {type: 'PWRSURG', mfr: 'TCI'},
  {type: 'PWRSURG', mfr: 'TRIPPLITE'},
  {type: 'PWRSURG', mfr: 'UNITED POWER'},
  {type: 'PWRSURG', mfr: 'UNKNOWN'},
  {type: 'RECORDER', mfr: 'AMETEK'},
  {type: 'RECORDER', mfr: 'BAILEY'},
  {type: 'RECORDER', mfr: 'BIF'},
  {type: 'RECORDER', mfr: 'BRISTOL'},
  {type: 'RECORDER', mfr: 'BRISTOL BABCOCK'},
  {type: 'RECORDER', mfr: 'DICKSON'},
  {type: 'RECORDER', mfr: 'DWYER'},
  {type: 'RECORDER', mfr: 'ENDRESS-HAUSER'},
  {type: 'RECORDER', mfr: 'FISCHER PORTER'},
  {type: 'RECORDER', mfr: 'HACH'},
  {type: 'RECORDER', mfr: 'HONEYWELL'},
  {type: 'RECORDER', mfr: 'LEED-NORTHRUP CO'},
  {type: 'RECORDER', mfr: 'MISSION COMMUNICATIONS'},
  {type: 'RECORDER', mfr: 'PARTLOW'},
  {type: 'RECORDER', mfr: 'SIGMA'},
  {type: 'RECORDER', mfr: 'TELOG'},
  {type: 'RECORDER', mfr: 'UNKNOWN'},
  {type: 'RTU-PLC', mfr: 'ALLEN BRADLEY'},
  {type: 'RTU-PLC', mfr: 'AUTOMATION DIRECT'},
  {type: 'RTU-PLC', mfr: 'BRISTOL'},
  {type: 'RTU-PLC', mfr: 'BRISTOL BABCOCK'},
  {type: 'RTU-PLC', mfr: 'CONTROLWAVE'},
  {type: 'RTU-PLC', mfr: 'GE'},
  {type: 'RTU-PLC', mfr: 'GORMAN RUPP'},
  {type: 'RTU-PLC', mfr: 'MERRICK'},
  {type: 'RTU-PLC', mfr: 'MISSION COMMUNICATIONS'},
  {type: 'RTU-PLC', mfr: 'MITSUBISHI'},
  {type: 'RTU-PLC', mfr: 'MODICON'},
  {type: 'RTU-PLC', mfr: 'QEI'},
  {type: 'RTU-PLC', mfr: 'SIEMENS'},
  {type: 'RTU-PLC', mfr: 'SQUARE D'},
  {type: 'RTU-PLC', mfr: 'STARNET'},
  {type: 'RTU-PLC', mfr: 'TOSHIBA'},
  {type: 'RTU-PLC', mfr: 'UNKNOWN'},
  {type: 'SAF-SHWR', mfr: 'BRADLEY'},
  {type: 'SAF-SHWR', mfr: 'DAYTON'},
  {type: 'SAF-SHWR', mfr: 'GUARDIAN'},
  {type: 'SAF-SHWR', mfr: 'HAWS'},
  {type: 'SAF-SHWR', mfr: 'SPEAKMAN'},
  {type: 'SAF-SHWR', mfr: 'UNKNOWN'},
  {type: 'SAFGASDT', mfr: 'ATI'},
  {type: 'SAFGASDT', mfr: 'BIOSYSTEMS'},
  {type: 'SAFGASDT', mfr: 'CAPITAL CONTROLS'},
  {type: 'SAFGASDT', mfr: 'DRAGER'},
  {type: 'SAFGASDT', mfr: 'ENMET'},
  {type: 'SAFGASDT', mfr: 'HONEYWELL'},
  {type: 'SAFGASDT', mfr: 'IN-USA'},
  {type: 'SAFGASDT', mfr: 'INDUSTRIAL SCIENTIFIC'},
  {type: 'SAFGASDT', mfr: 'MSA'},
  {type: 'SAFGASDT', mfr: 'REGAL'},
  {type: 'SAFGASDT', mfr: 'SCOTT'},
  {type: 'SAFGASDT', mfr: 'SIEMENS'},
  {type: 'SAFGASDT', mfr: 'UNKNOWN'},
  {type: 'SAFGASDT', mfr: 'US FILTER'},
  {type: 'SAFGASDT', mfr: 'WALLACE-TIERNAN'},
  {type: 'SAFGASDT', mfr: 'ZELLWEGER ANALYTICS'},
  {type: 'SCADASYS', mfr: 'UNKNOWN'},
  {type: 'SCALE', mfr: 'BRECKNELL'},
  {type: 'SCALE', mfr: 'CAPITAL'},
  {type: 'SCALE', mfr: 'CAPITAL CONTROLS'},
  {type: 'SCALE', mfr: 'DENVER INSTRUMENTS'},
  {type: 'SCALE', mfr: 'DETECTO'},
  {type: 'SCALE', mfr: 'EAGLE'},
  {type: 'SCALE', mfr: 'FAIRBANKS'},
  {type: 'SCALE', mfr: 'FLO-TECH'},
  {type: 'SCALE', mfr: 'FORCE FLOW'},
  {type: 'SCALE', mfr: 'FOXBORO'},
  {type: 'SCALE', mfr: 'HONEYWELL'},
  {type: 'SCALE', mfr: 'HOWE RICHARDSON'},
  {type: 'SCALE', mfr: 'INSCALE'},
  {type: 'SCALE', mfr: 'KISTLER-MORSE'},
  {type: 'SCALE', mfr: 'MERRICK'},
  {type: 'SCALE', mfr: 'METROHM'},
  {type: 'SCALE', mfr: 'METTLER'},
  {type: 'SCALE', mfr: 'METTLER TOLEDO'},
  {type: 'SCALE', mfr: 'OHAUS'},
  {type: 'SCALE', mfr: 'REGAL'},
  {type: 'SCALE', mfr: 'RICE LAKE'},
  {type: 'SCALE', mfr: 'SARTORIUS'},
  {type: 'SCALE', mfr: 'SCALETRON'},
  {type: 'SCALE', mfr: 'UNKNOWN'},
  {type: 'SCALE', mfr: 'WALLACE-TIERNAN'},
  {type: 'SCALE', mfr: 'WIZARD'},
  {type: 'SCRBBR', mfr: 'UNKNOWN'},
  {type: 'SCRBBR', mfr: 'US FILTER'},
  {type: 'SCREEN', mfr: 'ENVIREX'},
  {type: 'SCREEN', mfr: 'FMC'},
  {type: 'SCREEN', mfr: 'HAYWARD'},
  {type: 'SCREEN', mfr: 'JOHNSON'},
  {type: 'SCREEN', mfr: 'LINK-BELT REX NORD'},
  {type: 'SCREEN', mfr: 'ROCKWELL'},
  {type: 'SCREEN', mfr: 'SENSUS'},
  {type: 'SCREEN', mfr: 'UNKNOWN'},
  {type: 'SCREEN', mfr: 'VICTAULIC'},
  {type: 'SECSYS', mfr: 'ADT'},
  {type: 'SECSYS', mfr: 'ALLSTAR'},
  {type: 'SECSYS', mfr: 'GE'},
  {type: 'SECSYS', mfr: 'GENTEX CORP'},
  {type: 'SECSYS', mfr: 'GUARDIAN'},
  {type: 'SECSYS', mfr: 'SIMPLEX'},
  {type: 'SECSYS', mfr: 'UNKNOWN'},
  {type: 'SERVR', mfr: 'DELL'},
  {type: 'SERVR', mfr: 'HP'},
  {type: 'SERVR', mfr: 'IBM'},
  {type: 'SERVR', mfr: 'UNKNOWN'},
  {type: 'SVLV', mfr: 'ALLIS CHALMERS'},
  {type: 'SVLV', mfr: 'AMERICAN AVK'},
  {type: 'SVLV', mfr: 'AMERICAN CAST IRON PIPE'},
  {type: 'SVLV', mfr: 'AMERICAN DARLING'},
  {type: 'SVLV', mfr: 'AMERICAN FLOW CONTROL'},
  {type: 'SVLV', mfr: 'AMERICAN FOUNDRY'},
  {type: 'SVLV', mfr: 'AP SMITH'},
  {type: 'SVLV', mfr: 'APCO'},
  {type: 'SVLV', mfr: 'AVK'},
  {type: 'SVLV', mfr: 'AY MCDONALD'},
  {type: 'SVLV', mfr: 'CHAPMAN'},
  {type: 'SVLV', mfr: 'CLA-VAL'},
  {type: 'SVLV', mfr: 'CLOW'},
  {type: 'SVLV', mfr: 'COREY'},
  {type: 'SVLV', mfr: 'CRANE'},
  {type: 'SVLV', mfr: 'CRISPIN'},
  {type: 'SVLV', mfr: 'DARLING'},
  {type: 'SVLV', mfr: 'DEZURICK'},
  {type: 'SVLV', mfr: 'DRESSER'},
  {type: 'SVLV', mfr: 'EAST JORDAN'},
  {type: 'SVLV', mfr: 'ECLIPSE'},
  {type: 'SVLV', mfr: 'EDDY'},
  {type: 'SVLV', mfr: 'FMC'},
  {type: 'SVLV', mfr: 'FORD METER BOX'},
  {type: 'SVLV', mfr: 'FRANKLIN HYDRANTS'},
  {type: 'SVLV', mfr: 'GOLDEN ANDERSON'},
  {type: 'SVLV', mfr: 'IOWA'},
  {type: 'SVLV', mfr: 'JONES'},
  {type: 'SVLV', mfr: 'KENNEDY'},
  {type: 'SVLV', mfr: 'KUNKLE'},
  {type: 'SVLV', mfr: 'KUPFERLE'},
  {type: 'SVLV', mfr: 'LUDLOW'},
  {type: 'SVLV', mfr: 'M-H/MCWANE'},
  {type: 'SVLV', mfr: 'MATCO NORCA'},
  {type: 'SVLV', mfr: 'MH'},
  {type: 'SVLV', mfr: 'MICHIGAN'},
  {type: 'SVLV', mfr: 'MUELLER'},
  {type: 'SVLV', mfr: 'PENN-TROY'},
  {type: 'SVLV', mfr: 'PRATT'},
  {type: 'SVLV', mfr: 'PRATT-CADY'},
  {type: 'SVLV', mfr: 'RENSSELAER'},
  {type: 'SVLV', mfr: 'REZNOR'},
  {type: 'SVLV', mfr: 'SCOTT'},
  {type: 'SVLV', mfr: 'SMITH'},
  {type: 'SVLV', mfr: 'TCIW'},
  {type: 'SVLV', mfr: 'TRUFLO'},
  {type: 'SVLV', mfr: 'U.S. FOUNDRY'},
  {type: 'SVLV', mfr: 'UNITED POWER'},
  {type: 'SVLV', mfr: 'UNKNOWN'},
  {type: 'SVLV', mfr: 'US PIPE'},
  {type: 'SVLV', mfr: 'VAL-MATIC'},
  {type: 'SVLV', mfr: 'WACO'},
  {type: 'SVLV', mfr: 'WAL-MATIC'},
  {type: 'SVLV', mfr: 'WATEROUS'},
  {type: 'SVLV', mfr: 'WATTS'},
  {type: 'SVLV', mfr: 'WESTCOTT'},
  {type: 'SVLV', mfr: 'WILLAMETTE'},
  {type: 'SVLV-BO', mfr: 'AMERICAN AVK'},
  {type: 'SVLV-BO', mfr: 'AMERICAN CAST IRON PIPE'},
  {type: 'SVLV-BO', mfr: 'AMERICAN DARLING'},
  {type: 'SVLV-BO', mfr: 'AMERICAN FLOW CONTROL'},
  {type: 'SVLV-BO', mfr: 'AP SMITH'},
  {type: 'SVLV-BO', mfr: 'AY MCDONALD'},
  {type: 'SVLV-BO', mfr: 'CLOW'},
  {type: 'SVLV-BO', mfr: 'CRANE'},
  {type: 'SVLV-BO', mfr: 'DARLING'},
  {type: 'SVLV-BO', mfr: 'EDDY'},
  {type: 'SVLV-BO', mfr: 'FORD METER BOX'},
  {type: 'SVLV-BO', mfr: 'IOWA'},
  {type: 'SVLV-BO', mfr: 'KENNEDY'},
  {type: 'SVLV-BO', mfr: 'LUDLOW'},
  {type: 'SVLV-BO', mfr: 'M-H/MCWANE'},
  {type: 'SVLV-BO', mfr: 'MUELLER'},
  {type: 'SVLV-BO', mfr: 'PRATT'},
  {type: 'SVLV-BO', mfr: 'RENSSELAER'},
  {type: 'SVLV-BO', mfr: 'UNKNOWN'},
  {type: 'SVLV-BO', mfr: 'US PIPE'},
  {type: 'SVLV-BO', mfr: 'WATEROUS'},
  {type: 'TNK-CHEM', mfr: 'ADAMSON TANK'},
  {type: 'TNK-CHEM', mfr: 'ASSMANN'},
  {type: 'TNK-CHEM', mfr: 'BIF'},
  {type: 'TNK-CHEM', mfr: 'CHEM-TAINER'},
  {type: 'TNK-CHEM', mfr: 'CROWN'},
  {type: 'TNK-CHEM', mfr: 'EDWARDS FIBERGLASS'},
  {type: 'TNK-CHEM', mfr: 'HIGHLAND TANK'},
  {type: 'TNK-CHEM', mfr: 'JONES HUNT'},
  {type: 'TNK-CHEM', mfr: 'JUSTIN'},
  {type: 'TNK-CHEM', mfr: 'KINETICO'},
  {type: 'TNK-CHEM', mfr: 'LMI'},
  {type: 'TNK-CHEM', mfr: 'MERRICK'},
  {type: 'TNK-CHEM', mfr: 'NALGENE'},
  {type: 'TNK-CHEM', mfr: 'OMEGA'},
  {type: 'TNK-CHEM', mfr: 'PDM'},
  {type: 'TNK-CHEM', mfr: 'PLAS-TANKS'},
  {type: 'TNK-CHEM', mfr: 'POLYPROCESSING'},
  {type: 'TNK-CHEM', mfr: 'PROMINENT'},
  {type: 'TNK-CHEM', mfr: 'RAVEN'},
  {type: 'TNK-CHEM', mfr: 'SNYDER IND'},
  {type: 'TNK-CHEM', mfr: 'TERRACON'},
  {type: 'TNK-CHEM', mfr: 'UNKNOWN'},
  {type: 'TNK-CHEM', mfr: 'WARNER'},
  {type: 'TNK-CHEM', mfr: 'XERXES'},
  {type: 'TNK-FUEL', mfr: 'CATERPILLAR'},
  {type: 'TNK-FUEL', mfr: 'CUMMINS'},
  {type: 'TNK-FUEL', mfr: 'DETROIT'},
  {type: 'TNK-FUEL', mfr: 'HIGHLAND TANK'},
  {type: 'TNK-FUEL', mfr: 'UNKNOWN'},
  {type: 'TNK-PVAC', mfr: 'AMTROL'},
  {type: 'TNK-PVAC', mfr: 'BRUNNER'},
  {type: 'TNK-PVAC', mfr: 'DAYTON'},
  {type: 'TNK-PVAC', mfr: 'INGERSOL RAND'},
  {type: 'TNK-PVAC', mfr: 'LOCHINVAR'},
  {type: 'TNK-PVAC', mfr: 'MANCHESTER'},
  {type: 'TNK-PVAC', mfr: 'MELBEN'},
  {type: 'TNK-PVAC', mfr: 'PENWAY'},
  {type: 'TNK-PVAC', mfr: 'QUINCY'},
  {type: 'TNK-PVAC', mfr: 'SPEEDAIRE'},
  {type: 'TNK-PVAC', mfr: 'STEELFAB-SAMUEL'},
  {type: 'TNK-PVAC', mfr: 'STOYSTOWN TANK'},
  {type: 'TNK-PVAC', mfr: 'TACO'},
  {type: 'TNK-PVAC', mfr: 'UNKNOWN'},
  {type: 'TNK-PVAC', mfr: 'WESTINGHOUSE'},
  {type: 'TNK-WNON', mfr: 'BELL-GOSSETT'},
  {type: 'TNK-WNON', mfr: 'CALDWELL'},
  {type: 'TNK-WNON', mfr: 'CHICAGO BRIDGE-IRON'},
  {type: 'TNK-WNON', mfr: 'POLYPROCESSING'},
  {type: 'TNK-WNON', mfr: 'SEVERN TRENT'},
  {type: 'TNK-WNON', mfr: 'UNKNOWN'},
  {type: 'TNK-WPOT', mfr: 'ADAMSON TANK'},
  {type: 'TNK-WPOT', mfr: 'ADVANCE TANK'},
  {type: 'TNK-WPOT', mfr: 'AMTROL'},
  {type: 'TNK-WPOT', mfr: 'AO SMITH'},
  {type: 'TNK-WPOT', mfr: 'AQUASTORE'},
  {type: 'TNK-WPOT', mfr: 'BRUNNER'},
  {type: 'TNK-WPOT', mfr: 'BUFFALO TANK'},
  {type: 'TNK-WPOT', mfr: 'CALDWELL'},
  {type: 'TNK-WPOT', mfr: 'CHAMPION'},
  {type: 'TNK-WPOT', mfr: 'CHICAGO BRIDGE-IRON'},
  {type: 'TNK-WPOT', mfr: 'FISHER TANK CO'},
  {type: 'TNK-WPOT', mfr: 'GOULDS'},
  {type: 'TNK-WPOT', mfr: 'GRAVER TANK'},
  {type: 'TNK-WPOT', mfr: 'HIGHLAND TANK'},
  {type: 'TNK-WPOT', mfr: 'JOHN WOOD CO'},
  {type: 'TNK-WPOT', mfr: 'NATGUN'},
  {type: 'TNK-WPOT', mfr: 'NOOTER'},
  {type: 'TNK-WPOT', mfr: 'PDM'},
  {type: 'TNK-WPOT', mfr: 'PEABODY ENG'},
  {type: 'TNK-WPOT', mfr: 'RECO USA'},
  {type: 'TNK-WPOT', mfr: 'RHEEM'},
  {type: 'TNK-WPOT', mfr: 'UNKNOWN'},
  {type: 'TNK-WPOT', mfr: 'WESSELS'},
  {type: 'TNK-WSTE', mfr: 'AQUASTORE'},
  {type: 'TNK-WSTE', mfr: 'MYERS'},
  {type: 'TNK-WSTE', mfr: 'UNKNOWN'},
  {type: 'TOOL', mfr: 'CLIPPER POWER SYS'},
  {type: 'TOOL', mfr: 'CRAFTSMAN'},
  {type: 'TOOL', mfr: 'DAYTON'},
  {type: 'TOOL', mfr: 'FLUKE'},
  {type: 'TOOL', mfr: 'FORD MOTOR COMPANY'},
  {type: 'TOOL', mfr: 'GENERAC'},
  {type: 'TOOL', mfr: 'INGERSOL RAND'},
  {type: 'TOOL', mfr: 'JOHN DEERE'},
  {type: 'TOOL', mfr: 'JOHNSON'},
  {type: 'TOOL', mfr: 'KUBOTA'},
  {type: 'TOOL', mfr: 'LINCOLN MOTORS'},
  {type: 'TOOL', mfr: 'MUELLER'},
  {type: 'TOOL', mfr: 'RADIO DETECTION'},
  {type: 'TOOL', mfr: 'TORO'},
  {type: 'TOOL', mfr: 'TROY-BILT'},
  {type: 'TOOL', mfr: 'UNKNOWN'},
  {type: 'TOOL', mfr: 'WACKER'},
  {type: 'TOOL', mfr: 'WACKER NEUSON'},
  {type: 'TRAN-SW', mfr: 'ABB'},
  {type: 'TRAN-SW', mfr: 'ALLEN BRADLEY'},
  {type: 'TRAN-SW', mfr: 'ASCO'},
  {type: 'TRAN-SW', mfr: 'BEST-UPS'},
  {type: 'TRAN-SW', mfr: 'CATERPILLAR'},
  {type: 'TRAN-SW', mfr: 'CUMMINS'},
  {type: 'TRAN-SW', mfr: 'CUTLER HAMMER'},
  {type: 'TRAN-SW', mfr: 'DETROIT'},
  {type: 'TRAN-SW', mfr: 'EATON/CUTLER HAMMER'},
  {type: 'TRAN-SW', mfr: 'GE'},
  {type: 'TRAN-SW', mfr: 'GENERAC'},
  {type: 'TRAN-SW', mfr: 'KATOLIGHT'},
  {type: 'TRAN-SW', mfr: 'KOHLER'},
  {type: 'TRAN-SW', mfr: 'LAKE SHORE'},
  {type: 'TRAN-SW', mfr: 'MIDWEST'},
  {type: 'TRAN-SW', mfr: 'ONAN'},
  {type: 'TRAN-SW', mfr: 'RONK'},
  {type: 'TRAN-SW', mfr: 'RUSS ELECTRIC'},
  {type: 'TRAN-SW', mfr: 'SIEMENS'},
  {type: 'TRAN-SW', mfr: 'SQUARE D'},
  {type: 'TRAN-SW', mfr: 'UNKNOWN'},
  {type: 'TRAN-SW', mfr: 'WESTINGHOUSE'},
  {type: 'TRT-AER', mfr: 'LOWRY'},
  {type: 'TRT-AER', mfr: 'UNKNOWN'},
  {type: 'TRT-CLAR', mfr: 'ENVIREX'},
  {type: 'TRT-CLAR', mfr: 'SEW'},
  {type: 'TRT-CLAR', mfr: 'UNKNOWN'},
  {type: 'TRT-CONT', mfr: 'UNKNOWN'},
  {type: 'TRT-FILT', mfr: 'ASHBROOK SIMON HARTLEY'},
  {type: 'TRT-FILT', mfr: 'LEOPOLD'},
  {type: 'TRT-FILT', mfr: 'NETZSCH'},
  {type: 'TRT-FILT', mfr: 'ROBERTS'},
  {type: 'TRT-FILT', mfr: 'UNKNOWN'},
  {type: 'TRT-SOFT', mfr: 'KINETICO'},
  {type: 'TRT-SOFT', mfr: 'UNKNOWN'},
  {type: 'TRT-STRP', mfr: 'HYDRO GROUP'},
  {type: 'TRT-STRP', mfr: 'LAYNE CHRISTENSEN'},
  {type: 'TRT-STRP', mfr: 'UNKNOWN'},
  {type: 'TRT-UV', mfr: 'SENTINEL-CALGON'},
  {type: 'TRT-UV', mfr: 'TROJAN UV'},
  {type: 'TRT-UV', mfr: 'UNKNOWN'},
  {type: 'UPS', mfr: 'BEST'},
  {type: 'UPS', mfr: 'BEST-UPS'},
  {type: 'UPS', mfr: 'CD TECHNOLOGIES'},
  {type: 'UPS', mfr: 'EATON/CUTLER HAMMER'},
  {type: 'UPS', mfr: 'GE'},
  {type: 'UPS', mfr: 'INTERNATIONAL'},
  {type: 'UPS', mfr: 'LIEBERT'},
  {type: 'UPS', mfr: 'MESTA ELECTRONICS'},
  {type: 'UPS', mfr: 'PHOENIX CONTACT'},
  {type: 'UPS', mfr: 'SCHNEIDER ELECTRIC-APC'},
  {type: 'UPS', mfr: 'TRIPPLITE'},
  {type: 'UPS', mfr: 'UNKNOWN'},
  {type: 'UV-SOUND', mfr: 'LG SONIC'},
  {type: 'UV-SOUND', mfr: 'SONIC SOLUTIONS'},
  {type: 'UV-SOUND', mfr: 'UNKNOWN'},
  {type: 'VEH', mfr: 'CASE'},
  {type: 'VEH', mfr: 'CHEVROLET'},
  {type: 'VEH', mfr: 'CLARK'},
  {type: 'VEH', mfr: 'CROWN'},
  {type: 'VEH', mfr: 'DODGE'},
  {type: 'VEH', mfr: 'FORD MOTOR COMPANY'},
  {type: 'VEH', mfr: 'HYSTER'},
  {type: 'VEH', mfr: 'KUBOTA'},
  {type: 'VEH', mfr: 'SMITH'},
  {type: 'VEH', mfr: 'SMOKER CRAFT'},
  {type: 'VEH', mfr: 'TOYOTA'},
  {type: 'VEH', mfr: 'UNKNOWN'},
  {type: 'VEH', mfr: 'YALE'},
  {type: 'WELL', mfr: 'UNKNOWN'},
  {type: 'WELL', mfr: 'US MOTORS'},
  {type: 'WQANLZR', mfr: 'ACCUMET'},
  {type: 'WQANLZR', mfr: 'AGILENT-VARIAN'},
  {type: 'WQANLZR', mfr: 'ATI'},
  {type: 'WQANLZR', mfr: 'CAPITAL CONTROLS'},
  {type: 'WQANLZR', mfr: 'CHEMTRAC'},
  {type: 'WQANLZR', mfr: 'DENVER INSTRUMENTS'},
  {type: 'WQANLZR', mfr: 'ENDRESS-HAUSER'},
  {type: 'WQANLZR', mfr: 'ENTECH'},
  {type: 'WQANLZR', mfr: 'FISCHER PORTER'},
  {type: 'WQANLZR', mfr: 'FISHER SCIENTIFIC'},
  {type: 'WQANLZR', mfr: 'FOXBORO'},
  {type: 'WQANLZR', mfr: 'GREAT LAKES'},
  {type: 'WQANLZR', mfr: 'HACH'},
  {type: 'WQANLZR', mfr: 'HIAC-ROYCO'},
  {type: 'WQANLZR', mfr: 'HONEYWELL'},
  {type: 'WQANLZR', mfr: 'IN-USA'},
  {type: 'WQANLZR', mfr: 'LEED-NORTHRUP CO'},
  {type: 'WQANLZR', mfr: 'LMI'},
  {type: 'WQANLZR', mfr: 'MET ONE'},
  {type: 'WQANLZR', mfr: 'MILLTRONICS'},
  {type: 'WQANLZR', mfr: 'MILTON ROY'},
  {type: 'WQANLZR', mfr: 'OAKTON'},
  {type: 'WQANLZR', mfr: 'PROMINENT'},
  {type: 'WQANLZR', mfr: 'ROSEMOUNT'},
  {type: 'WQANLZR', mfr: 'SEVERN TRENT'},
  {type: 'WQANLZR', mfr: 'SHIMADZU'},
  {type: 'WQANLZR', mfr: 'SIEMENS'},
  {type: 'WQANLZR', mfr: 'SIGMA'},
  {type: 'WQANLZR', mfr: 'TELEDYNE'},
  {type: 'WQANLZR', mfr: 'THERMO-ORION'},
  {type: 'WQANLZR', mfr: 'THOMAS'},
  {type: 'WQANLZR', mfr: 'TURNER DESIGNS'},
  {type: 'WQANLZR', mfr: 'UNKNOWN'},
  {type: 'WQANLZR', mfr: 'US FILTER'},
  {type: 'WQANLZR', mfr: 'VWR SCIENTIFIC'},
  {type: 'WQANLZR', mfr: 'WALLACE-TIERNAN'},
  {type: 'WQANLZR', mfr: 'YSI'},
  {type: 'WQANLZR', mfr: 'ZELLWEGER ANALYTICS'},
  {type: 'WQANLZR', mfr: 'ZETA-METER'},
  {type: 'XFMR', mfr: 'ABB'},
  {type: 'XFMR', mfr: 'ACME'},
  {type: 'XFMR', mfr: 'ADVANCE'},
  {type: 'XFMR', mfr: 'AED INTERNATIONAL'},
  {type: 'XFMR', mfr: 'ALLEN BRADLEY'},
  {type: 'XFMR', mfr: 'ALLIS CHALMERS'},
  {type: 'XFMR', mfr: 'ALLIS CHAMBERS'},
  {type: 'XFMR', mfr: 'CHALLENGER'},
  {type: 'XFMR', mfr: 'CUTLER HAMMER'},
  {type: 'XFMR', mfr: 'DONGAN'},
  {type: 'XFMR', mfr: 'EATON/CUTLER HAMMER'},
  {type: 'XFMR', mfr: 'EGS'},
  {type: 'XFMR', mfr: 'FEDERAL'},
  {type: 'XFMR', mfr: 'FEDERAL PACIFIC'},
  {type: 'XFMR', mfr: 'FURNAS'},
  {type: 'XFMR', mfr: 'GE'},
  {type: 'XFMR', mfr: 'GENERAL SIGNAL-SPX'},
  {type: 'XFMR', mfr: 'HAMMOND'},
  {type: 'XFMR', mfr: 'HITRAN'},
  {type: 'XFMR', mfr: 'ITE'},
  {type: 'XFMR', mfr: 'JEFFERSON ELECTRIC'},
  {type: 'XFMR', mfr: 'MAGNETEK'},
  {type: 'XFMR', mfr: 'OLSUN ELECTRICS'},
  {type: 'XFMR', mfr: 'REX MANUFACTURING'},
  {type: 'XFMR', mfr: 'SIEMENS'},
  {type: 'XFMR', mfr: 'SPANG-MAGNETICS'},
  {type: 'XFMR', mfr: 'SQUARE D'},
  {type: 'XFMR', mfr: 'SUNBELT'},
  {type: 'XFMR', mfr: 'TCI'},
  {type: 'XFMR', mfr: 'UNKNOWN'},
  {type: 'XFMR', mfr: 'WAGNER'},
  {type: 'XFMR', mfr: 'WESTINGHOUSE'},
  {type: 'XMTR', mfr: 'ABB'},
  {type: 'XMTR', mfr: 'AGM ELECTRONICS'},
  {type: 'XMTR', mfr: 'AIRMATE'},
  {type: 'XMTR', mfr: 'AMETEK'},
  {type: 'XMTR', mfr: 'ANCHOR SCIENTIFIC'},
  {type: 'XMTR', mfr: 'ASHCROFT'},
  {type: 'XMTR', mfr: 'BADGER'},
  {type: 'XMTR', mfr: 'BIF'},
  {type: 'XMTR', mfr: 'BRISTOL'},
  {type: 'XMTR', mfr: 'BRISTOL BABCOCK'},
  {type: 'XMTR', mfr: 'CONTROLWAVE'},
  {type: 'XMTR', mfr: 'DAYTON'},
  {type: 'XMTR', mfr: 'DEVAR'},
  {type: 'XMTR', mfr: 'DREXELBROOK'},
  {type: 'XMTR', mfr: 'DWYER'},
  {type: 'XMTR', mfr: 'EMERSON'},
  {type: 'XMTR', mfr: 'ENDRESS-HAUSER'},
  {type: 'XMTR', mfr: 'FISCHER PORTER'},
  {type: 'XMTR', mfr: 'FLOW LINE'},
  {type: 'XMTR', mfr: 'FORCE FLOW'},
  {type: 'XMTR', mfr: 'FOXBORO'},
  {type: 'XMTR', mfr: 'GRUNDFOS'},
  {type: 'XMTR', mfr: 'HACH'},
  {type: 'XMTR', mfr: 'HONEYWELL'},
  {type: 'XMTR', mfr: 'INVENTRON'},
  {type: 'XMTR', mfr: 'ITT BARTON'},
  {type: 'XMTR', mfr: 'KISTLER-MORSE'},
  {type: 'XMTR', mfr: 'LESLIE CONTROLS'},
  {type: 'XMTR', mfr: 'MAGNATROL'},
  {type: 'XMTR', mfr: 'MERCOID'},
  {type: 'XMTR', mfr: 'MILLTRONICS'},
  {type: 'XMTR', mfr: 'MKS INSTRUMENTS'},
  {type: 'XMTR', mfr: 'MOORE INDUSTRIES'},
  {type: 'XMTR', mfr: 'MORSE'},
  {type: 'XMTR', mfr: 'PANAMETRICS'},
  {type: 'XMTR', mfr: 'PRECISION'},
  {type: 'XMTR', mfr: 'PULSAR'},
  {type: 'XMTR', mfr: 'REGAL'},
  {type: 'XMTR', mfr: 'RIGHTON'},
  {type: 'XMTR', mfr: 'ROSEMOUNT'},
  {type: 'XMTR', mfr: 'SENSUS'},
  {type: 'XMTR', mfr: 'SIEMENS'},
  {type: 'XMTR', mfr: 'SIGMA'},
  {type: 'XMTR', mfr: 'SONIC SOLUTIONS'},
  {type: 'XMTR', mfr: 'TAYLOR'},
  {type: 'XMTR', mfr: 'UNKNOWN'},
  {type: 'XMTR', mfr: 'WIKA'},
  {type: 'XMTR', mfr: 'YOKOGAWA'},
]

client = TinyTds::Client.new username: 'sa', password: 'mapcall#1', host: 'localhost', port: 1433, database: 'MapCallDev'

values.each do |value|
  type_id = client.execute("select id from sapequipmenttypes where abbreviation = '#{value[:type]}'").each

  if !type_id.any?
    puts "--SAPEquipmentType '#{value[:type]}' not found."
    next
  end

  type_id = type_id[0]['id']

  existing = client.execute("select id from sapequipmentmanufacturers where sapequipmenttypeid = #{type_id} and description = '#{value[:mfr]}'").each

  if !existing.any?
    puts "INSERT INTO SAPEquipmentManufacturers (SAPEquipmentTypeId, Description) VALUES (#{type_id}, '#{value[:mfr]}');"
  end
end
