
SET IDENTITY_INSERT WorkDescriptions ON

INSERT INTO [dbo].[WorkDescriptions]
	([WorkDescriptionID], [Description], [AssetTypeID], [TimeToComplete], [WorkCategoryID], [AccountingTypeID], [FirstRestorationAccountingCodeID], [FirstRestorationCostBreakdown], [FirstRestorationProductCodeID], [SecondRestorationAccountingCodeID], [SecondRestorationCostBreakdown], [SecondRestorationProductCodeID], [ShowBusinessUnit], [ShowApprovalAccounting], [EditOnly],[Revisit])
SELECT N'208' AS [WorkDescriptionID], N'Z-LWC/EW4 - 3 CONSECUTIVE MTHS OF 0 USAGE [ZERO]' AS [Description], N'4' AS [AssetTypeID], N'1.50' AS [TimeToComplete], N'26' AS [WorkCategoryID], N'1' AS [AccountingTypeID], N'1' AS [FirstRestorationAccountingCodeID], N'100' AS [FirstRestorationCostBreakdown], N'1' AS [FirstRestorationProductCodeID], NULL AS [SecondRestorationAccountingCodeID], NULL AS [SecondRestorationCostBreakdown], N'1' AS [SecondRestorationProductCodeID], N'0' AS [ShowBusinessUnit], N'1' AS [ShowApprovalAccounting], N'0' AS [EditOnly], N'0' AS [Revisit] UNION ALL 
SELECT N'209' AS [WorkDescriptionID], N'Z-LWC/EW4 - CHECK METER NON-EMERGENCY [CKMTR]' AS [Description], N'4' AS [AssetTypeID], N'1.50' AS [TimeToComplete], N'26' AS [WorkCategoryID], N'1' AS [AccountingTypeID], N'1' AS [FirstRestorationAccountingCodeID], N'100' AS [FirstRestorationCostBreakdown], N'1' AS [FirstRestorationProductCodeID], NULL AS [SecondRestorationAccountingCodeID], NULL AS [SecondRestorationCostBreakdown], N'1' AS [SecondRestorationProductCodeID], N'0' AS [ShowBusinessUnit], N'1' AS [ShowApprovalAccounting], N'0' AS [EditOnly], N'0' AS [Revisit] UNION ALL 
SELECT N'210' AS [WorkDescriptionID], N'Z-LWC/EW4 - DEMOLITION CLOSED ACCOUNT [DEMOC]' AS [Description], N'4' AS [AssetTypeID], N'1.50' AS [TimeToComplete], N'26' AS [WorkCategoryID], N'1' AS [AccountingTypeID], N'1' AS [FirstRestorationAccountingCodeID], N'100' AS [FirstRestorationCostBreakdown], N'1' AS [FirstRestorationProductCodeID], NULL AS [SecondRestorationAccountingCodeID], NULL AS [SecondRestorationCostBreakdown], N'1' AS [SecondRestorationProductCodeID], N'0' AS [ShowBusinessUnit], N'1' AS [ShowApprovalAccounting], N'0' AS [EditOnly], N'0' AS [Revisit] UNION ALL 
SELECT N'211' AS [WorkDescriptionID], N'Z-LWC/EW4 - METER CHANGE-OUT [MTRCH]' AS [Description], N'4' AS [AssetTypeID], N'1.50' AS [TimeToComplete], N'26' AS [WorkCategoryID], N'1' AS [AccountingTypeID], N'1' AS [FirstRestorationAccountingCodeID], N'100' AS [FirstRestorationCostBreakdown], N'1' AS [FirstRestorationProductCodeID], NULL AS [SecondRestorationAccountingCodeID], NULL AS [SecondRestorationCostBreakdown], N'1' AS [SecondRestorationProductCodeID], N'0' AS [ShowBusinessUnit], N'1' AS [ShowApprovalAccounting], N'0' AS [EditOnly], N'0' AS [Revisit] UNION ALL 
SELECT N'212' AS [WorkDescriptionID], N'Z-LWC/EW4 - READ MR EDIT - LOCAL OPS ONLY [MREDT]' AS [Description], N'4' AS [AssetTypeID], N'1.50' AS [TimeToComplete], N'26' AS [WorkCategoryID], N'1' AS [AccountingTypeID], N'1' AS [FirstRestorationAccountingCodeID], N'100' AS [FirstRestorationCostBreakdown], N'1' AS [FirstRestorationProductCodeID], NULL AS [SecondRestorationAccountingCodeID], NULL AS [SecondRestorationCostBreakdown], N'1' AS [SecondRestorationProductCodeID], N'0' AS [ShowBusinessUnit], N'1' AS [ShowApprovalAccounting], N'0' AS [EditOnly], N'0' AS [Revisit] UNION ALL 
SELECT N'213' AS [WorkDescriptionID], N'Z-LWC/EW4 - READ TO STOP ESTIMATE [EST]' AS [Description], N'4' AS [AssetTypeID], N'1.50' AS [TimeToComplete], N'26' AS [WorkCategoryID], N'1' AS [AccountingTypeID], N'1' AS [FirstRestorationAccountingCodeID], N'100' AS [FirstRestorationCostBreakdown], N'1' AS [FirstRestorationProductCodeID], NULL AS [SecondRestorationAccountingCodeID], NULL AS [SecondRestorationCostBreakdown], N'1' AS [SecondRestorationProductCodeID], N'0' AS [ShowBusinessUnit], N'1' AS [ShowApprovalAccounting], N'0' AS [EditOnly], N'0' AS [Revisit] UNION ALL 
SELECT N'214' AS [WorkDescriptionID], N'Z-LWC/EW4 - REPAIR/INSTALL READING DEVICE [REM]' AS [Description], N'4' AS [AssetTypeID], N'1.50' AS [TimeToComplete], N'26' AS [WorkCategoryID], N'1' AS [AccountingTypeID], N'1' AS [FirstRestorationAccountingCodeID], N'100' AS [FirstRestorationCostBreakdown], N'1' AS [FirstRestorationProductCodeID], NULL AS [SecondRestorationAccountingCodeID], NULL AS [SecondRestorationCostBreakdown], N'1' AS [SecondRestorationProductCodeID], N'0' AS [ShowBusinessUnit], N'1' AS [ShowApprovalAccounting], N'0' AS [EditOnly], N'0' AS [Revisit] UNION ALL 
SELECT N'215' AS [WorkDescriptionID], N'Z-LWC/EW4 - REREAD AND/OR INSPECT FOR LEAK [HILOW]' AS [Description], N'4' AS [AssetTypeID], N'1.50' AS [TimeToComplete], N'26' AS [WorkCategoryID], N'1' AS [AccountingTypeID], N'1' AS [FirstRestorationAccountingCodeID], N'100' AS [FirstRestorationCostBreakdown], N'1' AS [FirstRestorationProductCodeID], NULL AS [SecondRestorationAccountingCodeID], NULL AS [SecondRestorationCostBreakdown], N'1' AS [SecondRestorationProductCodeID], N'0' AS [ShowBusinessUnit], N'1' AS [ShowApprovalAccounting], N'0' AS [EditOnly], N'0' AS [Revisit] UNION ALL 
SELECT N'216' AS [WorkDescriptionID], N'Z-LWC/EW4 - SET METER/TURN ON & READ [ONSET]' AS [Description], N'4' AS [AssetTypeID], N'1.50' AS [TimeToComplete], N'26' AS [WorkCategoryID], N'1' AS [AccountingTypeID], N'1' AS [FirstRestorationAccountingCodeID], N'100' AS [FirstRestorationCostBreakdown], N'1' AS [FirstRestorationProductCodeID], NULL AS [SecondRestorationAccountingCodeID], NULL AS [SecondRestorationCostBreakdown], N'1' AS [SecondRestorationProductCodeID], N'0' AS [ShowBusinessUnit], N'1' AS [ShowApprovalAccounting], N'0' AS [EditOnly], N'0' AS [Revisit] UNION ALL 
SELECT N'217' AS [WorkDescriptionID], N'Z-LWC/EW4 - TURN ON WATER [ON]' AS [Description], N'4' AS [AssetTypeID], N'1.50' AS [TimeToComplete], N'26' AS [WorkCategoryID], N'1' AS [AccountingTypeID], N'1' AS [FirstRestorationAccountingCodeID], N'100' AS [FirstRestorationCostBreakdown], N'1' AS [FirstRestorationProductCodeID], NULL AS [SecondRestorationAccountingCodeID], NULL AS [SecondRestorationCostBreakdown], N'1' AS [SecondRestorationProductCodeID], N'0' AS [ShowBusinessUnit], N'1' AS [ShowApprovalAccounting], N'0' AS [EditOnly], N'0' AS [Revisit] 

SET IDENTITY_INSERT WorkDescriptions OFF
