//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MapCall.SAP.CustomerOrder
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://amwater.com/EAM/0022/MAPCALL/GetCustomerOrderDetails", ConfigurationName="CustomerOrder.CustomerOrder_FSR_Get_OB_SYN")]
    public interface CustomerOrder_FSR_Get_OB_SYN {
        // CODEGEN: Generating message contract since the operation CustomerOrder_FSR_Get_OB_SYN is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MapCall.SAP.CustomerOrder.CustomerOrder_FSR_Get_OB_SYNResponse CustomerOrder_FSR_Get_OB_SYN(MapCall.SAP.CustomerOrder.CustomerOrder_FSR_Get_OB_SYNRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        System.Threading.Tasks.Task<MapCall.SAP.CustomerOrder.CustomerOrder_FSR_Get_OB_SYNResponse> CustomerOrder_FSR_Get_OB_SYNAsync(MapCall.SAP.CustomerOrder.CustomerOrder_FSR_Get_OB_SYNRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://amwater.com/EAM/0022/MAPCALL/GetCustomerOrderDetails")]
    public partial class CustomerOrder_FSRQuery : object, System.ComponentModel.INotifyPropertyChanged {
        private string sourceIdentifierField;
        
        private CustomerOrder_FSRQueryFSR_WO fSR_WOField;
        
        private CustomerOrder_FSRQueryDailySchedule dailyScheduleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string SourceIdentifier {
            get {
                return this.sourceIdentifierField;
            }
            set {
                this.sourceIdentifierField = value;
                this.RaisePropertyChanged("SourceIdentifier");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public CustomerOrder_FSRQueryFSR_WO FSR_WO {
            get {
                return this.fSR_WOField;
            }
            set {
                this.fSR_WOField = value;
                this.RaisePropertyChanged("FSR_WO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public CustomerOrder_FSRQueryDailySchedule DailySchedule {
            get {
                return this.dailyScheduleField;
            }
            set {
                this.dailyScheduleField = value;
                this.RaisePropertyChanged("DailySchedule");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://amwater.com/EAM/0022/MAPCALL/GetCustomerOrderDetails")]
    public partial class CustomerOrder_FSRQueryFSR_WO : object, System.ComponentModel.INotifyPropertyChanged {
        private string fSR_IDField;
        
        private string workOrderField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string FSR_ID {
            get {
                return this.fSR_IDField;
            }
            set {
                this.fSR_IDField = value;
                this.RaisePropertyChanged("FSR_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string WorkOrder {
            get {
                return this.workOrderField;
            }
            set {
                this.workOrderField = value;
                this.RaisePropertyChanged("WorkOrder");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://amwater.com/EAM/0022/MAPCALL/GetCustomerOrderDetails")]
    public partial class CustomerOrder_FSRInfo : object, System.ComponentModel.INotifyPropertyChanged {
        private CustomerOrder_FSRInfoMapCall_Response mapCall_ResponseField;
        
        private CustomerOrder_FSRInfoResponse_WorkOrder[] aO_ResponseField;
        
        private string sAPStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public CustomerOrder_FSRInfoMapCall_Response MapCall_Response {
            get {
                return this.mapCall_ResponseField;
            }
            set {
                this.mapCall_ResponseField = value;
                this.RaisePropertyChanged("MapCall_Response");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Response_WorkOrder", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public CustomerOrder_FSRInfoResponse_WorkOrder[] AO_Response {
            get {
                return this.aO_ResponseField;
            }
            set {
                this.aO_ResponseField = value;
                this.RaisePropertyChanged("AO_Response");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string SAPStatus {
            get {
                return this.sAPStatusField;
            }
            set {
                this.sAPStatusField = value;
                this.RaisePropertyChanged("SAPStatus");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://amwater.com/EAM/0022/MAPCALL/GetCustomerOrderDetails")]
    public partial class CustomerOrder_FSRInfoMapCall_Response : object, System.ComponentModel.INotifyPropertyChanged {
        private CustomerOrder_FSRInfoMapCall_ResponseRecord[] response_FSRField;
        
        private CustomerOrder_FSRInfoMapCall_ResponseResponse_WorkOrder[] response_WorkOrderField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Record", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public CustomerOrder_FSRInfoMapCall_ResponseRecord[] Response_FSR {
            get {
                return this.response_FSRField;
            }
            set {
                this.response_FSRField = value;
                this.RaisePropertyChanged("Response_FSR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Response_WorkOrder", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public CustomerOrder_FSRInfoMapCall_ResponseResponse_WorkOrder[] Response_WorkOrder {
            get {
                return this.response_WorkOrderField;
            }
            set {
                this.response_WorkOrderField = value;
                this.RaisePropertyChanged("Response_WorkOrder");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://amwater.com/EAM/0022/MAPCALL/GetCustomerOrderDetails")]
    public partial class CustomerOrder_FSRInfoMapCall_ResponseRecord : object, System.ComponentModel.INotifyPropertyChanged {
        private string workOrderField;
        
        private string operationNoField;
        
        private string assignmentStartField;
        
        private string assignmentFinishField;
        
        private string priorityField;
        
        private string statusField;
        
        private string assignedEngineerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string WorkOrder {
            get {
                return this.workOrderField;
            }
            set {
                this.workOrderField = value;
                this.RaisePropertyChanged("WorkOrder");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string OperationNo {
            get {
                return this.operationNoField;
            }
            set {
                this.operationNoField = value;
                this.RaisePropertyChanged("OperationNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string AssignmentStart {
            get {
                return this.assignmentStartField;
            }
            set {
                this.assignmentStartField = value;
                this.RaisePropertyChanged("AssignmentStart");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string AssignmentFinish {
            get {
                return this.assignmentFinishField;
            }
            set {
                this.assignmentFinishField = value;
                this.RaisePropertyChanged("AssignmentFinish");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Priority {
            get {
                return this.priorityField;
            }
            set {
                this.priorityField = value;
                this.RaisePropertyChanged("Priority");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string AssignedEngineer {
            get {
                return this.assignedEngineerField;
            }
            set {
                this.assignedEngineerField = value;
                this.RaisePropertyChanged("AssignedEngineer");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://amwater.com/EAM/0022/MAPCALL/GetCustomerOrderDetails")]
    public partial class CustomerOrder_FSRInfoMapCall_ResponseResponse_WorkOrder : object, System.ComponentModel.INotifyPropertyChanged {
        private string equipTextField;
        
        private string equipmentIDField;
        
        private string functionalLocationField;
        
        private string installationDateField;
        
        private string houseNumberField;
        
        private string streetField;
        
        private string criticalityField;
        
        private string yearMFGField;
        
        private string latitudeField;
        
        private string longitudeField;
        
        private string manufacturerField;
        
        private string equipLongTextField;
        
        private string safetyConcernDescrField;
        
        private string notificationNumberField;
        
        private string notificationShortTextField;
        
        private string notificationLongTextField;
        
        private string priorityField;
        
        private string backReportingTypeField;
        
        private string createTimeField;
        
        private string createDateField;
        
        private string asFoundCodeField;
        
        private string curbBox_LongitudeField;
        
        private string curbBox_LatitudeField;
        
        private string workOrderField;
        
        private string statusField;
        
        private string wBSElementField;
        
        private string planningPlantField;
        
        private string workOrderTextField;
        
        private string operationTextField;
        
        private string customerField;
        
        private string customerPhoneField;
        
        private string customerAlternatePhoneField;
        
        private string customerMailingAddressField;
        
        private string crossStreetField;
        
        private string isWorkRequiredField;
        
        private string nextReplacementYearField;
        
        private string serviceTypeField;
        
        private string serialNumberField;
        
        private string mFGSerialNumField;
        
        private string isCustomerEnrolledForEmailField;
        
        private CustomerOrder_FSRInfoMapCall_ResponseResponse_WorkOrderDependencyNode[] dependencyNodeField;
        
        private CustomerOrder_FSRInfoMapCall_ResponseResponse_WorkOrderSecurityThreatNode[] securityThreatNodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string EquipText {
            get {
                return this.equipTextField;
            }
            set {
                this.equipTextField = value;
                this.RaisePropertyChanged("EquipText");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string EquipmentID {
            get {
                return this.equipmentIDField;
            }
            set {
                this.equipmentIDField = value;
                this.RaisePropertyChanged("EquipmentID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string FunctionalLocation {
            get {
                return this.functionalLocationField;
            }
            set {
                this.functionalLocationField = value;
                this.RaisePropertyChanged("FunctionalLocation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string InstallationDate {
            get {
                return this.installationDateField;
            }
            set {
                this.installationDateField = value;
                this.RaisePropertyChanged("InstallationDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string HouseNumber {
            get {
                return this.houseNumberField;
            }
            set {
                this.houseNumberField = value;
                this.RaisePropertyChanged("HouseNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string Street {
            get {
                return this.streetField;
            }
            set {
                this.streetField = value;
                this.RaisePropertyChanged("Street");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string Criticality {
            get {
                return this.criticalityField;
            }
            set {
                this.criticalityField = value;
                this.RaisePropertyChanged("Criticality");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string YearMFG {
            get {
                return this.yearMFGField;
            }
            set {
                this.yearMFGField = value;
                this.RaisePropertyChanged("YearMFG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string Latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
                this.RaisePropertyChanged("Latitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string Longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
                this.RaisePropertyChanged("Longitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string Manufacturer {
            get {
                return this.manufacturerField;
            }
            set {
                this.manufacturerField = value;
                this.RaisePropertyChanged("Manufacturer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string EquipLongText {
            get {
                return this.equipLongTextField;
            }
            set {
                this.equipLongTextField = value;
                this.RaisePropertyChanged("EquipLongText");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string SafetyConcernDescr {
            get {
                return this.safetyConcernDescrField;
            }
            set {
                this.safetyConcernDescrField = value;
                this.RaisePropertyChanged("SafetyConcernDescr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string NotificationNumber {
            get {
                return this.notificationNumberField;
            }
            set {
                this.notificationNumberField = value;
                this.RaisePropertyChanged("NotificationNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string NotificationShortText {
            get {
                return this.notificationShortTextField;
            }
            set {
                this.notificationShortTextField = value;
                this.RaisePropertyChanged("NotificationShortText");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string NotificationLongText {
            get {
                return this.notificationLongTextField;
            }
            set {
                this.notificationLongTextField = value;
                this.RaisePropertyChanged("NotificationLongText");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string Priority {
            get {
                return this.priorityField;
            }
            set {
                this.priorityField = value;
                this.RaisePropertyChanged("Priority");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string BackReportingType {
            get {
                return this.backReportingTypeField;
            }
            set {
                this.backReportingTypeField = value;
                this.RaisePropertyChanged("BackReportingType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string CreateTime {
            get {
                return this.createTimeField;
            }
            set {
                this.createTimeField = value;
                this.RaisePropertyChanged("CreateTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string CreateDate {
            get {
                return this.createDateField;
            }
            set {
                this.createDateField = value;
                this.RaisePropertyChanged("CreateDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string AsFoundCode {
            get {
                return this.asFoundCodeField;
            }
            set {
                this.asFoundCodeField = value;
                this.RaisePropertyChanged("AsFoundCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public string CurbBox_Longitude {
            get {
                return this.curbBox_LongitudeField;
            }
            set {
                this.curbBox_LongitudeField = value;
                this.RaisePropertyChanged("CurbBox_Longitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public string CurbBox_Latitude {
            get {
                return this.curbBox_LatitudeField;
            }
            set {
                this.curbBox_LatitudeField = value;
                this.RaisePropertyChanged("CurbBox_Latitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public string WorkOrder {
            get {
                return this.workOrderField;
            }
            set {
                this.workOrderField = value;
                this.RaisePropertyChanged("WorkOrder");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=25)]
        public string WBSElement {
            get {
                return this.wBSElementField;
            }
            set {
                this.wBSElementField = value;
                this.RaisePropertyChanged("WBSElement");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=26)]
        public string PlanningPlant {
            get {
                return this.planningPlantField;
            }
            set {
                this.planningPlantField = value;
                this.RaisePropertyChanged("PlanningPlant");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=27)]
        public string WorkOrderText {
            get {
                return this.workOrderTextField;
            }
            set {
                this.workOrderTextField = value;
                this.RaisePropertyChanged("WorkOrderText");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=28)]
        public string OperationText {
            get {
                return this.operationTextField;
            }
            set {
                this.operationTextField = value;
                this.RaisePropertyChanged("OperationText");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=29)]
        public string Customer {
            get {
                return this.customerField;
            }
            set {
                this.customerField = value;
                this.RaisePropertyChanged("Customer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=30)]
        public string CustomerPhone {
            get {
                return this.customerPhoneField;
            }
            set {
                this.customerPhoneField = value;
                this.RaisePropertyChanged("CustomerPhone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=31)]
        public string CustomerAlternatePhone {
            get {
                return this.customerAlternatePhoneField;
            }
            set {
                this.customerAlternatePhoneField = value;
                this.RaisePropertyChanged("CustomerAlternatePhone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=32)]
        public string CustomerMailingAddress {
            get {
                return this.customerMailingAddressField;
            }
            set {
                this.customerMailingAddressField = value;
                this.RaisePropertyChanged("CustomerMailingAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=33)]
        public string CrossStreet {
            get {
                return this.crossStreetField;
            }
            set {
                this.crossStreetField = value;
                this.RaisePropertyChanged("CrossStreet");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=34)]
        public string IsWorkRequired {
            get {
                return this.isWorkRequiredField;
            }
            set {
                this.isWorkRequiredField = value;
                this.RaisePropertyChanged("IsWorkRequired");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=35)]
        public string NextReplacementYear {
            get {
                return this.nextReplacementYearField;
            }
            set {
                this.nextReplacementYearField = value;
                this.RaisePropertyChanged("NextReplacementYear");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=36)]
        public string ServiceType {
            get {
                return this.serviceTypeField;
            }
            set {
                this.serviceTypeField = value;
                this.RaisePropertyChanged("ServiceType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=37)]
        public string SerialNumber {
            get {
                return this.serialNumberField;
            }
            set {
                this.serialNumberField = value;
                this.RaisePropertyChanged("SerialNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=38)]
        public string MFGSerialNum {
            get {
                return this.mFGSerialNumField;
            }
            set {
                this.mFGSerialNumField = value;
                this.RaisePropertyChanged("MFGSerialNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=39)]
        public string IsCustomerEnrolledForEmail {
            get {
                return this.isCustomerEnrolledForEmailField;
            }
            set {
                this.isCustomerEnrolledForEmailField = value;
                this.RaisePropertyChanged("IsCustomerEnrolledForEmail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DependencyNode", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=40)]
        public CustomerOrder_FSRInfoMapCall_ResponseResponse_WorkOrderDependencyNode[] DependencyNode {
            get {
                return this.dependencyNodeField;
            }
            set {
                this.dependencyNodeField = value;
                this.RaisePropertyChanged("DependencyNode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SecurityThreatNode", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=41)]
        public CustomerOrder_FSRInfoMapCall_ResponseResponse_WorkOrderSecurityThreatNode[] SecurityThreatNode {
            get {
                return this.securityThreatNodeField;
            }
            set {
                this.securityThreatNodeField = value;
                this.RaisePropertyChanged("SecurityThreatNode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://amwater.com/EAM/0022/MAPCALL/GetCustomerOrderDetails")]
    public partial class CustomerOrder_FSRInfoMapCall_ResponseResponse_WorkOrderDependencyNode : object, System.ComponentModel.INotifyPropertyChanged {
        private string codeGroupField;
        
        private string codeField;
        
        private string codeTextField;
        
        private string dependencyTextField;
        
        private string validDateField;
        
        private string expirationDateField;
        
        private string dependencyIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string CodeGroup {
            get {
                return this.codeGroupField;
            }
            set {
                this.codeGroupField = value;
                this.RaisePropertyChanged("CodeGroup");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string CodeText {
            get {
                return this.codeTextField;
            }
            set {
                this.codeTextField = value;
                this.RaisePropertyChanged("CodeText");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string DependencyText {
            get {
                return this.dependencyTextField;
            }
            set {
                this.dependencyTextField = value;
                this.RaisePropertyChanged("DependencyText");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string ValidDate {
            get {
                return this.validDateField;
            }
            set {
                this.validDateField = value;
                this.RaisePropertyChanged("ValidDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string ExpirationDate {
            get {
                return this.expirationDateField;
            }
            set {
                this.expirationDateField = value;
                this.RaisePropertyChanged("ExpirationDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string DependencyID {
            get {
                return this.dependencyIDField;
            }
            set {
                this.dependencyIDField = value;
                this.RaisePropertyChanged("DependencyID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://amwater.com/EAM/0022/MAPCALL/GetCustomerOrderDetails")]
    public partial class CustomerOrder_FSRInfoMapCall_ResponseResponse_WorkOrderSecurityThreatNode : object, System.ComponentModel.INotifyPropertyChanged {
        private string threat_Notif_NoField;
        
        private string address_securityField;
        
        private string iSPendingInvestigationField;
        
        private string iSPoliceEscortField;
        
        private string creationDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Threat_Notif_No {
            get {
                return this.threat_Notif_NoField;
            }
            set {
                this.threat_Notif_NoField = value;
                this.RaisePropertyChanged("Threat_Notif_No");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Address_security {
            get {
                return this.address_securityField;
            }
            set {
                this.address_securityField = value;
                this.RaisePropertyChanged("Address_security");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string ISPendingInvestigation {
            get {
                return this.iSPendingInvestigationField;
            }
            set {
                this.iSPendingInvestigationField = value;
                this.RaisePropertyChanged("ISPendingInvestigation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string ISPoliceEscort {
            get {
                return this.iSPoliceEscortField;
            }
            set {
                this.iSPoliceEscortField = value;
                this.RaisePropertyChanged("ISPoliceEscort");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string CreationDate {
            get {
                return this.creationDateField;
            }
            set {
                this.creationDateField = value;
                this.RaisePropertyChanged("CreationDate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://amwater.com/EAM/0022/MAPCALL/GetCustomerOrderDetails")]
    public partial class CustomerOrder_FSRInfoResponse_WorkOrder : object, System.ComponentModel.INotifyPropertyChanged {
        private string equipTextField;
        
        private string equipmentIDField;
        
        private string installationDateField;
        
        private string houseNumberField;
        
        private string streetField;
        
        private string cityField;
        
        private string stateField;
        
        private string zipField;
        
        private string latitudeField;
        
        private string longitudeField;
        
        private string safetyConcernDescrField;
        
        private string notificationShortTextField;
        
        private string notificationLongTextField;
        
        private string priorityTextField;
        
        private string companyCodeField;
        
        private string premiseField;
        
        private string createTimeField;
        
        private string createDateField;
        
        private string workOrderField;
        
        private string statusField;
        
        private string basicStartDateField;
        
        private string startTimeField;
        
        private string workOrderTextField;
        
        private string mATCodeField;
        
        private string mATCodeDescField;
        
        private string fSRIDField;
        
        private string fSRNameField;
        
        private string customerNumberField;
        
        private string customerField;
        
        private string customerPhoneField;
        
        private string customerMailingAddressField;
        
        private string isWorkRequiredField;
        
        private string serviceTypeField;
        
        private CustomerOrder_FSRInfoResponse_WorkOrderDependencyNode[] dependencyNodeField;
        
        private CustomerOrder_FSRInfoResponse_WorkOrderSecurityThreatNode[] securityThreatNodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string EquipText {
            get {
                return this.equipTextField;
            }
            set {
                this.equipTextField = value;
                this.RaisePropertyChanged("EquipText");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string EquipmentID {
            get {
                return this.equipmentIDField;
            }
            set {
                this.equipmentIDField = value;
                this.RaisePropertyChanged("EquipmentID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string InstallationDate {
            get {
                return this.installationDateField;
            }
            set {
                this.installationDateField = value;
                this.RaisePropertyChanged("InstallationDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string HouseNumber {
            get {
                return this.houseNumberField;
            }
            set {
                this.houseNumberField = value;
                this.RaisePropertyChanged("HouseNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Street {
            get {
                return this.streetField;
            }
            set {
                this.streetField = value;
                this.RaisePropertyChanged("Street");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("City");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
                this.RaisePropertyChanged("State");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string Zip {
            get {
                return this.zipField;
            }
            set {
                this.zipField = value;
                this.RaisePropertyChanged("Zip");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string Latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
                this.RaisePropertyChanged("Latitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string Longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
                this.RaisePropertyChanged("Longitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string SafetyConcernDescr {
            get {
                return this.safetyConcernDescrField;
            }
            set {
                this.safetyConcernDescrField = value;
                this.RaisePropertyChanged("SafetyConcernDescr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string NotificationShortText {
            get {
                return this.notificationShortTextField;
            }
            set {
                this.notificationShortTextField = value;
                this.RaisePropertyChanged("NotificationShortText");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string NotificationLongText {
            get {
                return this.notificationLongTextField;
            }
            set {
                this.notificationLongTextField = value;
                this.RaisePropertyChanged("NotificationLongText");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string PriorityText {
            get {
                return this.priorityTextField;
            }
            set {
                this.priorityTextField = value;
                this.RaisePropertyChanged("PriorityText");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string CompanyCode {
            get {
                return this.companyCodeField;
            }
            set {
                this.companyCodeField = value;
                this.RaisePropertyChanged("CompanyCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string Premise {
            get {
                return this.premiseField;
            }
            set {
                this.premiseField = value;
                this.RaisePropertyChanged("Premise");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string CreateTime {
            get {
                return this.createTimeField;
            }
            set {
                this.createTimeField = value;
                this.RaisePropertyChanged("CreateTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string CreateDate {
            get {
                return this.createDateField;
            }
            set {
                this.createDateField = value;
                this.RaisePropertyChanged("CreateDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string WorkOrder {
            get {
                return this.workOrderField;
            }
            set {
                this.workOrderField = value;
                this.RaisePropertyChanged("WorkOrder");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string BasicStartDate {
            get {
                return this.basicStartDateField;
            }
            set {
                this.basicStartDateField = value;
                this.RaisePropertyChanged("BasicStartDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public string StartTime {
            get {
                return this.startTimeField;
            }
            set {
                this.startTimeField = value;
                this.RaisePropertyChanged("StartTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public string WorkOrderText {
            get {
                return this.workOrderTextField;
            }
            set {
                this.workOrderTextField = value;
                this.RaisePropertyChanged("WorkOrderText");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public string MATCode {
            get {
                return this.mATCodeField;
            }
            set {
                this.mATCodeField = value;
                this.RaisePropertyChanged("MATCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public string MATCodeDesc {
            get {
                return this.mATCodeDescField;
            }
            set {
                this.mATCodeDescField = value;
                this.RaisePropertyChanged("MATCodeDesc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=25)]
        public string FSRID {
            get {
                return this.fSRIDField;
            }
            set {
                this.fSRIDField = value;
                this.RaisePropertyChanged("FSRID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=26)]
        public string FSRName {
            get {
                return this.fSRNameField;
            }
            set {
                this.fSRNameField = value;
                this.RaisePropertyChanged("FSRName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=27)]
        public string CustomerNumber {
            get {
                return this.customerNumberField;
            }
            set {
                this.customerNumberField = value;
                this.RaisePropertyChanged("CustomerNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=28)]
        public string Customer {
            get {
                return this.customerField;
            }
            set {
                this.customerField = value;
                this.RaisePropertyChanged("Customer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=29)]
        public string CustomerPhone {
            get {
                return this.customerPhoneField;
            }
            set {
                this.customerPhoneField = value;
                this.RaisePropertyChanged("CustomerPhone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=30)]
        public string CustomerMailingAddress {
            get {
                return this.customerMailingAddressField;
            }
            set {
                this.customerMailingAddressField = value;
                this.RaisePropertyChanged("CustomerMailingAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=31)]
        public string IsWorkRequired {
            get {
                return this.isWorkRequiredField;
            }
            set {
                this.isWorkRequiredField = value;
                this.RaisePropertyChanged("IsWorkRequired");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=32)]
        public string ServiceType {
            get {
                return this.serviceTypeField;
            }
            set {
                this.serviceTypeField = value;
                this.RaisePropertyChanged("ServiceType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DependencyNode", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=33)]
        public CustomerOrder_FSRInfoResponse_WorkOrderDependencyNode[] DependencyNode {
            get {
                return this.dependencyNodeField;
            }
            set {
                this.dependencyNodeField = value;
                this.RaisePropertyChanged("DependencyNode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SecurityThreatNode", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=34)]
        public CustomerOrder_FSRInfoResponse_WorkOrderSecurityThreatNode[] SecurityThreatNode {
            get {
                return this.securityThreatNodeField;
            }
            set {
                this.securityThreatNodeField = value;
                this.RaisePropertyChanged("SecurityThreatNode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://amwater.com/EAM/0022/MAPCALL/GetCustomerOrderDetails")]
    public partial class CustomerOrder_FSRInfoResponse_WorkOrderDependencyNode : object, System.ComponentModel.INotifyPropertyChanged {
        private string codeGroupField;
        
        private string codeField;
        
        private string codeTextField;
        
        private string dependencyTextField;
        
        private string validDateField;
        
        private string expirationDateField;
        
        private string dependencyIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string CodeGroup {
            get {
                return this.codeGroupField;
            }
            set {
                this.codeGroupField = value;
                this.RaisePropertyChanged("CodeGroup");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string CodeText {
            get {
                return this.codeTextField;
            }
            set {
                this.codeTextField = value;
                this.RaisePropertyChanged("CodeText");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string DependencyText {
            get {
                return this.dependencyTextField;
            }
            set {
                this.dependencyTextField = value;
                this.RaisePropertyChanged("DependencyText");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string ValidDate {
            get {
                return this.validDateField;
            }
            set {
                this.validDateField = value;
                this.RaisePropertyChanged("ValidDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string ExpirationDate {
            get {
                return this.expirationDateField;
            }
            set {
                this.expirationDateField = value;
                this.RaisePropertyChanged("ExpirationDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string DependencyID {
            get {
                return this.dependencyIDField;
            }
            set {
                this.dependencyIDField = value;
                this.RaisePropertyChanged("DependencyID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://amwater.com/EAM/0022/MAPCALL/GetCustomerOrderDetails")]
    public partial class CustomerOrder_FSRInfoResponse_WorkOrderSecurityThreatNode : object, System.ComponentModel.INotifyPropertyChanged {
        private string threat_Notif_NoField;
        
        private string address_securityField;
        
        private string iSPendingInvestigationField;
        
        private string iSPoliceEscortField;
        
        private string creationDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Threat_Notif_No {
            get {
                return this.threat_Notif_NoField;
            }
            set {
                this.threat_Notif_NoField = value;
                this.RaisePropertyChanged("Threat_Notif_No");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Address_security {
            get {
                return this.address_securityField;
            }
            set {
                this.address_securityField = value;
                this.RaisePropertyChanged("Address_security");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string ISPendingInvestigation {
            get {
                return this.iSPendingInvestigationField;
            }
            set {
                this.iSPendingInvestigationField = value;
                this.RaisePropertyChanged("ISPendingInvestigation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string ISPoliceEscort {
            get {
                return this.iSPoliceEscortField;
            }
            set {
                this.iSPoliceEscortField = value;
                this.RaisePropertyChanged("ISPoliceEscort");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string CreationDate {
            get {
                return this.creationDateField;
            }
            set {
                this.creationDateField = value;
                this.RaisePropertyChanged("CreationDate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://amwater.com/EAM/0022/MAPCALL/GetCustomerOrderDetails")]
    public partial class CustomerOrder_FSRQueryDailySchedule : object, System.ComponentModel.INotifyPropertyChanged {
        private string orderTypeField;
        
        private string dateField;
        
        private string companyCodeField;
        
        private string planningPlantField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string OrderType {
            get {
                return this.orderTypeField;
            }
            set {
                this.orderTypeField = value;
                this.RaisePropertyChanged("OrderType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
                this.RaisePropertyChanged("Date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string CompanyCode {
            get {
                return this.companyCodeField;
            }
            set {
                this.companyCodeField = value;
                this.RaisePropertyChanged("CompanyCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string PlanningPlant {
            get {
                return this.planningPlantField;
            }
            set {
                this.planningPlantField = value;
                this.RaisePropertyChanged("PlanningPlant");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CustomerOrder_FSR_Get_OB_SYNRequest {
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://amwater.com/EAM/0022/MAPCALL/GetCustomerOrderDetails", Order=0)]
        public MapCall.SAP.CustomerOrder.CustomerOrder_FSRQuery CustomerOrder_FSRRequest;
        
        public CustomerOrder_FSR_Get_OB_SYNRequest() {
        }
        
        public CustomerOrder_FSR_Get_OB_SYNRequest(MapCall.SAP.CustomerOrder.CustomerOrder_FSRQuery CustomerOrder_FSRRequest) {
            this.CustomerOrder_FSRRequest = CustomerOrder_FSRRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CustomerOrder_FSR_Get_OB_SYNResponse {
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://amwater.com/EAM/0022/MAPCALL/GetCustomerOrderDetails", Order=0)]
        public MapCall.SAP.CustomerOrder.CustomerOrder_FSRInfo CustomerOrder_FSRResponse;
        
        public CustomerOrder_FSR_Get_OB_SYNResponse() {
        }
        
        public CustomerOrder_FSR_Get_OB_SYNResponse(MapCall.SAP.CustomerOrder.CustomerOrder_FSRInfo CustomerOrder_FSRResponse) {
            this.CustomerOrder_FSRResponse = CustomerOrder_FSRResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CustomerOrder_FSR_Get_OB_SYNChannel : MapCall.SAP.CustomerOrder.CustomerOrder_FSR_Get_OB_SYN, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CustomerOrder_FSR_Get_OB_SYNClient : System.ServiceModel.ClientBase<MapCall.SAP.CustomerOrder.CustomerOrder_FSR_Get_OB_SYN>, MapCall.SAP.CustomerOrder.CustomerOrder_FSR_Get_OB_SYN {
        public CustomerOrder_FSR_Get_OB_SYNClient() {
        }
        
        public CustomerOrder_FSR_Get_OB_SYNClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CustomerOrder_FSR_Get_OB_SYNClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerOrder_FSR_Get_OB_SYNClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerOrder_FSR_Get_OB_SYNClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MapCall.SAP.CustomerOrder.CustomerOrder_FSR_Get_OB_SYNResponse MapCall.SAP.CustomerOrder.CustomerOrder_FSR_Get_OB_SYN.CustomerOrder_FSR_Get_OB_SYN(MapCall.SAP.CustomerOrder.CustomerOrder_FSR_Get_OB_SYNRequest request) {
            return base.Channel.CustomerOrder_FSR_Get_OB_SYN(request);
        }
        
        public MapCall.SAP.CustomerOrder.CustomerOrder_FSRInfo CustomerOrder_FSR_Get_OB_SYN(MapCall.SAP.CustomerOrder.CustomerOrder_FSRQuery CustomerOrder_FSRRequest) {
            MapCall.SAP.CustomerOrder.CustomerOrder_FSR_Get_OB_SYNRequest inValue = new MapCall.SAP.CustomerOrder.CustomerOrder_FSR_Get_OB_SYNRequest();
            inValue.CustomerOrder_FSRRequest = CustomerOrder_FSRRequest;
            MapCall.SAP.CustomerOrder.CustomerOrder_FSR_Get_OB_SYNResponse retVal = ((MapCall.SAP.CustomerOrder.CustomerOrder_FSR_Get_OB_SYN)(this)).CustomerOrder_FSR_Get_OB_SYN(inValue);
            return retVal.CustomerOrder_FSRResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MapCall.SAP.CustomerOrder.CustomerOrder_FSR_Get_OB_SYNResponse> MapCall.SAP.CustomerOrder.CustomerOrder_FSR_Get_OB_SYN.CustomerOrder_FSR_Get_OB_SYNAsync(MapCall.SAP.CustomerOrder.CustomerOrder_FSR_Get_OB_SYNRequest request) {
            return base.Channel.CustomerOrder_FSR_Get_OB_SYNAsync(request);
        }
        
        public System.Threading.Tasks.Task<MapCall.SAP.CustomerOrder.CustomerOrder_FSR_Get_OB_SYNResponse> CustomerOrder_FSR_Get_OB_SYNAsync(MapCall.SAP.CustomerOrder.CustomerOrder_FSRQuery CustomerOrder_FSRRequest) {
            MapCall.SAP.CustomerOrder.CustomerOrder_FSR_Get_OB_SYNRequest inValue = new MapCall.SAP.CustomerOrder.CustomerOrder_FSR_Get_OB_SYNRequest();
            inValue.CustomerOrder_FSRRequest = CustomerOrder_FSRRequest;
            return ((MapCall.SAP.CustomerOrder.CustomerOrder_FSR_Get_OB_SYN)(this)).CustomerOrder_FSR_Get_OB_SYNAsync(inValue);
        }
    }
}
