//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MapCall.SAP.CreateUnscheduledWOWS
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://amwater.com/EAM/0007/MAPCALL/CreateWorkOrder", ConfigurationName="CreateUnscheduledWOWS.CreateUnscheduledWO_OB_SYN")]
    public interface CreateUnscheduledWO_OB_SYN {
        // CODEGEN: Generating message contract since the operation CreateUnscheduledWO_OB_SYN is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MapCall.SAP.CreateUnscheduledWOWS.CreateUnscheduledWO_OB_SYNResponse CreateUnscheduledWO_OB_SYN(MapCall.SAP.CreateUnscheduledWOWS.CreateUnscheduledWO_OB_SYNRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        System.Threading.Tasks.Task<MapCall.SAP.CreateUnscheduledWOWS.CreateUnscheduledWO_OB_SYNResponse> CreateUnscheduledWO_OB_SYNAsync(MapCall.SAP.CreateUnscheduledWOWS.CreateUnscheduledWO_OB_SYNRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://amwater.com/EAM/0007/MAPCALL/CreateWorkOrder")]
    public partial class CreateUnscheduledWOWorkOrder : object, System.ComponentModel.INotifyPropertyChanged {
        private string orderTypeField;
        
        private string priorityField;
        
        private string functionalLocationField;
        
        private string equipmentField;
        
        private string shortTextField;
        
        private string longTextField;
        
        private string maintenanceActivityTypeField;
        
        private string basicStartDateField;
        
        private string operationField;
        
        private string operationDurationField;
        
        private string purposeField;
        
        private string purposeCodeField;
        
        private string permitsField;
        
        private string breakDownIndicatorField;
        
        private string settlementReceiverField;
        
        private string employeeField;
        
        private string personResponsibleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string OrderType {
            get {
                return this.orderTypeField;
            }
            set {
                this.orderTypeField = value;
                this.RaisePropertyChanged("OrderType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Priority {
            get {
                return this.priorityField;
            }
            set {
                this.priorityField = value;
                this.RaisePropertyChanged("Priority");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string FunctionalLocation {
            get {
                return this.functionalLocationField;
            }
            set {
                this.functionalLocationField = value;
                this.RaisePropertyChanged("FunctionalLocation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Equipment {
            get {
                return this.equipmentField;
            }
            set {
                this.equipmentField = value;
                this.RaisePropertyChanged("Equipment");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string ShortText {
            get {
                return this.shortTextField;
            }
            set {
                this.shortTextField = value;
                this.RaisePropertyChanged("ShortText");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string LongText {
            get {
                return this.longTextField;
            }
            set {
                this.longTextField = value;
                this.RaisePropertyChanged("LongText");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string MaintenanceActivityType {
            get {
                return this.maintenanceActivityTypeField;
            }
            set {
                this.maintenanceActivityTypeField = value;
                this.RaisePropertyChanged("MaintenanceActivityType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string BasicStartDate {
            get {
                return this.basicStartDateField;
            }
            set {
                this.basicStartDateField = value;
                this.RaisePropertyChanged("BasicStartDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string Operation {
            get {
                return this.operationField;
            }
            set {
                this.operationField = value;
                this.RaisePropertyChanged("Operation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string OperationDuration {
            get {
                return this.operationDurationField;
            }
            set {
                this.operationDurationField = value;
                this.RaisePropertyChanged("OperationDuration");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string Purpose {
            get {
                return this.purposeField;
            }
            set {
                this.purposeField = value;
                this.RaisePropertyChanged("Purpose");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string PurposeCode {
            get {
                return this.purposeCodeField;
            }
            set {
                this.purposeCodeField = value;
                this.RaisePropertyChanged("PurposeCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string Permits {
            get {
                return this.permitsField;
            }
            set {
                this.permitsField = value;
                this.RaisePropertyChanged("Permits");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string BreakDownIndicator {
            get {
                return this.breakDownIndicatorField;
            }
            set {
                this.breakDownIndicatorField = value;
                this.RaisePropertyChanged("BreakDownIndicator");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string SettlementReceiver {
            get {
                return this.settlementReceiverField;
            }
            set {
                this.settlementReceiverField = value;
                this.RaisePropertyChanged("SettlementReceiver");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string Employee {
            get {
                return this.employeeField;
            }
            set {
                this.employeeField = value;
                this.RaisePropertyChanged("Employee");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string PersonResponsible {
            get {
                return this.personResponsibleField;
            }
            set {
                this.personResponsibleField = value;
                this.RaisePropertyChanged("PersonResponsible");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://amwater.com/EAM/0007/MAPCALL/CreateWorkOrder")]
    public partial class UnscheduledWOStatus : object, System.ComponentModel.INotifyPropertyChanged {
        private UnscheduledWOStatusStatus[] statusField;
        
        private string sAPStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Status", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public UnscheduledWOStatusStatus[] Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string SAPStatus {
            get {
                return this.sAPStatusField;
            }
            set {
                this.sAPStatusField = value;
                this.RaisePropertyChanged("SAPStatus");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://amwater.com/EAM/0007/MAPCALL/CreateWorkOrder")]
    public partial class UnscheduledWOStatusStatus : object, System.ComponentModel.INotifyPropertyChanged {
        private string sAPOrderNumberField;
        
        private string sAPNotificationNumberField;
        
        private string wBSElementField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string SAPOrderNumber {
            get {
                return this.sAPOrderNumberField;
            }
            set {
                this.sAPOrderNumberField = value;
                this.RaisePropertyChanged("SAPOrderNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string SAPNotificationNumber {
            get {
                return this.sAPNotificationNumberField;
            }
            set {
                this.sAPNotificationNumberField = value;
                this.RaisePropertyChanged("SAPNotificationNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string WBSElement {
            get {
                return this.wBSElementField;
            }
            set {
                this.wBSElementField = value;
                this.RaisePropertyChanged("WBSElement");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateUnscheduledWO_OB_SYNRequest {
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://amwater.com/EAM/0007/MAPCALL/CreateWorkOrder", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("WorkOrder", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public MapCall.SAP.CreateUnscheduledWOWS.CreateUnscheduledWOWorkOrder[] UnscheduledWORequest;
        
        public CreateUnscheduledWO_OB_SYNRequest() {
        }
        
        public CreateUnscheduledWO_OB_SYNRequest(MapCall.SAP.CreateUnscheduledWOWS.CreateUnscheduledWOWorkOrder[] UnscheduledWORequest) {
            this.UnscheduledWORequest = UnscheduledWORequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateUnscheduledWO_OB_SYNResponse {
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://amwater.com/EAM/0007/MAPCALL/CreateWorkOrder", Order=0)]
        public MapCall.SAP.CreateUnscheduledWOWS.UnscheduledWOStatus UnscheduledWOResponse;
        
        public CreateUnscheduledWO_OB_SYNResponse() {
        }
        
        public CreateUnscheduledWO_OB_SYNResponse(MapCall.SAP.CreateUnscheduledWOWS.UnscheduledWOStatus UnscheduledWOResponse) {
            this.UnscheduledWOResponse = UnscheduledWOResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CreateUnscheduledWO_OB_SYNChannel : MapCall.SAP.CreateUnscheduledWOWS.CreateUnscheduledWO_OB_SYN, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CreateUnscheduledWO_OB_SYNClient : System.ServiceModel.ClientBase<MapCall.SAP.CreateUnscheduledWOWS.CreateUnscheduledWO_OB_SYN>, MapCall.SAP.CreateUnscheduledWOWS.CreateUnscheduledWO_OB_SYN {
        public CreateUnscheduledWO_OB_SYNClient() {
        }
        
        public CreateUnscheduledWO_OB_SYNClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CreateUnscheduledWO_OB_SYNClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CreateUnscheduledWO_OB_SYNClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CreateUnscheduledWO_OB_SYNClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MapCall.SAP.CreateUnscheduledWOWS.CreateUnscheduledWO_OB_SYNResponse MapCall.SAP.CreateUnscheduledWOWS.CreateUnscheduledWO_OB_SYN.CreateUnscheduledWO_OB_SYN(MapCall.SAP.CreateUnscheduledWOWS.CreateUnscheduledWO_OB_SYNRequest request) {
            return base.Channel.CreateUnscheduledWO_OB_SYN(request);
        }
        
        public MapCall.SAP.CreateUnscheduledWOWS.UnscheduledWOStatus CreateUnscheduledWO_OB_SYN(MapCall.SAP.CreateUnscheduledWOWS.CreateUnscheduledWOWorkOrder[] UnscheduledWORequest) {
            MapCall.SAP.CreateUnscheduledWOWS.CreateUnscheduledWO_OB_SYNRequest inValue = new MapCall.SAP.CreateUnscheduledWOWS.CreateUnscheduledWO_OB_SYNRequest();
            inValue.UnscheduledWORequest = UnscheduledWORequest;
            MapCall.SAP.CreateUnscheduledWOWS.CreateUnscheduledWO_OB_SYNResponse retVal = ((MapCall.SAP.CreateUnscheduledWOWS.CreateUnscheduledWO_OB_SYN)(this)).CreateUnscheduledWO_OB_SYN(inValue);
            return retVal.UnscheduledWOResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MapCall.SAP.CreateUnscheduledWOWS.CreateUnscheduledWO_OB_SYNResponse> MapCall.SAP.CreateUnscheduledWOWS.CreateUnscheduledWO_OB_SYN.CreateUnscheduledWO_OB_SYNAsync(MapCall.SAP.CreateUnscheduledWOWS.CreateUnscheduledWO_OB_SYNRequest request) {
            return base.Channel.CreateUnscheduledWO_OB_SYNAsync(request);
        }
        
        public System.Threading.Tasks.Task<MapCall.SAP.CreateUnscheduledWOWS.CreateUnscheduledWO_OB_SYNResponse> CreateUnscheduledWO_OB_SYNAsync(MapCall.SAP.CreateUnscheduledWOWS.CreateUnscheduledWOWorkOrder[] UnscheduledWORequest) {
            MapCall.SAP.CreateUnscheduledWOWS.CreateUnscheduledWO_OB_SYNRequest inValue = new MapCall.SAP.CreateUnscheduledWOWS.CreateUnscheduledWO_OB_SYNRequest();
            inValue.UnscheduledWORequest = UnscheduledWORequest;
            return ((MapCall.SAP.CreateUnscheduledWOWS.CreateUnscheduledWO_OB_SYN)(this)).CreateUnscheduledWO_OB_SYNAsync(inValue);
        }
    }
}
