//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace LINQTo271.Views.Restorations {
    
    
    public partial class RestorationReadOnlyDetailView {
        
        /// <summary>
        /// fvRestoration control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::LINQTo271.Common.WorkOrdersFormView fvRestoration;
        
        /// <summary>
        /// odsRestoration control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MMSINC.Controls.MvpObjectContainerDataSource odsRestoration;
    }
}
