using FluentMigrator;

namespace MapCall.Common.Model.Migrations._2017
{
    [Migration(20170705093803454), Tags("Production")]
    public class PutSomeBacterialSampleTypesBackForBug3904 : Migration
    {
        public override void Up()
        {
            Execute.Sql(@"set identity_insert BacterialSampleTypes ON;

insert into BacterialSampleTypes (Id, Description) VALUES (2, 'Process Control');
insert into BacterialSampleTypes (Id, Description) VALUES (3, 'New Main');
insert into BacterialSampleTypes (Id, Description) VALUES (5, 'System Repair');

set identity_insert BacterialSampleTypes OFF;");

            Execute.Sql("UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 22150;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 22178;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 22179;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 22180;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 22181;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 22182;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 22184;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 22185;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 22186;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 22201;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 22271;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 22272;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 22368;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 22388;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 22402;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 22438;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 22440;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 22484;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 22485;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 22486;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 22487;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 22488;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 22489;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 22490;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 22491;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 22492;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 22493;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 22494;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 22540;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 22542;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 22543;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 22544;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 22581;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 22592;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 22593;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 22594;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 22595;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 22596;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 22597;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 22640;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 22693;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 22694;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 22695;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 22696;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 22697;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 22698;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 22732;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 22733;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 22734;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 22736;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 22775;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 22784;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 22785;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 22786;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 22787;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 22788;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 22789;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 22946;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 22947;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 22948;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 23039;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 23040;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 23041;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 23042;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 23138;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 23218;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 23255;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 23277;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 23304;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 23307;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 23554;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 23630;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 23687;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 23764;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 23835;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 23915;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 23917;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 23918;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 23922;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 23988;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 24101;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 24256;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 24339;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 24340;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 24757;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 24840;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 24841;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 24842;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 24843;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 24844;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 24845;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 24846;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 24847;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 24848;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 24849;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 24850;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 24851;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 24852;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 24853;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 25024;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 25025;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 25026;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 25027;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 25028;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 25029;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 25030;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 25031;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 25032;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 25033;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 25034;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 25035;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 25036;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 25037;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 25038;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 25271;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 25272;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 25273;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 25274;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 25275;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 25276;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 25277;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 25278;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 25279;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 25280;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 25281;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 25343;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 25344;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 25345;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 25346;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 25347;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 25348;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 25349;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 25350;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 25351;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 25352;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 25487;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 25488;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 25489;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 25490;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 25491;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 25492;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 25494;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 25496;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 25498;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 25503;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 25506;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 25509;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 25511;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 25682;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 25683;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 25684;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 25685;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 25686;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 25687;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 25688;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 25689;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 25690;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 25691;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 25692;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 25693;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 25695;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 25697;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 25858;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 25859;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 25860;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 25861;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 25862;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 25863;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 25864;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 25865;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 25866;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 25867;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 25869;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 25870;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 25871;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 25900;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 25901;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 25989;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 25990;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 25991;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 25992;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 25993;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 25994;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 25995;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 25996;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 25997;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 25998;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 25999;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 26000;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 26001;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 26002;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 26003;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 26083;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 26084;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 26085;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 26086;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 26087;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 26088;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 26089;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 26090;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 26091;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 26092;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 26093;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 26094;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 26095;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 26563;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 26564;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 26565;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 26566;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 26567;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 26568;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 26569;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 26570;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 26571;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 26572;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 26573;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 26670;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 26671;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 26672;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 26673;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 26674;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 26675;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 26676;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 26677;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 26678;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 26679;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 26680;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 26681;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 26682;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 27024;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 27025;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 27026;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 27027;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 27028;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 27029;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 27030;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 27031;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 27032;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 27033;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 27034;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 27035;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 27036;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 27254;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 27255;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 27256;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 27258;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 27259;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 27260;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 27261;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 27262;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 27263;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 27264;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 27265;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 27266;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 27267;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 27298;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 27299;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 27300;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 27301;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 27302;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 27303;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 27304;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 27305;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 27306;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 27307;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 27308;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 27309;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 27310;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 27311;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 27386;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 27387;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 27388;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 27389;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 27390;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 27428;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 27436;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 27437;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 27438;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 27439;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 27440;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 27441;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 27442;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 27443;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 27444;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 27446;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 27540;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 27541;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 27542;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 27543;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 27544;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 27545;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 27546;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 27547;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 27548;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 27549;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 27550;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 27551;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 27552;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 27553;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 27640;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 27641;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 27647;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 27651;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 28110;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 28111;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 28112;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 28113;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 28114;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 28115;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 28116;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 28117;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 28118;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 28119;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 28120;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 28532;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 28825;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 28826;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 28829;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 28831;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 29137;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 29138;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 29139;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 29140;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 29141;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 29142;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 29143;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 29144;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 29145;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 29146;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 29147;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 29338;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 29339;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 29340;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 29342;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 29343;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 29344;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 29345;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 29346;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 29347;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 29488;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 29489;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 29491;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 29648;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 29649;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 29650;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 29651;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 29652;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 29654;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 29655;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 29656;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 29657;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 29658;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 29659;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 29660;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 29812;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 29814;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 29815;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 29817;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 29819;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 29820;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 29823;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 29825;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 29827;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 29828;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 29829;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 29830;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 29831;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 30078;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 30081;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 30082;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 30083;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 30084;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 30085;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 30086;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 30160;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 30229;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 30230;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 30231;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 30232;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 30233;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 30341;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 30342;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 30344;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 30347;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 30348;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 30349;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 30364;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 30422;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 30687;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 30734;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 30741;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 30742;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 30775;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 30777;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 30810;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 30812;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 30814;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 30815;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 30816;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 30817;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 30818;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 30820;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 30821;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 30826;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 30827;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 30828;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 30835;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 30843;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 30875;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 30880;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 30966;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 30999;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 31014;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 31068;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 31111;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 31112;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 31113;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 31114;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 31117;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 31118;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 31119;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 31120;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 31121;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 31232;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 31233;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 31234;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 31235;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 31236;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 31237;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 31238;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 31239;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 31240;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 31241;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 31242;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 31243;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 31244;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 31251;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 31280;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 31401;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 31402;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 31403;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 31404;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 31405;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 31406;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 31407;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 31410;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 31411;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 31412;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 31429;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 31520;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 31743;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 31815;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 31816;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 31817;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 31818;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 31820;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 31821;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 31822;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 31823;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 31824;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 31909;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 31942;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 31997;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 32039;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 32047;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 32050;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 32051;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 32054;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 32056;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 32058;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 32059;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 32061;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 32062;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 32063;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 32064;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 32122;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 32174;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 32230;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 32268;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 32367;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 32374;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 32618;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 32652;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 32751;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 33024;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 33065;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 33275;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 33301;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 33313;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 33562;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 33619;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 33639;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 33704;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 33775;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 33821;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 33880;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 33977;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 34039;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 34123;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 34215;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 34229;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 34305;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 34309;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 34384;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 34433;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 34446;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 34500;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 34501;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 34625;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 34698;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 34701;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 34770;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 34779;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 34899;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 34901;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 34980;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 34983;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 35051;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 35054;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 35109;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 35117;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 35186;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 35207;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 35254;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 35267;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 35327;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 35401;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 35409;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 35459;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 35558;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 35729;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 35788;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 35866;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 35978;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 36028;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 36105;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 36114;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 36177;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 36187;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 36261;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 36341;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 36343;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 36422;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 36426;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 36482;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 36487;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 36539;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 36595;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 36666;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 36716;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 36782;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 36788;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 36861;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 36895;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 36982;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 37037;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 37047;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 37143;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 37189;" +
                        "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = 2 WHERE Id = 37223;");
        }

        public override void Down()
        {
            Execute.Sql(
                "UPDATE BacterialWaterSamples SET BacterialSampleTypeId = NULL WHERE BacterialSampleTypeId = 2");
            Execute.Sql("DELETE FROM BacterialSampleTypes WHERE ID IN (2, 3, 5)");
        }
    }
}
