using FluentMigrator;
using MapCall.Common.ClassExtensions;
using MMSINC.ClassExtensions.FluentMigratorExtensions;

namespace MapCall.Common.Model.Migrations._2020
{
    [Migration(20200904121712974), Tags("Production")]
    public class AddSewerAuthorityCodesToShortCycleForMC2583 : Migration
    {
        public override void Up()
        {
            this.Create.LookupTable("SewerAuthorityCodes", 50)
                .WithColumn("SAPCode").AsAnsiString(10).NotNullable();
            InsertSewerAuthorityCodes();
            Alter.Table("ShortCycleWorkOrders")
                 .AddForeignKeyColumn("CriticalCareTypeId", "PremiseCriticalCareTypes")
                 .AddForeignKeyColumn("SewerAuthorityCode1Id", "SewerAuthorityCodes")
                 .AddForeignKeyColumn("SewerAuthorityCode2Id", "SewerAuthorityCodes")
                 .AddForeignKeyColumn("SewerAuthorityCode3Id", "SewerAuthorityCodes");
        }

        private void InsertSewerAuthorityCodes()
        {
            InsertSewerAuthorityCode("CACHLVISTA", "City of Chula Vista");
            InsertSewerAuthorityCode("CACORONADO", "City of Coronado");
            InsertSewerAuthorityCode("CAH2OWSLAC", "CAAW WaterSmart - LA Countym");
            InsertSewerAuthorityCode("CAH2OWSVEN", "CAAW WaterSmart - Ventura");
            InsertSewerAuthorityCode("CAIMPLBCH", "City of Imperial Beach");
            InsertSewerAuthorityCode("CAISLETON", "City of Isleton");
            InsertSewerAuthorityCode("CAMONTARA", "Montara Sewer District");
            InsertSewerAuthorityCode("CAMONTEREY", "Monterey Peninsula Water Mngt");
            InsertSewerAuthorityCode("CASANDIEGO", "City of San Diego");
            InsertSewerAuthorityCode("CASNMARINO", "City of San Marino");
            InsertSewerAuthorityCode("CATHSOAKS", "City of Thousand Oaks");
            InsertSewerAuthorityCode("EXEMPT_BFV", "Exempt from usage data-Bluefld");
            InsertSewerAuthorityCode("EXEMPT_CA", "Exempt from usage data- Califo");
            InsertSewerAuthorityCode("EXEMPT_HI", "Exempt from usage data- Hawaii");
            InsertSewerAuthorityCode("EXEMPT_IA", "Exempt from usage data- Iowa");
            InsertSewerAuthorityCode("EXEMPT_IL", "Exempt from usage data- Illino");
            InsertSewerAuthorityCode("EXEMPT_IN", "Exempt from usage data- Indian");
            InsertSewerAuthorityCode("EXEMPT_KY", "Exempt from usage data- Kentuc");
            InsertSewerAuthorityCode("EXEMPT_MD", "Exempt from usage data- Maryla");
            InsertSewerAuthorityCode("EXEMPT_MO", "Exempt from usage data- Missou");
            InsertSewerAuthorityCode("EXEMPT_NJ", "Exempt from usage data- New Je");
            InsertSewerAuthorityCode("EXEMPT_NY", "Exempt from usage data- New Yo");
            InsertSewerAuthorityCode("EXEMPT_PA", "Exempt from usage data- Pennsy");
            InsertSewerAuthorityCode("EXEMPT_TN", "Exempt from usage data- Tennes");
            InsertSewerAuthorityCode("EXEMPT_VA", "Exempt from usage data- Virgin");
            InsertSewerAuthorityCode("EXEMPT_WV", "Exempt from usage data- West V");
            InsertSewerAuthorityCode("IABETNDORF", "City of Bettendorf");
            InsertSewerAuthorityCode("IABLUEGRAS", "City of Blue Grass");
            InsertSewerAuthorityCode("IACLINTON", "City of Clinton");
            InsertSewerAuthorityCode("IADAVNPORT", "City of Davenport");
            InsertSewerAuthorityCode("IADIXON", "Dixon");
            InsertSewerAuthorityCode("IALECLAIRE", "City of LeClaire");
            InsertSewerAuthorityCode("IARIVERDLE", "City of Riverdale");
            InsertSewerAuthorityCode("ILALTON", "Alton");
            InsertSewerAuthorityCode("ILALTONCTY", "City of Alton");
            InsertSewerAuthorityCode("ILALTONRES", "Alton Fix");
            InsertSewerAuthorityCode("ILAMERBOTM", "American Bottoms");
            InsertSewerAuthorityCode("ILBELVILLE", "Belleville");
            InsertSewerAuthorityCode("ILBOLINBRK", "Village of Bolingbrook");
            InsertSewerAuthorityCode("ILBROOKLYN", "Brooklyn IL");
            InsertSewerAuthorityCode("ILCAIRO", "Cairo Public Utility");
            InsertSewerAuthorityCode("ILCASYVIL", "Caseyville");
            InsertSewerAuthorityCode("ILCENTRVLC", "Centerville City Hall");
            InsertSewerAuthorityCode("ILCHAMPGN", "Champaign");
            InsertSewerAuthorityCode("ILCOLUMBIA", "City of Columbia");
            InsertSewerAuthorityCode("ILCOMNFLDS", "Commonfields of Cahokia Public");
            InsertSewerAuthorityCode("ILDUPGEPW", "Dupage Co Public Works");
            InsertSewerAuthorityCode("ILESTLOUIS", "City of East St Louis");
            InsertSewerAuthorityCode("ILFAIRMONT", "Village of Fairmont");
            InsertSewerAuthorityCode("ILFARMINGN", "Farmington");
            InsertSewerAuthorityCode("ILGODFREY", "Village of Godfrey");
            InsertSewerAuthorityCode("ILGRAFTON", "City of Grafton");
            InsertSewerAuthorityCode("ILGRANITE", "Granite City");
            InsertSewerAuthorityCode("ILGRANTOIR", "Granite City OIR only");
            InsertSewerAuthorityCode("ILLINCOLN", "Lincoln Village");
            InsertSewerAuthorityCode("ILLOMBARD", "Village of Lombard");
            InsertSewerAuthorityCode("ILMADISON", "Madison County Special Sewer A");
            InsertSewerAuthorityCode("ILMETROEST", "Metro East Sanitation");
            InsertSewerAuthorityCode("ILPEKIN", "City of Pekin");
            InsertSewerAuthorityCode("ILPEORIA", "Peoria");
            InsertSewerAuthorityCode("ILPONTIAC", "Pontiac");
            InsertSewerAuthorityCode("ILREADINGT", "Reading Township Sewer");
            InsertSewerAuthorityCode("ILROMEOVIL", "City of Romeoville");
            InsertSewerAuthorityCode("ILSALTCREK", "Salt Creek Sanitary");
            InsertSewerAuthorityCode("ILSAUNEMIN", "village of Saunemin");
            InsertSewerAuthorityCode("ILSHILOH", "City of Shiloh");
            InsertSewerAuthorityCode("ILSOBELOIT", "South Beloit");
            InsertSewerAuthorityCode("ILSTCLRTWP", "St Clair Township");
            InsertSewerAuthorityCode("ILSTERLING", "Sterling");
            InsertSewerAuthorityCode("ILSTJOSEPH", "Village of St Joseph");
            InsertSewerAuthorityCode("ILSTOOKEY", "Stookey");
            InsertSewerAuthorityCode("ILSTREATOR", "Streator");
            InsertSewerAuthorityCode("ILSWANSEA", "Swansea");
            InsertSewerAuthorityCode("ILWHTNARRD", "Wheaton Arrowhead");
            InsertSewerAuthorityCode("ILWHTNLBRD", "Wheaton Liberty Ridge");
            InsertSewerAuthorityCode("ILWHTNWTR", "Wheaton Water");
            InsertSewerAuthorityCode("ILWOODRI", "Wood River Township");
            InsertSewerAuthorityCode("INAMSUBUTL", "Am Suburban Utilities");
            InsertSewerAuthorityCode("INBRNSHBR", "Town of Burns Harbour");
            InsertSewerAuthorityCode("INCHRLSTON", "City of Charlestown Utilities");
            InsertSewerAuthorityCode("INCHSTRTON", "Chesterton Utilities");
            InsertSewerAuthorityCode("INCITPLSNT", "CITIZENS PLEASANT VALLEY");
            InsertSewerAuthorityCode("INCLRKSVLE", "Clarksville Waste Treatment");
            InsertSewerAuthorityCode("INCRAWFVLL", "City of Crawfordsville");
            InsertSewerAuthorityCode("INDAMONRUN", "Damon Run");
            InsertSewerAuthorityCode("INFARMSBRG", "Town of Farmersburg");
            InsertSewerAuthorityCode("INFLWWELLS", "Flowing Wells");
            InsertSewerAuthorityCode("INFRANKLIN", "City Of Franklin");
            InsertSewerAuthorityCode("INFRANKRES", "City of Franklin IN - RES");
            InsertSewerAuthorityCode("INGARYSAN", "Gary Sanitary District");
            InsertSewerAuthorityCode("INGEORGETO", "Georgetown");
            InsertSewerAuthorityCode("INGRNWOOD", "Greenwood Sanitation Dept");
            InsertSewerAuthorityCode("INHOBART", "Hobart Sanitary");
            InsertSewerAuthorityCode("ININDEPHIL", "Independence Hill");
            InsertSewerAuthorityCode("INJAKSNCTY", "Jackson County");
            InsertSewerAuthorityCode("INJEFSNVIL", "City Of Jeffersonville");
            InsertSewerAuthorityCode("INKOKOMO", "Kokomo Municipal Sanitation");
            InsertSewerAuthorityCode("INLKSTAION", "City of Lake Stiation Sewer");
            InsertSewerAuthorityCode("INMERLVILE", "Merrillville Conservancy");
            InsertSewerAuthorityCode("INMOORSVIL", "Mooresville Sewage");
            InsertSewerAuthorityCode("INMUNCIE", "Muncie Sanitary District");
            InsertSewerAuthorityCode("INNEWALBNY", "New Albany Municipal Utilities");
            InsertSewerAuthorityCode("INNEWBURGH", "Town of Newburgh");
            InsertSewerAuthorityCode("INNOBLSVIL", "City of Noblesville Wastewater");
            InsertSewerAuthorityCode("INPORTAGE", "Portage Utilities Service");
            InsertSewerAuthorityCode("INPORTER", "Town of Porter");
            InsertSewerAuthorityCode("INRICHMOND", "City of Richmond");
            InsertSewerAuthorityCode("INRUSSIAVL", "Town of Russiaville");
            InsertSewerAuthorityCode("INSELMA", "Selma");
            InsertSewerAuthorityCode("INSEYMOUR", "City of Seymour Sewer");
            InsertSewerAuthorityCode("INSHELBURN", "Town of Shelburn");
            InsertSewerAuthorityCode("INSHLBYVIL", "City of Shelbyville");
            InsertSewerAuthorityCode("INSHORWOOD", "Shorewood Sanitary");
            InsertSewerAuthorityCode("INSOHAVEN", "South Haven Sewer Works");
            InsertSewerAuthorityCode("INSULLIVAN", "City of Sullivan");
            InsertSewerAuthorityCode("INTERRHAUT", "City of Terre Haute");
            InsertSewerAuthorityCode("INWABASH", "City of Wabash");
            InsertSewerAuthorityCode("INWARSAW", "City of Warsaw");
            InsertSewerAuthorityCode("INWHITELND", "New Whiteland");
            InsertSewerAuthorityCode("INWINCHSTR", "Winchester Sewer");
            InsertSewerAuthorityCode("INWINFIELD", "Town of Winfield");
            InsertSewerAuthorityCode("INWINONA", "Winona Lake");
            InsertSewerAuthorityCode("INWLAFYTTE", "West Lafayette");
            InsertSewerAuthorityCode("KYBLUESKY", "Blue Sky Sewer Auth - LFUCG");
            InsertSewerAuthorityCode("KYCAROLTON", "Carrolton Utilities");
            InsertSewerAuthorityCode("KYGRGTOWN", "City of Georgetown Sewer Auth");
            InsertSewerAuthorityCode("KYHORSEPRK", "Kentucky Horse Park");
            InsertSewerAuthorityCode("KYLFUCG", "LFUCG");
            InsertSewerAuthorityCode("KYTETRATCH", "TetraTech - Delaplain");
            InsertSewerAuthorityCode("KYTREEHVN", "Treehaven");
            InsertSewerAuthorityCode("KYVERNAHL", "Verna Hills");
            InsertSewerAuthorityCode("MDBELAIR", "Town of Bel Air");
            InsertSewerAuthorityCode("MDHARFDCTY", "Harford County");
            InsertSewerAuthorityCode("MOBRANSON", "City of Branson");
            InsertSewerAuthorityCode("MOBRNSWICK", "City of Brunswick");
            InsertSewerAuthorityCode("MOCNTRYCLB", "Village of Country Club");
            InsertSewerAuthorityCode("MODUCKTCRK", "Duckett Creek");
            InsertSewerAuthorityCode("MODUQUESNE", "City of Duguesne");
            InsertSewerAuthorityCode("MOECNTRLMO", "East Central Missouri - Reside");
            InsertSewerAuthorityCode("MOJAKSNCTY", "Jackson County");
            InsertSewerAuthorityCode("MOJEFFCITY", "Jefferson City");
            InsertSewerAuthorityCode("MOJOPLIN", "City of Joplin");
            InsertSewerAuthorityCode("MOKCMO", "KCMO Riverside");
            InsertSewerAuthorityCode("MOKMBERLNG", "Kimberling a.k.a. Golden Acres");
            InsertSewerAuthorityCode("MOMEXICO", "City of Mexico");
            InsertSewerAuthorityCode("MOMILLCRDO", "Mill Creek");
            InsertSewerAuthorityCode("MOMSD", "Metro St Louis Sewer Dist");
            InsertSewerAuthorityCode("MONEPUBSWR", "Northeast Public Sewer");
            InsertSewerAuthorityCode("MOOFALLON", "O Fallon Water and Sewer Auth");
            InsertSewerAuthorityCode("MOPLATTECO", "Platte County Mo");
            InsertSewerAuthorityCode("MOPLATWOOD", "City Platte Wood");
            InsertSewerAuthorityCode("MOPRKVILLE", "Parkville MO");
            InsertSewerAuthorityCode("MOSESWRDST", "Southeast Sewer District");
            InsertSewerAuthorityCode("MOSTCHARLS", "City of St Charles");
            InsertSewerAuthorityCode("MOSTJOSEPH", "City of St Joseph");
            InsertSewerAuthorityCode("MOSTPETERS", "City of St Peters");
            InsertSewerAuthorityCode("MOTANEYCO", "Taney County Regional Swr Dist");
            InsertSewerAuthorityCode("MOWRRNSBRG", "City of Warrensburg");
            InsertSewerAuthorityCode("NJABSECON", "City of Absecon");
            InsertSewerAuthorityCode("NJAQUA", "Aqua NJ Inc");
            InsertSewerAuthorityCode("NJASBURYPK", "Asbury Park");
            InsertSewerAuthorityCode("NJBARRNGTN", "Barrington");
            InsertSewerAuthorityCode("NJBAYHEAD", "Bay Head");
            InsertSewerAuthorityCode("NJBDMNSTER", "Township of Bedminster");
            InsertSewerAuthorityCode("NJBELVDERE", "Town of Belvidere Sewer");
            InsertSewerAuthorityCode("NJBNDBROOK", "Boundbrook");
            InsertSewerAuthorityCode("NJBRICKTWP", "Brick Twp.");
            InsertSewerAuthorityCode("NJBRKLYHTS", "Township of Berkeley Heights");
            InsertSewerAuthorityCode("NJBRNRDVIL", "Borough Of Bernardsville");
            InsertSewerAuthorityCode("NJBVRLYTWN", "Beverly Township");
            InsertSewerAuthorityCode("NJCAMDEN", "Camden");
            InsertSewerAuthorityCode("NJCAPEMAY", "Cape May");
            InsertSewerAuthorityCode("NJCARNEYPT", "Carney''s Point Sewerage Author");
            InsertSewerAuthorityCode("NJCHATHAM", "Township of Chatham");
            InsertSewerAuthorityCode("NJCHESTERB", "Borough of Chester");
            InsertSewerAuthorityCode("NJCHRYHILL", "Cherry Hill Township");
            InsertSewerAuthorityCode("NJCINMINSN", "Cinnaminson");
            InsertSewerAuthorityCode("NJCLARKTWN", "Clark Township");
            InsertSewerAuthorityCode("NJCRANBURY", "Cranbury Township");
            InsertSewerAuthorityCode("NJCRANFORD", "Cranford Township");
            InsertSewerAuthorityCode("NJDELANCO", "Delanco");
            InsertSewerAuthorityCode("NJDELRAN", "Township of Delran");
            InsertSewerAuthorityCode("NJDOVER", "Dover Twp.");
            InsertSewerAuthorityCode("NJDUNELLEN", "Borough of Dunellen");
            InsertSewerAuthorityCode("NJEATONTNC", "Eatontown Sewer - Commercial");
            InsertSewerAuthorityCode("NJEATONTWN", "Eatontown");
            InsertSewerAuthorityCode("NJEDGWTRPK", "Edgewater Park");
            InsertSewerAuthorityCode("NJEDISON", "Edison Township");
            InsertSewerAuthorityCode("NJEGGHRBOR", "Egg Harbor Township Usage");
            InsertSewerAuthorityCode("NJFANWOOD", "Fanwood Borough");
            InsertSewerAuthorityCode("NJFLRHMPRK", "Florham Park AWE");
            InsertSewerAuthorityCode("NJFRHLBORO", "Far Hills Borough");
            InsertSewerAuthorityCode("NJGARWOOD", "Borough of Garwood");
            InsertSewerAuthorityCode("NJGARWOODC", "Borough of Garwood-Commercial");
            InsertSewerAuthorityCode("NJGLADSTNE", "Gladstone");
            InsertSewerAuthorityCode("NJHADDON", "Haddon Township");
            InsertSewerAuthorityCode("NJHARRIRES", "Harrison NJ Res, Jan, Feb, Mar");
            InsertSewerAuthorityCode("NJHARRISON", "Harrison Township - Commercial");
            InsertSewerAuthorityCode("NJHAZLET", "Hazlet Township");
            InsertSewerAuthorityCode("NJHILANDS", "Borough of Highlands");
            InsertSewerAuthorityCode("NJHILLSIDE", "Hillside Township");
            InsertSewerAuthorityCode("NJHILSBORO", "Hillsboro");
            InsertSewerAuthorityCode("NJHOLMDEL", "HOLMDEL");
            InsertSewerAuthorityCode("NJHOWELL", "Howell Township");
            InsertSewerAuthorityCode("NJJAMSBURG", "Jamesburg");
            InsertSewerAuthorityCode("NJLAVLETTE", "Lavallette");
            InsertSewerAuthorityCode("NJLAWRENCE", "Township of Lawrence");
            InsertSewerAuthorityCode("NJLINDEN", "Linden");
            InsertSewerAuthorityCode("NJLNGBRNCH", "Long Branch");
            InsertSewerAuthorityCode("NJLONGHILL", "Township of Longhill");
            InsertSewerAuthorityCode("NJLTLFALLS", "Little Falls");
            InsertSewerAuthorityCode("NJMANTLKNG", "Mantoloking");
            InsertSewerAuthorityCode("NJMANVILLE", "Manville Twp");
            InsertSewerAuthorityCode("NJMDLTWNSP", "Middle Township");
            InsertSewerAuthorityCode("NJMENDHAM", "Mendham Borough Usage");
            InsertSewerAuthorityCode("NJMIDLESEX", "Borough of Middlesex");
            InsertSewerAuthorityCode("NJMIDLTOWN", "Middletown Twp");
            InsertSewerAuthorityCode("NJMLTMUA", "Mount Laurel MUA");
            InsertSewerAuthorityCode("NJMNDHAMBO", "Mendham Borough");
            InsertSewerAuthorityCode("NJMNDHAMTN", "Mendham Township");
            InsertSewerAuthorityCode("NJMNTHOLLY", "Mount Holly MUA");
            InsertSewerAuthorityCode("NJMNTNSIDE", "Mountainside Borough");
            InsertSewerAuthorityCode("NJMONROE", "Monroe Township");
            InsertSewerAuthorityCode("NJMONTGMRY", "Township of Montgomery");
            InsertSewerAuthorityCode("NJMPLSHADE", "Maple Shade");
            InsertSewerAuthorityCode("NJMTOLIVE", "Mount Olive Twp-Itc");
            InsertSewerAuthorityCode("NJMTSDBORR", "Mountainside Borough - Res");
            InsertSewerAuthorityCode("NJNPLNFLD", "North Plainfield");
            InsertSewerAuthorityCode("NJNRTHFLD", "City of Northfield Usage");
            InsertSewerAuthorityCode("NJOCEANTWP", "Township of Ocean");
            InsertSewerAuthorityCode("NJOCNGROVE", "Ocean Grove Sewer Authority");
            InsertSewerAuthorityCode("NJPASSAICV", "Passaic Valley Sewerage Com");
            InsertSewerAuthorityCode("NJPEAPACK", "Peapack");
            InsertSewerAuthorityCode("NJPENSAUKN", "Pennsauken Sewer");
            InsertSewerAuthorityCode("NJPISCATWY", "Township of Piscataway");
            InsertSewerAuthorityCode("NJPLMYRA", "Borough of Palmyra, NJ");
            InsertSewerAuthorityCode("NJPLNFIELD", "Plainfield");
            InsertSewerAuthorityCode("NJPLSNTVIL", "City of Pleasantville");
            InsertSewerAuthorityCode("NJPLUMSTD", "Plumsted MUA");
            InsertSewerAuthorityCode("NJPNSGROIR", "Pennsgrove Sewage OIR");
            InsertSewerAuthorityCode("NJPRINCTON", "Princeton Township");
            InsertSewerAuthorityCode("NJPRNCTNJC", "Princeton Junct (West Windsor)");
            InsertSewerAuthorityCode("NJPRNCTNUV", "Princeton University Usage");
            InsertSewerAuthorityCode("NJRARITAN", "Raritan Borough");
            InsertSewerAuthorityCode("NJREDBANK", "Red Bank");
            InsertSewerAuthorityCode("NJRIVRSIDE", "Riverside");
            InsertSewerAuthorityCode("NJRIVRTON", "Riverton");
            InsertSewerAuthorityCode("NJROSELBOR", "Roselle Park Borough");
            InsertSewerAuthorityCode("NJROSELLE", "Roselle");
            InsertSewerAuthorityCode("NJROXBURY", "Township of Roxbury");
            InsertSewerAuthorityCode("NJSCOTCHPL", "Scotch Plains");
            InsertSewerAuthorityCode("NJSEABRGHT", "Sea Bright Borough");
            InsertSewerAuthorityCode("NJSOBNDBRK", "South Bound Brook Borough");
            InsertSewerAuthorityCode("NJSOBRNSWK", "South Brunswick Township");
            InsertSewerAuthorityCode("NJSOHMPTWP", "Southampton Township");
            InsertSewerAuthorityCode("NJSOMERSPT", "Somers Point");
            InsertSewerAuthorityCode("NJSOMVILLE", "Borough of Somerville");
            InsertSewerAuthorityCode("NJSOPLNFLD", "Borough of South Plainfield");
            InsertSewerAuthorityCode("NJTNTNFALS", "Tinton Falls");
            InsertSewerAuthorityCode("NJTOMSRIVR", "Toms River MUA");
            InsertSewerAuthorityCode("NJTWORIVRS", "Two Rivers WRA");
            InsertSewerAuthorityCode("NJUNTWNSHP", "Union Township");
            InsertSewerAuthorityCode("NJVAUXHALL", "Vauxhall Twp");
            InsertSewerAuthorityCode("NJWARRENTN", "Warren Township");
            InsertSewerAuthorityCode("NJWHITETWP", "White Township");
            InsertSewerAuthorityCode("NJWLNGBORO", "Willingboro MUA");
            InsertSewerAuthorityCode("NYMNTEBOUD", "Mt Ebo Sewerage Works");
            InsertSewerAuthorityCode("PAABBYWDS", "Abbey Woods HOA");
            InsertSewerAuthorityCode("PAALCOSAN", "Alcosan");
            InsertSewerAuthorityCode("PAAMITY", "Amity Township");
            InsertSewerAuthorityCode("PAANNVILLE", "Annville Township");
            InsertSewerAuthorityCode("PAAPPLWLD", "Applewold Borough");
            InsertSewerAuthorityCode("PAAQUAPA", "Aqua Pennsylvania, Inc");
            InsertSewerAuthorityCode("PAAVOCA", "Avoca Borough");
            InsertSewerAuthorityCode("PABALDWINB", "Borough of Baldwin");
            InsertSewerAuthorityCode("PABALDWNT", "Township of Baldwin");
            InsertSewerAuthorityCode("PABANGOR", "Bangor Borough Authority");
            InsertSewerAuthorityCode("PABELLTWPJ", "Bell Township - Jefferson Cnty");
            InsertSewerAuthorityCode("PABERWICK", "BAGSA - Berwick Borough");
            InsertSewerAuthorityCode("PABETHELPK", "Municipality of Bethel Park");
            InsertSewerAuthorityCode("PABIGRUN", "Big Run");
            InsertSewerAuthorityCode("PABNGROIR", "Bangor Boro - OIR only");
            InsertSewerAuthorityCode("PABRDGPORT", "Borough of Bridgeport");
            InsertSewerAuthorityCode("PABRDGWATR", "Bridgewater Township");
            InsertSewerAuthorityCode("PABRENTWD", "Borough of Brentwood");
            InsertSewerAuthorityCode("PABRGSMITH", "Burgettstown-Smith Twp Joint");
            InsertSewerAuthorityCode("PABRIDGVLE", "Bridgeville Borough");
            InsertSewerAuthorityCode("PABRWIKOIR", "Berwick for OIR only");
            InsertSewerAuthorityCode("PABRWNSVIL", "Brownsville Municipal Athrty");
            InsertSewerAuthorityCode("PABTLROIR", "Butler Sewer Authority OIR DIS");
            InsertSewerAuthorityCode("PABUTLER", "Butler Area Sewer Authority");
            InsertSewerAuthorityCode("PACALIFNIA", "Borough of California Sewer");
            InsertSewerAuthorityCode("PACALNTWP", "Caln Township");
            InsertSewerAuthorityCode("PACAMPHILL", "Camp Hill Borough");
            InsertSewerAuthorityCode("PACANONSBG", "Canonsburg Borough");
            InsertSewerAuthorityCode("PACANTON", "Canton Twp");
            InsertSewerAuthorityCode("PACARNEGIE", "Borough of Carnegie");
            InsertSewerAuthorityCode("PACARROLL", "Carroll Township");
            InsertSewerAuthorityCode("PACCLLWRNC", "Cecil Township - Lawrence");
            InsertSewerAuthorityCode("PACCLMLRUN", "Cecil Township - Mill Run Rd");
            InsertSewerAuthorityCode("PACECILTWP", "Cecil Township");
            InsertSewerAuthorityCode("PACENTERW", "Center West JSA");
            InsertSewerAuthorityCode("PACHRTIERS", "Township of Chartiers");
            InsertSewerAuthorityCode("PACHSTHLBR", "Chester Hill Borough");
            InsertSewerAuthorityCode("PACLAIRTON", "Clairton Municipal Authority");
            InsertSewerAuthorityCode("PACLCHRYBK", "Cecil Township - Cherrybrook");
            InsertSewerAuthorityCode("PACLKSUMMT", "Borough of Clarks Summit");
            InsertSewerAuthorityCode("PACLLRTWQ", "Collier Town Square");
            InsertSewerAuthorityCode("PACOLLIER", "Collier Township");
            InsertSewerAuthorityCode("PACOLONIAL", "Colonial JSA");
            InsertSewerAuthorityCode("PACONLSVIL", "Connellsville Municipal Athrty");
            InsertSewerAuthorityCode("PACONNOQNS", "Connoquenessing Borough");
            InsertSewerAuthorityCode("PACONTWPJA", "Connellsville Twp Mun Jnt Auth");
            InsertSewerAuthorityCode("PACONYGHAM", "Conyngham Twp Sewer Auth");
            InsertSewerAuthorityCode("PACRAFTON", "Crafton Borough");
            InsertSewerAuthorityCode("PACSTLSHN", "Borough of Castle Shannon");
            InsertSewerAuthorityCode("PACUMRUTWP", "Cumru Township");
            InsertSewerAuthorityCode("PADALLAREA", "Dallas Area Municipal Authorit");
            InsertSewerAuthorityCode("PADECATUR", "Decatur Township");
            InsertSewerAuthorityCode("PADERRYTWP", "Derry Township Muncpl Athrty");
            InsertSewerAuthorityCode("PADORMONT", "Dormont Borough");
            InsertSewerAuthorityCode("PADUNBAR", "Dunbar Township Municipal Auth");
            InsertSewerAuthorityCode("PADUPONT", "Dupont Borough");
            InsertSewerAuthorityCode("PADUQUESNE", "City of Duquesne");
            InsertSewerAuthorityCode("PADURYEA", "Duryea Borough");
            InsertSewerAuthorityCode("PAEANORITN", "East Norriton Township");
            InsertSewerAuthorityCode("PAEAWASHTN", "Washington East Washington");
            InsertSewerAuthorityCode("PAECVENTRY", "East Coventry Township");
            InsertSewerAuthorityCode("PAEDWRDSVL", "Borough of Edwardsville");
            InsertSewerAuthorityCode("PAELIZABTH", "Elizabeth Borough Muni Auth");
            InsertSewerAuthorityCode("PAELLPORT", "Ellport Borough Sewer Athrty");
            InsertSewerAuthorityCode("PAELLWOOD", "Borough of Ellwood City");
            InsertSewerAuthorityCode("PAELZBETH", "Elizabeth Township");
            InsertSewerAuthorityCode("PAENNTYVLY", "East Nittany Valley JSA");
            InsertSewerAuthorityCode("PAEPNSBORO", "East Pennsboro Township");
            InsertSewerAuthorityCode("PAEVINCENT", "East Vincent Municipal Auth");
            InsertSewerAuthorityCode("PAEXETRTWP", "Exeter Township");
            InsertSewerAuthorityCode("PAFALLSTWP", "Twp of Falls Water & Sewer");
            InsertSewerAuthorityCode("PAFORWARD", "Forward Township");
            InsertSewerAuthorityCode("PAFORWDTWP", "Forward Township Sewer Authori");
            InsertSewerAuthorityCode("PAFRANKTWP", "Franklin Twp Municipal Athrty");
            InsertSewerAuthorityCode("PAFRCKVILE", "Frackville Area Mun. Auth.");
            InsertSewerAuthorityCode("PAFRSTCTY", "Forest City Borough");
            InsertSewerAuthorityCode("PAFRVWTWP", "Fairview Township");
            InsertSewerAuthorityCode("PAGLADETWP", "Glade Township");
            InsertSewerAuthorityCode("PAGLASPORT", "Borough of Glassport");
            InsertSewerAuthorityCode("PAGREENTR", "Green Tree Borough");
            InsertSewerAuthorityCode("PAGREGGTWP", "Gregg Township Muncpl Athrty");
            InsertSewerAuthorityCode("PAHAMPDEN", "Hampden Township");
            InsertSewerAuthorityCode("PAHANVRTWP", "Hanover Township Muncipal Auth");
            InsertSewerAuthorityCode("PAHEIDLBRG", "Heidelberg Borough");
            InsertSewerAuthorityCode("PAHICKORY", "Hickory Township");
            InsertSewerAuthorityCode("PAHLSTDGB", "Hallstead-Great Bend Swr Auth");
            InsertSewerAuthorityCode("PAHOMESTD", "Homestead Borough");
            InsertSewerAuthorityCode("PAIN79ASOC", "I-79 Associates");
            InsertSewerAuthorityCode("PAINDCCJSA", "Independence Cross Creek JSA");
            InsertSewerAuthorityCode("PAINDIANA", "Indiana Borough");
            InsertSewerAuthorityCode("PAINGRAM", "Ingram Borough");
            InsertSewerAuthorityCode("PAJEFFRSON", "Jefferson Borough");
            InsertSewerAuthorityCode("PAKANE", "Kane Borough");
            InsertSewerAuthorityCode("PAKELLYTWP", "Kelly Township Sewer Authority");
            InsertSewerAuthorityCode("PAKITTNING", "Kittanning Borough");
            InsertSewerAuthorityCode("PAKOPPEL", "Koppel Borough Authority");
            InsertSewerAuthorityCode("PALAFAIRVW", "Lower Allen Township");
            InsertSewerAuthorityCode("PALAKWNRVB", "Lackawanna River Basin");
            InsertSewerAuthorityCode("PALAWHICK", "Lawrence Hickory Muni Authorit");
            InsertSewerAuthorityCode("PALEMOYNE", "Borough of Lemoyne");
            InsertSewerAuthorityCode("PALEWISBRG", "Lewisburg Sewer Authority");
            InsertSewerAuthorityCode("PALIBERTY", "Liberty Borough");
            InsertSewerAuthorityCode("PALINCOLN", "Lincoln Borough");
            InsertSewerAuthorityCode("PALMRIKTWP", "Limerick Twp Mun Auth");
            InsertSewerAuthorityCode("PALNESBORO", "Borough of Lanesboro");
            InsertSewerAuthorityCode("PALOWALLEN", "Lower Allen Township");
            InsertSewerAuthorityCode("PALRALNOIR", "Lower Allen Township OIR");
            InsertSewerAuthorityCode("PALRKSVILE", "Larksville Borough Sew Auth");
            InsertSewerAuthorityCode("PALUZERNE", "Luzerne Twp");
            InsertSewerAuthorityCode("PALWRHDLBG", "Lower Heidelberg Township");
            InsertSewerAuthorityCode("PALWRLAKWN", "Lower Lackawanna Sewer");
            InsertSewerAuthorityCode("PALWRMKFLD", "Lower Makefield Twp Swr Athrty");
            InsertSewerAuthorityCode("PALWRPROV", "Lower Providence Sewer");
            InsertSewerAuthorityCode("PAMAHONTWP", "Mahoning Township");
            InsertSewerAuthorityCode("PAMANORTWP", "Manor Twp Joint Municpl Athrty");
            InsertSewerAuthorityCode("PAMCALMONT", "McCalmont Township");
            InsertSewerAuthorityCode("PAMCDONALD", "McDonald Sewage Authority");
            InsertSewerAuthorityCode("PAMCKSPORT", "City of McKeesport");
            InsertSewerAuthorityCode("PAMDLSMTH", "Middle Smithfield Township");
            InsertSewerAuthorityCode("PAMENALLEN", "Menallen Twp Sewer Authority");
            InsertSewerAuthorityCode("PAMIDWAY", "Midway Sewerage Authority");
            InsertSewerAuthorityCode("PAMILTON", "MWWTP - Borough of Milton");
            InsertSewerAuthorityCode("PAMNTNTOP", "Mountaintop Sewer Authority");
            InsertSewerAuthorityCode("PAMONGHELA", "Monongahela City");
            InsertSewerAuthorityCode("PAMONTROSE", "Montrose Municipal Authority");
            InsertSewerAuthorityCode("PAMONVLLY", "Mon Valley Sewage Authority");
            InsertSewerAuthorityCode("PAMORRIS", "Morris Township Municipal Auth");
            InsertSewerAuthorityCode("PAMTLEBNON", "Mount Lebanon Municipality");
            InsertSewerAuthorityCode("PAMTOLV", "Borough of Mount Oliver");
            InsertSewerAuthorityCode("PAMTPENN", "Mt Penn Borough");
            InsertSewerAuthorityCode("PAMTPOCONO", "Mount Pocono Municipal Athrty");
            InsertSewerAuthorityCode("PAMTPOCSMT", "Mt Pocono Mun Auth Summit Pnt");
            InsertSewerAuthorityCode("PAMUNHALL", "Munhall Borough");
            InsertSewerAuthorityCode("PANAZARETH", "Nazareth Borough");
            InsertSewerAuthorityCode("PANESCPK", "Nescopeck Borough");
            InsertSewerAuthorityCode("PANEWCSTLE", "New Castle Sanitation Athrty");
            InsertSewerAuthorityCode("PANEWEAGLE", "New Eagle Borough");
            InsertSewerAuthorityCode("PANLONDDRY", "North Londonderry Township");
            InsertSewerAuthorityCode("PANOFYETTE", "North Fayette Township");
            InsertSewerAuthorityCode("PANORRISTN", "Norristown Mun Waste Authority");
            InsertSewerAuthorityCode("PANSHNNOCK", "Neshannock Township");
            InsertSewerAuthorityCode("PANSWCKLEY", "North Sewickley Sewer Athrty");
            InsertSewerAuthorityCode("PANTHSTRBN", "North Strabane Twp Mun Athrty");
            InsertSewerAuthorityCode("PANUMBRLND", "Northumberland Sewer");
            InsertSewerAuthorityCode("PANUNIONTP", "North Union Township");
            InsertSewerAuthorityCode("PANWBRYTWP", "Newberry Twp Municipal Authrty");
            InsertSewerAuthorityCode("PANWCMBLND", "New Cumberland Authority");
            InsertSewerAuthorityCode("PAOLDFORGE", "Old Forge PA Shut off only");
            InsertSewerAuthorityCode("PAORD", "ORD Sewer Authority");
            InsertSewerAuthorityCode("PAPALMER", "Township of Palmer");
            InsertSewerAuthorityCode("PAPALMYRA", "Palmyra Borough");
            InsertSewerAuthorityCode("PAPENARGYL", "Pen Argyl Borough Sewer");
            InsertSewerAuthorityCode("PAPERKOMEN", "Perkiomen Township - Disconnec");
            InsertSewerAuthorityCode("PAPERRYTWP", "Perry Township");
            InsertSewerAuthorityCode("PAPHLPSBRG", "Philipsburg Borough");
            InsertSewerAuthorityCode("PAPITTBRGH", "Pgh Water & Sewer Authority");
            InsertSewerAuthorityCode("PAPLAINTWP", "Plains Township Sewer Athrty");
            InsertSewerAuthorityCode("PAPLHILLSB", "Pleasant Hills Borough");
            InsertSewerAuthorityCode("PAPLSNTHLS", "Pleasant Hills Authority");
            InsertSewerAuthorityCode("PAPLYMOUTH", "Plymouth Twn Sewer Billing");
            InsertSewerAuthorityCode("PAPNXTWNY", "Punxsutawney Sewage Rental Dpt");
            InsertSewerAuthorityCode("PAPOCONOMT", "Pocono Mountains Ind Auth");
            InsertSewerAuthorityCode("PAPOINTTWP", "Point Township Sewer Authority");
            InsertSewerAuthorityCode("PAPRINGLE", "Pringle Borough");
            InsertSewerAuthorityCode("PAPTRSCRK", "Peters Creek Sanitation Athrty");
            InsertSewerAuthorityCode("PAPTRSTWP", "Peters Twp Sanitation Athrty");
            InsertSewerAuthorityCode("PARAYBURN", "Rayburn");
            InsertSewerAuthorityCode("PAREDSTONE", "Redstone Twp");
            InsertSewerAuthorityCode("PAROBNSON", "Robinson Township Mun Athrty");
            InsertSewerAuthorityCode("PAROSETO", "Roseto Borough Sewer Authority");
            InsertSewerAuthorityCode("PAROSSLFM", "Borough of Rosslyn Farms");
            InsertSewerAuthorityCode("PARUSH", "Rush Township");
            InsertSewerAuthorityCode("PARYRSFORD", "Royersford Borough");
            InsertSewerAuthorityCode("PASADSBURY", "Sadsbury Township");
            InsertSewerAuthorityCode("PASALEMTWP", "Salem Township PA");
            InsertSewerAuthorityCode("PASANNVLLE", "South Annville Township");
            InsertSewerAuthorityCode("PASCOATSVL", "South Coatsville");
            InsertSewerAuthorityCode("PASCONNLSV", "Borough of South Coatesville");
            InsertSewerAuthorityCode("PASCOTT", "Scott Township");
            InsertSewerAuthorityCode("PASCRANTON", "Scranton Sewer Authority");
            InsertSewerAuthorityCode("PASFAYETTE", "Township of South Fayette");
            InsertSewerAuthorityCode("PASFRANKLN", "South Franklin Township");
            InsertSewerAuthorityCode("PASGRNOTCH", "Borough of Sugar Notch");
            InsertSewerAuthorityCode("PASHANOVER", "Township of South Hanover");
            InsertSewerAuthorityCode("PASHENANGO", "Shenango Township");
            InsertSewerAuthorityCode("PASHICKSNY", "Shickshinny Borough Sew Auth");
            InsertSewerAuthorityCode("PASHIPNVIL", "Shippenville Borough");
            InsertSewerAuthorityCode("PASLIGOBOR", "Sligo Borough Authority");
            InsertSewerAuthorityCode("PASLONDDRY", "South Londonderry Township");
            InsertSewerAuthorityCode("PASLVRSPNG", "Silver Springs Township Auth");
            InsertSewerAuthorityCode("PASNCBORO", "SOUTH NEW CASTLE BORO");
            InsertSewerAuthorityCode("PASNKSPRNG", "Sinking Spring Borough");
            InsertSewerAuthorityCode("PASOCNLSVL", "South Connellsville Borough");
            InsertSewerAuthorityCode("PASOHDLBRG", "South Heidelberg Township");
            InsertSewerAuthorityCode("PASOPOINT", "Southpointe Sewer District");
            InsertSewerAuthorityCode("PASOPRKTWP", "South Park Township");
            InsertSewerAuthorityCode("PASPRING", "Township of Spring, Berks");
            InsertSewerAuthorityCode("PASTKRTOWN", "Stockertown Borough");
            InsertSewerAuthorityCode("PASTLTNBOR", "Steelton Borough");
            InsertSewerAuthorityCode("PASTRTNVIL", "Strattanville Water Authority");
            InsertSewerAuthorityCode("PASUNNTWP", "South Uniontown Township");
            InsertSewerAuthorityCode("PASXNBURG", "Saxonburg Area Authority");
            InsertSewerAuthorityCode("PATATAMY", "Tatamy Borough Sewer");
            InsertSewerAuthorityCode("PATAYLORTP", "Taylor Twp");
            InsertSewerAuthorityCode("PATHOMPSON", "Thompson Borough");
            InsertSewerAuthorityCode("PATHRNBURG", "Thornburg Boro");
            InsertSewerAuthorityCode("PATRIBORO", "Tri-Boro Municipal Authority");
            InsertSewerAuthorityCode("PAUNIONFN", "Union Township - Finleyville");
            InsertSewerAuthorityCode("PAUNIONTWN", "Uniontown Sewage System");
            InsertSewerAuthorityCode("PAUNIONTWP", "Union Township");
            InsertSewerAuthorityCode("PAUPMERION", "Upper Merion Township");
            InsertSewerAuthorityCode("PAUPPRPROV", "Upper Providence Township");
            InsertSewerAuthorityCode("PAUPPRSTCL", "Township of Upper St Clair");
            InsertSewerAuthorityCode("PAUPRALLEN", "Upper Allen Township");
            InsertSewerAuthorityCode("PAWARREN", "City of Warren");
            InsertSewerAuthorityCode("PAWAVERLY", "Township of Waverly");
            InsertSewerAuthorityCode("PAWAYNETWP", "Wayne Township Sewer Authority");
            InsertSewerAuthorityCode("PAWBUTLER", "West Butler County Authority");
            InsertSewerAuthorityCode("PAWDLBIGLR", "Woodland Bigler Area Auth");
            InsertSewerAuthorityCode("PAWELZBTH", "West Elizabeth Sanitary");
            InsertSewerAuthorityCode("PAWHANOVER", "West Hanover Township");
            InsertSewerAuthorityCode("PAWHAWPCA", "West Hills Water Pollution Con");
            InsertSewerAuthorityCode("PAWHITAKER", "Whitaker Borough");
            InsertSewerAuthorityCode("PAWHITDEER", "White Deer Twp Sewer Auth");
            InsertSewerAuthorityCode("PAWHITERUN", "White Run Regional Muncpl Auth");
            InsertSewerAuthorityCode("PAWHITETWP", "White Township");
            InsertSewerAuthorityCode("PAWHITHALL", "Whitehall Borough");
            InsertSewerAuthorityCode("PAWHITPAIN", "Whitpain Township Sewer");
            InsertSewerAuthorityCode("PAWHOMESTD", "West Homestead");
            InsertSewerAuthorityCode("PAWINDGAP", "Wind Gap Sewer Authority");
            InsertSewerAuthorityCode("PAWKBARTWP", "Wilkes-Barre Township");
            InsertSewerAuthorityCode("PAWLCTBOGS", "Wallaceton Boggs Municipal");
            InsertSewerAuthorityCode("PAWLKSBARR", "City of Wilkes-Barre");
            InsertSewerAuthorityCode("PAWMIFFLIN", "West Mifflin Borough");
            InsertSewerAuthorityCode("PAWNORITON", "West Norriton Township");
            InsertSewerAuthorityCode("PAWORCSTER", "Worcester Township");
            InsertSewerAuthorityCode("PAWPIKERUN", "West Pike Run Twp");
            InsertSewerAuthorityCode("PAWPITTSTN", "Borough of West Pittston");
            InsertSewerAuthorityCode("PAWRMLYBRG", "Wormleysburg Borough");
            InsertSewerAuthorityCode("PAWWYMING", "Borough of West Wyoming");
            InsertSewerAuthorityCode("PAWYMGVALY", "Wyoming Valley Sewer Athrty");
            InsertSewerAuthorityCode("PAWYOMSSNG", "Wyomissing Borough");
            InsertSewerAuthorityCode("PAYARDLEY", "Yardley Borough Sewer");
            InsertSewerAuthorityCode("PAYOUNGTWP", "Young Township");
            InsertSewerAuthorityCode("TNCHATTNGA", "City of Chattanooga");
            InsertSewerAuthorityCode("TNERDGCTY", "City of East Ridge (Hamilton)");
            InsertSewerAuthorityCode("TNERDGGTN", "City of East Ridge Gtown (Ham)");
            InsertSewerAuthorityCode("TNHAMLTON", "Hamilton County");
            InsertSewerAuthorityCode("TNJASPER", "City of Whitwell");
            InsertSewerAuthorityCode("TNLKOUTHM", "Lookout Mountain TN (Hamilton)");
            InsertSewerAuthorityCode("TNLKOUTMT", "Lookout Mountain");
            InsertSewerAuthorityCode("TNOGLETHRP", "City of Oglethorpe");
            InsertSewerAuthorityCode("TNREDBANK", "City of Red Bank (Hamilton)");
            InsertSewerAuthorityCode("TNRIDGSIDE", "City of Ridgeside (Hamilton)");
            InsertSewerAuthorityCode("TNRIGGOLD", "City of Ringgold");
            InsertSewerAuthorityCode("TNROSSVILE", "City of Rossville");
            InsertSewerAuthorityCode("TNWALKER", "Walker County W&S Authority");
            InsertSewerAuthorityCode("VAALEXNDRA", "Alexandria Renew Enterprises");
            InsertSewerAuthorityCode("VAARLINGTN", "Arlington County");
            InsertSewerAuthorityCode("VADALESVC", "Dale Service Corporation");
            InsertSewerAuthorityCode("VAFAIRFAX", "Fairfax County");
            InsertSewerAuthorityCode("VAHOPEWELL", "City of Hopewell");
            InsertSewerAuthorityCode("VAPRINCW", "City Prince William Sewer Auth");
            InsertSewerAuthorityCode("VAPRNCGAP", "Prince George Sewer Authority");
            InsertSewerAuthorityCode("VAPRNCWILM", "City Prince William Sewer Auth");
            InsertSewerAuthorityCode("WIBELOIT", "City of Beloit");
            InsertSewerAuthorityCode("WVANSTED", "Ansted Sewer");
            InsertSewerAuthorityCode("WVARBUCKLE", "Arbuckle PSD");
            InsertSewerAuthorityCode("WVBARBSVIL", "Barboursville Sanitary Board");
            InsertSewerAuthorityCode("WVBELLESAN", "Belle Sanitary Board");
            InsertSewerAuthorityCode("WVBIGBEND", "Big Bend Utilities");
            InsertSewerAuthorityCode("WVBLFLDVLY", "Bluefield Valley VA");
            InsertSewerAuthorityCode("WVBLUEFLD", "Bluefield Sanitary Board");
            InsertSewerAuthorityCode("WVBLUSPRUC", "Blue Spruce PSD (rgn of SALTR)");
            InsertSewerAuthorityCode("WVBOONDANV", "Boone County (Danville) PSD");
            InsertSewerAuthorityCode("WVBOONRLGH", "Boone Raleigh PSD");
            InsertSewerAuthorityCode("WVBUFFALO", "Buffalo PSD");
            InsertSewerAuthorityCode("WVCEREDO", "Ceredo Sanitary Board");
            InsertSewerAuthorityCode("WVCHELYAN", "Chelyan PSD");
            InsertSewerAuthorityCode("WVCHESAPK", "Chesapeake Sanitary Board");
            InsertSewerAuthorityCode("WVCHRLSTON", "Charleston Sanitary Board");
            InsertSewerAuthorityCode("WVCHSTNUT", "Chestnut Point Sanitary");
            InsertSewerAuthorityCode("WVCLNDENIN", "City of Clendenin");
            InsertSewerAuthorityCode("WVCLRKESTS", "Clark Estates Sewer");
            InsertSewerAuthorityCode("WVCULLODEN", "Culloden PSD");
            InsertSewerAuthorityCode("WVDEEPWTR", "Deepwater PSD");
            InsertSewerAuthorityCode("WVDUNBAR", "Dunbar Sanitary Board");
            InsertSewerAuthorityCode("WVELEANOR", "Town of Eleanor");
            InsertSewerAuthorityCode("WVELKVALLY", "Elk Valley PSD");
            InsertSewerAuthorityCode("WVESQESTAT", "Esquire Estates Sewage");
            InsertSewerAuthorityCode("WVFLTWDCRN", "Flatwoods-Canoe Run PSD");
            InsertSewerAuthorityCode("WVGLADSPNG", "Glade Springs");
            InsertSewerAuthorityCode("WVGLASGOW", "Glasgow Municipal");
            InsertSewerAuthorityCode("WVGRMMEADW", "Graham Meadows Service Distric");
            InsertSewerAuthorityCode("WVGRNACRES", "Green Acres Utilities");
            InsertSewerAuthorityCode("WVGRVALPRN", "Green Valley PSD (Princeton)");
            InsertSewerAuthorityCode("WVGRVALSTA", "Green Valley PSD (St Albans)");
            InsertSewerAuthorityCode("WVGTRSTALB", "Greater St Albans PSD");
            InsertSewerAuthorityCode("WVGUTHRIE", "Guthrie PSD");
            InsertSewerAuthorityCode("WVHAMLIN", "Hamlin PSD");
            InsertSewerAuthorityCode("WVHANDLEY", "Handley Sanitary Board");
            InsertSewerAuthorityCode("WVHINTON", "Hinton Sanitary Board");
            InsertSewerAuthorityCode("WVHNTNGTON", "Huntington Sanitary Board");
            InsertSewerAuthorityCode("WVHOLDYPRK", "Holiday Park");
            InsertSewerAuthorityCode("WVHURICANE", "City of Hurricane");
            InsertSewerAuthorityCode("WVJANELEWM", "Jane Lew Municipal Authority");
            InsertSewerAuthorityCode("WVJHRICHMD", "J H Richmond Sewer");
            InsertSewerAuthorityCode("WVKNWAFALS", "Kanawha Falls PSD");
            InsertSewerAuthorityCode("WVLINMONT", "Linmont Sanitary Board");
            InsertSewerAuthorityCode("WVMALDON", "Malden PSD");
            InsertSewerAuthorityCode("WVMARMET", "Marmet Sanitary Board");
            InsertSewerAuthorityCode("WVMONTGMRY", "Montgomery Sanitary Board");
            InsertSewerAuthorityCode("WVMTTYLER", "Mount Tyler PSD");
            InsertSewerAuthorityCode("WVNITRO", "Nitro Sanitary Board");
            InsertSewerAuthorityCode("WVNOWAYCTY", "Northern Wayne City PSD");
            InsertSewerAuthorityCode("WVOAKHILL", "Oak Hill Sanitary Board");
            InsertSewerAuthorityCode("WVOAKVALE", "Oakvale Road PSD");
            InsertSewerAuthorityCode("WVOHRIVER", "Ohio River PSD");
            InsertSewerAuthorityCode("WVPEARDGE", "Pea Ridge PSD");
            InsertSewerAuthorityCode("WVPOCASAN", "Poca Sanitary Board");
            InsertSewerAuthorityCode("WVPRATT", "Town of Pratt");
            InsertSewerAuthorityCode("WVPRNCTON", "Princeton Sanitary Board");
            InsertSewerAuthorityCode("WVPUTNAM", "Putnam Public Service District");
            InsertSewerAuthorityCode("WVSALTROCK", "Salt Rock PSD");
            InsertSewerAuthorityCode("WVSCHLSTON", "South Charleston Sanitary Bd");
            InsertSewerAuthorityCode("WVSISNVILL", "Sissonville PSD");
            InsertSewerAuthorityCode("WVSMITHERS", "Smithers Sanitary Board");
            InsertSewerAuthorityCode("WVSPNGVALY", "Spring Valley PSD");
            InsertSewerAuthorityCode("WVSTALBANS", "City of St Albans");
            InsertSewerAuthorityCode("WVUNIONPSD", "Union PSD");
            InsertSewerAuthorityCode("WVUNIONTWP", "WV Union Township");
            InsertSewerAuthorityCode("WVUPRKANWA", "Upper Kanawha Valley PSD");
            InsertSewerAuthorityCode("WVVANBOONE", "Van-Boone County PSD");
            InsertSewerAuthorityCode("WVWBSTRSPG", "Webster Springs PSD");
            InsertSewerAuthorityCode("WVWDUNBAR", "West Dunbar PSD");
            InsertSewerAuthorityCode("WVWHITEOAK", "White Oak PSD");
            InsertSewerAuthorityCode("WVWHSPOAK", "Whispering Oaks Mobile Village");
            InsertSewerAuthorityCode("WVWINFIELD", "Winfield Sanitary Board");
            InsertSewerAuthorityCode("WVWLMSBRG", "Williamsburg Sewer System, Inc");
            InsertSewerAuthorityCode("WVWSTNSAN", "Weston Sanitary Board");
        }

        private void InsertSewerAuthorityCode(string sapcode, string description)
        {
            Execute.Sql($"INSERT INTO SewerAuthorityCodes(SAPCode, Description) Values('{sapcode}', '{description}');");
        }

        public override void Down()
        {
            Delete.ForeignKeyColumn("ShortCycleWorkOrders", "CriticalCareTypeId", "PremiseCriticalCareTypes");
            Delete.ForeignKeyColumn("ShortCycleWorkOrders", "SewerAuthorityCode1Id", "SewerAuthorityCodes");
            Delete.ForeignKeyColumn("ShortCycleWorkOrders", "SewerAuthorityCode2Id", "SewerAuthorityCodes");
            Delete.ForeignKeyColumn("ShortCycleWorkOrders", "SewerAuthorityCode3Id", "SewerAuthorityCodes");
            Delete.Table("SewerAuthorityCodes");
        }
    }
}
